import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,TextInput,View} from 'react-native';
import {router,useLocalSearchParams} from 'expo-router';
import {catalogQuery,loadCatalog,type Filters} from '../../lib/catalog';
import {supabase} from '../../lib/supabase';
import {useLoad} from '../../components/use-load';
import {ListingCard} from '../../components/listing-card';
import {ListingMap} from '../../components/listing-map';
import {styles} from '../../components/styles';
export default function Listings(){const filters=catalogQuery(useLocalSearchParams<Record<string,string|string[]>>());return <Catalog key={JSON.stringify(filters)} filters={filters}/>;}
function Catalog({filters}:{filters:Filters}){
 const [q,setQ]=useState(filters.q),[area,setArea]=useState(filters.area),[intent,setIntent]=useState(filters.intent),[view,setView]=useState<'list'|'map'>('list');
 const loader=useCallback(()=>{if(!supabase)throw new Error('Connection unavailable');return loadCatalog(supabase,filters);},[filters]);
 const result=useLoad(JSON.stringify(filters),loader);
 const navigate=(page:number,search=filters)=>router.setParams({q:search.q,area:search.area,intent:search.intent,page:String(page)});
 const apply=()=>navigate(1,catalogQuery({q,area,intent}));
 const header=<View style={{gap:18}}><Text style={styles.title}>Find your next chapter.</Text><Text style={styles.body}>Published properties from the Open House team.</Text><TextInput accessibilityLabel="Search properties" placeholder="Property name or area" style={styles.input} value={q} onChangeText={setQ} maxLength={120}/><TextInput accessibilityLabel="Filter by area" placeholder="Area" style={styles.input} value={area} onChangeText={setArea} maxLength={120}/><View style={{flexDirection:'row',gap:16}}>{(['all','sale','rent'] as const).map(value=><Pressable accessibilityRole="button" accessibilityState={{selected:intent===value}} onPress={()=>setIntent(value)} key={value}><Text style={styles.link}>{value==='all'?'All':value==='sale'?'Buy':'Rent'}{intent===value?' ✓':''}</Text></Pressable>)}</View><Pressable accessibilityRole="button" onPress={apply} style={styles.button}><Text style={styles.buttonText}>Search properties</Text></Pressable><View style={{flexDirection:'row',gap:24}}>{(['list','map'] as const).map(value=><Pressable key={value} accessibilityRole="button" accessibilityState={{selected:view===value}} onPress={()=>setView(value)}><Text style={styles.link}>{value==='list'?'List':'Map'}{view===value?' ✓':''}</Text></Pressable>)}</View>{result.loading?<ActivityIndicator color="#003A8C" accessibilityLabel="Loading properties"/>:result.error?<><Text accessibilityRole="alert" style={styles.body}>{result.error}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></>:result.data&&<><Text style={styles.body}>{result.data.total.toLocaleString('en-JM')} published properties · Page {result.data.page} of {result.data.pages}</Text>{result.data.total===0?<Text style={styles.body}>No published properties match your search. Try another area or filter.</Text>:result.data.rows.length===0?<><Text style={styles.body}>Inventory changed while this page loaded. Refresh to see current properties.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh properties</Text></Pressable></>:view==='map'&&<ListingMap key={result.data.rows.map(row=>row.id).join(',')} rows={result.data.rows}/>}</>}</View>;
 return <FlatList contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled" data={view==='list'?result.data?.rows||[]:[]} keyExtractor={row=>row.id} renderItem={({item})=><ListingCard row={item}/>} ItemSeparatorComponent={()=><View style={{height:18}}/>} ListHeaderComponent={header} ListFooterComponent={result.data&&<View style={{gap:18,paddingTop:24}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Pressable accessibilityRole="button" accessibilityState={{disabled:result.data.page===1}} disabled={result.data.page===1} onPress={()=>navigate(result.data!.page-1)}><Text style={styles.link}>← Previous</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{disabled:result.data.page===result.data.pages}} disabled={result.data.page===result.data.pages} onPress={()=>navigate(result.data!.page+1)}><Text style={styles.link}>Next →</Text></Pressable></View><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh inventory</Text></Pressable></View>}/>;
}
