import type {Metadata} from 'next';
import {SiteFooter} from '@/components/discovery/site-footer';
import {SiteHeader} from '@/components/discovery/site-header';
export const metadata:Metadata={title:'Property services | Open House Realty',description:'Explore buying, renting, selling and property management with Open House Realty in Jamaica.'};
const services=[
 {number:'01',title:'Find your next home.',description:'Explore properties for sale or rent, compare locations on the map and connect with a realtor whose working style suits you.',links:[{href:'/listings?intent=sale',label:'Browse homes to buy'},{href:'/listings?intent=rent',label:'Browse homes to rent'}]},
 {number:'02',title:'Plan your next sale.',description:'Start with your property, your timing and what matters to you. Share private details through your verified account for the sales team to review.',links:[{href:'/sell',label:'Start a property conversation'},{href:'/realtors',label:'Meet the realtors'}]},
 {number:'03',title:'Care for your property.',description:'Discuss your portfolio, resident needs and maintenance priorities with the team. Together, define the management scope and the next steps for your property.',links:[{href:'mailto:ohrealty@flashcreate.co?subject=Property%20management%20enquiry',label:'Discuss property management'},{href:'/account',label:'Open your existing workspace'}]},
];
export default function Services(){return <><a className="skip-link" href="#services">Skip to services</a><SiteHeader/><main id="services" className="services-page"><section className="services-intro"><p className="eyebrow">OPEN HOUSE REALTY SERVICES</p><h1>People first.<br/>Property possibilities.</h1><p>Whether you are finding a home, planning a sale or managing a property, start with a conversation about what you need.</p><a className="button-link" href="/realtors#match">Find your realtor ↗</a></section><section className="services-grid" aria-label="Our services">{services.map(service=><article className="service-card" key={service.number}><span className="eyebrow">{service.number}</span><h2>{service.title}</h2><p>{service.description}</p><div className="service-links">{service.links.map(link=><a key={link.href} href={link.href}>{link.label} ↗</a>)}</div></article>)}</section><section className="services-next"><div><p className="eyebrow">YOUR NEXT STEP</p><h2>Tell us what you have in mind.</h2><p>For general questions or a management conversation, email the Open House team. Include your preferred contact details and the area you are interested in.</p></div><a className="button-link" href="mailto:ohrealty@flashcreate.co?subject=Open%20House%20Realty%20services">Contact the team ↗</a></section></main><SiteFooter/></>;}
