import {redirect} from 'next/navigation';
import {SiteHeader} from '@/components/discovery/site-header';
import {OpenHouseBrowser,type PublicOpenHouse} from '@/components/open-houses/public-browser';
import {createClient} from '@/lib/supabase/server';
import {catalogQuery,CATALOG_PAGE_SIZE} from '@/lib/discovery/catalog-query';
export const dynamic='force-dynamic';
export default async function OpenHouses({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const filters=catalogQuery(await searchParams),client=await createClient(),now=new Date().toISOString();
 const query=(head=false)=>{let result=client.from('open_house_events').select('id,title,starts_at,ends_at,capacity,listings!inner(id,title,area,intent,price_jmd,bedrooms,bathrooms,parking_spaces,size_sq_ft,description,photo_url,approximate_latitude,approximate_longitude,location_label)',{count:'exact',head}).eq('status','scheduled').gte('starts_at',now).eq('listings.status','published');if(filters.area)result=result.ilike('listings.area',`%${filters.area}%`);if(filters.intent!=='all')result=result.eq('listings.intent',filters.intent);return result;};
 const href=(page:number)=>`/open-houses?${new URLSearchParams({area:filters.area,intent:filters.intent,page:String(page)})}`;
 const [counts,{data:{user}}]=await Promise.all([query(true),client.auth.getUser()]);const pages=Math.max(1,Math.ceil((counts.count||0)/CATALOG_PAGE_SIZE));if(!counts.error&&filters.page>pages)redirect(href(pages));
 const rows=counts.error?{data:null,error:counts.error}:await query().order('starts_at').order('id').range((filters.page-1)*CATALOG_PAGE_SIZE,filters.page*CATALOG_PAGE_SIZE-1);
 const events:PublicOpenHouse[]=(rows.data||[]).flatMap(row=>{const listing=Array.isArray(row.listings)?row.listings[0]:row.listings;return listing?[{id:row.id,title:row.title,starts_at:row.starts_at,ends_at:row.ends_at,capacity:row.capacity,listing}]:[]});
 const {data:reservations,error:reservationError}=user?.email_confirmed_at&&events.length?await client.from('open_house_rsvps').select('event_id,party_size,status,version,attendance_state,attended_count').eq('user_id',user.id).in('event_id',events.map(event=>event.id)):{data:[],error:null};
 return <><SiteHeader/><main><section className="page-intro"><p className="eyebrow">MEET YOUR NEXT HOME</p><h1>Step inside. Picture your life.</h1><p>Explore upcoming open houses by neighborhood. Map pins show approved approximate locations; confirm arrival details with the team.</p></section><section className="listing-workspace"><form method="get" className="filter-bar"><label>Neighborhood<input name="area" defaultValue={filters.area} placeholder="City, parish or community"/></label><label>Looking to<select name="intent" defaultValue={filters.intent}><option value="all">Buy or rent</option><option value="sale">Buy</option><option value="rent">Rent</option></select></label><button>Find open houses</button></form>{rows.error?<div className="empty-state" role="alert"><h2>Open houses are unavailable</h2><p>Please try again shortly.</p></div>:<><p role="alert" hidden={!reservationError}>Unable to load your reservations. Please refresh before making changes.</p><OpenHouseBrowser key={href(filters.page)} events={events} verified={!!user?.email_confirmed_at&&!reservationError} reservations={reservations||[]}/></>}<nav className="results-toolbar" aria-label="Open house pages">{filters.page>1?<a href={href(filters.page-1)}>← Previous</a>:<span/>}<span>{counts.count||0} upcoming events · Page {filters.page} of {pages}</span>{filters.page<pages?<a href={href(filters.page+1)}>Next →</a>:<span/>}</nav></section></main></>;
}
