import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
export const dynamic='force-dynamic';
export default async function AttendanceHistory({params,searchParams}:{params:Promise<{eventId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','realtor','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const {eventId}=await params;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(eventId))notFound();
 const event=await client.from('open_house_events').select('id,title,open_house_management!inner(organization_id)').eq('id',eventId).eq('open_house_management.organization_id',membership.organization_id).maybeSingle();if(event.error)throw new Error('Unable to verify event access.');if(!event.data)notFound();
 const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const query=(head=false)=>client.from('open_house_attendance_changes').select('id,rsvp_id,actor_user_id,version,state,attended_count,reason,created_at,open_house_rsvps!inner(event_id)',{head,count:'exact'}).eq('organization_id',membership.organization_id).eq('open_house_rsvps.event_id',eventId);
 const counts=await query(true);if(counts.error)throw new Error('Unable to load attendance history.');const pages=Math.max(1,Math.ceil((counts.count||0)/25)),href=(next:number)=>`/staff/open-houses/${eventId}/attendance?page=${next}`;if(page>pages)redirect(href(pages));
 const [rows,directory]=await Promise.all([query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1),client.rpc('enquiry_staff_directory')]);const staff=directory.data as {user_id:string;display_name:string|null;role:string}[]|null;
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Private attendance audit</p><h1>{event.data.title}</h1><p>Recorded outcomes and corrections, newest first. Staff names reflect the current directory; actor references remain part of the audit.</p>{directory.error&&<p role="alert">Staff names are unavailable. Actor references remain visible.</p>}{rows.error?<p role="alert">Unable to load history. Please refresh.</p>:rows.data?.length?rows.data.map(row=><article className="staff-editor" key={row.id}><h2>{row.state==='attended'?`${row.attended_count} attended`:row.state==='no_show'?'Did not attend':'Attendance cleared'}</h2><p>{new Date(row.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</p><p>Recorded by {staff?.find(person=>person.user_id===row.actor_user_id)?.display_name||'Staff member / former staff'}</p><p className="enquiry-message">{row.reason}</p><small>Actor reference: {row.actor_user_id}<br/>Reservation: {row.rsvp_id} · Attendance revision {row.version}</small></article>):<p>No attendance records or corrections yet.</p>}<nav className="results-toolbar" aria-label="Attendance history pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{counts.count||0} changes · Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><a href={`/staff/open-houses/${eventId}`}>Back to attendee roster ↗</a></section></main></>;
}
