import {AccountWorkspace} from '../components/account-workspace';
import {styles} from '../components/styles';
import {ScrollView,Text,View,ActivityIndicator,Pressable} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {supabase} from '../lib/supabase';
import {useRef,useState} from 'react';
export default function Home(){const {user,loading,error,refresh}=useIdentity();const active=useRef(false);const [message,setMessage]=useState('');
 async function signOut(){if(active.current||!supabase)return;active.current=true;setMessage('');try{const {error}=await supabase.auth.signOut();if(error)setMessage('Unable to sign out. Try again.');await refresh();}catch{setMessage('Unable to sign out. Try again.');await refresh();}finally{active.current=false;}}
 return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Your Open House.</Text><Text style={styles.body}>A clearer view of your property journey.</Text>{loading?<ActivityIndicator accessibilityLabel="Checking your account" color="#003A8C"/>:user?<><View style={styles.card}><Text style={styles.heading}>Welcome back</Text><Text style={styles.body}>{user.email}</Text><Text style={styles.body}>Your verified account connects your saved homes, conversations and next steps.</Text></View><AccountWorkspace/><Pressable accessibilityRole="button" onPress={()=>void signOut()} style={styles.button}><Text style={styles.buttonText}>Sign out</Text></Pressable></>:<View style={styles.card}><Text style={styles.heading}>Make your next move.</Text><Text style={styles.body}>Sign in to keep your shortlist, follow enquiries and manage your applications.</Text><Link href="/sign-in" style={styles.link}>Sign in →</Link><Link href="/register" style={styles.link}>Create an account →</Link><Link href="/demo-listings" style={styles.link}>Explore demo properties →</Link><Link href="/demo-realtors" style={styles.link}>Try demo realtor matching →</Link></View>}{error&&<View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>{error}</Text><Pressable accessibilityRole="button" onPress={()=>void refresh()}><Text style={styles.link}>Check account again</Text></Pressable></View>}{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}<Text style={styles.body}>Unlocking value, building connections.</Text></ScrollView>;
}
