import {FinanceInvoiceLedger} from '../components/finance-invoice-ledger';
import {FinanceInvoiceDocuments} from '../components/finance-invoice-documents';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeInvoiceHistory} from '../lib/finance-invoice-history';
import {formatJmdMinor} from '../lib/finance-statement';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
const status=(value:string)=>value.replaceAll('_',' ');
const when=(value:string)=>new Date(value).toLocaleString('en-JM',{timeZone:'America/Jamaica'});
export default function Invoice(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!validId(id))return <Text accessibilityRole="alert">Valid invoice reference required.</Text>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review a vendor invoice →</Link></View>;return <Detail key={JSON.stringify([user.id,id])} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return financeInvoiceHistory(supabase,owner,id);},[owner,id]);const result=useLoad(JSON.stringify([owner,id]),loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading invoice and review history"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Invoice and complete history unavailable. Check your verified invoice membership and refresh.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invoice</Text></Pressable><Link href="/finance-invoices" style={styles.link}>Vendor invoice register →</Link></View>;const {invoice:r,rows}=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>{r.vendor}</Text><Text style={styles.heading}>Invoice {r.number}</Text><Text style={styles.heading}>{formatJmdMinor(r.amount)}</Text><Text style={styles.body}>{status(r.state)} · Revision {r.version}</Text><Text style={styles.body}>Invoice reference: {r.id}</Text><Text style={styles.body}>Submitted by {r.submitter} · {when(r.submitted)} (Jamaica time)</Text>{r.reviewer&&r.reviewed&&<Text style={styles.body}>Reviewed by {r.reviewer} · {when(r.reviewed)} (Jamaica time)</Text>}{r.approver&&r.approved&&<Text style={styles.body}>Approved by {r.approver} · {when(r.approved)} (Jamaica time)</Text>}<Text style={styles.body}>Property allocation: {r.property??'Organization invoice'}</Text>{r.work&&<Text style={styles.body}>Work order reference: {r.work}</Text>}<Text style={styles.body}>Submitted invoice details are fixed. Approval does not create a ledger posting or confirm vendor payment.</Text><FinanceInvoiceDocuments key={JSON.stringify([owner,id,r.version])} owner={owner} id={id} version={r.version} onRefresh={result.retry}/>{['admin','finance'].includes(r.role)&&<FinanceInvoiceLedger key={JSON.stringify([owner,id,r.version])} owner={owner} id={id} version={r.version} onRefresh={result.retry}/>}<Text style={styles.heading}>Review history</Text>{rows.map(event=><View key={event.id} style={styles.card}><Text style={styles.heading}>{event.action} · Revision {event.version}</Text><Text style={styles.body}>{event.previous?status(event.previous):'New invoice'} → {status(event.state)}</Text><Text style={styles.body}>{event.reason}</Text><Text style={styles.body}>Actor: {event.actor} · {when(event.created)} (Jamaica time)</Text><Text style={styles.body}>Request reference: {event.request}</Text></View>)}<Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invoice</Text></Pressable><Link href="/finance-invoices" style={styles.link}>Vendor invoice register →</Link></ScrollView>;}
