import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeCheques,chequeStates,type ChequeState} from '../lib/finance-cheques';
import {formatJmdMinor} from '../lib/finance-statement';
import {supabase} from '../lib/supabase';
const labels={received:'Received',deposited:'Deposited',cleared:'Cleared',returned:'Returned',cancelled:'Cancelled'};
export default function Cheques(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review cheque records →</Link></View>;return <Filters key={user.id} owner={user.id}/>;}
function Filters({owner}:{owner:string}){const [state,setState]=useState<ChequeState|null>(null);return <View style={{flex:1}}><View style={styles.card}><Text style={styles.heading}>Cheque status</Text>{([null,...chequeStates] as const).map(value=><Pressable key={value??'all'} accessibilityRole="radio" accessibilityState={{selected:state===value}} onPress={()=>setState(value)}><Text style={styles.link}>{state===value?'●':'○'} {value?labels[value]:'All cheques'}</Text></Pressable>)}</View><Register key={JSON.stringify([owner,state])} owner={owner} state={state}/></View>;}
function Register({owner,state}:{owner:string;state:ChequeState|null}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeCheques(supabase,owner,page,state);},[owner,page,state]);const result=useLoad(JSON.stringify([owner,state,page]),loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading cheque records"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Cheque records unavailable. Verified administrator or finance membership is required.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh cheque records</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={i=>i.id} ListHeaderComponent={<View><Text style={styles.title}>Cheque custody register</Text><Link href="/finance-cheque-new" style={styles.link}>Record a cheque receipt →</Link><Text style={styles.body}>Receipt records custody. Deposit and clearance require retained bank evidence. Ledger posting and bank reconciliation are separate steps.</Text><Text style={styles.body}>Cheque records are private to verified administrators and finance staff.</Text>{!r.total&&<Text style={styles.body}>No cheques match this status.</Text>}</View>} renderItem={({item:i})=><View style={styles.card}><Text style={styles.heading}>{i.payer}</Text><Text style={styles.body}>{i.bank}</Text><Text style={styles.body}>Cheque {i.number} · {labels[i.state]}</Text><Text style={styles.heading}>{formatJmdMinor(i.amount)}</Text><Text style={styles.body}>Received {new Date(i.received).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text style={styles.body}>Cheque reference: {i.id}</Text><Link href={{pathname:"/finance-cheque",params:{id:i.id}}} style={styles.link}>Review custody history →</Link></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} cheques · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} accessibilityState={{disabled:r.page===1}} onPress={()=>{if(r.page>1)setPage(r.page-1);}}><Text style={styles.link}>← Previous cheques</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} accessibilityState={{disabled:r.page===r.pages}} onPress={()=>{if(r.page<r.pages)setPage(r.page+1);}}><Text style={styles.link}>Next cheques →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh cheque records</Text></Pressable><Link href="/" style={styles.link}>Your account →</Link></View>}/>;}
