import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeAccounts} from '../lib/finance-accounts';
import {supabase} from '../lib/supabase';
export default function Accounts(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review approved finance accounts →</Link></View>;return <Register key={user.id} owner={user.id}/>;}
function Register({owner}:{owner:string}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeAccounts(supabase,owner,page);},[owner,page]);const result=useLoad(owner+page,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading approved accounts"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Approved accounts unavailable. A verified administrator or finance membership is required.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh approved accounts</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={i=>i.id} ListHeaderComponent={<View><Text style={styles.title}>Approved account register</Text><Text style={styles.body}>Organization accounts used for journal postings. Registration does not create a balance or confirm a payment.</Text><Text style={styles.body}>An organization administrator registers approved accounts. Finance staff can review this register.</Text>{r.role==='admin'&&<Link href="/finance-account-new" style={styles.link}>Register an approved account →</Link>}{!r.total&&<Text style={styles.body}>No approved accounts registered.</Text>}</View>} renderItem={({item:i})=><View style={styles.card}><Text style={styles.heading}>{i.code} · {i.name}</Text><Text style={styles.body}>{i.classification}</Text><Text style={styles.body}>Approval reason: {i.reason}</Text><Text style={styles.body}>Approved by {i.approver}</Text><Text style={styles.body}>Registered {new Date(i.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text style={styles.body}>Account reference: {i.id}</Text><Link href={{pathname:'/finance-statement',params:{id:i.id}}} style={styles.link}>View account statement →</Link></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} accounts · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" accessibilityState={{disabled:r.page===1}} disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Previous accounts</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{disabled:r.page===r.pages}} disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Next accounts →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh approved accounts</Text></Pressable><Link href="/finance-journals" style={styles.link}>Journal history →</Link><Link href="/finance-trial" style={styles.link}>Trial balance →</Link><Link href="/account" style={styles.link}>Your account →</Link></View>}/>;}
