import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeTrial,formatJmdMinor,statementQuery} from '../lib/finance-trial';
import {supabase} from '../lib/supabase';
export default function Trial(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review the trial balance →</Link></View>;return <Filters key={user.id} owner={user.id}/>;}
function Filters({owner}:{owner:string}){const [today]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Jamaica',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[through,setThrough]=useState(today),[query,setQuery]=useState(today),[error,setError]=useState('');return <View style={{flex:1}}><View style={styles.card}><Text style={styles.heading}>Through date</Text><TextInput accessibilityLabel="Through date YYYY-MM-DD" value={through} onChangeText={setThrough} maxLength={10} autoCapitalize="none" style={styles.input}/><Pressable accessibilityRole="button" onPress={()=>{try{const r=statementQuery({from:through,to:through},today);setQuery(r.to);setError('');}catch{setError('Choose a valid through date using YYYY-MM-DD.');}}}><Text style={styles.link}>View trial balance</Text></Pressable>{!!error&&<Text accessibilityRole="alert" style={styles.body}>{error}</Text>}</View><Register key={owner+query} owner={owner} through={query} today={today}/></View>;}
function Register({owner,through,today}:{owner:string;through:string;today:string}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeTrial(supabase,owner,{through,page:String(page)},today);},[owner,through,page,today]);const result=useLoad(owner+through+page,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading trial balance"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Trial balance unavailable. Confirm your approved finance membership or refresh.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh trial balance</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.accounts} keyExtractor={a=>a.id} ListHeaderComponent={<View><Text style={styles.title}>Trial balance</Text><Text style={styles.body}>Net account balances from all journals posted through {r.through} (Jamaica date). Reversals remain in journal history.</Text><Text style={styles.body}>Total debit balances: {formatJmdMinor(r.debit)}</Text><Text style={styles.body}>Total credit balances: {formatJmdMinor(r.credit)}</Text><Text accessibilityRole={r.balanced?'text':'alert'} style={styles.body}>{r.balanced?'Debit and credit balances agree.':'Balances differ. Investigate the underlying journals.'}</Text><Text style={styles.body}>Agreement does not independently confirm bank settlement.</Text>{!r.total&&<Text style={styles.body}>No approved accounts registered.</Text>}</View>} renderItem={({item:a})=><View style={styles.card}><Text style={styles.heading}>{a.code} · {a.name}</Text><Text style={styles.body}>{a.classification}</Text><Text style={styles.body}>Debit balance {formatJmdMinor(a.debit)} · Credit balance {formatJmdMinor(a.credit)}</Text><Link href={{pathname:'/finance-statement',params:{id:a.id,from:r.through.slice(0,7)+'-01',to:r.through}}} style={styles.link}>Review account statement →</Link></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} accounts · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Previous accounts</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Next accounts →</Text></Pressable><Text style={styles.body}>As of {new Date(r.asOf).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh trial balance</Text></Pressable><Link href="/finance-accounts" style={styles.link}>Approved account register →</Link></View>}/>;}
