import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeJournals} from '../lib/finance-journals';
import {supabase} from '../lib/supabase';
export default function Accounts(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review journal history →</Link></View>;return <Register key={user.id} owner={user.id}/>;}
function Register({owner}:{owner:string}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeJournals(supabase,owner,page);},[owner,page]);const result=useLoad(owner+page,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading journal history"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Journal history unavailable. A verified administrator or finance membership is required.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh journal history</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={i=>i.id} ListHeaderComponent={<View><Text style={styles.title}>Posted journal history</Text><Text style={styles.body}>Approved journal postings are immutable. Corrections are retained as reversal journals. Posting does not independently confirm bank settlement.</Text><Text style={styles.body}>Verified administrators and finance staff can review organization journals.</Text><Link href="/finance-journal-new" style={styles.link}>Review a new posting →</Link>{!r.total&&<Text style={styles.body}>No journals posted.</Text>}</View>} renderItem={({item:i})=><View style={styles.card}><Link href={{pathname:'/finance-journal',params:{id:i.id}}} style={styles.heading}>{i.memo} →</Link><Text style={styles.body}>Approval reason: {i.reason}</Text><Text style={styles.body}>Posted by {i.actor}</Text><Text style={styles.body}>{new Date(i.posted).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} journals · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" accessibilityState={{disabled:r.page===1}} disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Newer journals</Text></Pressable><Pressable accessibilityRole="button" accessibilityState={{disabled:r.page===r.pages}} disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Older journals →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh journal history</Text></Pressable><Link href="/finance-trial" style={styles.link}>Trial balance →</Link><Link href="/" style={styles.link}>Your account →</Link></View>}/>;}
