import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeInvoices,invoiceStates,type InvoiceState} from '../lib/finance-invoices';
import {formatJmdMinor} from '../lib/finance-statement';
import {supabase} from '../lib/supabase';
const labels={submitted:'Submitted',under_review:'Under review',approved:'Approved',rejected:'Rejected'};
export default function Invoices(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review vendor invoices →</Link></View>;return <Filters key={user.id} owner={user.id}/>;}
function Filters({owner}:{owner:string}){const [state,setState]=useState<InvoiceState|null>(null);return <View style={{flex:1}}><View style={styles.card}><Text style={styles.heading}>Invoice status</Text>{([null,...invoiceStates] as const).map(value=><Pressable key={value??'all'} accessibilityRole="radio" accessibilityState={{selected:state===value}} onPress={()=>setState(value)}><Text style={styles.link}>{state===value?'●':'○'} {value?labels[value]:'All invoices'}</Text></Pressable>)}</View><Register key={JSON.stringify([owner,state])} owner={owner} state={state}/></View>;}
function Register({owner,state}:{owner:string;state:InvoiceState|null}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeInvoices(supabase,owner,page,state);},[owner,page,state]);const result=useLoad(JSON.stringify([owner,state,page]),loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading vendor invoices"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Vendor invoices unavailable. Verified administrator, manager or finance membership is required.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh vendor invoices</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={i=>i.id} ListHeaderComponent={<View><Text style={styles.title}>Vendor invoice register</Text><Link href="/finance-invoice-new" style={styles.link}>Submit vendor invoice →</Link><Text style={styles.body}>An approved invoice is not automatically posted to the ledger or paid. Review, approval, ledger posting and bank settlement are separate steps.</Text><Text style={styles.body}>Managers can submit and view invoices. Finance review and approval require independent actors.</Text>{!r.total&&<Text style={styles.body}>No invoices match this status.</Text>}</View>} renderItem={({item:i})=><View style={styles.card}><Text style={styles.heading}>{i.vendor}</Text><Text style={styles.body}>Invoice {i.number} · {labels[i.state]}</Text><Text style={styles.heading}>{formatJmdMinor(i.amount)}</Text><Text style={styles.body}>Submitted {new Date(i.submitted).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text style={styles.body}>Invoice reference: {i.id}</Text><Link href={{pathname:"/finance-invoice",params:{id:i.id}}} style={styles.link}>Review invoice and history →</Link></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} invoices · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} accessibilityState={{disabled:r.page===1}} onPress={()=>{if(r.page>1)setPage(r.page-1);}}><Text style={styles.link}>← Previous invoices</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} accessibilityState={{disabled:r.page===r.pages}} onPress={()=>{if(r.page<r.pages)setPage(r.page+1);}}><Text style={styles.link}>Next invoices →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh vendor invoices</Text></Pressable><Link href="/account" style={styles.link}>Your account →</Link></View>}/>;}
