import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,TextInput,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeStatement,formatJmdMinor,statementQuery} from '../lib/finance-statement';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function Statement(){const params=useLocalSearchParams<{id?:string|string[];from?:string|string[];to?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!validId(id))return <Text accessibilityRole="alert">Valid account reference required.</Text>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review an account statement →</Link></View>;return <Filters key={JSON.stringify([user.id,id,params.from,params.to])} owner={user.id} account={id} initialFrom={params.from} initialTo={params.to}/>;}
function Filters({owner,account,initialFrom,initialTo}:{owner:string;account:string;initialFrom?:string|string[];initialTo?:string|string[]}){const [today]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Jamaica',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[initial]=useState(()=>{try{return statementQuery({from:initialFrom,to:initialTo},today);}catch{return statementQuery({},today);}}),[from,setFrom]=useState(initial.from),[to,setTo]=useState(initial.to),[query,setQuery]=useState({from:initial.from,to:initial.to}),[error,setError]=useState('');return <View style={{flex:1}}><View style={styles.card}><Text style={styles.heading}>Report dates</Text><TextInput accessibilityLabel="From date YYYY-MM-DD" value={from} onChangeText={setFrom} maxLength={10} autoCapitalize="none" style={styles.input}/><TextInput accessibilityLabel="Through date YYYY-MM-DD" value={to} onChangeText={setTo} maxLength={10} autoCapitalize="none" style={styles.input}/><Text style={styles.body}>Use YYYY-MM-DD, spanning up to 367 inclusive days.</Text><Pressable accessibilityRole="button" onPress={()=>{try{const r=statementQuery({from,to},today);setQuery({from:r.from,to:r.to});setError('');}catch{setError('Choose valid dates spanning up to 367 inclusive days.');}}}><Text style={styles.link}>View statement</Text></Pressable>{!!error&&<Text accessibilityRole="alert" style={styles.body}>{error}</Text>}</View><Register key={owner+account+query.from+query.to} owner={owner} account={account} from={query.from} to={query.to} today={today}/></View>;}
function Register({owner,account,from,to,today}:{owner:string;account:string;from:string;to:string;today:string}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeStatement(supabase,owner,account,{from,to,page:String(page)},today);},[owner,account,from,to,page,today]);const result=useLoad(owner+account+from+to+page,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading account statement"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Account statement unavailable. Confirm your approved finance membership or refresh.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh statement</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.entries} keyExtractor={e=>e.id} ListHeaderComponent={<View><Text style={styles.title}>{r.account.code} · {r.account.name}</Text><Text style={styles.body}>{r.account.classification} · {r.from} through {r.to} · Jamaica dates</Text><Text style={styles.body}>Balances use debits minus credits. Negative balances show a net credit. Posted entries do not independently confirm bank settlement.</Text><Text style={styles.body}>Opening balance: {formatJmdMinor(r.opening)}</Text><Text style={styles.body}>Period debits: {formatJmdMinor(r.debit)}</Text><Text style={styles.body}>Period credits: {formatJmdMinor(r.credit)}</Text><Text style={styles.body}>Closing balance: {formatJmdMinor(r.closing)}</Text>{!r.total&&<Text style={styles.body}>No postings in this period.</Text>}</View>} renderItem={({item:e})=><View style={styles.card}><Text style={styles.heading}>{e.memo}</Text><Text style={styles.body}>{new Date(e.posted).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text style={styles.body}>Debit {formatJmdMinor(e.debit)} · Credit {formatJmdMinor(e.credit)} · Balance {formatJmdMinor(e.balance)}</Text><Link href={{pathname:'/finance-journal',params:{id:e.journal}}} style={styles.link}>Review journal {e.journal} →</Link></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} lines · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Previous lines</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Next lines →</Text></Pressable><Text style={styles.body}>Statement as of {new Date(r.asOf).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh statement</Text></Pressable><Link href="/finance-accounts" style={styles.link}>Approved account register →</Link></View>}/>;}
