import {FinanceReversalReview} from '../components/finance-reversal-review';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {financeJournalDetail} from '../lib/finance-journal-detail';
import {formatJmdMinor} from '../lib/finance-statement';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function Journal(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!validId(id))return <Text accessibilityRole="alert">Valid journal reference required.</Text>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review a posted journal →</Link></View>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return financeJournalDetail(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading posted journal"/>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Posted journal unavailable. Check your approved finance membership or refresh.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh journal</Text></Pressable></View>;if(!result.data)return <View style={styles.page}><Text style={styles.body}>No journal is available for this organization.</Text><Link href="/finance-journals" style={styles.link}>Journal history →</Link></View>;const r=result.data,relation=r.outgoing||r.incoming;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>{r.memo}</Text><Text style={styles.body}>Approval reason: {r.reason}</Text><Text style={styles.body}>Posted by {r.actor} · {new Date(r.posted).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text style={styles.body}>Journal reference: {r.id}</Text><Text style={styles.body}>Request reference: {r.request}</Text><Text style={styles.body}>Posted journals are immutable. Posting does not independently confirm bank settlement.</Text>{r.lines.map(l=><View key={l.id} style={styles.card}><Text style={styles.heading}>Line {l.number}</Text><Link href={{pathname:'/finance-statement',params:{id:l.account}}} style={styles.link}>Account {l.account} →</Link><Text style={styles.body}>Debit {formatJmdMinor(l.debit)} · Credit {formatJmdMinor(l.credit)}</Text>{l.property&&<Text style={styles.body}>Property reference: {l.property}</Text>}{l.unit&&<Text style={styles.body}>Unit reference: {l.unit}</Text>}</View>)}<Text style={styles.body}>Debits {formatJmdMinor(r.debit)} · Credits {formatJmdMinor(r.credit)} · Balanced</Text>{relation&&<View style={styles.card}><Text style={styles.heading}>{r.outgoing?'Reversed':'Reversal journal'}</Text><Text style={styles.body}>{relation.reason}</Text><Text style={styles.body}>Recorded by {relation.actor} · {new Date(relation.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Link href={{pathname:'/finance-journal',params:{id:r.outgoing?relation.reversal:relation.original}}} style={styles.link}>{r.outgoing?'Review reversal journal':'Review original journal'} →</Link></View>}<FinanceReversalReview key={owner+id} owner={owner} id={id} memo={r.memo} available={!relation} onRefresh={result.retry}/><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh journal</Text></Pressable><Link href="/finance-journals" style={styles.link}>Journal history →</Link></ScrollView>;}
