import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {catalogQuery} from '../lib/catalog';
import {applicantLeaseReview} from '../lib/lease-reviews';
import {LeaseReviewResponse} from '../components/lease-review-response';
import {supabase} from '../lib/supabase';
export default function Summaries(){const params=useLocalSearchParams<Record<string,string|string[]>>(),id=typeof params.application==='string'?params.application:'invalid',draft=typeof params.draft==='string'?params.draft:'invalid',page=catalogQuery(params).page;const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review shared summaries →</Link></View>;return <Detail key={user.id+id+draft+page} owner={user.id} id={id} draft={draft} page={page}/>;}
function Detail({owner,id,draft,page}:{owner:string;id:string;draft:string;page:number}){
 const loader=useCallback(()=>{if(!supabase)throw Error();return applicantLeaseReview(supabase,owner,id,draft,page);},[owner,id,draft,page]);const result=useLoad(owner+id+draft+page,loader);
 if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading shared lease summaries"/></View>;
 if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Shared summaries could not be loaded.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;
 const data=result.data;
 return <FlatList contentContainerStyle={styles.page} data={data.items} keyExtractor={r=>r.id} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Summary conversation.</Text><Text style={styles.heading}>{data.summary.property_name} · {data.summary.unit_label}</Text><Text style={styles.body}>Summary version {data.summary.version} · {data.summary.state}</Text><Text style={styles.body}>{data.current?'Current released summary.':'Historical summary. Refresh the shared summary register for current terms.'}</Text><Text style={styles.body}>Questions, recorded reviews and property team responses do not sign a lease or authorize payment or move-in.</Text><LeaseReviewResponse key={data.release+":"+data.revision} owner={owner} application={id} draft={draft} release={data.release} version={data.revision} current={data.current} latestAction={data.latestAction} onRefresh={result.retry}/><Text style={styles.body}>{data.total} responses · Page {data.page} of {data.pages}</Text>{!data.total&&<Text style={styles.body}>No responses are recorded yet.</Text>}{!!data.total&&!data.items.length&&<Text style={styles.body}>Responses changed while loading. Refresh to check.</Text>}<Link href={{pathname:'/lease-summaries',params:{application:id}}} style={styles.link}>Shared summaries →</Link></View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.actor_kind==='staff'?'Property team':'Applicant'} · {item.action}</Text>{item.message?<Text style={styles.body}>{item.message}</Text>:<Text style={styles.body}>Summary review recorded.</Text>}<Text style={styles.body}>Response {item.version} · {new Date(item.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text></View>} ListFooterComponent={<View style={{gap:18}}><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh conversation</Text></Pressable></View>}/>;
}
