import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {catalogQuery} from '../lib/catalog';
import {applicantLeaseSummaries,leaseSummaryMoney} from '../lib/lease-summaries';
import {supabase} from '../lib/supabase';
export default function Summaries(){const params=useLocalSearchParams<Record<string,string|string[]>>(),id=typeof params.application==='string'?params.application:'invalid',page=catalogQuery(params).page;const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review shared summaries →</Link></View>;return <Detail key={user.id+id+page} owner={user.id} id={id} page={page}/>;}
function Detail({owner,id,page}:{owner:string;id:string;page:number}){
 const loader=useCallback(()=>{if(!supabase)throw Error();return applicantLeaseSummaries(supabase,owner,id,page);},[owner,id,page]);const result=useLoad(owner+id+page,loader);
 if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading shared lease summaries"/></View>;
 if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Shared summaries could not be loaded.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;
 const data=result.data;
 return <FlatList contentContainerStyle={styles.page} data={data.items} keyExtractor={r=>r.id} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Shared lease summaries.</Text><Text style={styles.body}>Review the terms released by your property team. These summaries do not constitute a signed lease, payment request or move-in authorization.</Text><Text style={styles.body}>{data.total} summaries · Page {data.page} of {data.pages}</Text>{!data.total&&<Text style={styles.body}>Your property team has not shared a lease summary yet.</Text>}{!!data.total&&!data.items.length&&<Text style={styles.body}>Summaries changed while loading. Refresh to check.</Text>}<Link href={{pathname:'/applications/[id]',params:{id}}} style={styles.link}>Application review →</Link></View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.property_name} · {item.unit_label}</Text><Text style={styles.body}>Version {item.version} · {item.state}</Text><Text style={styles.body}>Term: {item.starts_on} to {item.ends_on}</Text><Text style={styles.body}>Monthly rent: {leaseSummaryMoney(item.rent_minor)}</Text><Text style={styles.body}>Deposit: {leaseSummaryMoney(item.deposit_minor)}</Text><Text style={styles.body}>Billing day: {item.billing_day}</Text><Text style={styles.body}>Template: {item.template_title}</Text><Text style={styles.body}>Shared {new Date(item.released_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text><Link href={{pathname:'/lease-review',params:{application:id,draft:item.id}}} style={styles.link}>Review conversation →</Link></View>} ListFooterComponent={<View style={{gap:18}}><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh summaries</Text></Pressable></View>}/>;
}
