import {ManagerPreventiveEditor} from '../components/manager-preventive-editor';
import {ManagerPreventiveDecision} from '../components/manager-preventive-decision';
import {ManagerPreventiveSkips} from '../components/manager-preventive-skips';
import {ManagerPreventiveOccurrences} from '../components/manager-preventive-occurrences';
import {ManagerPreventiveHistory} from '../components/manager-preventive-history';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {managerPreventiveDetail} from '../lib/manager-preventive-detail';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function PlanDetail(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review a preventive plan →</Link></View>;if(!validId(id))return <View style={styles.page}><Text accessibilityRole="alert">Valid plan reference required.</Text><Link href="/manage-preventive-plans" style={styles.link}>Return to plans →</Link></View>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerPreventiveDetail(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading preventive plan"/>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Plan unavailable. Check current management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh plan</Text></Pressable></View>;if(!result.data)return <View style={styles.page}><Text style={styles.body}>This plan is unavailable.</Text><Link href="/manage-preventive-plans" style={styles.link}>Return to plans →</Link></View>;const r=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>{r.title}</Text><Text style={styles.body}>{r.state} · {r.priority} priority · Revision {r.version}</Text><Text style={styles.heading}>Planned work</Text><Text style={styles.body}>{r.description}</Text><Text style={styles.heading}>{r.property}</Text><Text selectable style={styles.body}>Property reference: {r.propertyId}</Text><Text selectable style={styles.body}>{r.unit?`Unit reference: ${r.unit}`:'Property-wide plan'}</Text><Text style={styles.body}>Next due {r.due} · Every {r.interval} days</Text><Text style={styles.body}>Issuing a scheduled occurrence creates a work order. Contractor assignment, appointments, entry and completion are separate decisions.</Text><Text selectable style={styles.body}>Plan reference: {r.id}</Text><ManagerPreventiveEditor owner={owner} id={id} version={r.version} state={r.state} due={r.due} interval={r.interval} initialTitle={r.title} initialDescription={r.description} initialPriority={r.priority} onRefresh={result.retry}/><ManagerPreventiveDecision owner={owner} id={id} version={r.version} state={r.state} due={r.due} interval={r.interval} onRefresh={result.retry}/><ManagerPreventiveOccurrences key={owner+id} owner={owner} id={id}/><ManagerPreventiveSkips key={owner+id} owner={owner} id={id}/><ManagerPreventiveHistory key={owner+id} owner={owner} id={id}/><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh plan</Text></Pressable><Link href="/manage-preventive-plans" style={styles.link}>Return to plans →</Link></ScrollView>;}
