import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {managerPreventivePlans} from '../lib/manager-preventive-plans';
import {supabase} from '../lib/supabase';
export default function PreventivePlans(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review preventive plans →</Link></View>;return <Register key={user.id} owner={user.id}/>;}
function Register({owner}:{owner:string}){const [state,setState]=useState('active'),[page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return managerPreventivePlans(supabase,owner,state,page);},[owner,state,page]);const result=useLoad(owner+state+page,loader);const heading=<View style={{gap:12}}><Text style={styles.title}>Preventive maintenance.</Text><Link href="/manage-preventive-new" style={styles.link}>Create an approved plan →</Link><Text style={styles.body}>Review planned work by due date. A plan does not assign a contractor or confirm completed work.</Text>{['active','paused','retired'].map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:state===value}} onPress={()=>{setState(value);setPage(1);}}><Text style={styles.link}>{state===value?'●':'○'} {value}</Text></Pressable>)}</View>;if(result.loading)return <View style={styles.page}>{heading}<ActivityIndicator accessibilityLabel="Loading preventive plans"/></View>;if(result.error||!result.data)return <View style={styles.page}>{heading}<Text accessibilityRole="alert" style={styles.body}>Plan register unavailable. Check approved management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh plans</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<>{heading}{!r.total&&<Text style={styles.body}>No {state} plans are recorded.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Records changed while loading. Refresh to check.</Text>}</>} renderItem={({item})=><View style={styles.card}><Link href={{pathname:'/manage-preventive-detail',params:{id:item.id}}} style={styles.heading}>{item.title} →</Link><Text style={styles.body}>Due {item.due} · Every {item.interval} days · Revision {item.version}</Text><Text selectable style={styles.body}>Plan reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:12}}><Text style={styles.body}>{r.total} plans · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Earlier plans</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Later plans →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh plans</Text></Pressable><Link href="/manage-work" style={styles.link}>Open management work queue →</Link></View>}/>;}
