import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {catalogQuery} from '../lib/catalog';
import {managerWork,workStates,workState} from '../lib/manager-work';
import {supabase} from '../lib/supabase';
export default function Queue(){const params=useLocalSearchParams<Record<string,string|string[]>>(),page=catalogQuery(params).page,state=workState(params.state);const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view management work →</Link></View>;return <Register key={user.id+page+state} owner={user.id} page={page} state={state}/>;}
function Register({owner,page,state}:{owner:string;page:number;state:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerWork(supabase,owner,page,state);},[owner,page,state]);const result=useLoad(owner+page+state,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading management work queue"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>The work queue could not be loaded. Confirm your approved management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh work queue</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<View style={{gap:12}}><Text style={styles.title}>Management work queue.</Text><Text style={styles.body}>Current recorded work-order states for your organization. Priority reflects the recorded triage decision.</Text>{['',...workStates].map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:state===value}} onPress={()=>router.setParams({state:value,page:'1'})}><Text style={styles.link}>{state===value?'●':'○'} {value?value.replaceAll('_',' '):'All states'}</Text></Pressable>)}{!r.total&&<Text style={styles.body}>No work orders match this view.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Records changed while loading. Refresh to check.</Text>}</View>} renderItem={({item})=><View style={styles.card}><Link href={{pathname:"/manage-work-detail",params:{id:item.id}}} style={styles.heading}>{item.title} →</Link><Text style={styles.body}>{item.state.replaceAll('_',' ')} · {item.priority} priority</Text><Text style={styles.body}>Reported {new Date(item.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text selectable style={styles.body}>Work reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:12}}><Text style={styles.body}>{r.total} work orders · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>router.setParams({page:String(r.page-1)})}><Text style={styles.link}>← Newer work orders</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>router.setParams({page:String(r.page+1)})}><Text style={styles.link}>Older work orders →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh work queue</Text></Pressable></View>}/>;}
