import {AdminInvitationEditor} from '../components/admin-invitation-editor';
import {AdminInvitationHistory} from '../components/admin-invitation-history';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {adminInvitationDetail} from '../lib/admin-invitation-detail';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function AssignmentDetail(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review a staff invitation →</Link></View>;if(!validId(id))return <View style={styles.page}><Text accessibilityRole="alert">Valid assignment reference required.</Text><Link href="/manage-invitations" style={styles.link}>Invitation register → →</Link></View>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return adminInvitationDetail(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading staff invitation"/>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Assignment unavailable. Check current administrator membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignment</Text></Pressable></View>;if(!result.data)return <View style={styles.page}><Text style={styles.body}>This assignment is unavailable.</Text><Link href="/manage-invitations" style={styles.link}>Invitation register → →</Link></View>;const r=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Staff invitation</Text><Text style={styles.heading}>{r.email}</Text><Text style={styles.body}>{r.role} · {r.state} · Revision {r.version}</Text><Text style={styles.body}>Expires {new Date(r.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time). Expiry may close a pending invitation before it is recorded as expired.</Text><Text style={styles.body}>The recipient must verify this exact email and accept current approval before receiving staff access. Invitation status does not prove email delivery; check the delivery monitor on the web.</Text><Text style={styles.body}>Recorded {new Date(r.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><AdminInvitationEditor key={owner+id+r.version} owner={owner} invitation={r}/><AdminInvitationHistory key={owner+id} owner={owner} id={id}/><Text selectable style={styles.body}>Assignment reference: {r.id}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignment</Text></Pressable><Link href="/manage-invitations" style={styles.link}>Invitation register →</Link></ScrollView>;}
