import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {managerContractorReport} from '../lib/manager-contractor-report';
import {reportPeriod} from '../../../lib/reports/period';
import {supabase} from '../lib/supabase';
export default function ContractorReport(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view management reports →</Link></View>;return <Report key={user.id} owner={user.id}/>;}
function Report({owner}:{owner:string}){const [start,setStart]=useState(''),[end,setEnd]=useState(''),[applied,setApplied]=useState({start:'',end:''}),[message,setMessage]=useState('');return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Contractor coordination.</Text><Text style={styles.body}>Current stored offer, appointment and completion-report states, grouped by creation date in Jamaica. This is not appointment time or response time.</Text><TextInput accessibilityLabel="Created from (YYYY-MM-DD)" value={start} maxLength={10} onChangeText={setStart} style={styles.input}/><TextInput accessibilityLabel="Created through (YYYY-MM-DD)" value={end} maxLength={10} onChangeText={setEnd} style={styles.input}/><Pressable accessibilityRole="button" onPress={()=>{try{reportPeriod({start,end});setApplied({start,end});setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Check report dates.');}}}><Text style={styles.link}>Apply period</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{setStart('');setEnd('');setApplied({start:'',end:''});setMessage('');}}><Text style={styles.link}>All dates</Text></Pressable>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}<Metrics key={owner+applied.start+applied.end} owner={owner} start={applied.start} end={applied.end}/><Link href="/manage-work" style={styles.link}>Open management work queue →</Link></ScrollView>;}
function Metrics({owner,start,end}:{owner:string;start:string;end:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerContractorReport(supabase,owner,start,end);},[owner,start,end]);const result=useLoad(owner+start+end,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading contractor coordination counts"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Report unavailable. Check current management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh report</Text></Pressable></View>;const r=result.data;return <View style={{gap:12}}><Text style={styles.heading}>{r.period?`${r.period.start} through ${r.period.end} (Jamaica)`:'All report dates'}</Text><Text style={styles.body}>Counts are read independently and can change while loading.</Text>{['Work offers','Appointments','Completion reports'].map(title=><View key={title} style={{gap:12}}><Text style={styles.heading}>{title}</Text>{r.rows.filter(row=>row.title===title).map(row=><View key={row.key} style={styles.card}><Text style={styles.body}>{row.state.replaceAll('_',' ')}: {row.count===null?'Unavailable':row.count.toLocaleString('en-JM')}</Text></View>)}</View>)}{r.rows.some(row=>row.count===null)&&<Text accessibilityRole="alert" style={styles.body}>Some counts are unavailable. Refresh before making a decision.</Text>}<Text style={styles.body}>These are record counts, not unique contractors or performance ratings. Offered records may have passed their response window before expiry is recorded. A confirmed appointment does not prove entry, attendance or completion.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh report</Text></Pressable></View>;}
