import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {managerWorkDetail} from '../lib/manager-work-detail';
import {ManagerCurrentVisit} from '../components/manager-current-visit';
import {ManagerCurrentOffer} from '../components/manager-current-offer';
import {ManagerOfferHistory} from '../components/manager-offer-history';
import {ManagerPresenceHistory} from '../components/manager-presence-history';
import {ManagerWorkHistory} from '../components/manager-work-history';
import {ManagerWorkTransition} from '../components/manager-work-transition';
import {supabase} from '../lib/supabase';
export default function Detail(){const params=useLocalSearchParams<Record<string,string|string[]>>(),id=typeof params.id==='string'?params.id:'invalid';const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view management work →</Link></View>;return <Record key={user.id+id} owner={user.id} id={id}/>;}
function Record({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerWorkDetail(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading private work detail"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>This work order could not be loaded. Confirm the reference and your current management access.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh work order</Text></Pressable><Link href="/manage-work" style={styles.link}>Work queue →</Link></View>;const r=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>{r.title}</Text><Text style={styles.body}>{r.state.replaceAll('_',' ')} · {r.priority} priority · Revision {r.version}</Text><Text style={styles.body}>{r.description}</Text><View style={styles.card}><Text style={styles.heading}>{r.property}</Text><Text selectable style={styles.body}>Property reference: {r.propertyId}</Text>{r.unit&&<Text selectable style={styles.body}>Unit reference: {r.unit}</Text>}</View><Text style={styles.body}>Reported {new Date(r.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text selectable style={styles.body}>Reported by: {r.reporter||'Baseline record'}</Text><ManagerWorkTransition key={r.id+':'+r.version} owner={owner} id={r.id} version={r.version} state={r.state} initialPriority={r.priority} onRefresh={result.retry}/><ManagerCurrentOffer key={r.id+':offer:'+r.version} owner={owner} work={id} onRefresh={result.retry}/><ManagerCurrentVisit key={r.id+':visit:'+r.version} owner={owner} work={id}/><ManagerOfferHistory key={r.id+':offers:'+r.version} owner={owner} id={id}/><ManagerPresenceHistory key={r.id+':presence:'+r.version} owner={owner} id={id}/><ManagerWorkHistory key={r.id+':history:'+r.version} owner={owner} id={id}/><Text selectable style={styles.body}>Work reference: {r.id}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh work order</Text></Pressable><Link href="/manage-work" style={styles.link}>Work queue →</Link></ScrollView>;}
