import {AdminOwnerAccessDecision} from '../components/admin-owner-access-decision';
import {AdminOwnerAccessHistory} from '../components/admin-owner-access-history';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {adminOwnerAccessDetail} from '../lib/admin-owner-access-detail';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function AssignmentDetail(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review a owner access record →</Link></View>;if(!validId(id))return <View style={styles.page}><Text accessibilityRole="alert">Valid assignment reference required.</Text><Link href="/manage-owner-access" style={styles.link}>Owner access register → →</Link></View>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return adminOwnerAccessDetail(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading owner access record"/>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Assignment unavailable. Check current administrator membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignment</Text></Pressable></View>;if(!result.data)return <View style={styles.page}><Text style={styles.body}>This assignment is unavailable.</Text><Link href="/manage-owner-access" style={styles.link}>Owner access register → →</Link></View>;const r=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Owner portfolio access</Text><Text style={styles.heading}>{r.property.name}</Text><Text style={styles.body}>{r.active?'Active':'Inactive'} · Revision {r.version}</Text><Text selectable style={styles.body}>Approved owner account reference: {r.user}</Text><Text selectable style={styles.body}>Property reference: {r.property.property}</Text><Text style={styles.body}>Access authorizes portfolio reporting for this property. It does not establish legal title or ownership shares.</Text><Text style={styles.body}>Recorded {new Date(r.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><AdminOwnerAccessDecision owner={owner} id={id} version={r.version} initialActive={r.active} onRefresh={result.retry}/><AdminOwnerAccessHistory key={owner+id} owner={owner} id={id}/><Text selectable style={styles.body}>Assignment reference: {r.id}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignment</Text></Pressable><Link href="/manage-owner-access" style={styles.link}>Owner access register →</Link></ScrollView>;}
