import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {managerMaintenanceReport} from '../lib/manager-maintenance-report';
import {reportPeriod} from '../../../lib/reports/period';
import {supabase} from '../lib/supabase';
export default function MaintenanceReport(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view management reports →</Link></View>;return <Report key={user.id} owner={user.id}/>;}
function Report({owner}:{owner:string}){const [start,setStart]=useState(''),[end,setEnd]=useState(''),[applied,setApplied]=useState({start:'',end:''}),[message,setMessage]=useState('');return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Maintenance workload.</Text><Text style={styles.body}>Current states of work reported within the selected Jamaica dates. These counts do not measure work completed during the period.</Text><TextInput accessibilityLabel="Reported from (YYYY-MM-DD)" value={start} maxLength={10} onChangeText={setStart} style={styles.input}/><TextInput accessibilityLabel="Reported through (YYYY-MM-DD)" value={end} maxLength={10} onChangeText={setEnd} style={styles.input}/><Pressable accessibilityRole="button" onPress={()=>{try{reportPeriod({start,end});setApplied({start,end});setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Check report dates.');}}}><Text style={styles.link}>Apply period</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{setStart('');setEnd('');setApplied({start:'',end:''});setMessage('');}}><Text style={styles.link}>All dates</Text></Pressable>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}<Metrics key={owner+applied.start+applied.end} owner={owner} start={applied.start} end={applied.end}/><Link href="/manage-work" style={styles.link}>Open management work queue →</Link></ScrollView>;}
function Metrics({owner,start,end}:{owner:string;start:string;end:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerMaintenanceReport(supabase,owner,start,end);},[owner,start,end]);const result=useLoad(owner+start+end,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading maintenance counts"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Report unavailable. Check current management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh report</Text></Pressable></View>;const r=result.data;return <View style={{gap:12}}><Text style={styles.heading}>{r.period?`${r.period.start} through ${r.period.end} (Jamaica)`:'All report dates'}</Text><Text style={styles.body}>Counts are read independently and can change while loading.</Text><Text style={styles.heading}>Work orders by current state</Text>{r.rows.filter(row=>row.state).map(row=><View key={row.key} style={styles.card}><Link href={{pathname:'/manage-work',params:{state:row.state}}} style={styles.link}>{row.state.replaceAll('_',' ')} →</Link><Text style={styles.body}>{row.count===null?'Unavailable':row.count.toLocaleString('en-JM')}</Text></View>)}<Text style={styles.heading}>Open work by priority</Text><Text style={styles.body}>Open excludes completed, closed and cancelled work. Priority does not establish a contractual response deadline.</Text>{r.rows.filter(row=>row.priority).map(row=><View key={row.key} style={styles.card}><Text style={styles.body}>{row.priority}: {row.count===null?'Unavailable':row.count.toLocaleString('en-JM')}</Text></View>)}{r.rows.some(row=>row.count===null)&&<Text accessibilityRole="alert" style={styles.body}>Some counts are unavailable. Refresh before making a decision.</Text>}<Text style={styles.body}>Queue links show all dates for the selected state.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh report</Text></Pressable></View>;}
