import {ManagerSecurityDecision} from '../components/manager-security-decision';
import {ManagerSecurityHistory} from '../components/manager-security-history';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {managerSecurityAssignment} from '../lib/manager-security-assignment';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function AssignmentDetail(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review a security assignment →</Link></View>;if(!validId(id))return <View style={styles.page}><Text accessibilityRole="alert">Valid assignment reference required.</Text><Link href="/manage-security" style={styles.link}>Property security register → →</Link></View>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerSecurityAssignment(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading security assignment"/>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Assignment unavailable. Check current management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignment</Text></Pressable></View>;if(!result.data)return <View style={styles.page}><Text style={styles.body}>This assignment is unavailable.</Text><Link href="/manage-security" style={styles.link}>Property security register → →</Link></View>;const r=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Property security assignment</Text><Text style={styles.heading}>{r.property.name}</Text><Text style={styles.body}>{r.active?'Active':'Inactive'} · Revision {r.version}</Text><Text selectable style={styles.body}>Security account reference: {r.user}</Text><Text selectable style={styles.body}>Property reference: {r.property.property}</Text><Text style={styles.body}>Assignment authorizes eligible security entry workflows for this property. It does not grant internal work or resident-record access.</Text><Text style={styles.body}>Recorded {new Date(r.created).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><ManagerSecurityDecision owner={owner} id={id} version={r.version} initialActive={r.active} onRefresh={result.retry}/><ManagerSecurityHistory key={owner+id} owner={owner} id={id}/><Text selectable style={styles.body}>Assignment reference: {r.id}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignment</Text></Pressable><Link href="/manage-security" style={styles.link}>Property security register →</Link></ScrollView>;}
