import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,ScrollView,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {AdminInvitationEditor} from '../components/admin-invitation-editor';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {adminInvitations} from '../lib/admin-invitations';
import {supabase} from '../lib/supabase';
export default function Invitations(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review staff invitations →</Link></View>;return <Register key={user.id} owner={user.id}/>;}
function Register({owner}:{owner:string}){const [page,setPage]=useState(1),[creating,setCreating]=useState(false),loader=useCallback(()=>{if(!supabase)throw Error();return adminInvitations(supabase,owner,page);},[owner,page]);const result=useLoad(owner+page,loader);if(creating)return <ScrollView contentContainerStyle={styles.page}><AdminInvitationEditor owner={owner}/></ScrollView>;if(result.loading)return <ActivityIndicator accessibilityLabel="Loading invitations"/>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Invitations unavailable. Check current administrator membership or refresh.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invitations</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={i=>i.id} ListHeaderComponent={<View><Text style={styles.title}>Invite your team</Text><Text style={styles.body}>Invitations reserve an approved role for one verified email. Existing staff access is managed in the membership register. Invitation status does not prove email delivery.</Text><Pressable accessibilityRole="button" onPress={()=>setCreating(true)}><Text style={styles.link}>Create approved invitation →</Text></Pressable><Link href="/manage-staff" style={styles.link}>Staff membership register →</Link>{!r.total&&<Text style={styles.body}>No staff invitations recorded.</Text>}</View>} renderItem={({item:i})=><View style={styles.card}><Link href={{pathname:'/manage-invitation-detail',params:{id:i.id}}} style={styles.heading}>{i.email} →</Link><Text style={styles.body}>{i.role} · {i.state} · Revision {i.version}</Text><Text style={styles.body}>Expires {new Date(i.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text></View>} ListFooterComponent={<View><Text style={styles.body}>{r.total} invitations · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Newer invitations</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Older invitations →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invitations</Text></Pressable></View>}/>;}
