import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {ownerPortfolio,formatJmdMinor,statementQuery} from '../lib/owner-portfolio';
import {supabase} from '../lib/supabase';
export default function Portfolio(){const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view your approved portfolio →</Link></View>;return <Filters key={user.id} owner={user.id}/>;}
function Filters({owner}:{owner:string}){const [today]=useState(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Jamaica',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())),[from,setFrom]=useState(today.slice(0,7)+'-01'),[to,setTo]=useState(today),[query,setQuery]=useState({from:today.slice(0,7)+'-01',to:today}),[error,setError]=useState('');return <View style={{flex:1}}><View style={styles.card}><Text style={styles.heading}>Report dates</Text><TextInput accessibilityLabel="From date YYYY-MM-DD" value={from} onChangeText={setFrom} maxLength={10} autoCapitalize="none" style={styles.input}/><TextInput accessibilityLabel="Through date YYYY-MM-DD" value={to} onChangeText={setTo} maxLength={10} autoCapitalize="none" style={styles.input}/><Text style={styles.body}>Use YYYY-MM-DD, spanning up to 367 inclusive days.</Text><Pressable accessibilityRole="button" onPress={()=>{try{const r=statementQuery({from,to},today);setQuery({from:r.from,to:r.to});setError('');}catch{setError('Choose valid dates spanning up to 367 inclusive days.');}}}><Text style={styles.link}>Update report</Text></Pressable>{!!error&&<Text accessibilityRole="alert" style={styles.body}>{error}</Text>}</View><Register key={owner+query.from+query.to} owner={owner} from={query.from} to={query.to} today={today}/></View>;}
function Register({owner,from,to,today}:{owner:string;from:string;to:string;today:string}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return ownerPortfolio(supabase,owner,{from,to,page:String(page)},today);},[owner,from,to,page,today]);const result=useLoad(owner+from+to+page,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading approved portfolio"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>The portfolio could not be loaded. Confirm approved property access with Open House or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh portfolio</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.properties} keyExtractor={p=>p.id} ListHeaderComponent={<View style={{gap:12}}><Text style={styles.title}>Your approved properties.</Text><Text style={styles.body}>{r.from} through {r.to} · Jamaica dates</Text><Text style={styles.body}>Amounts reflect property-attributed posted income and expenses. They do not show cash collected or distributions owed. Unit and maintenance counts reflect current records.</Text><Text style={styles.body}>Verified occupancy reporting awaits tenancy activation.</Text>{!r.total&&<Text style={styles.body}>No properties currently have approved portfolio access for this account. Contact Open House to review access.</Text>}{!!r.total&&!r.properties.length&&<Text style={styles.body}>Records changed while loading. Refresh to check.</Text>}</View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.name}</Text>{item.area&&<Text style={styles.body}>{item.area}</Text>}<Text style={styles.body}>{item.units} managed units · {item.openWork} current open work orders</Text><Text style={styles.body}>Posted income: {formatJmdMinor(item.income)}</Text><Text style={styles.body}>Posted expenses: {formatJmdMinor(item.expenses)}</Text><Text style={styles.body}>Posted net income: {formatJmdMinor(item.net)}</Text></View>} ListFooterComponent={<View style={{gap:12}}><Text style={styles.body}>{r.total} properties · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Previous properties</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Next properties →</Text></Pressable><Text style={styles.body}>Generated {new Date(r.asOf).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh portfolio</Text></Pressable></View>}/>;}
