import {useEffect,useRef,useState} from 'react';
import {KeyboardAvoidingView,Platform,ScrollView,Text,TextInput,Pressable} from 'react-native';
import {Link} from 'expo-router';
import {supabase} from '../lib/supabase';
import {registerNativeAccount} from '../lib/account-access';
import {styles} from '../components/styles';
export default function Register(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);try{await registerNativeAccount(supabase,email,password,consent);if(!mounted.current)return;complete.current=true;setDone(true);setPassword('');setMessage('If registration is available for this email, check your inbox and spam folder. Open the newest confirmation on this device, then sign in. This does not confirm email delivery or account access.');}catch(error){if(mounted.current)setMessage(error instanceof Error&&error.message==='Sign out before creating another account.'?error.message:'Registration could not be confirmed. Use a valid email, a password of at least 12 characters and confirm account creation. Check your email before retrying.');}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.page}><Text style={styles.title}>Find your place.</Text><Text style={styles.body}>Create your prospect account. Staff and resident access is assigned separately by the Open House team.</Text>{!supabase&&<Text style={styles.body}>Account connection is unavailable.</Text>}{!done&&<><TextInput accessibilityLabel="Email" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" value={email} onChangeText={setEmail} editable={!busy} style={styles.input}/><TextInput accessibilityLabel="New password, at least 12 characters" secureTextEntry textContentType="newPassword" value={password} onChangeText={setPassword} editable={!busy} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:consent,disabled:busy}} disabled={busy} onPress={()=>setConsent(!consent)}><Text style={styles.body}>{consent?'☑':'☐'} I want to create an account using this email.</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||!consent||!supabase} onPress={()=>void submit()} style={styles.button}><Text style={styles.buttonText}>{busy?'Requesting registration…':'Create account'}</Text></Pressable></>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}<Link href="/sign-in" style={styles.link}>Already have an account? Sign in →</Link></ScrollView></KeyboardAvoidingView>;
}
