import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {SaveProperty} from '../components/save-property';
import {ListingCard} from '../components/listing-card';
import {catalogQuery} from '../lib/catalog';
import {savedProperties} from '../lib/saves';
import {supabase} from '../lib/supabase';
import {styles} from '../components/styles';
export default function Saved(){const {user,loading,error,refresh}=useIdentity();const page=catalogQuery(useLocalSearchParams<Record<string,string|string[]>>()).page;if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking your account"/></View>;if(!user)return <View style={styles.page}><Text style={styles.title}>Your saved properties.</Text><Link href="/demo-saved" style={styles.link}>Explore your demo shortlist →</Link><Text style={styles.body}>{error||'Sign in with your verified account to view your saved properties.'}</Text><Link href="/sign-in" style={styles.link}>Sign in →</Link>{!!error&&<Pressable accessibilityRole="button" onPress={()=>void refresh()}><Text style={styles.link}>Check account again</Text></Pressable>}</View>;return <SavedContent key={user.id+':'+page} owner={user.id} page={page}/>;}
function SavedContent({owner,page}:{owner:string;page:number}){
 const loader=useCallback(()=>{if(!supabase)throw new Error('Connection unavailable');return savedProperties(supabase,owner,page);},[owner,page]);
 const result=useLoad(owner+':'+page,loader);
 return <FlatList contentContainerStyle={styles.page} data={result.data?.rows||[]} keyExtractor={row=>row.id} ItemSeparatorComponent={()=><View style={{height:18}}/>} renderItem={({item})=><View style={{gap:12}}>{item.listing?<ListingCard row={item.listing}/>:<View style={styles.card}><Text style={styles.heading}>Property no longer published</Text><Text style={styles.body}>Private or withdrawn property details are unavailable.</Text></View>}<SaveProperty listingId={item.id} removeOnly onChanged={result.retry}/></View>} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Your saved properties.</Text><Link href="/demo-saved" style={styles.link}>Explore your demo shortlist →</Link><Text style={styles.body}>Keep your shortlist with your verified account.</Text>{result.loading?<ActivityIndicator accessibilityLabel="Loading saved properties"/>:result.error?<><Text accessibilityRole="alert" style={styles.body}>Unable to load your saved properties.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></>:result.data&&<><Text style={styles.body}>{result.data.total} saved · Page {result.data.page} of {result.data.pages}</Text>{result.data.total===0?<Text style={styles.body}>You haven’t saved any properties yet.</Text>:result.data.rows.length===0&&<Text style={styles.body}>Your shortlist changed while loading. Refresh to see its current state.</Text>}</>}<Link href="/listings" style={styles.link}>Explore properties →</Link></View>} ListFooterComponent={result.data&&<View style={{gap:18,paddingTop:24}}><View style={{flexDirection:'row',justifyContent:'space-between'}}><Pressable accessibilityRole="button" disabled={result.data.page===1} onPress={()=>router.setParams({page:String(result.data!.page-1)})}><Text style={styles.link}>← Previous</Text></Pressable><Pressable accessibilityRole="button" disabled={result.data.page===result.data.pages} onPress={()=>router.setParams({page:String(result.data!.page+1)})}><Text style={styles.link}>Next →</Text></Pressable></View><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh saved properties</Text></Pressable></View>}/>;
}
