import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {validId} from '../lib/catalog';
import {securityEntry} from '../lib/security-entry';
import {SecurityHistory} from '../components/security-presence-history';
import {SecurityPresence} from '../components/security-presence';
import {supabase} from '../lib/supabase';
export default function Entry(){const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to check an entry permit →</Link></View>;return <Lookup key={user.id} owner={user.id}/>;}
function Lookup({owner}:{owner:string}){const [input,setInput]=useState(''),[permit,setPermit]=useState(''),[error,setError]=useState('');return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Check an entry permit.</Text><Text style={styles.body}>Use the reference supplied by the contractor or property manager. Your verified account must have current security coverage for the property.</Text><TextInput accessibilityLabel="Permit reference" autoCapitalize="none" autoCorrect={false} maxLength={36} value={input} onChangeText={setInput} style={styles.input}/><Pressable accessibilityRole="button" onPress={()=>{const value=input.trim();if(!validId(value)){setError('Enter the full permit reference.');return;}setError('');setPermit(value);}}><Text style={styles.link}>Check permit</Text></Pressable>{!!error&&<Text accessibilityRole="alert" style={styles.body}>{error}</Text>}{!!permit&&<Snapshot key={owner+permit} owner={owner} permit={permit}/>}</ScrollView>;}
function Snapshot({owner,permit}:{owner:string;permit:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return securityEntry(supabase,owner,permit);},[owner,permit]);const result=useLoad(owner+permit,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Checking assigned permit"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>This permit could not be checked. Confirm the reference and your current security assignment with management.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Check again</Text></Pressable></View>;const r=result.data,time=(v:string)=>new Date(v).toLocaleString('en-JM',{timeZone:'America/Jamaica'});return <View style={styles.card}><Text style={styles.heading}>{r.property}</Text><Text style={styles.heading}>{r.company}</Text><Text style={styles.body}>{r.title}</Text><Text style={styles.body}>Permit: {r.state} · {time(r.from)} to {time(r.until)} (Jamaica time)</Text><Text style={styles.body}>{r.instructions}</Text>{r.arrival&&<Text style={styles.body}>Arrival: {time(r.arrival)}</Text>}{r.departure&&<Text style={styles.body}>Departure: {time(r.departure)}</Text>}<Text style={styles.body}>{r.presenceState==='on_site'?'Arrival is recorded. Departure must be recorded separately.':r.presenceState==='exited'?'Departure is recorded. Another visit requires a new appointment and permit.':r.entryAllowed?'At the time of this check the permit is eligible for entry. Verify visitor identity and refresh before recording arrival.':'Entry is unavailable. Contact management to review the appointment or permit.'}</Text>{(r.presenceState==='on_site'||r.entryAllowed)&&<SecurityPresence key={r.permit+':'+r.presenceVersion} owner={owner} permit={permit} presence={r.presence} version={r.presenceVersion??0} onRefresh={result.retry}/>}{r.presence&&<SecurityHistory key={r.permit+':history:'+r.presenceVersion} owner={owner} permit={permit}/>}<Text selectable style={styles.body}>Permit reference: {r.permit}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh permit status</Text></Pressable></View>;}
