import {useEffect,useRef,useState} from 'react';
import {KeyboardAvoidingView,Platform,ScrollView,Text,TextInput,Pressable} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {invitationReturnId} from '../lib/invitation-link';
import {supabase} from '../lib/supabase';
import {useIdentity} from '../components/identity';
import {RecoveryRequest} from '../components/recovery-request';
import {ConfirmationResend} from '../components/confirmation-resend';
import {verifiedPasswordSignIn} from '../lib/account-access';
import {styles} from '../components/styles';
export default function SignIn(){const params=useLocalSearchParams<{invitation?:string|string[]}>();const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false);const {refresh}=useIdentity();
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function submit(){if(active.current||complete.current||!mounted.current)return;if(!supabase){setMessage('Account connection is not configured for this app.');return;}const invitation=invitationReturnId(params.invitation);active.current=true;setBusy(true);setMessage('');try{const expected=await verifiedPasswordSignIn(supabase,email,password);if(!mounted.current)return;setPassword('');await refresh();if(!mounted.current)return;const current=await supabase.auth.getUser();if(current.error||current.data.user?.id!==expected||!current.data.user.email_confirmed_at||current.data.user.is_anonymous)throw Error('Your signed-in account could not be verified. Try again.');if(!mounted.current)return;complete.current=true;if(invitation)router.replace({pathname:'/team-invitation',params:{id:invitation}});else router.replace('/');}catch(error){if(mounted.current)setMessage(error instanceof Error&&['Enter a valid email and password.','Unable to sign in. Check your details and try again.','Verify your email before signing in.','Your signed-in account could not be verified. Try again.','Account access could not be confirmed. Try signing out and signing in again.'].includes(error.message)?error.message:'Unable to sign in or save your session. Try again.');}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.page}><Text style={styles.title}>Welcome home.</Text><Text style={styles.body}>Sign in with your verified Open House account.</Text><Text style={styles.body}>Email</Text><TextInput accessibilityLabel="Email" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" textContentType="emailAddress" value={email} onChangeText={setEmail} editable={!busy} style={styles.input}/><Text style={styles.body}>Password</Text><TextInput accessibilityLabel="Password" secureTextEntry textContentType="password" value={password} onChangeText={setPassword} editable={!busy} style={styles.input}/><Pressable accessibilityRole="button" accessibilityState={{disabled:busy}} disabled={busy} onPress={()=>void submit()} style={styles.button}><Text style={styles.buttonText}>{busy?'Signing in…':'Sign in'}</Text></Pressable>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}<RecoveryRequest/><ConfirmationResend/><Link href="/register" style={styles.link}>Create an account →</Link></ScrollView></KeyboardAvoidingView>;
}
