import {TeamInvitationDecision} from '../components/team-invitation-decision';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {teamInvitation} from '../lib/team-invitations';
import {validId} from '../lib/catalog';
import {supabase} from '../lib/supabase';
export default function Invitation(){const params=useLocalSearchParams<{id?:string|string[]}>(),id=typeof params.id==='string'?params.id:'';const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <View style={styles.page}><Link href={validId(id)?{pathname:'/sign-in',params:{invitation:id}}:'/sign-in'} style={styles.link}>Sign in with the invited account →</Link></View>;if(!validId(id))return <Text accessibilityRole="alert">Valid invitation reference required.</Text>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return teamInvitation(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading your invitation"/>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Invitation unavailable. Check your verified email or refresh.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invitation</Text></Pressable></View>;if(!result.data)return <View style={styles.page}><Text style={styles.body}>No invitation is available for this verified account.</Text><Link href="/team-invitations" style={styles.link}>Your invitations →</Link></View>;const r=result.data;return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Join {r.organization}</Text><Text style={styles.heading}>Approved role: {r.role}</Text><Text style={styles.body}>Invited email: {r.email} · Status: {r.state} · Revision {r.version}</Text><Text style={styles.body}>Expires {new Date(r.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text><Text style={styles.body}>Accepting grants the organization access associated with this approved role. Review the invitation with the team if you do not recognize it.</Text>{r.blocked&&<Text accessibilityRole="alert" style={styles.body}>{r.blocked}</Text>}<TeamInvitationDecision key={owner+id+r.version} owner={owner} invitation={r} onRefresh={result.retry}/><Text style={styles.body}>{r.canAccept?'Acceptance is currently available.':'Acceptance is currently unavailable.'} {r.canDecline?'Decline is currently available.':'Decline is currently unavailable.'}</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invitation</Text></Pressable><Link href="/team-invitations" style={styles.link}>Your invitations →</Link></ScrollView>;}
