import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {catalogQuery} from '../lib/catalog';
import {contractorWorkOffers,offerState} from '../lib/work-offers';
import {supabase} from '../lib/supabase';
export default function Offers(){const params=useLocalSearchParams<Record<string,string|string[]>>(),page=catalogQuery(params).page,state=offerState(params.state);const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view your contractor work →</Link></View>;return <Register key={user.id+page+state} owner={user.id} page={page} state={state}/>;}
function Register({owner,page,state}:{owner:string;page:number;state:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return contractorWorkOffers(supabase,owner,page,state);},[owner,page,state]);const result=useLoad(owner+page+state,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading contractor work offers"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Work offers could not be loaded.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;const data=result.data;return <FlatList contentContainerStyle={styles.page} data={data.rows} keyExtractor={r=>r.id} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Your contractor work.</Text><Text style={styles.body}>Work offers describe the approved assignment. Visit scheduling and entry authorization are separate.</Text>{!data.registered?<Text style={styles.body}>No active contractor registration is linked to your verified account. Contact the Open House team about an approved registration.</Text>:<><View style={{gap:8}}>{['','offered','accepted','declined','withdrawn','expired','completed'].map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:state===value}} onPress={()=>router.setParams({state:value,page:'1'})}><Text style={styles.link}>{state===value?'●':'○'} {value||'All states'}</Text></Pressable>)}</View><Text style={styles.body}>{data.total} offers · Page {data.page} of {data.pages}</Text>{!data.total&&<Text style={styles.body}>No offers match this view.</Text>}{!!data.total&&!data.rows.length&&<Text style={styles.body}>Offers changed while loading. Refresh to check.</Text>}</>}<Link href="/account" style={styles.link}>Your account →</Link></View>} renderItem={({item})=><View style={styles.card}><Link href={{pathname:"/work-offer",params:{id:item.id}}} style={styles.heading}>{item.title} →</Link><Text style={styles.body}>{item.trade} · {item.expired?'Expired':item.state}</Text><Text style={styles.body}>Expires {new Date(item.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text><Text selectable style={styles.body}>Offer reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:18}}>{data.registered&&<><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable></>}<Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh work offers</Text></Pressable></View>}/>;}
