import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {catalogQuery} from '../lib/catalog';
import {contractorVisitHistory} from '../lib/contractor-visit-history';
import {supabase} from '../lib/supabase';
export default function Visits(){const params=useLocalSearchParams<Record<string,string|string[]>>(),offer=typeof params.offer==='string'?params.offer:'invalid',page=catalogQuery(params).page;const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view retained appointments →</Link></View>;return <Register key={user.id+offer+page} owner={user.id} offer={offer} page={page}/>;}
function Register({owner,offer,page}:{owner:string;offer:string;page:number}){const loader=useCallback(()=>{if(!supabase)throw Error();return contractorVisitHistory(supabase,owner,offer,page);},[owner,offer,page]);const result=useLoad(owner+offer+page,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading appointment history"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Appointment history could not be loaded.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;const data=result.data,date=(v:string)=>new Date(v).toLocaleString('en-JM',{timeZone:'America/Jamaica'});return <FlatList contentContainerStyle={styles.page} data={data.rows} keyExtractor={r=>r.id} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Retained appointments.</Text><Text style={styles.body}>Each appointment shows its current recorded status. A past appointment does not authorize entry.</Text><Text style={styles.body}>{data.total} appointments · Page {data.page} of {data.pages}</Text>{!data.total&&<Text style={styles.body}>No appointments have been recorded for this assignment.</Text>}{!!data.total&&!data.rows.length&&<Text style={styles.body}>Appointments changed while loading. Refresh to check.</Text>}<Link href={{pathname:'/work-offer',params:{id:offer}}} style={styles.link}>Current assignment →</Link></View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.state} · Version {item.version}</Text><Text style={styles.body}>{date(item.starts)} → {date(item.ends)} (Jamaica time)</Text><Text style={styles.body}>{item.note}</Text><Text selectable style={styles.body}>Appointment reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:18}}><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh appointments</Text></Pressable></View>}/>;}
