import {useCallback} from 'react';
import {ActivityIndicator,Pressable,ScrollView,Text,View} from 'react-native';
import {Link,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {contractorWorkOffer} from '../lib/work-offers';
import {WorkOfferResponse} from '../components/work-offer-response';
import {ContractorVisit} from '../components/contractor-visit';
import {supabase} from '../lib/supabase';
export default function Offer(){const params=useLocalSearchParams<Record<string,string|string[]>>(),id=typeof params.id==='string'?params.id:'invalid';const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to review the work offer →</Link></View>;return <Detail key={user.id+id} owner={user.id} id={id}/>;}
function Detail({owner,id}:{owner:string;id:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return contractorWorkOffer(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading work offer"/></View>;if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>This offer could not be loaded.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;const offer=result.data;return <ScrollView contentContainerStyle={styles.page}>{offer?<><Text style={styles.title}>{offer.title}</Text><Text style={styles.body}>{offer.company} · {offer.trade}</Text><Text style={styles.body}>Recorded status: {offer.expired?'Expired':offer.state} · Version {offer.version}</Text><Text style={styles.heading}>Approved scope</Text><Text style={styles.body}>{offer.scope}</Text><Text style={styles.body}>Expires {new Date(offer.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text><Text style={styles.body}>Acceptance records an assignment. The team arranges visits and entry authorization separately.</Text>{offer.state==='accepted'&&<ContractorVisit key={offer.id+':visit:'+offer.version} owner={owner} offer={offer.id}/>}<Link href={{pathname:"/work-visits",params:{offer:offer.id}}} style={styles.link}>Retained appointments →</Link><Link href={{pathname:"/work-completion",params:{offer:offer.id}}} style={styles.link}>Completion reports and feedback →</Link><Link href={{pathname:"/work-evidence",params:{offer:offer.id}}} style={styles.link}>Review private evidence →</Link><WorkOfferResponse key={offer.id+":"+offer.version} owner={owner} id={offer.id} version={offer.version} state={offer.state} expired={offer.expired} onRefresh={result.retry}/></>:<Text style={styles.body}>This offer is unavailable to your active contractor account.</Text>}<Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh offer</Text></Pressable><Link href="/work-offers" style={styles.link}>Your work offers →</Link></ScrollView>;}
