import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../components/identity';
import {useLoad} from '../components/use-load';
import {styles} from '../components/styles';
import {catalogQuery} from '../lib/catalog';
import {contractorEvidence} from '../lib/contractor-evidence';
import {EvidenceOpen} from '../components/contractor-evidence-open';
import {EvidenceWithdraw} from '../components/contractor-evidence-withdraw';
import {EvidenceCertify} from '../components/contractor-evidence-certify';
import {EvidenceUpload} from '../components/contractor-evidence-upload';
import {supabase} from '../lib/supabase';
export default function Visits(){const params=useLocalSearchParams<Record<string,string|string[]>>(),offer=typeof params.offer==='string'?params.offer:'invalid',page=catalogQuery(params).page;const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view private evidence →</Link></View>;return <Register key={user.id+offer+page} owner={user.id} offer={offer} page={page}/>;}
function Register({owner,offer,page}:{owner:string;offer:string;page:number}){const loader=useCallback(()=>{if(!supabase)throw Error();return contractorEvidence(supabase,owner,offer,page);},[owner,offer,page]);const result=useLoad(owner+offer+page,loader);if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading private evidence"/></View>;if(result.error||!result.data)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Private evidence could not be loaded.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;const data=result.data;return <FlatList contentContainerStyle={styles.page} data={data.rows} keyExtractor={r=>r.id} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Private evidence.</Text><Text style={styles.body}>Review your assignment files before submitting a completion report. Files fixed to a report remain part of that report.</Text>{data.offerState==='accepted'&&<EvidenceUpload owner={owner} offer={offer} onRefresh={result.retry}/>}<Text style={styles.body}>{data.total} files · Page {data.page} of {data.pages}</Text>{!data.total&&<Text style={styles.body}>No evidence files have been recorded for this assignment.</Text>}{!!data.total&&!data.rows.length&&<Text style={styles.body}>Files changed while loading. Refresh to check.</Text>}<Link href={{pathname:'/work-offer',params:{id:offer}}} style={styles.link}>Current assignment →</Link></View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.name}</Text><Text style={styles.body}>{item.state==='uploaded'?'Verified upload':'Unfinished reservation'} · {item.mime} · {item.size.toLocaleString('en-JM')} bytes</Text><Text style={styles.body}>{item.frozen?'Fixed to a submitted report.':'Not fixed to a report.'}</Text>{item.state==='reserved'&&<Text style={styles.body}>Reservation expires {new Date(item.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text>}{item.state==='reserved'&&!item.frozen&&data.offerState==='accepted'&&<EvidenceCertify key={item.id+':certify'} owner={owner} offer={offer} id={item.id} onRefresh={result.retry}/>}
{item.state==='uploaded'&&<EvidenceOpen key={item.id} owner={owner} offer={offer} id={item.id}/>}{!item.frozen&&data.offerState==='accepted'&&<EvidenceWithdraw key={item.id+':withdraw'} owner={owner} offer={offer} id={item.id} onRefresh={result.retry}/>}<Text selectable style={styles.body}>Evidence reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:18}}><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh files</Text></Pressable></View>}/>;}
