'use client';
import {useMemo,useState} from 'react';
import {homes,photoUrl,priceLabel} from '@/lib/discovery/data';
import {PropertyMap} from './property-map';
export function ListingBrowser({initialIntent='all'}:{initialIntent?:string}){
 const [intent,setIntent]=useState(initialIntent);const [area,setArea]=useState('all');const [query,setQuery]=useState('');const [view,setView]=useState<'split'|'list'|'map'>('split');const [selected,setSelected]=useState('');const [saved,setSaved]=useState<string[]>([]);const [savedOnly,setSavedOnly]=useState(false);
 const filtered=useMemo(()=>homes.filter(h=>(intent==='all'||h.intent===intent)&&(area==='all'||h.area===area)&&(!savedOnly||saved.includes(h.id))&&`${h.title} ${h.area}`.toLowerCase().includes(query.toLowerCase())),[intent,area,query,saved,savedOnly]);
 const selectedHome=filtered.find(h=>h.id===selected);
 return <><section className="page-intro"><p className="eyebrow">DEMO INVENTORY · EXPLORE OPEN HOUSE</p><h1>A home. A neighborhood.<br />A new possibility.</h1><p>Explore fictional homes on the list or map. All photos, prices and locations are illustrative; these properties are not available.</p></section><section className="listing-workspace"><div className="filter-bar"><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Home or neighborhood" /></label><label>Looking to<select value={intent} onChange={e=>setIntent(e.target.value)}><option value="all">Buy or rent</option><option value="sale">Buy</option><option value="rent">Rent</option></select></label><label>Area<select value={area} onChange={e=>setArea(e.target.value)}><option value="all">All areas</option>{Array.from(new Set(homes.map(h=>h.area))).sort().map(name=><option key={name}>{name}</option>)}</select></label><button className={savedOnly?'filter-active':''} aria-pressed={savedOnly} onClick={()=>setSavedOnly(!savedOnly)}>♡ Saved ({saved.length})</button></div><div className="results-toolbar"><span aria-live="polite">{filtered.length} demo homes · illustrative photos</span><div className="segmented">{(['split','list','map'] as const).map(v=><button key={v} aria-pressed={view===v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='split'?'List + map':v==='list'?'List':'Map'}</button>)}</div></div><div className={`results-layout view-${view}`}>
 {view!=='map'&&<div className="results-cards">{filtered.map(home=><article id={`home-${home.id}`} key={home.id} className={`listing-card ${selected===home.id?'is-selected':''}`}><a href={`/demo/listings/${home.id}`} className="listing-image"><img src={photoUrl(home)} alt={`Illustrative ${home.title}`} loading="lazy" /><span className="listing-label">DEMO · {home.intent==='rent'?'FOR RENT':'FOR SALE'}</span></a><div className="listing-content"><p className="eyebrow">Demo property · {home.area}</p><h2><a href={`/demo/listings/${home.id}`}>{home.title}</a></h2><strong>{priceLabel(home)}</strong><p className="listing-meta">{home.beds} beds · {home.baths} baths · {home.size.toLocaleString()} sq ft</p><div className="listing-actions"><button aria-pressed={saved.includes(home.id)} className="secondary" onClick={()=>setSaved(s=>s.includes(home.id)?s.filter(id=>id!==home.id):[...s,home.id])}>{saved.includes(home.id)?'♥ Saved':'♡ Save'}</button><button className="primary" onClick={()=>{setSelected(home.id);setView('split')}}>Show on map</button></div></div></article>)}{!filtered.length&&<div className="empty-state"><h2>No homes match yet</h2><p>Try another area or clear your filters.</p><button onClick={()=>{setIntent('all');setArea('all');setQuery('');setSavedOnly(false)}}>Clear filters</button></div>}</div>}
 {view!=='list'&&<aside className="results-map"><PropertyMap homes={filtered} selected={selected} onSelect={id=>setSelected(id)} />{selectedHome&&<div className="map-selection" aria-live="polite"><strong>{selectedHome.title}</strong><p>{selectedHome.area} · {priceLabel(selectedHome)}</p><a href={`/demo/listings/${selectedHome.id}`}>View property ↗</a></div>}{!filtered.length&&<p>No matching homes on this map.</p>}</aside>}
 </div><p className="inventory-note">Demo inventory and approximate pins. Saved homes stay in this page session.</p></section></>
}
