'use client';
import { useMemo, useState } from 'react';
import { catalogHref, CATALOG_PAGE_SIZE, type catalogQuery } from '@/lib/discovery/catalog-query';
import { PropertyMap } from './property-map';
import { SaveProperty } from '@/components/auth/save-property';
import type { Home } from '@/lib/discovery/data';
export type PublishedListing = { id:string;title:string;area:string;intent:string;price_jmd:number;bedrooms:number;bathrooms:number;parking_spaces:number;size_sq_ft:number|null;description:string|null;photo_url:string|null;approximate_latitude:number|null;approximate_longitude:number|null;location_label:string|null };
export function LiveCatalog({ listings, savedIds, filters, total, totalPages }: { listings:PublishedListing[];savedIds:string[];filters:ReturnType<typeof catalogQuery>;total:number;totalPages:number }) {
  const [selected,setSelected]=useState('');const [view,setView]=useState<'split'|'list'|'map'>('split');
  const filtered = listings;
  const mapped=useMemo(()=>filtered.filter(row=>row.approximate_latitude!==null&&row.approximate_longitude!==null).map(row=>({id:row.id,title:row.title,area:row.area,intent:row.intent as 'rent'|'sale',price:Number(row.price_jmd),beds:Number(row.bedrooms),baths:Number(row.bathrooms),parking:row.parking_spaces,size:row.size_sq_ft||0,lat:row.approximate_latitude!,lng:row.approximate_longitude!,photo:'',description:row.description||''} satisfies Home)),[filtered]);
  const selectedRow=filtered.find(row=>row.id===selected);
  return <><form action="/listings" method="get" className="filter-bar"><label>Search<input name="q" defaultValue={filters.q} placeholder="Property or neighborhood"/></label><label>Looking to<select name="intent" defaultValue={filters.intent}><option value="all">Buy or rent</option><option value="sale">Buy</option><option value="rent">Rent</option></select></label><label>Area<input name="area" defaultValue={filters.area} placeholder="City, parish or community"/></label><button type="submit">Search properties</button></form><div className="results-toolbar"><span role="status">{total} matching properties · {listings.length ? `${(filters.page-1)*CATALOG_PAGE_SIZE+1}–${(filters.page-1)*CATALOG_PAGE_SIZE+listings.length} shown` : 'none shown'} · {mapped.length} map locations on this page</span><div className="segmented">{(['split','list','map'] as const).map(mode=><button key={mode} aria-pressed={view===mode} onClick={()=>setView(mode)}>{mode==='split'?'List + map':mode==='list'?'List':'Map'}</button>)}</div></div><div className={`results-layout view-${view}`}>
  {view!=='map'&&<div className="results-cards">{filtered.map(row=><article className={`listing-card ${selected===row.id?'is-selected':''}`} key={row.id}>{row.photo_url&&<img src={row.photo_url} alt={row.title} loading="lazy" referrerPolicy="no-referrer" className="live-property-photo"/>}<div className="listing-content"><p className="eyebrow">{row.area} · {row.intent==='rent'?'For rent':'For sale'}</p><h2><a href={`/listings/${row.id}`}>{row.title}</a></h2><strong>JMD {Number(row.price_jmd).toLocaleString('en-JM')}{row.intent==='rent'?' / month':''}</strong><p>{row.bedrooms} beds · {row.bathrooms} baths</p><p>{row.description}</p><SaveProperty listingId={row.id} initialSaved={savedIds.includes(row.id)}/>{row.approximate_latitude!==null&&row.approximate_longitude!==null?<button className="secondary" onClick={()=>{setSelected(row.id);setView('split');}}>Show on map</button>:<p>Contact the team for location details.</p>}</div></article>)}{!filtered.length&&<div className="empty-state"><h2>{filters.q||filters.area||filters.intent!=='all'?'No matching properties':'Our next collection is coming.'}</h2><p>{filters.q||filters.area||filters.intent!=='all'?'Try another area or search.':'The team is preparing approved properties for publication.'}</p>{filters.q||filters.area||filters.intent!=='all'?<a href="/listings">Clear filters</a>:<a href="/demo/listings">Explore illustrative demo properties ↗</a>}</div>}</div>}
  {view!=='list'&&<aside className="results-map"><PropertyMap homes={mapped} selected={selected} onSelect={setSelected} demo={false}/>{selectedRow&&<div className="map-selection" role="status"><strong>{selectedRow.title}</strong><p>{selectedRow.location_label||selectedRow.area}</p><a href={`/listings/${selectedRow.id}`}>View property ↗</a></div>}{filtered.length>mapped.length&&<p>{filtered.length-mapped.length} properties have no public map location; they remain available in the list.</p>}</aside>}
  </div>{totalPages>1&&<nav className="results-toolbar" aria-label="Property result pages">{filters.page>1?<a className="secondary" href={catalogHref(filters,filters.page-1)}>← Previous</a>:<span/>}<span>Page {filters.page} of {totalPages}</span>{filters.page<totalPages?<a className="secondary" href={catalogHref(filters,filters.page+1)}>Next →</a>:<span/>}</nav>}</>;
}
