'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export function SellerHandoff({id,area,type,listingId,canAuthor}:{id:string;area:string|null;type:string|null;listingId:string|null;canAuthor:boolean}){
 const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[requestId,setRequestId]=useState(''),[created,setCreated]=useState('');
 const linked=listingId||created;
 if(linked)return <section><h3>Listing preparation</h3><p>This proposal is linked to a property and listing draft. Publication requires approved details, pricing, photography and approximate map coordinates where available.</p>{canAuthor?<a className="button-link" href={`/staff?listing=${linked}`}>Review the linked listing ↗</a>:<p>A catalog author can edit the linked listing.</p>}</section>;
 if(!canAuthor)return <p>An authorized catalog author prepares the listing draft after seller approval.</p>;
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setMessage('');try{const response=await fetch('/api/staff/sellers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,request_id:retry,public_title:form.get('public_title'),public_area:form.get('public_area'),property_type:form.get('property_type'),approval_reason:form.get('approval_reason'),seller_approved:form.get('seller_approved')==='on'})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error);}setCreated(result.listing_id);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Unable to prepare the draft. Retry without changing the form.');}finally{setBusy(false);}}
 return <form onSubmit={submit} onChange={()=>setRequestId('')}><h3>Prepare the approved listing draft</h3><p>The private address stays in the property record. These fields are intended for public review; omit exact addresses and private seller details.</p><fieldset disabled={busy}><label>Approved public title<input name="public_title" required minLength={3} maxLength={160}/></label><label>Approved public community or parish<input name="public_area" required minLength={2} maxLength={120} defaultValue={area||''}/></label><label>Listing type<select name="property_type" defaultValue={type&&['house','apartment','townhouse','land','commercial'].includes(type)?type:'house'}>{['house','apartment','townhouse','land','commercial'].map(value=><option key={value}>{value}</option>)}</select></label><label>Approval reason (shared with seller)<textarea name="approval_reason" required minLength={5} maxLength={500}/></label><label><input name="seller_approved" type="checkbox" required/> The seller approved the proposal and authorized draft preparation. I reviewed these public-facing fields.</label><button>{busy?'Preparing draft…':'Prepare property and listing draft'}</button></fieldset><p role="status">{message}</p></form>;
}
