import {useCallback} from 'react';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {useIdentity} from '../../components/identity';
import {useLoad} from '../../components/use-load';
import {styles} from '../../components/styles';
import {catalogQuery} from '../../lib/catalog';
import {CosignerDecisions} from '../../components/cosigner-decisions';
import {cosignerInvitation} from '../../lib/cosigners';
import {supabase} from '../../lib/supabase';
export default function Invitation(){const params=useLocalSearchParams<Record<string,string|string[]>>(),id=typeof params.id==='string'?params.id:'invalid',page=catalogQuery(params).page;const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Text style={styles.body}>Sign in with the verified email that received this invitation.</Text><Link href="/sign-in" style={styles.link}>Sign in →</Link></View>;return <Detail key={user.id+id+page} owner={user.id} id={id} page={page}/>;}
function Detail({owner,id,page}:{owner:string;id:string;page:number}){
 const loader=useCallback(()=>{if(!supabase)throw Error();return cosignerInvitation(supabase,owner,id,page);},[owner,id,page]);const result=useLoad(owner+id+page,loader);
 if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading private invitation"/></View>;
 if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Invitation access could not be confirmed. Use the invited email and check the latest invitation.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;
 if(!result.data)return <View style={styles.page}><Text style={styles.heading}>Invitation unavailable</Text><Link href="/" style={styles.link}>Home →</Link></View>;
 const data=result.data,[whole,decimal]=data.rent.split('.');const rent=`JMD ${BigInt(whole).toLocaleString('en-JM')}${decimal?'.'+decimal.padEnd(2,'0'):''}`;
 return <FlatList contentContainerStyle={styles.page} data={data.events} keyExtractor={e=>e.id} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>Private co-signer review.</Text><Text style={styles.heading}>{data.title}</Text><Text style={styles.body}>{data.area} · Advertised monthly rent at application: {rent}</Text><Text style={styles.body}>Applicant: {data.applicant}</Text><Text style={styles.body}>Recorded invitation status: {data.state}</Text><Text style={styles.body}>Expires {new Date(data.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text><Text style={styles.body}>{data.active?'Invitation is currently available for review.':'Invitation is not currently available for a new review decision.'}</Text><Text style={styles.body}>Participation in application review does not sign a lease or create a legal guarantee.</Text><CosignerDecisions key={id+data.version} owner={owner} id={id} version={data.version} state={data.state} available={data.active} onRefresh={result.retry}/><Text style={styles.heading}>Invitation history</Text><Text style={styles.body}>{data.total} events · Page {data.page} of {data.pages}</Text>{!data.total&&<Text style={styles.body}>No invitation history is recorded.</Text>}{!!data.total&&!data.events.length&&<Text style={styles.body}>History changed while loading. Refresh to check.</Text>}</View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.event_name.replaceAll('_',' ')} · {item.new_state}</Text><Text style={styles.body}>{new Date(item.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text></View>} ListFooterComponent={<View style={{gap:18}}><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh invitation</Text></Pressable><Link href="/" style={styles.link}>Home →</Link></View>}/>;
}
