import {notFound,redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {SiteHeader} from '@/components/discovery/site-header';
import {statementQuery} from '@/lib/finance/statement-query';
import {formatJmdMinor} from '@/lib/finance/money';
export const dynamic='force-dynamic';
type Portfolio={page:number;pages:number;total:number;as_of:string;properties:{id:string;name:string;area:string|null;managed_units:number;current_open_work_orders:number;posted_income_minor:string;posted_expense_minor:string;posted_net_minor:string}[]};
export default async function OwnerPortfolio({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const client=await createClient();const {data:{user},error:authError}=await client.auth.getUser();if(authError||!user?.email_confirmed_at)redirect('/sign-in');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Jamaica',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 let query;try{query=statementQuery(await searchParams,today);}catch{return <><SiteHeader/><main className="account-layout"><section className="account-card"><h1>Your portfolio</h1><p role="alert">Choose valid dates spanning up to 367 inclusive days.</p><a href="/account/portfolio">Reset date filters</a></section></main></>;}
 const {data,error}=await client.rpc('owner_portfolio_summary',{p_from:query.from,p_to:query.to,p_page:query.page});if(error?.code==='42501')notFound();if(error||!data)throw new Error('Unable to load the approved portfolio.');
 const report=data as Portfolio,href=(page:number)=>`/account/portfolio?${new URLSearchParams({from:query.from,to:query.to,page:String(page)})}`;if(report.page!==query.page)redirect(href(report.page));
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Owner portfolio</p><h1>Your approved properties.</h1><form className="filter-bar" action="/account/portfolio"><label>From<input type="date" name="from" defaultValue={query.from} required/></label><label>Through<input type="date" name="to" defaultValue={query.to} required/></label><button className="secondary">Update report</button></form><p>Financial amounts reflect property-attributed posted income and expenses for these dates. They do not show cash collected or distributions owed. Unit and maintenance counts reflect current records.</p><p>Verified occupancy reporting is awaiting tenancy activation.</p>{report.properties.length?report.properties.map(property=><article className="staff-editor" key={property.id}><h2>{property.name}</h2>{property.area&&<p>{property.area}</p>}<dl><dt>Managed units</dt><dd>{property.managed_units}</dd><dt>Current open work orders</dt><dd>{property.current_open_work_orders}</dd><dt>Posted income</dt><dd>{formatJmdMinor(property.posted_income_minor)}</dd><dt>Posted expenses</dt><dd>{formatJmdMinor(property.posted_expense_minor)}</dd><dt>Posted net income</dt><dd>{formatJmdMinor(property.posted_net_minor)}</dd></dl></article>):<p>No properties currently have approved portfolio access for this account. Contact Open House to review access.</p>}<nav className="results-toolbar" aria-label="Owner portfolio pages">{report.page>1?<a href={href(report.page-1)}>← Previous</a>:<span/>}<span>{report.total} properties · Page {report.page} of {report.pages}</span>{report.page<report.pages?<a href={href(report.page+1)}>Next →</a>:<span/>}</nav><small>Report generated {new Date(report.as_of).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</small><p><a href="/account">Back to your account →</a></p></section></main></>;
}
