import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {ContractorEditor} from '@/components/staff/contractor-editor';
export const dynamic='force-dynamic';
export default async function Contractors({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const input=await searchParams;
 const state=typeof input.state==='string'&&['active','inactive'].includes(input.state)?input.state:'',page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1,href=(next:number)=>`/staff/contractors?page=${next}${state?`&state=${state}`:''}`;
 const query=(head=false)=>{let q=client.from('contractor_accounts').select('id,company_name,trade_coverage,is_active',{head,count:'exact'}).eq('organization_id',membership.organization_id);if(state)q=q.eq('is_active',state==='active');return q;};
 const count=await query(true);if(count.error)throw new Error('Unable to count contractor registrations.');const pages=Math.max(1,Math.ceil((count.count||0)/25));if(page>pages)redirect(href(pages));
 const rows=await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Approved contractor register</p><h1>Your maintenance partners.</h1><p>Register an approved account after the contractor verifies its email. Registration records identity and approved coverage. Work offers, scheduling and entry authorization are being prepared.</p><ContractorEditor/><form className="filter-bar" action="/staff/contractors"><label>Registration state<select name="state" defaultValue={state}><option value="">All states</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><button className="secondary">Apply filter</button></form>{rows.error?<p role="alert">Unable to load registrations. Please refresh.</p>:rows.data?.length?rows.data.map(row=><article className="staff-editor" key={row.id}><h2><a href={`/staff/contractors/${row.id}`}>{row.company_name}</a></h2><p>{row.is_active?'Active':'Inactive'} · {row.trade_coverage.join(' · ')}</p></article>):<p>No contractor registrations in this view.</p>}<nav className="results-toolbar" aria-label="Contractor register pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{count.count||0} registrations · Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><a href="/staff/work-orders">Work orders ↗</a></section></main></>;
}
