import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {SecurityAssignmentEditor} from '@/components/staff/security-assignment-editor';
export const dynamic='force-dynamic';
export default async function Contractor({params,searchParams}:{params:Promise<{assignmentId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const {assignmentId}=await params;
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(assignmentId))notFound();
 const account=await client.from('property_security_assignments').select('id,user_id,property_id,is_active,version').eq('id',assignmentId).eq('organization_id',membership.organization_id).maybeSingle();if(account.error)throw new Error('Unable to verify contractor access.');if(!account.data)notFound();
 const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1,href=(next:number)=>`/staff/security/assignments/${assignmentId}?page=${next}`;
 const query=(head=false)=>client.from('property_security_assignment_changes').select('id,actor_user_id,previous_active,new_active,version,reason,created_at',{head,count:'exact'}).eq('organization_id',membership.organization_id).eq('assignment_id',assignmentId);
 const count=await query(true);if(count.error)throw new Error('Unable to count contractor history.');const pages=Math.max(1,Math.ceil((count.count||0)/25));if(page>pages)redirect(href(pages));const history=await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Private property security approval</p><h1>Security assignment</h1><SecurityAssignmentEditor key={`${assignmentId}-${account.data.version}`} assignment={account.data}/><h2>Approval history</h2>{history.error?<p role="alert">Unable to load history. Please refresh.</p>:history.data?.length?history.data.map(event=><article className="staff-editor" key={event.id}><h3>Revision {event.version}</h3><p className="enquiry-message">{event.reason}</p><p>{event.previous_active === null ? 'New assignment' : event.previous_active ? 'Active' : 'Inactive'} → {event.new_active ? 'Active' : 'Inactive'}</p><small>Actor: {event.actor_user_id}<br/>{new Date(event.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</small></article>):<p>No approval history yet.</p>}<nav className="results-toolbar" aria-label="Contractor approval history pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{count.count||0} changes · Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><a href={`/staff/security/${account.data.property_id}`}>Back to property security register ↗</a></section></main></>;
}
