import {useCallback} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link,router,useLocalSearchParams} from 'expo-router';
import {useIdentity} from '../../components/identity';
import {useLoad} from '../../components/use-load';
import {styles} from '../../components/styles';
import {catalogQuery} from '../../lib/catalog';
import {applicationDetail} from '../../lib/applications';
import {ApplicationActions} from '../../components/application-actions';
import {supabase} from '../../lib/supabase';
export default function Application(){const params=useLocalSearchParams<Record<string,string|string[]>>();const id=typeof params.id==='string'?params.id:'invalid',page=catalogQuery(params).page;const {user,loading}=useIdentity();if(loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Checking account"/></View>;if(!user)return <View style={styles.page}><Link href="/sign-in" style={styles.link}>Sign in to view your application →</Link></View>;return <Detail key={user.id+id+page} owner={user.id} id={id} page={page}/>;}
function Detail({owner,id,page}:{owner:string;id:string;page:number}){
 const loader=useCallback(()=>{if(!supabase)throw new Error('Connection unavailable');return applicationDetail(supabase,owner,id,page);},[owner,id,page]);const result=useLoad(owner+id+page,loader);
 if(result.loading)return <View style={styles.page}><ActivityIndicator accessibilityLabel="Loading application"/></View>;
 if(result.error)return <View style={styles.page}><Text accessibilityRole="alert" style={styles.body}>Unable to load your application and shared history.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Try again</Text></Pressable></View>;
 if(!result.data)return <View style={styles.page}><Text style={styles.heading}>Application unavailable</Text><Link href="/applications" style={styles.link}>Your applications →</Link></View>;
 const data=result.data,a=data.application;
 return <FlatList contentContainerStyle={styles.page} data={data.events} keyExtractor={e=>e.id} ItemSeparatorComponent={()=><View style={{height:18}}/>} ListHeaderComponent={<View style={{gap:18}}><Text style={styles.title}>{a.title}</Text><Text style={styles.body}>Recorded status: {a.status.replaceAll('_',' ')}</Text><Text style={styles.body}>Household: {a.household_size} · Preferred move-in: {a.move_in}</Text><Text style={styles.body}>{a.message}</Text><Text selectable style={styles.body}>Reference: {a.id}</Text><Text style={styles.body}>Approval does not activate a signed lease or tenancy.</Text><Link href={{pathname:'/lease-summaries',params:{application:a.id}}} style={styles.link}>Shared lease summaries →</Link><Link href={{pathname:'/listings/[id]',params:{id:a.listing_id}}} style={styles.link}>Published property →</Link><ApplicationActions key={a.id+':'+a.version} owner={owner} id={a.id} version={a.version} status={a.status} onRefresh={result.retry}/><Link href={{pathname:'/application-documents/[id]',params:{id:a.id}}} style={styles.link}>Supporting documents →</Link><Link href={{pathname:'/application-cosigners/[id]',params:{id:a.id}}} style={styles.link}>Co-signer invitations →</Link><Text style={styles.heading}>Shared review history</Text><Text style={styles.body}>{data.total} events · Page {data.page} of {data.pages}</Text>{!data.total?<Text style={styles.body}>No shared review messages yet.</Text>:!data.events.length&&<Text style={styles.body}>History changed while loading. Refresh to check current messages.</Text>}</View>} renderItem={({item})=><View style={styles.card}><Text style={styles.heading}>{item.status.replaceAll('_',' ')}</Text><Text style={styles.body}>{new Date(item.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text><Text style={styles.body}>{item.message}</Text></View>} ListFooterComponent={<View style={{gap:18,paddingTop:24}}><Pressable accessibilityRole="button" disabled={data.page===1} onPress={()=>router.setParams({page:String(data.page-1)})}><Text style={styles.link}>← Newer</Text></Pressable><Pressable accessibilityRole="button" disabled={data.page===data.pages} onPress={()=>router.setParams({page:String(data.page+1)})}><Text style={styles.link}>Older →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh application</Text></Pressable></View>}/>;
}
