import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
export const dynamic='force-dynamic';
export default async function Skipped({params,searchParams}:{params:Promise<{planId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();
 const {planId}=await params;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(planId))notFound();
 const {data:plan,error}=await client.from('preventive_maintenance_plans').select('id,title').eq('id',planId).eq('organization_id',membership.organization_id).maybeSingle();if(error)throw new Error('Unable to verify preventive plan.');if(!plan)notFound();
 const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const {count,error:countError}=await client.from('preventive_maintenance_skips').select('due_on',{head:true,count:'exact'}).eq('plan_id',planId).eq('organization_id',membership.organization_id);if(countError)throw new Error('Unable to count skipped dates.');
 const pages=Math.max(1,Math.ceil((count||0)/25)),href=(n:number)=>`/staff/preventive-plans/${planId}/skipped?page=${n}`;if(page>pages)redirect(href(pages));
 const {data,error:rowError}=await client.from('preventive_maintenance_skips').select('due_on,snapshot,created_at,decision:preventive_maintenance_events(reason,actor_user_id,action,organization_id,plan_id)').eq('plan_id',planId).eq('organization_id',membership.organization_id).order('due_on',{ascending:false}).range((page-1)*25,page*25-1);if(rowError)throw new Error('Unable to load skipped dates.');
 const records=(data||[]).map(row=>{const decision=Array.isArray(row.decision)?row.decision.length===1?row.decision[0]:null:row.decision;if(!decision||decision.action!=='skip'||decision.organization_id!==membership.organization_id||decision.plan_id!==planId)throw new Error('Unable to verify skipped-date decision.');return {...row,decision};});
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Retained skipped-date register</p><h1>{plan.title}</h1><p>Skipped dates retain the approved exception. They do not represent completed maintenance or generated work orders.</p>{records.length?records.map(row=><article key={row.due_on}><h2>Skipped {row.due_on}</h2><p>{row.decision.reason}</p><small>Approved by {row.decision.actor_user_id} · {new Date(row.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</small><details><summary>Approved scope at the skipped date</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(row.snapshot,null,2)}</pre></details></article>):<p>No recorded skipped dates.</p>}<nav aria-label="Skipped-date pages">{page>1&&<a href={href(page-1)}>← Newer skipped dates</a>}<span> Page {page} of {pages} </span>{page<pages&&<a href={href(page+1)}>Older skipped dates →</a>}</nav><p><a href={`/staff/preventive-plans/${planId}/history`}>All decisions and issued work →</a></p><a href={`/staff/preventive-plans/${planId}`}>Current plan →</a></section></main></>;
}
