import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {AttendanceEditor} from '@/components/open-houses/attendance-editor';
import {SiteHeader} from '@/components/discovery/site-header';
export const dynamic='force-dynamic';
type Roster={event:{id:string;title:string;starts_at:string;ends_at:string;capacity:number|null;status:string};page:number;pages:number;total:number;reserved_places:number;going_parties:number;cancelled_parties:number;rows:{id:string;party_size:number;status:string;version:number;attendance_state:string;attended_count:number;attendance_version:number;created_at:string;contact_email:string|null}[]};
export default async function OpenHouseRoster({params,searchParams}:{params:Promise<{eventId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','realtor','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const {eventId}=await params;if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(eventId))notFound();const input=await searchParams,state=typeof input.state==='string'&&['going','cancelled','all'].includes(input.state)?input.state:'going',page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const {data,error}=await client.rpc('open_house_staff_roster',{p_event_id:eventId,p_state:state,p_page:page});if(error?.code==='42501')notFound();if(error||!data)throw new Error('Unable to load this event attendee roster.');const roster=data as Roster,href=(next:number)=>`/staff/open-houses/${eventId}?${new URLSearchParams({state,page:String(next)})}`;if(roster.page!==page)redirect(href(roster.page));const time=(value:string)=>new Date(value).toLocaleString('en-JM',{timeZone:'America/Jamaica'});
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Private organization attendee roster</p><h1>{roster.event.title}</h1><p>{time(roster.event.starts_at)} – {time(roster.event.ends_at)} · Jamaica time</p><p>Event {roster.event.status} · {roster.event.capacity===null?'Capacity needs review':`Capacity ${roster.event.capacity}`}</p><p>{roster.reserved_places} places reserved across {roster.going_parties} parties · {roster.cancelled_parties} cancelled RSVPs</p>{roster.event.status==='scheduled'&&roster.event.capacity!==null&&<p>{Math.max(0,roster.event.capacity-roster.reserved_places)} unreserved places</p>}{roster.event.status!=='scheduled'&&<p>Reservation totals are historical. This event is no longer accepting attendance.</p>}<p>Contact details are for event follow-up within your organization. RSVPs record attendance intent. Staff can record actual attendance during the event window; corrections require a reason.</p><form method="get"><label>Reservation state<select name="state" defaultValue={state}><option value="going">Reserved</option><option value="cancelled">Cancelled</option><option value="all">All</option></select></label><button>Filter attendees</button></form><div className="enquiry-grid">{roster.rows.map(row=><article className="staff-editor" key={row.id}><h2>{row.party_size} attendee{row.party_size===1?'':'s'}</h2><p>{row.status==='going'?'Reserved':'Cancelled'} · Created {time(row.created_at)}</p>{row.contact_email?<p><a href={`mailto:${encodeURIComponent(row.contact_email)}`}>{row.contact_email}</a></p>:<p>Verified contact email unavailable. Review the account before contacting this attendee.</p>}<p>Attendance: {row.attendance_state==='attended'?`${row.attended_count} attended`:row.attendance_state==='no_show'?'Did not attend':'Not recorded'}</p>{row.status==='going'&&<AttendanceEditor key={`${row.id}-${row.version}-${row.attendance_version}`} id={row.id} rsvpVersion={row.version} attendanceVersion={row.attendance_version} partySize={row.party_size} currentState={row.attendance_state} attendedCount={row.attended_count} startsAt={roster.event.starts_at} endsAt={roster.event.ends_at} eventStatus={roster.event.status}/>}<small>Reservation reference: {row.id} · Revision {row.version}</small></article>)}</div>{!roster.rows.length&&<p>No reservations match this state.</p>}<nav className="results-toolbar" aria-label="Attendee roster pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{roster.total} parties · Page {roster.page} of {roster.pages}</span>{page<roster.pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><p><a href={`/staff/open-houses/${eventId}/arrival`}>Manage approved arrival instructions ↗</a></p><p><a href={`/staff/open-houses/${eventId}/attendance`}>Review attendance audit ↗</a></p><a href="/staff/open-houses">Back to event schedule ↗</a></section></main></>;
}
