'use client';
import {useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {jamaicaInputToIso,viewingTime} from '@/lib/viewings/validation';
type Slot={id:string;listing_id:string;starts_at:string;ends_at:string;state:string;hold_expires_at:string|null};
export function StaffCalendar({listings,slots}:{listings:{id:string;title:string}[];slots:Slot[]}){
 const router=useRouter();const reference=useRef('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function save(body:Record<string,unknown>){const response=await fetch('/api/staff/viewings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save availability.');}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=event.currentTarget;const data=new FormData(form);if(!reference.current)reference.current=crypto.randomUUID();try{const start=jamaicaInputToIso(String(data.get('starts_at')));const end=new Date(Date.parse(start)+Number(data.get('duration'))*60000).toISOString();await save({action:'create',request_id:reference.current,listing_id:data.get('listing_id'),starts_at:start,ends_at:end});reference.current='';form.reset();setMessage('Availability saved. It becomes public when the property is published.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Unable to save. Please retry with the same details.');}finally{setBusy(false);}}
 async function close(id:string){setBusy(true);setMessage('');try{await save({action:'close',slot_id:id});setMessage('Viewing slot closed.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Unable to close this slot.');}finally{setBusy(false);}}
 const title=(id:string)=>listings.find(row=>row.id===id)?.title||'Property';
 return <section><h2>Plan upcoming viewings.</h2><p>Times are entered in Jamaica time. Slots are hosted by the staff member creating them; the database blocks overlapping property or host appointments.</p><form className="staff-editor" onSubmit={submit}><label>Property<select name="listing_id" required defaultValue=""><option value="">Choose a property</option>{listings.map(row=><option value={row.id} key={row.id}>{row.title}</option>)}</select></label><div className="staff-fields"><label>Date and start time (Jamaica)<input name="starts_at" type="datetime-local" required/></label><label>Duration<select name="duration" defaultValue="30">{[15,30,45,60,90,120].map(minutes=><option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label></div><button className="primary" disabled={busy||!listings.length}>Publish availability</button></form><p role="status">{message}</p><div className="enquiry-grid">{slots.map(slot=><article className="viewing-card" key={slot.id}><p className="eyebrow">{slot.state}</p><h3>{title(slot.listing_id)}</h3><p>{viewingTime(slot.starts_at)} (Jamaica)</p><p>{Math.round((Date.parse(slot.ends_at)-Date.parse(slot.starts_at))/60000)} minutes</p>{slot.state==='open'&&<button className="secondary" disabled={busy} onClick={()=>close(slot.id)}>Close availability</button>}{slot.state==='held'&&<p>Resolve or cancel the related viewing before closing this slot.</p>}</article>)}</div></section>;
}
