'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {viewingTime} from '@/lib/viewings/validation';
export type ViewingRow={id:string;slot_id:string|null;listing_id:string;title_snapshot:string|null;requested_for:string;ends_at:string|null;hold_expires_at:string|null;contact_name:string|null;contact_email:string|null;phone:string|null;status:string;cancellation_reason:string|null};
export function ViewingList({viewings,staff=false}:{viewings:ViewingRow[];staff?:boolean}){
 const router=useRouter();const acting=useRef(false);const [rows,setRows]=useState(viewings);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');const [cancelId,setCancelId]=useState('');const [reason,setReason]=useState('');
 async function act(id:string,action:string){
  if(acting.current)return;acting.current=true;setBusy(id);setMessage('');
  try{
   const response=await fetch('/api/viewings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({viewing_id:id,action,reason:action==='cancel'?reason:''})});const result=await response.json();
   if(response.status===409&&result?.status==='expired'){setRows(current=>current.map(row=>row.id===id?{...row,status:'expired'}:row));setMessage('The confirmation window expired. Check available times before requesting another viewing.');setCancelId('');setReason('');router.refresh();return;}
   if(!response.ok){if(response.status>=500)throw new Error('Uncertain update');setMessage(typeof result?.error==='string'?result.error:'Unable to update this viewing. Refresh its status before retrying.');return;}
   const expected={confirm:'confirmed',cancel:'cancelled',complete:'completed',no_show:'no_show'}[action as 'confirm'|'cancel'|'complete'|'no_show'];
   if(!expected||result?.status!==expected)throw new Error('Unconfirmed status');
   setRows(current=>current.map(row=>row.id===id?{...row,status:expected,cancellation_reason:action==='cancel'?reason:row.cancellation_reason}:row));setMessage(`Viewing ${expected.replace('_',' ')}. The update is saved.`);setCancelId('');setReason('');router.refresh();
  }catch{setMessage('The update could not be confirmed. Refresh this page to check the viewing status before retrying.');}finally{acting.current=false;setBusy('');}
 }

 return <div className="viewing-list"><p role="status">{message}</p>{!rows.length?<p>Viewing requests will appear here.</p>:rows.map(row=>{const expired=row.status==='requested'&&row.hold_expires_at!==null&&Date.parse(row.hold_expires_at)<=Date.now();const status=expired?'expired':row.status;const future=Date.parse(row.requested_for)>Date.now();const active=['requested','confirmed'].includes(status);return <article className="viewing-card" key={row.id}><p className="eyebrow">{status.replace('_',' ')}</p><h3>{row.title_snapshot||'Property viewing'}</h3><p>{viewingTime(row.requested_for)} (Jamaica)</p>{staff&&<p>{row.contact_name} · {row.contact_email}{row.phone&&` · ${row.phone}`}</p>}{status==='requested'&&row.hold_expires_at&&<p>Awaiting staff confirmation. The hold expires {viewingTime(row.hold_expires_at)}.</p>}{status==='confirmed'&&<p>Your appointment is confirmed. The team will arrange the meeting details.</p>}{status==='expired'&&<p>The confirmation window elapsed. Choose a new available time.</p>}{row.cancellation_reason&&<p>Cancellation: {row.cancellation_reason}</p>}<a href={`/listings/${row.listing_id}`}>Property details ↗</a>{row.slot_id&&<div className="viewing-actions">{staff&&row.status==='requested'&&<button className="primary" disabled={Boolean(busy)} onClick={()=>act(row.id,'confirm')}>{expired?'Resolve expired request':'Confirm viewing'}</button>}{staff&&status==='confirmed'&&row.ends_at&&Date.parse(row.ends_at)<=Date.now()&&<><button disabled={Boolean(busy)} onClick={()=>act(row.id,'complete')}>Mark completed</button><button disabled={Boolean(busy)} onClick={()=>act(row.id,'no_show')}>Mark no-show</button></>}{active&&(staff||future)&&<button className="secondary" disabled={Boolean(busy)} onClick={()=>{setCancelId(row.id);setReason('');}}>Cancel viewing</button>}{cancelId===row.id&&<div className="cancel-viewing"><label>Reason shared with the prospect<textarea disabled={Boolean(busy)} value={reason} onChange={event=>setReason(event.target.value)} minLength={5} maxLength={500} rows={3}/></label><button disabled={Boolean(busy)||reason.trim().length<5} onClick={()=>act(row.id,'cancel')}>Confirm cancellation</button><button disabled={Boolean(busy)} onClick={()=>setCancelId('')}>Keep viewing</button></div>}</div>}</article>;})}</div>;
}
