import {redirect} from 'next/navigation';
import {SiteHeader} from '@/components/discovery/site-header';
import {catalogAccess} from '@/lib/staff/access';
import {SellerHandoff} from '@/components/sellers/seller-handoff';
import {SellerStages} from '@/components/sellers/seller-stages';
import {sellerStages,sellerStageLabel} from '@/lib/sellers/validation';
export const dynamic='force-dynamic';
export default async function Sellers({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const input=await searchParams;const status=typeof input.status==='string'&&sellerStages.includes(input.status as typeof sellerStages[number])?input.status:'all';const raw=typeof input.page==='string'?input.page:'';const page=/^\d{1,6}$/.test(raw)?Math.max(1,Math.min(100000,Number(raw))):1;
 const href=(value:number)=>`/staff/sellers?${new URLSearchParams({...status!=='all'?{status}:{},...value>1?{page:String(value)}:{}})}`;
 const {client,user,membership}=await catalogAccess(['admin','realtor','manager']);if(!user)redirect('/sign-in');if(!membership)return <><SiteHeader/><main className="account-layout"><h1>Staff access required.</h1><a href="/account">Return to your account</a></main></>;
 const query=(head=false)=>{let request=client.from('seller_leads').select('id,name,email,phone,property_address,area,property_type,seller_intent,message,status,listing_id,created_at,seller_lead_events(id,new_status,reason,created_at)',{head,count:'exact'}).eq('organization_id',membership.organization_id);if(status!=='all')request=request.eq('status',status);return request;};
 const {count,error:countError}=await query(true);const totalPages=Math.max(1,Math.ceil((count||0)/25));if(!countError&&page>totalPages)redirect(href(totalPages));const {data,error}=countError?{data:null,error:countError}:await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <><SiteHeader/><main className="listing-workspace"><section className="page-intro"><p className="eyebrow">STAFF SELLER REQUESTS</p><h1>From possibility to proposal.</h1><p>Private property reviews for your organization. Record a shared reason when advancing a request.</p><a href="/staff/enquiries">Enquiries ↗</a> · <a href="/staff">Catalog ↗</a></section><form className="filter-bar" action="/staff/sellers"><label>Review stage<select name="status" defaultValue={status}><option value="all">All stages</option>{sellerStages.map(stage=><option key={stage} value={stage}>{sellerStageLabel(stage)}</option>)}</select></label><button>Filter requests</button><p>{count||0} matching requests</p></form>{error?<p role="alert">Unable to load seller requests. Please refresh.</p>:<div className="enquiry-grid">{data?.map(lead=><article className="staff-editor" key={lead.id}><p className="eyebrow">{sellerStageLabel(lead.status)} · {lead.area}</p><h2>{lead.name||'Seller request'}</h2><p><a href={`mailto:${encodeURIComponent(lead.email||'')}`}>{lead.email}</a> · {lead.phone||'No phone supplied'}</p><p>Private address: {lead.property_address}</p><p>{lead.property_type} · {lead.seller_intent}</p><p className="enquiry-message">{lead.message}</p><small>Reference: {lead.id}</small><details><summary>Shared follow-up history</summary>{lead.seller_lead_events?.slice().sort((a,b)=>b.created_at.localeCompare(a.created_at)).map(event=><p key={event.id}>{sellerStageLabel(event.new_status)}{event.reason&&`: ${event.reason}`}</p>)}</details>{(lead.status==='proposal'||lead.listing_id)&&<SellerHandoff id={lead.id} area={lead.area} type={lead.property_type} listingId={lead.listing_id} canAuthor={['admin','realtor'].includes(membership.role)}/>}<SellerStages key={`${lead.id}-${lead.status}`} id={lead.id} status={lead.status}/></article>)}{!data?.length&&<section className="empty-state"><h2>No seller requests in this view.</h2><p>Verified property-review requests appear here.</p></section>}</div>}{!error&&totalPages>1&&<nav className="results-toolbar" aria-label="Seller request pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>Page {page} of {totalPages}</span>{page<totalPages?<a href={href(page+1)}>Next →</a>:<span/>}</nav>}</main></>;
}
