import {useState} from 'react';
import {Link} from 'expo-router';
import {Pressable,Text,View,StyleSheet} from 'react-native';
import {styles} from './styles';
const personal=[['/saved','Saved properties','Your shortlist, ready to revisit'],['/enquiries','My enquiries','Keep track of your conversations'],['/appointments','Scheduled visits','Review your upcoming appointments'],['/applications','My applications','Follow your application journey'],['/cosigners','Co-signer invitations','Review invitations shared with you'],['/team-invitations','Team invitations','Review your approved team invitations']] as const;
const workspaces=[
 {id:'management',title:'Property management',description:'Inventory, maintenance and team coordination',links:[['/manage-inventory','Properties & units'],['/manage-work','Maintenance work queue'],['/manage-preventive-plans','Preventive maintenance'],['/manage-maintenance-report','Maintenance report'],['/manage-contractor-report','Contractor coordination'],['/manage-security','Property security assignments']]},
 {id:'finance',title:'Finance',description:'Invoices, cheque custody and approved accounts',links:[['/finance-invoices','Vendor invoices'],['/finance-cheques','Cheque custody'],['/finance-accounts','Finance accounts'],['/finance-journals','Journal history'],['/finance-trial','Trial balance']]},
 {id:'access',title:'Access administration',description:'Staff membership and owner permissions',links:[['/manage-staff','Staff access'],['/manage-owner-access','Owner access']]},
 {id:'owner',title:'Owner portfolio',description:'Your approved properties and operating activity',links:[['/portfolio','Portfolio overview']]},
 {id:'contractor',title:'Contractor workspace',description:'Approved offers, assignments and visits',links:[['/work-offers','My contractor work']]},
 {id:'security',title:'Security workspace',description:'Verify authorized visits and entry permits',links:[['/security-entry','Check an entry permit']]}
] as const;
export function AccountWorkspace(){const [open,setOpen]=useState<string|null>(null);return <><Text style={styles.heading}>Your next chapter</Text><View style={s.list}>{personal.map(([href,title,subtitle])=><Link asChild key={href} href={href}><Pressable accessibilityRole="button" style={s.row}><View style={s.copy}><Text style={s.title}>{title}</Text><Text style={s.subtitle}>{subtitle}</Text></View><Text style={s.arrow}>›</Text></Pressable></Link>)}</View><View style={s.teamHeading}><Text style={styles.heading}>Team &amp; property tools</Text><Text style={styles.body}>Open the workspace relevant to your role. Each destination checks your verified access before showing private records.</Text></View>{workspaces.map(group=><View key={group.id} style={s.group}><Pressable accessibilityRole="button" accessibilityState={{expanded:open===group.id}} accessibilityLabel={`${group.title} workspace`} onPress={()=>setOpen(current=>current===group.id?null:group.id)} style={s.row}><View style={s.copy}><Text style={s.title}>{group.title}</Text><Text style={s.subtitle}>{group.description}</Text></View><Text style={s.arrow}>{open===group.id?'−':'+'}</Text></Pressable>{open===group.id&&<View style={s.expanded}>{group.links.map(([href,title])=><Link key={href} href={href} style={styles.link}>{title} →</Link>)}</View>}</View>)}</>}
const s=StyleSheet.create({list:{borderWidth:1,borderColor:'#E2E8F0',borderRadius:20,overflow:'hidden',backgroundColor:'#fff'},row:{padding:18,flexDirection:'row',alignItems:'center',gap:16,minHeight:72},copy:{flex:1,gap:6},title:{fontFamily:'BrandStrong',fontSize:16,color:'#0B2346'},subtitle:{fontFamily:'BrandBody',fontSize:12,lineHeight:19,color:'#52647B'},arrow:{color:'#003A8C',fontSize:24},teamHeading:{gap:12,marginTop:8},group:{backgroundColor:'#fff',borderRadius:18,borderWidth:1,borderColor:'#E2E8F0'},expanded:{paddingHorizontal:18,paddingBottom:12,borderTopWidth:1,borderTopColor:'#E2E8F0'}});
