import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {randomUUID} from 'expo-crypto';
import {ownerAccessCreation,sendOwnerAccessCreation,type OwnerAccessCreation} from '../lib/admin-owner-access-creation';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function AdminOwnerAccessCreate({owner,property,name}:{owner:string;property:string;name:string}){
 const [email,setEmail]=useState(''),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<OwnerAccessCreation|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[result,setResult]=useState<{id:string;currentActive:boolean;currentVersion:number}|null>(null),[message,setMessage]=useState('');
 const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<OwnerAccessCreation|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved)return;try{const input=ownerAccessCreation({access_id:null,property_id:property,email,version:0,request_id:randomUUID(),is_active:true,reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Enter a valid account email and a reason of 5–500 characters, then approve the owner access.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendOwnerAccessCreation(supabase,owner,input);if(mounted.current){complete.current=true;setResult(receipt);setUncertain(false);setMessage('Assignment creation confirmed.');}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry this same reviewed request before starting another owner access.':'Creation was not confirmed. Check the verified account, property access and reason before retrying.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Approve owner portfolio access</Text><Text style={styles.body}>{name}</Text><Text style={styles.body}>Use the email of an existing verified account. This grants portfolio reporting permission for this property. It does not create an account or establish legal title or ownership shares.</Text>{!result&&!review&&<><TextInput accessibilityLabel="Owner account email" keyboardType="email-address" autoCapitalize="none" autoCorrect={false} maxLength={254} value={email} onChangeText={v=>{if(editable())setEmail(v);}} style={styles.input}/><TextInput accessibilityLabel="Assignment approval reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable())setReason(v);}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this account’s portfolio access to this property.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review owner access</Text></Pressable></>}{!result&&review&&<><Text style={styles.body}>Activate {review.email} for {name}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Creating owner access…':uncertain?'Retry same owner access':'Confirm owner access'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit owner access</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{result&&<><Text style={styles.body}>Current owner access: {result.currentActive?'active':'inactive'} · revision {result.currentVersion}</Text><Link href={{pathname:'/manage-owner-access-detail',params:{id:result.id}}} style={styles.link}>Open created owner access →</Link></>}</View>;
}
