import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,ScrollView,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {adminOwnerAccessRegister} from '../lib/admin-owner-access-register';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
import {AdminOwnerAccessCreate} from './admin-owner-access-create';
import {useLoad} from './use-load';
export function AdminOwnerAccessRegister({owner,property}:{owner:string;property:string}){const [page,setPage]=useState(1),[creating,setCreating]=useState<string|null>(null),loader=useCallback(()=>{if(!supabase)throw Error();return adminOwnerAccessRegister(supabase,owner,property,page);},[owner,property,page]);const result=useLoad(owner+property+page,loader);if(creating)return <ScrollView contentContainerStyle={styles.page}><AdminOwnerAccessCreate owner={owner} property={property} name={creating}/></ScrollView>;const heading=<View><Text style={styles.title}>Owner portfolio access register</Text><Text style={styles.body}>Approved access grants portfolio reporting for this property. It does not establish legal title or ownership shares.</Text></View>;if(result.loading)return <View style={styles.page}>{heading}<ActivityIndicator accessibilityLabel="Loading owner access records"/></View>;if(result.error||!result.data)return <View style={styles.page}>{heading}<Text accessibilityRole="alert" style={styles.body}>Owner access register unavailable. Check approved administrator membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignments</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<>{heading}<Text style={styles.heading}>{r.property.name}</Text><Pressable accessibilityRole="button" onPress={()=>setCreating(r.property.name)}><Text style={styles.link}>Approve another owner account →</Text></Pressable>{!r.total&&<Text style={styles.body}>No owner access records are recorded.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Records changed while loading. Refresh to check.</Text>}</>} renderItem={({item})=><View style={styles.card}><Link href={{pathname:'/manage-owner-access-detail',params:{id:item.id}}} style={styles.heading}>Owner account {item.user} →</Link><Text style={styles.body}>{item.active?'Active':'Inactive'} · Revision {item.version}</Text><Text selectable style={styles.body}>Assignment reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:12}}><Text style={styles.body}>{r.total} assignments · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Newer assignments</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Older assignments →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignments</Text></Pressable><Link href="/manage-work" style={styles.link}>Open management work queue →</Link></View>}/>;}
