import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {Link} from 'expo-router';
import {randomUUID} from 'expo-crypto';
import {adminInvitationCommand,sendAdminInvitationCommand,type InvitationCommand} from '../lib/admin-invitation-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function AdminInvitationEditor({owner,invitation}:{owner:string;invitation?:{id:string;version:number;email:string;role:string;state:string}}){
 const [email,setEmail]=useState(''),[role,setRole]=useState('realtor'),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<InvitationCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[receipt,setReceipt]=useState<{id:string;currentState:string;currentVersion:number}|null>(null),[message,setMessage]=useState('');const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<InvitationCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved)return;try{const input=adminInvitationCommand({action:invitation?'revoke':'create',invitation_id:invitation?.id??null,version:invitation?.version??0,email:invitation?null:email,role:invitation?null:role,reason,request_id:randomUUID(),approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Check the approved email, role and reason of 5–500 characters.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const result=await sendAdminInvitationCommand(supabase,owner,input);if(mounted.current){complete.current=true;setReceipt(result);setUncertain(false);setMessage('Invitation decision confirmed. This receipt does not prove email delivery.');}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Outcome could not be confirmed. Retry this exact reviewed request before starting another.':'Change was not confirmed. Check current administrator access and invitation revision before changing the request.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(invitation&&invitation.state!=='pending')return null;
 return <View style={styles.card}><Text style={styles.heading}>{invitation?'Revoke invitation':'Invite a team member'}</Text><Text style={styles.body}>The recipient must sign up, verify the exact email and accept current approval before staff access is granted. Invitations expire after seven days. Use membership management for existing staff access. Check the web delivery monitor for email worker/provider outcomes.</Text>{invitation&&<Text style={styles.body}>{invitation.email} · {invitation.role} · Revision {invitation.version}</Text>}{!receipt&&!review&&<>{!invitation&&<><TextInput accessibilityLabel="Approved invitation email" keyboardType="email-address" autoCapitalize="none" autoCorrect={false} maxLength={254} value={email} onChangeText={v=>{if(editable())setEmail(v);}} style={styles.input}/>{['admin','realtor','manager','finance'].map(v=><Pressable key={v} accessibilityRole="radio" accessibilityState={{selected:role===v}} onPress={()=>{if(editable())setRole(v);}}><Text style={styles.body}>{role===v?'●':'○'} {v}</Text></Pressable>)}</>}<TextInput accessibilityLabel="Invitation approval reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable())setReason(v);}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this invitation decision.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review invitation decision</Text></Pressable></>}{!receipt&&review&&<><Text style={styles.body}>Confirm {review.action} · {review.email??invitation?.email} · {review.role??invitation?.role}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording decision…':uncertain?'Retry same invitation decision':'Confirm invitation decision'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit invitation decision</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{receipt&&<><Text style={styles.body}>Current invitation: {receipt.currentState} · Revision {receipt.currentVersion}</Text><Link href={{pathname:'/manage-invitation-detail',params:{id:receipt.id}}} style={styles.link}>Review recorded invitation →</Link></>}</View>;
}
