import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {membershipCommand,sendMembershipCommand,type MembershipCommand} from '../lib/admin-membership-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function AdminMembershipEditor({owner,member,onRefresh}:{owner:string;member?:{email:string;role:string;revision:string;user:string};onRefresh:()=>void}){
 const [email,setEmail]=useState(member?.email??''),[role,setRole]=useState<string|null>(member?.role??'realtor'),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<MembershipCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<MembershipCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved)return;try{const input=membershipCommand({email:member?.email??email,role,revision:member?.revision??null,request_id:randomUUID(),reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Check the verified account email, chosen role, and reason of 5–500 characters.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendMembershipCommand(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded ${receipt.role??'staff access revocation'} for account ${receipt.user}. Revision: ${receipt.revision??'No current membership'}. Refresh for the current directory.`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Outcome could not be confirmed. Retry the same reviewed request. If your own administrator access changed, another administrator must review membership history.':'Change was not confirmed. Check current membership and keep another verified administrator before changing an administrator role.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>{member?'Review staff access':'Assign a verified staff account'}</Text><Text style={styles.body}>These roles grant implemented organization workflows. They do not create resident, contractor or owner access. Keep another verified administrator before changing or revoking an administrator role. Revocation does not sign out the prospect account or undo earlier work.</Text>{member&&<Text selectable style={styles.body}>{member.email} · Current role: {member.role} · Account: {member.user}</Text>}{!done&&!review&&<>{!member&&<TextInput accessibilityLabel="Approved staff email" keyboardType="email-address" autoCapitalize="none" autoCorrect={false} maxLength={254} value={email} onChangeText={v=>{if(editable())setEmail(v);}} style={styles.input}/>} {['admin','realtor','manager','finance',...(member?[null]:[])].map(v=><Pressable key={v??'revoke'} accessibilityRole="radio" accessibilityState={{selected:role===v}} onPress={()=>{if(editable())setRole(v);}}><Text style={styles.body}>{role===v?'●':'○'} {v??'Revoke staff access'}</Text></Pressable>)}<TextInput accessibilityLabel="Membership approval reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable())setReason(v);}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this staff access change.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review staff change</Text></Pressable></>}{!done&&review&&<><Text style={styles.body}>Confirm {review.role??'revocation'} for {review.email}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording change…':uncertain?'Retry same staff change':'Confirm staff change'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit staff change</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh staff directory</Text></Pressable>}</View>;
}
