import {useIdentity} from './identity';
import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {adminMembershipHistory} from '../lib/admin-membership-history';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function MembershipHistory({owner}:{owner:string}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return adminMembershipHistory(supabase,owner,page);},[owner,page]);const result=useLoad(owner+page,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading membership history"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Membership history could not be loaded. Confirm your current administrator membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh history</Text></Pressable></View>;const r=result.data,time=(v:string)=>new Date(v).toLocaleString('en-JM',{timeZone:'America/Jamaica'});return <View style={styles.card}><Text style={styles.heading}>Staff membership changes</Text><Text style={styles.body}>{r.total} events · Page {r.page} of {r.pages}</Text>{!r.total&&<Text style={styles.body}>No audited changes recorded. Trusted bootstrap assignments may predate this history.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Events changed while loading. Refresh to check.</Text>}{r.rows.map(row=><View key={row.id} style={styles.card}><Text style={styles.heading}>{row.email}</Text><Text style={styles.body}>{row.before??'No staff access'} → {row.after??'Access revoked'} · {time(row.created)} (Jamaica time)</Text><Text style={styles.body}>{row.reason}</Text><Text selectable style={styles.body}>Account: {row.user}</Text><Text selectable style={styles.body}>Recorded by: {row.actor}</Text><Text selectable style={styles.body}>Event reference: {row.id}</Text></View>)}<Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Newer events</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Older events →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh history</Text></Pressable></View>;}

export function AdminMembershipHistoryScreen(){const {user,loading}=useIdentity();if(loading)return <ActivityIndicator accessibilityLabel="Checking account"/>;if(!user)return <Text style={styles.body}>Sign in to review staff membership history.</Text>;return <MembershipHistory key={user.id} owner={user.id}/>;}
