import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {applicationAction,transitionApplication,type ApplicationAction} from '../lib/applications';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ApplicationActions({owner,id,version,status,onRefresh}:{owner:string;id:string;version:number;status:string;onRefresh:()=>void}){
 const [action,setAction]=useState<'reply'|'withdraw'|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[notice,setNotice]=useState(''),[done,setDone]=useState(false);
 const active=useRef(false),mounted=useRef(true),attempt=useRef<ApplicationAction|null>(null),completed=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function submit(){if(active.current||completed.current||!mounted.current)return;active.current=true;setBusy(true);const retrying=attempt.current!==null;try{if(!supabase)throw new EnquiryFailure('Connection unavailable.',false);if(!action)throw new EnquiryFailure('Choose your next step.',false);const payload=attempt.current??applicationAction({id,requestId:randomUUID(),version,action,message});attempt.current=payload;const stored=await transitionApplication(supabase,owner,payload);if(!mounted.current)return;completed.current=true;setDone(true);setUncertain(false);setNotice(`Application history updated. Recorded status: ${stored.status.replaceAll('_',' ')}. Refresh to see the current record.`);}catch(error){if(mounted.current){const unknown=retrying||!(error instanceof EnquiryFailure)||error.uncertain;setUncertain(unknown);if(!unknown)attempt.current=null;setNotice(error instanceof EnquiryFailure?error.message:'Unable to confirm update. Retry the same update.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 const locked=busy||uncertain||done;const canWithdraw=['submitted','under_review','needs_info','approved'].includes(status);
 if(!canWithdraw)return <Text style={styles.body}>No applicant action is available at this stage.</Text>;
 return <View style={styles.card}><Text style={styles.heading}>Your next step</Text>{!done&&<>{status==='needs_info'&&<Pressable accessibilityRole="radio" accessibilityState={{checked:action==='reply',disabled:locked}} disabled={locked} onPress={()=>setAction('reply')}><Text style={styles.link}>{action==='reply'?'◉':'○'} Reply and resubmit</Text></Pressable>}<Pressable accessibilityRole="radio" accessibilityState={{checked:action==='withdraw',disabled:locked}} disabled={locked} onPress={()=>setAction('withdraw')}><Text style={styles.link}>{action==='withdraw'?'◉':'○'} Withdraw application</Text></Pressable>{action==='withdraw'&&<Text style={styles.body}>Withdrawal ends this application. The team will see your reason in shared history.</Text>}<Text style={styles.body}>Shared reply or withdrawal reason</Text><TextInput accessibilityLabel="Shared application message" value={message} onChangeText={setMessage} editable={!locked} multiline maxLength={2000} style={styles.input}/><Pressable accessibilityRole="button" disabled={busy||(!uncertain&&(!action||message.trim().length<5))} onPress={()=>void submit()} style={styles.button}><Text style={styles.buttonText}>{busy?'Recording…':uncertain?'Retry same update':action==='withdraw'?'Confirm withdrawal':'Record next step'}</Text></Pressable></>}{!!notice&&<Text accessibilityRole={uncertain?'alert':'text'} style={styles.body}>{notice}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Check current application and history</Text></Pressable>}{uncertain&&<Text style={styles.body}>Check shared history before starting another update if you leave this screen.</Text>}</View>;
}
