import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {contractorVisitAttempt,respondToContractorVisit,type ContractorVisitAttempt} from '../lib/contractor-visit-response';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ContractorVisitResponse({owner,assignment,id,version,state,started,onRefresh}:{owner:string;assignment:string;id:string;version:number;state:string;started:boolean;onRefresh:()=>void}){
 const [action,setAction]=useState<ContractorVisitAttempt['action']>(state==='confirmed'?'cancel':started?'decline':'confirm'),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<ContractorVisitAttempt|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 const available=state==='confirmed'||state==='proposed';
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??contractorVisitAttempt({assignment,visit_id:id,request_id:randomUUID(),version,action,reason});frozen.current=input;const result=await respondToContractorVisit(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current appointment: ${result.currentState} (version ${result.currentVersion}). This does not authorize a visit or entry.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the appointment.':'Response was not confirmed. Check the reason and refresh the appointment before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Respond to the appointment</Text>{!done&&<>{!confirm&&<>{(state==='confirmed'?['cancel']:started?['decline','cancel']:['confirm','decline','cancel']).map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:action===value}} onPress={()=>{if(editable())setAction(value as ContractorVisitAttempt['action']);}}><Text style={styles.body}>{action===value?'●':'○'} {value}</Text></Pressable>)}<TextInput accessibilityLabel="Appointment response reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. Confirmation reserves the approved time window. Cancellation may require the team to resolve progressed work first.</Text><Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(true);}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same appointment response':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh appointment</Text></Pressable>}</View>;
}
