import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {completionAttempt,submitContractorCompletion,type CompletionAttempt} from '../lib/contractor-completion-submit';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function CompletionSubmit({owner,offer,version,onRefresh}:{owner:string;offer:string;version:number;onRefresh:()=>void}){
 const [summary,setSummary]=useState(''),[tests,setTests]=useState(''),[outstanding,setOutstanding]=useState(''),[reason,setReason]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<CompletionAttempt|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable())return;try{completionAttempt({action:'submit',offer_id:offer,offer_version:version,version:0,request_id:randomUUID(),summary,tests_performed:tests,outstanding_items:outstanding,reason});setMessage('');setReview(true);}catch{setMessage('Provide work details (20–4000 characters), tests and results (10–2000), outstanding items (5–2000), and a submission reason (5–500).');}}
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!review)return;active.current=true;setBusy(true);try{const input=frozen.current??completionAttempt({action:'submit',offer_id:offer,offer_version:version,version:0,request_id:randomUUID(),summary,tests_performed:tests,outstanding_items:outstanding,reason});frozen.current=input;const r=await submitContractorCompletion(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Report recorded as submitted (version ${r.version}). Current review: ${r.currentState} (version ${r.currentVersion}). Report reference: ${r.id}. Submission does not confirm approved completion or payment.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Submission could not be confirmed. Keep these details and retry the same report, or refresh the report register before preparing another.':'Submission was not confirmed. Check the details and refresh readiness before changing the report.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Prepare a completion report</Text>{!done&&<>{!review?<>{([{label:'Work performed',value:summary,set:setSummary,max:4000},{label:'Tests and results',value:tests,set:setTests,max:2000},{label:'Outstanding items',value:outstanding,set:setOutstanding,max:2000},{label:'Submission reason',value:reason,set:setReason,max:500}]).map(field=><View key={field.label}><Text style={styles.body}>{field.label}</Text><TextInput accessibilityLabel={field.label} multiline maxLength={field.max} value={field.value} editable={!busy&&!uncertain} onChangeText={value=>{if(editable())field.set(value);}} style={styles.input}/></View>)}<Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review report</Text></Pressable></>:<><Text style={styles.heading}>Work performed</Text><Text style={styles.body}>{summary}</Text><Text style={styles.heading}>Tests and results</Text><Text style={styles.body}>{tests}</Text><Text style={styles.heading}>Outstanding items</Text><Text style={styles.body}>{outstanding}</Text><Text style={styles.heading}>Submission reason</Text><Text style={styles.body}>{reason}</Text><Text style={styles.body}>Submission includes verified uploaded evidence for this assignment and fixes those files to the report. Unfinished reservations are excluded. The server checks current work and recorded departures again.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Submitting report…':uncertain?'Retry same report':'Confirm submission'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setReview(false);}}><Text style={styles.link}>Edit report</Text></Pressable>}</>}</>}{!!message&&<Text selectable accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh reports and readiness</Text></Pressable>}</View>;
}
