import {useCallback} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {contractorCurrentVisit} from '../lib/contractor-visit';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {ContractorVisitResponse} from './contractor-visit-response';
import {styles} from './styles';
const date=(value:string)=>new Date(value).toLocaleString('en-JM',{timeZone:'America/Jamaica'});
export function ContractorVisit({owner,offer}:{owner:string;offer:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return contractorCurrentVisit(supabase,owner,offer);},[owner,offer]);const result=useLoad(owner+offer,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Checking appointment and entry authorization"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Appointment and entry authorization could not be checked.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Check again</Text></Pressable></View>;const {visit,permit}=result.data;return <View style={styles.card}><Text style={styles.heading}>Appointment and entry</Text>{visit?<><Text style={styles.body}>{visit.state==='confirmed'?'Confirmed appointment':'Proposed appointment'}</Text><Text style={styles.body}>{date(visit.starts)} → {date(visit.ends)} (Jamaica time)</Text><Text style={styles.body}>{visit.note}</Text><ContractorVisitResponse key={visit.id+":"+visit.version} owner={owner} assignment={offer} id={visit.id} version={visit.version} state={visit.state} started={visit.started} onRefresh={result.retry}/><Text style={styles.body}>The appointment reserves a time window. Entry requires separate authorization.</Text>{permit?<><Text style={styles.heading}>Recorded entry permit</Text><Text selectable style={styles.body}>Permit reference: {permit.id}</Text><Text style={styles.body}>{permit.window==='expired'?'Permit window expired':permit.window==='upcoming'?'Permit window is upcoming':'Within the recorded permit window at the last check'}</Text><Text style={styles.body}>{date(permit.from)} → {date(permit.until)}</Text><Text style={styles.body}>{permit.instructions}</Text></>:<Text style={styles.body}>No entry authorization is recorded for this appointment. Contact management before visiting.</Text>}</>:<Text style={styles.body}>No current appointment is recorded. Contact the property team about scheduling.</Text>}<Text style={styles.body}>Property security must verify your identity and current authorization before entry. Refresh before visiting.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh appointment and permit</Text></Pressable></View>;}
