import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {revokeCosigner,cosignerRevocation,type CosignerRevocation} from '../lib/application-cosigners';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function CosignerRevoke({owner,application,id,version,onRefresh}:{owner:string;application:string;id:string;version:number;onRefresh:()=>void}){
 const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<CosignerRevocation|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function withdraw(){if(active.current||complete.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??cosignerRevocation({application,id,version,requestId:randomUUID()});frozen.current=input;await revokeCosigner(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage('This invitation is recorded as revoked.');}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Revocation could not be confirmed. Retry this same request or refresh its recorded state.':'Revocation was not confirmed. Refresh the invitation before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={{gap:12}}>{!done&&<>{!confirm?<Pressable accessibilityRole="button" onPress={()=>setConfirm(true)}><Text style={styles.link}>Revoke invitation</Text></Pressable>:<><Text style={styles.body}>Revoke this invitation and remove its review participation? This does not cancel a separately signed legal agreement.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void withdraw()}><Text style={styles.link}>{busy?'Confirming…':uncertain?'Retry same invitation revocation':'Confirm revocation'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>setConfirm(false)}><Text style={styles.link}>Keep invitation</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityRole={uncertain?'alert':'text'} style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh invitation register</Text></Pressable>}</View>;
}
