import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {cosignerDecision,respondToCosigner,type CosignerDecision} from '../lib/cosigners';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function CosignerDecisions({owner,id,version,state,available,onRefresh}:{owner:string;id:string;version:number;state:string;available:boolean;onRefresh:()=>void}){
 const [action,setAction]=useState<'accept'|'decline'|'withdraw'|null>(null),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),frozen=useRef<CosignerDecision|null>(null),completed=useRef(false),unknownAttempt=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function submit(){if(active.current||completed.current||!mounted.current||!supabase||!action)return;active.current=true;setBusy(true);try{const attempt=frozen.current??cosignerDecision({id,requestId:randomUUID(),version,action,consent});frozen.current=attempt;const result=await respondToCosigner(supabase,owner,attempt);if(!mounted.current)return;completed.current=true;unknownAttempt.current=false;setDone(true);setUncertain(false);setMessage(`Recorded invitation status: ${result.state}. This does not sign a lease or create a guarantee.`);}catch(error){if(mounted.current){const unknown=!!frozen.current&&(unknownAttempt.current||!(error instanceof EnquiryFailure)||error.uncertain);if(!unknown)frozen.current=null;unknownAttempt.current=unknown;setUncertain(unknown);setMessage(unknown?'Decision could not be confirmed. Retry this same decision or refresh its recorded status.':'This decision was not confirmed. Check consent and refresh the invitation before changing your decision.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 const choices=state==='pending'?['accept','decline'] as const:state==='accepted'?['withdraw'] as const:[];
 return <View style={styles.card}><Text style={styles.heading}>Your review decision</Text><Text style={styles.body}>Accepting permits participation in rental application review. Legal obligations require a separate approved agreement.</Text>{!done&&(available||uncertain)&&<>{!uncertain&&choices.map(choice=><Pressable key={choice} accessibilityRole="radio" accessibilityState={{checked:action===choice,disabled:busy}} disabled={busy} onPress={()=>{if(active.current||frozen.current||completed.current||!mounted.current)return;setAction(choice);setConsent(false);}}><Text style={styles.link}>{action===choice?'●':'○'} {choice==='accept'?'Accept review participation':choice==='decline'?'Decline invitation':'Withdraw review consent'}</Text></Pressable>)}{action==='accept'&&!uncertain&&<Pressable accessibilityRole="checkbox" accessibilityState={{checked:consent,disabled:busy}} disabled={busy} onPress={()=>{if(active.current||frozen.current||completed.current||!mounted.current)return;setConsent(!consent);}}><Text style={styles.body}>{consent?'☑':'☐'} I explicitly consent to participate in this application review.</Text></Pressable>}{action&&<><Text style={styles.body}>Confirm {action==='withdraw'?'withdrawal of your review consent':action==='decline'?'declining this invitation':'review participation'}?</Text><Pressable accessibilityRole="button" disabled={busy||action==='accept'&&!consent} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording…':uncertain?'Retry same decision':'Confirm decision'}</Text></Pressable></>}</>}{!available&&!uncertain&&!done&&<Text style={styles.body}>A new decision is not currently available.</Text>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh recorded invitation</Text></Pressable>}</View>;
}
