import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {cosignerInvite,inviteCosigner,type CosignerInvite} from '../lib/application-cosigners';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function CosignerInviteControl({owner,application,onRefresh}:{owner:string;application:string;onRefresh:()=>void}){
 const [email,setEmail]=useState(''),[permission,setPermission]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),frozen=useRef<CosignerInvite|null>(null),unknownAttempt=useRef(false),completed=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function submit(){if(active.current||completed.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??cosignerInvite(application,randomUUID(),email,permission);frozen.current=input;const result=await inviteCosigner(supabase,owner,input);if(!mounted.current)return;completed.current=true;setDone(true);setUncertain(false);setMessage(`Invitation recorded for ${input.email}. Current status: ${result.state}. This does not confirm email delivery or recipient consent.`);}catch(error){if(mounted.current){const unknown=!!frozen.current&&(unknownAttempt.current||!(error instanceof EnquiryFailure)||error.uncertain);unknownAttempt.current=unknown;if(!unknown)frozen.current=null;setUncertain(unknown);setMessage(unknown?'Invitation could not be confirmed. Retry this same recipient request or refresh your invitation register.':'Invitation was not confirmed. Check the recipient, sharing permission, application stage and invitation limits.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Invite a co-signer</Text><Text style={styles.body}>The recipient receives your name, the property and advertised rent for application review. Participation is separate from signing a legal guarantee.</Text>{!done&&<><TextInput accessibilityLabel="Co-signer email" autoCapitalize="none" autoCorrect={false} keyboardType="email-address" value={email} editable={!busy&&!uncertain} onChangeText={value=>{if(!active.current&&!frozen.current&&!completed.current&&mounted.current)setEmail(value);}} style={styles.input}/>{!uncertain&&<Pressable accessibilityRole="checkbox" accessibilityState={{checked:permission,disabled:busy}} disabled={busy} onPress={()=>{if(!active.current&&!frozen.current&&!completed.current&&mounted.current)setPermission(!permission);}}><Text style={styles.body}>{permission?'☑':'☐'} I have permission to share this invitation with the recipient.</Text></Pressable>}<Pressable accessibilityRole="button" disabled={busy||!permission} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording invitation…':uncertain?'Retry same invitation request':'Confirm invitation'}</Text></Pressable></>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh invitation register</Text></Pressable>}</View>;
}
