import {useState} from 'react';
import {Pressable,Text,View,StyleSheet} from 'react-native';
import {Link} from 'expo-router';
import {matchRealtors,realtors,type MatchPreferences} from '../../../lib/discovery/data';
const areas=Array.from(new Set(realtors.flatMap(r=>r.areas))).sort();
const questions:{key:keyof MatchPreferences;title:string;options:readonly (readonly [string,string])[]}[]=[
 {key:'intent',title:'What brings you here?',options:[['buy','Buy a home'],['rent','Rent a home'],['sell','Sell a property']]},
 {key:'area',title:'Where are you looking?',options:areas.map(area=>[area,area] as const)},
 {key:'communication',title:'How do you like to communicate?',options:[['thoughtful','Thoughtful and reassuring'],['direct','Direct and clear'],['collaborative','Collaborative and conversational']]},
 {key:'guidance',title:'What guidance feels right?',options:[['step-by-step','Walk me through each step'],['data-led','Help me compare the evidence'],['independent','Give me room to explore']]},
 {key:'pace',title:'How do you like to decide?',options:[['considered','Time to reflect'],['decisive','A focused plan'],['flexible','A flexible rhythm']]}
];
export function DemoRealtorMatch(){const [step,setStep]=useState(0),[answers,setAnswers]=useState<Partial<MatchPreferences>>({}),[complete,setComplete]=useState(false);const question=questions[step];const results=complete?matchRealtors(answers as MatchPreferences):[];
 return <View style={s.panel}><Text style={s.kicker}>DEMO · FIND YOUR FIT</Text><Text style={s.heading}>Good chemistry starts with a conversation.</Text><Text style={s.body}>Five quick questions about the way you like to work. Fictional profiles; no real assignment or message is made.</Text>{!complete?<><Text style={s.progress} accessibilityLiveRegion="polite">Question {step+1} of {questions.length}</Text><Text style={s.question}>{question.title}</Text>{question.options.map(([value,label])=><Pressable key={value} accessibilityRole="radio" accessibilityState={{checked:answers[question.key]===value}} onPress={()=>setAnswers(previous=>({...previous,[question.key]:value}))} style={[s.option,answers[question.key]===value&&s.selected]}><Text style={s.optionText}>{answers[question.key]===value?'●':'○'}  {label}</Text></Pressable>)}<View style={s.actions}><Pressable accessibilityRole="button" disabled={step===0} accessibilityState={{disabled:step===0}} onPress={()=>setStep(previous=>Math.max(0,previous-1))} style={s.back}><Text style={s.optionText}>Back</Text></Pressable><Pressable accessibilityRole="button" disabled={!answers[question.key]} accessibilityState={{disabled:!answers[question.key]}} onPress={()=>{if(!answers[question.key])return;if(step===questions.length-1)setComplete(true);else setStep(previous=>previous+1);}} style={[s.button,!answers[question.key]&&s.disabled]}><Text style={s.buttonText}>{step===questions.length-1?'See my matches':'Continue'} →</Text></Pressable></View></>:<><Text style={s.question}>Your demo matches</Text><Text style={s.body}>{answers.intent} · {answers.area}. Suggestions reflect preferences, not a personality diagnosis. You can choose any realtor.</Text>{results.map(({realtor,points,reasons})=><View style={s.result} key={realtor.id}><Text style={s.kicker}>FICTIONAL REALTOR · {points}/8 PREFERENCE POINTS</Text><Text style={s.question}>{realtor.name}</Text><Text style={s.body}>{realtor.tagline}</Text>{reasons.map(reason=><Text style={s.body} key={reason}>✓ {reason}</Text>)}<Link href="https://www.openhousejamaica.com/demo?role=prospect" style={s.link}>Explore the prospect simulation in your browser ↗</Link></View>)}{!results.length&&<Text style={s.body}>No demo profile covers this area and journey. Change your answers to explore another option.</Text>}<Pressable accessibilityRole="button" onPress={()=>{setComplete(false);setStep(0);}}><Text style={s.link}>Edit my answers</Text></Pressable></>}<Text style={s.note}>Answers stay in this screen session and are not saved to your real account.</Text></View>;
}
const s=StyleSheet.create({panel:{padding:22,gap:16,borderRadius:22,backgroundColor:'#fff',borderWidth:1,borderColor:'#E2E8F0'},kicker:{fontSize:11,fontWeight:'700',letterSpacing:1,color:'#003A8C'},heading:{fontFamily:'BrandHeading',fontSize:27,lineHeight:33,fontWeight:'600',color:'#0B2346'},body:{fontFamily:'BrandBody',fontSize:15,lineHeight:23,color:'#52647B'},progress:{fontSize:12,color:'#003A8C',fontWeight:'600'},question:{fontFamily:'BrandHeading',fontSize:21,lineHeight:27,fontWeight:'600',color:'#0B2346'},option:{padding:17,borderRadius:14,borderWidth:1,borderColor:'#E2E8F0'},selected:{borderColor:'#003A8C',backgroundColor:'#EAF1FA'},optionText:{fontSize:15,color:'#003A8C'},actions:{flexDirection:'row',gap:16,alignItems:'center'},back:{padding:12},button:{flex:1,padding:16,borderRadius:12,backgroundColor:'#003A8C'},disabled:{backgroundColor:'#667A96'},buttonText:{fontSize:15,fontWeight:'600',color:'#fff',textAlign:'center'},result:{padding:18,gap:12,backgroundColor:'#F8FAFC',borderRadius:16},link:{paddingVertical:12,color:'#003A8C',fontWeight:'600',fontSize:15},note:{fontFamily:'BrandBody',fontSize:12,lineHeight:18,color:'#52647B'}});
