import {useCallback,useEffect,useRef,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {applicationDocumentReservations} from '../lib/application-documents';
import {finishDocument} from '../lib/document-upload';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {DocumentWithdraw} from './document-withdraw';
import {styles} from './styles';
export function DocumentRecovery({owner,application}:{owner:string;application:string}){
 const [page,setPage]=useState(1);const loader=useCallback(()=>{if(!supabase)throw Error();return applicationDocumentReservations(supabase,owner,application,page);},[owner,application,page]);const result=useLoad(owner+application+page,loader);
 return <View style={styles.card}><Text style={styles.heading}>Interrupted uploads</Text><Text style={styles.body}>Stored reservations remain available after closing the app. Check certification if your file may already have reached storage. Otherwise withdraw the reservation and choose the file again.</Text>{result.loading?<Text style={styles.body}>Checking reservations…</Text>:result.error?<Text accessibilityRole="alert" style={styles.body}>Reservations could not be loaded.</Text>:result.data&&<><Text style={styles.body}>{result.data.total} reservations · Page {result.data.page} of {result.data.pages}</Text>{!result.data.total&&<Text style={styles.body}>No unfinished reservations are recorded.</Text>}{!!result.data.total&&!result.data.rows.length&&<Text style={styles.body}>Records changed while loading. Refresh to check.</Text>}{result.data.rows.map(row=><View key={row.id} style={styles.card}><Text style={styles.heading}>{row.file_name}</Text><Text style={styles.body}>{row.kind} · reserved</Text><Text style={styles.body}>Reservation expires {new Date(row.expires_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</Text><Text selectable style={styles.body}>Reference: {row.id}</Text><Certify owner={owner} id={row.id} onRefresh={result.retry}/><DocumentWithdraw owner={owner} application={application} id={row.id} onRefresh={result.retry}/></View>)}<Pressable accessibilityRole="button" disabled={result.data.page===1} onPress={()=>setPage(result.data!.page-1)}><Text style={styles.link}>← Newer reservations</Text></Pressable><Pressable accessibilityRole="button" disabled={result.data.page===result.data.pages} onPress={()=>setPage(result.data!.page+1)}><Text style={styles.link}>Older reservations →</Text></Pressable></>}<Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh reservations</Text></Pressable></View>;
}
export function Certify({owner,id,onRefresh}:{owner:string;id:string;onRefresh:()=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[done,setDone]=useState(false);const active=useRef(false),mounted=useRef(true),complete=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const base=process.env.EXPO_PUBLIC_APP_URL||'';
 async function check(){if(active.current||complete.current||!mounted.current||!supabase||!base)return;active.current=true;setBusy(true);try{await finishDocument(supabase,owner,base,id);if(!mounted.current)return;complete.current=true;setDone(true);setMessage('Document recorded as uploaded. Refresh document records to view it.');}catch{if(mounted.current)setMessage('Certification could not be confirmed. The file may be missing, expired or invalid, or the connection unavailable. Retry this same reservation or withdraw it.');}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={{gap:12}}>{base?!done&&<Pressable accessibilityRole="button" disabled={busy} onPress={()=>void check()}><Text style={styles.link}>{busy?'Checking…':'Check stored file and finish upload'}</Text></Pressable>:<Text style={styles.body}>Certification awaits the secure application connection.</Text>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh reservation records</Text></Pressable>}</View>;
}
