import {FinanceInvoiceUpload} from './finance-invoice-upload';
import {FinanceInvoiceReservations} from './finance-invoice-reservations';
import {FinanceInvoiceReview} from './finance-invoice-review';
import {FinanceInvoiceOpen} from './finance-invoice-open';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {financeInvoiceEvidence} from '../lib/finance-invoice-evidence';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function FinanceInvoiceDocuments({owner,id,version,onRefresh}:{owner:string;id:string;version:number;onRefresh:()=>void}){const loader=useCallback(()=>{if(!supabase)throw Error();return financeInvoiceEvidence(supabase,owner,id);},[owner,id]);const result=useLoad(JSON.stringify([owner,id,version]),loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading certified invoice documents"/>;if(result.error||!result.data||result.data.invoice.version!==version)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Certified invoice documents unavailable or the invoice changed. Refresh the invoice before reviewing.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh documents</Text></Pressable></View>;const r=result.data;return <View style={styles.card}><Text style={styles.heading}>Invoice documents</Text><Text style={styles.body}>{r.sealed?'These certified documents are frozen at review revision 2. Approval retains the same reviewed source.':'These are certified uploaded documents. Documents are frozen when independent finance review begins.'}</Text>{!r.sourceReady&&<Text style={styles.body}>No certified vendor invoice document is recorded. A source invoice is required before review.</Text>}{r.rows.map(file=><View key={file.id} style={styles.card}><Text style={styles.heading}>{file.name}</Text><Text style={styles.body}>{file.kind==='invoice'?'Vendor invoice':'Supporting document'} · {file.mime} · {file.size.toLocaleString()} bytes</Text><Text selectable style={styles.body}>Document reference: {file.id}</Text><FinanceInvoiceOpen key={JSON.stringify([owner,id,version,file.id])} owner={owner} invoice={id} id={file.id}/></View>)}<>{r.invoice.submitter===owner&&r.invoice.state==='submitted'&&<FinanceInvoiceUpload key={JSON.stringify([owner,id,version])} owner={owner} invoice={id} onRefresh={onRefresh}/>} {r.invoice.submitter===owner&&<FinanceInvoiceReservations key={JSON.stringify([owner,id,version])} owner={owner} id={id} version={version} onRefresh={onRefresh}/>}</><FinanceInvoiceReview key={JSON.stringify([owner,id,version])} owner={owner} id={id} version={version} actions={r.invoice.actions.filter(action=>action!=="review"||r.sourceReady)} onRefresh={onRefresh}/><Text style={styles.body}>Document certification does not independently verify the vendor claim or confirm payment.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh documents</Text></Pressable></View>;}
