import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {financeAccountCommand,sendFinanceAccount,type AccountCommand} from '../lib/finance-account-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function FinanceAccountReview({owner,onRefresh}:{owner:string;onRefresh:()=>void}){
 const [code,setCode]=useState(''),[name,setName]=useState(''),[classification,setClassification]=useState('asset');
 const [reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<AccountCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<AccountCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved)return;try{const input=financeAccountCommand({code,name,account_class:classification,request_id:randomUUID(),reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Provide a reason of 5–500 characters and explicit approval to register this account.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendFinanceAccount(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Account ${receipt.code} · ${receipt.name} registered (${receipt.id}). Refresh the approved register.`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry this same account request before making another decision.':'Response was not confirmed. Check your finance account and approved account fields before changing the request.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Register an approved account</Text><Text style={styles.body}>Account registration is immutable and does not create a balance or confirm a payment. Confirm the code, name and classification against your approved chart of accounts.</Text>{!done&&!review&&<><TextInput accessibilityLabel="Account code" value={code} maxLength={40} autoCapitalize="characters" onChangeText={v=>{if(editable())setCode(v);}} style={styles.input}/><TextInput accessibilityLabel="Account name" value={name} maxLength={120} onChangeText={v=>{if(editable())setName(v);}} style={styles.input}/>{['asset','liability','equity','income','expense'].map(c=><Pressable key={c} accessibilityRole="radio" accessibilityState={{selected:classification===c}} onPress={()=>{if(editable())setClassification(c);}}><Text style={styles.body}>{classification===c?'●':'○'} {c}</Text></Pressable>)}<TextInput accessibilityLabel="Account approval reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable())setReason(v);}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve registration of this account and classification.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review account</Text></Pressable></>}{!done&&review&&<><Text style={styles.body}>Confirm {review.code} · {review.name} · {review.account_class}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Registering account…':uncertain?'Retry same account registration':'Confirm account registration'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit account</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh approved accounts</Text></Pressable>}</View>;
}
