import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {financeInvoiceCommand,sendFinanceInvoice,type InvoiceCommand} from '../lib/finance-invoice-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function FinanceInvoiceReview({owner,id,version,actions,onRefresh}:{owner:string;id:string;version:number;actions:InvoiceCommand['action'][];onRefresh:()=>void}){
 const [reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<InvoiceCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<InvoiceCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(action:InvoiceCommand['action']){if(!editable()||!approved||!actions.includes(action))return;try{const input=financeInvoiceCommand({invoice_id:id,version,action,request_id:randomUUID(),reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Provide a reason of 5–500 characters and explicit approval for this invoice decision.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendFinanceInvoice(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Invoice ${receipt.id}: ${receipt.state} recorded at revision ${receipt.version}. Current state: ${receipt.currentState}, revision ${receipt.currentVersion}. Refresh to review retained history.`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry this same invoice request before making another decision.':'Response was not confirmed. Check your finance account and invoice before changing the request.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!actions.length&&!review&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Review invoice decision</Text><Text style={styles.body}>Invoice {id} · Revision {version}</Text><Text style={styles.body}>Review and approval require independent finance actors. Submitted details remain fixed. Approval does not post the invoice to the ledger or pay the vendor.</Text>{!done&&!review&&<><TextInput accessibilityLabel="Invoice decision reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable()){setReason(v);setApproved(false);}}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this invoice decision and its recorded reason.</Text></Pressable><View>{actions.map(action=><Pressable key={action} accessibilityRole="button" onPress={()=>prepare(action)}><Text style={styles.link}>Review {action} decision</Text></Pressable>)}</View></>}{!done&&review&&<><Text style={styles.body}>Confirm {review.action} for {review.invoice_id}, revision {review.version}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording decision…':uncertain?'Retry same decision':'Confirm invoice decision'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);setApproved(false);}}}><Text style={styles.link}>Edit decision</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh invoice</Text></Pressable>}</View>;
}
