import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {financeChequeReservations} from '../lib/finance-cheque-reservations';
import {ChequeUploadCertify} from './finance-cheque-upload-certify';
import {ChequeUploadWithdraw} from './finance-cheque-upload-withdraw';
import {financeChequeDecisions} from '../lib/finance-cheque-decisions';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function FinanceChequeReservations({owner,id,version,onRefresh}:{owner:string;id:string;version:number;onRefresh:()=>void}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeChequeReservations(supabase,owner,id,page);},[owner,id,page]);const result=useLoad(JSON.stringify([owner,id,version,page]),loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading your cheque upload records"/>;if(result.error||!result.data||result.data.cheque.version!==version)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Your upload records are unavailable or the cheque changed. Refresh the cheque before changing documents.</Text><Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh cheque</Text></Pressable></View>;const r=result.data,kinds=financeChequeDecisions(r.cheque.state).flatMap(c=>c.kind?[c.kind]:[]);return <View style={styles.card}><Text style={styles.heading}>Your upload records</Text><Text style={styles.body}>Reservations are not certified documents. Check stored files to finish an interrupted upload, using their retained reservation, or withdraw an abandoned unused upload. Bank approval is a separate step.</Text>{!r.total&&<Text style={styles.body}>No upload reservations recorded.</Text>}{r.rows.map(file=><View key={file.id} style={styles.card}><Text style={styles.heading}>{file.name}</Text><Text style={styles.body}>{file.kind} · {file.state} · {file.size.toLocaleString()} bytes</Text>{file.state==='reserved'&&<Text style={styles.body}>Reservation expires {new Date(file.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text>}<Text selectable style={styles.body}>Document reference: {file.id}</Text>{!file.used&&kinds.includes(file.kind)&&file.state==='reserved'&&<ChequeUploadCertify key={owner+id+file.id} owner={owner} cheque={id} id={file.id} onRefresh={onRefresh}/>}{!!kinds.length&&!file.used&&['reserved','uploaded'].includes(file.state)&&<ChequeUploadWithdraw key={owner+id+file.id} owner={owner} cheque={id} id={file.id} onRefresh={onRefresh}/>}</View>)}{!kinds.length&&<Text style={styles.body}>Document certification is closed at this cheque stage.</Text>}<Text style={styles.body}>{r.total} upload records · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>{if(r.page>1)setPage(r.page-1);}}><Text style={styles.link}>← Newer records</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>{if(r.page<r.pages)setPage(r.page+1);}}><Text style={styles.link}>Older records →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh upload records</Text></Pressable></View>;}
