import {useEffect,useRef,useState} from 'react';
import {Modal,Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {FinanceAccountPicker} from './finance-account-picker';
import {financeInvoicePostCommand,postFinanceInvoice,type InvoicePostCommand} from '../lib/finance-invoice-post-command';
import type {financeAccount} from '../lib/finance-account';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
type Account=Awaited<ReturnType<typeof financeAccount>>;
export function FinanceInvoicePostReview({owner,id,version,amount,onRefresh}:{owner:string;id:string;version:number;amount:string;onRefresh:()=>void}){
 const [debit,setDebit]=useState<Account|null>(null),[credit,setCredit]=useState<Account|null>(null),[picker,setPicker]=useState<'debit'|'credit'|null>(null),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<InvoicePostCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<InvoicePostCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const editable=()=>mounted.current&&!active.current&&!locked.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved||picker)return;try{if(!debit||!credit||!['asset','expense'].includes(debit.classification)||credit.classification!=='liability')throw Error();const input=financeInvoicePostCommand({invoice_id:id,version,debit_account_id:debit.id,credit_account_id:credit.id,request_id:randomUUID(),reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Select distinct asset/expense debit and liability credit accounts, provide a reason and confirm the allocation.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await postFinanceInvoice(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Invoice posting verified in journal ${receipt.journal}.${receipt.reversal?' The original posting has a retained reversal.':''}`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Posting could not be confirmed. Retry the same request before creating another posting.':'Posting was not confirmed. Check the accounts, invoice and current finance authority.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Post approved invoice to ledger</Text><Text style={styles.body}>{amount} · Revision {version}. Record the gross invoice accrual. Payment and tax allocation are separate workflows.</Text>{!done&&!review&&<><Text style={styles.body}>Debit: {debit?`${debit.code} · ${debit.name}`:'Choose asset or expense'}</Text><Text style={styles.body}>Credit: {credit?`${credit.code} · ${credit.name}`:'Choose liability'}</Text>{(['debit','credit'] as const).map(side=><Pressable key={side} accessibilityRole="button" onPress={()=>{if(editable())setPicker(side);}}><Text style={styles.link}>Choose {side} account</Text></Pressable>)}<Modal visible={!!picker} animationType="slide" onRequestClose={()=>{if(editable())setPicker(null);}}><View style={{flex:1,padding:16}}><Pressable accessibilityRole="button" onPress={()=>{if(editable())setPicker(null);}}><Text style={styles.link}>Cancel account selection</Text></Pressable>{picker&&<FinanceAccountPicker key={picker} owner={owner} onSelect={account=>{if(!editable())return;if(picker==='debit'&&!['asset','expense'].includes(account.classification)||picker==='credit'&&account.classification!=='liability'){setMessage('This account classification cannot be used on the selected side.');return;}if(picker==='debit')setDebit(account);else setCredit(account);setPicker(null);setApproved(false);setMessage('');}}/>}</View></Modal><TextInput accessibilityLabel="Invoice posting reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable()){setReason(v);setApproved(false);}}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this invoice accounting allocation.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review invoice posting</Text></Pressable></>}{!done&&review&&<><Text style={styles.body}>Confirm {amount}: debit {debit?.code} · {debit?.name}; credit {credit?.code} · {credit?.name}. Reason: {review.reason}</Text><Text selectable style={styles.body}>Request: {review.request_id}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Posting invoice…':uncertain?'Retry same invoice posting':'Confirm invoice posting'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);setApproved(false);}}}><Text style={styles.link}>Edit posting</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh invoice posting</Text></Pressable>}</View>;
}
