import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {financeInvoiceReservations} from '../lib/finance-invoice-reservations';
import {InvoiceUploadCertify} from './finance-invoice-upload-certify';
import {InvoiceUploadWithdraw} from './finance-invoice-upload-withdraw';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function FinanceInvoiceReservations({owner,id,version,onRefresh}:{owner:string;id:string;version:number;onRefresh:()=>void}){const [page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return financeInvoiceReservations(supabase,owner,id,page);},[owner,id,page]);const result=useLoad(JSON.stringify([owner,id,version,page]),loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading your invoice upload records"/>;if(result.error||!result.data||result.data.invoice.version!==version)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Your upload records are unavailable or the invoice changed. Refresh the invoice before changing documents.</Text><Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh invoice</Text></Pressable></View>;const r=result.data,editable=r.invoice.state==='submitted';return <View style={styles.card}><Text style={styles.heading}>Your upload records</Text><Text style={styles.body}>Reservations are not certified documents. Check stored files to finish an interrupted upload, or withdraw abandoned records. Withdrawal does not promise immediate file deletion.</Text>{!r.total&&<Text style={styles.body}>No upload reservations recorded.</Text>}{r.rows.map(file=><View key={file.id} style={styles.card}><Text style={styles.heading}>{file.name}</Text><Text style={styles.body}>{file.kind} · {file.state} · {file.size.toLocaleString()} bytes</Text>{file.state==='reserved'&&<Text style={styles.body}>Reservation expires {new Date(file.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text>}<Text selectable style={styles.body}>Document reference: {file.id}</Text>{editable&&file.state==='reserved'&&<InvoiceUploadCertify key={owner+id+file.id} owner={owner} invoice={id} id={file.id} onRefresh={onRefresh}/>} {editable&&['reserved','uploaded'].includes(file.state)&&<InvoiceUploadWithdraw key={owner+id+file.id} owner={owner} invoice={id} id={file.id} onRefresh={onRefresh}/>}</View>)}{!editable&&<Text style={styles.body}>Document changes are closed after invoice review or rejection.</Text>}<Text style={styles.body}>{r.total} upload records · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>{if(r.page>1)setPage(r.page-1);}}><Text style={styles.link}>← Newer records</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>{if(r.page<r.pages)setPage(r.page+1);}}><Text style={styles.link}>Older records →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh upload records</Text></Pressable></View>;}
