import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {withdrawInvoiceUpload} from '../lib/finance-invoice-withdraw';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function InvoiceUploadWithdraw({owner,invoice,id,onRefresh}:{owner:string;invoice:string;id:string;onRefresh:()=>void}){
 const [confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function withdraw(){if(active.current||complete.current||!mounted.current||!supabase||!confirm)return;active.current=true;setBusy(true);try{await withdrawInvoiceUpload(supabase,owner,invoice,id);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage('This evidence is withdrawn from invoice review.');}catch{if(mounted.current){setUncertain(true);setMessage('Withdrawal could not be confirmed. Retry withdrawal of this same evidence or refresh its current state.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={{gap:12}}>{!done&&<>{!confirm?<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current)setConfirm(true);}}><Text style={styles.link}>Withdraw this evidence</Text></Pressable>:<><Text style={styles.body}>Remove this evidence from invoice documents? This does not promise immediate file deletion.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void withdraw()}><Text style={styles.link}>{busy?'Confirming…':uncertain?'Retry same evidence withdrawal':'Confirm evidence withdrawal'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!uncertain)setConfirm(false);}}><Text style={styles.link}>Keep evidence</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityRole={uncertain?'alert':'text'} style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh evidence records</Text></Pressable>}</View>;
}
