import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {financeReversalCommand,sendFinanceReversal,type ReversalCommand} from '../lib/finance-reversal-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function FinanceReversalReview({owner,id,memo,available,onRefresh}:{owner:string;id:string;memo:string;available:boolean;onRefresh:()=>void}){
 const [reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<ReversalCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<ReversalCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved||!available)return;try{const input=financeReversalCommand({journal_id:id,request_id:randomUUID(),reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Provide a reason of 5–500 characters and explicit approval to reverse this journal.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendFinanceReversal(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Reversal journal ${receipt.id} recorded for ${receipt.original}. Refresh to review the retained journal.`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry this same reversal request before making another decision.':'Response was not confirmed. Check your finance account and original journal before changing the request.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!review&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Review journal reversal</Text><Text style={styles.body}>{memo} · Journal {id}</Text><Text style={styles.body}>Reversal creates a new journal with every original line’s debit and credit swapped. The original remains in history. This does not refund money or confirm bank settlement.</Text>{!done&&!review&&<><TextInput accessibilityLabel="Reversal approval reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable())setReason(v);}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve reversal of every line in this journal.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review reversal</Text></Pressable></>}{!done&&review&&<><Text style={styles.body}>Confirm reversal of {review.journal_id}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording reversal…':uncertain?'Retry same reversal':'Confirm reversal'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit reversal</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh journal</Text></Pressable>}</View>;
}
