import {useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {financeAccounts} from '../lib/finance-accounts';
import {financeAccount} from '../lib/finance-account';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function FinanceAccountPicker({owner,onSelect}:{owner:string;onSelect:(account:Awaited<ReturnType<typeof financeAccount>>)=>void}){
 const [page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),active=useRef(false),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const loader=useCallback(()=>{if(!supabase)throw Error();return financeAccounts(supabase,owner,page);},[owner,page]),result=useLoad(owner+page,loader);
 async function select(id:string){if(active.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);setMessage('');try{const location=await financeAccount(supabase,owner,id);if(mounted.current)onSelect(location);}catch{if(mounted.current)setMessage('Account selection could not be confirmed. Refresh current finance access and try again.');}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(result.loading)return <ActivityIndicator accessibilityLabel="Loading approved accounts"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert">Approved accounts unavailable.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh accounts</Text></Pressable></View>;const r=result.data;
 return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<View><Text style={styles.heading}>Choose an approved account</Text><Text style={styles.body}>Select an account from the organization-approved chart.</Text>{!r.total&&<Text style={styles.body}>No approved accounts are available.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Accounts changed while loading. Refresh to check.</Text>}</View>} renderItem={({item})=><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void select(item.id)} style={styles.card}><Text style={styles.heading}>{item.code} · {item.name} →</Text><Text selectable style={styles.body}>Account reference: {item.id}</Text></Pressable>} ListFooterComponent={<View style={styles.card}><Text style={styles.body}>{r.total} accounts · Page {r.page} of {r.pages}</Text>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}{busy&&<ActivityIndicator accessibilityLabel="Checking selected account"/>}<Pressable accessibilityRole="button" disabled={busy||r.page===1} onPress={()=>{if(!active.current)setPage(r.page-1);}}><Text style={styles.link}>← Previous accounts</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||r.page===r.pages} onPress={()=>{if(!active.current)setPage(r.page+1);}}><Text style={styles.link}>More accounts →</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={()=>{if(!active.current)result.retry();}}><Text style={styles.link}>Refresh accounts</Text></Pressable></View>}/>;
}
