import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {applicantReviewAttempt,respondToLeaseSummary,type ApplicantReviewAttempt} from '../lib/lease-reviews';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function LeaseReviewResponse({owner,application,draft,release,version,current,latestAction,onRefresh}:{owner:string;application:string;draft:string;release:string;version:number;current:boolean;latestAction:string|null;onRefresh:()=>void}){
 const [action,setAction]=useState<'question'|'reviewed'>('question'),[text,setText]=useState(''),[acknowledged,setAcknowledged]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),frozen=useRef<ApplicantReviewAttempt|null>(null),unknownAttempt=useRef(false),completed=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const available=current&&latestAction!=='question';
 const editable=()=>!active.current&&!frozen.current&&!completed.current&&mounted.current;
 async function submit(){if(active.current||completed.current||!mounted.current||!supabase||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??applicantReviewAttempt({application,draft,release_id:release,request_id:randomUUID(),version,action,message:action==='reviewed'?'':text,review_only_acknowledged:acknowledged as true});frozen.current=input;const result=await respondToLeaseSummary(supabase,owner,input);if(!mounted.current)return;completed.current=true;setDone(true);setUncertain(false);setMessage(`Response ${result.version} recorded: ${result.action}. This does not sign a lease or authorize payment or move-in.`);}catch(error){if(mounted.current){const unknown=!!frozen.current&&(unknownAttempt.current||!(error instanceof EnquiryFailure)||error.uncertain);unknownAttempt.current=unknown;if(!unknown)frozen.current=null;setUncertain(unknown);setMessage(unknown?'Response could not be confirmed. Retry the same response or refresh the conversation.':'Response was not confirmed. Check your acknowledgment, message and the current summary conversation.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Respond to the summary</Text>{!available&&!done&&!uncertain&&<Text style={styles.body}>{current?'Your question is awaiting a property team reply.':'This summary is historical. Open the current shared summary before responding.'}</Text>}{!done&&(available||uncertain)&&<>{!uncertain&&<><Pressable accessibilityRole="radio" accessibilityState={{selected:action==='question',disabled:busy}} disabled={busy} onPress={()=>{if(editable())setAction('question');}}><Text style={styles.body}>{action==='question'?'●':'○'} Ask a question</Text></Pressable>{latestAction!=='reviewed'&&<Pressable accessibilityRole="radio" accessibilityState={{selected:action==='reviewed',disabled:busy}} disabled={busy} onPress={()=>{if(editable())setAction('reviewed');}}><Text style={styles.body}>{action==='reviewed'?'●':'○'} Record that I reviewed this summary</Text></Pressable>}</>}{action==='question'&&<TextInput accessibilityLabel="Summary question" multiline maxLength={2000} value={text} editable={!busy&&!uncertain} onChangeText={value=>{if(editable())setText(value);}} style={styles.input}/>}<Text style={styles.body}>{action==='question'?'Questions require 10–2000 characters.':'A recorded review shares no additional message.'}</Text>{!uncertain&&<Pressable accessibilityRole="checkbox" accessibilityState={{checked:acknowledged,disabled:busy}} disabled={busy} onPress={()=>{if(editable())setAcknowledged(!acknowledged);}}><Text style={styles.body}>{acknowledged?'☑':'☐'} I understand this is a review-only response, separate from signing a lease.</Text></Pressable>}<Pressable accessibilityRole="button" disabled={busy||!acknowledged} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same response':'Confirm response'}</Text></Pressable></>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh conversation</Text></Pressable>}</View>;
}
