import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {managerEntryCommand,submitManagerEntry,type ManagerEntryCommand} from '../lib/manager-entry-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerEntryRevoke({owner,work,offer,visit,id,version,state,onRefresh}:{owner:string;work:string;offer:string;visit:string;id:string;version:number;state:string;onRefresh:()=>void}){
 const action='revoke' as const;const [reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<ManagerEntryCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 const available=state==='authorized';
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??managerEntryCommand({work,offer_id:offer,visit_id:visit,permit_id:id,request_id:randomUUID(),version,action,reason});frozen.current=input;const result=await submitManagerEntry(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current permit: ${result.currentState} (version ${result.currentVersion}). Refresh the work order before authorizing another permit.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the permit.':'Response was not confirmed. Check the reason and refresh the permit before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Revoke this entry permit</Text>{!done&&<>{!confirm&&<><TextInput accessibilityLabel="Entry revocation authority reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 10–500 characters. Revocation ends this entry authorization. It does not record departure or cancel the appointment.</Text><Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(true);}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same revocation':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh permits</Text></Pressable>}</View>;
}
