import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {managerEntryCommand,submitManagerEntry,type ManagerEntryCommand} from '../lib/manager-entry-command';
import {jamaicaTimestamp} from '../../../lib/staff/jamaica-time';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerEntryAuthorize({owner,work,offer,visit,version,company,appointmentStarts,appointmentEnds,onRefresh}:{owner:string;work:string;version:number;offer:string;visit:string;company:string;appointmentStarts:string;appointmentEnds:string;onRefresh:()=>void}){
 const [starts,setStarts]=useState(''),[ends,setEnds]=useState(''),[note,setNote]=useState(''),[approved,setApproved]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<ManagerEntryCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable())return;try{managerEntryCommand({work,offer_id:offer,action:'authorize',visit_id:visit,permit_id:null,version:0,visit_version:version,request_id:randomUUID(),valid_from:jamaicaTimestamp(starts),valid_until:jamaicaTimestamp(ends),shared_instructions:note,approved:approved as true,reason});setMessage('');setReview(true);}catch{setMessage('Enter Jamaica start/end as YYYY-MM-DDTHH:mm, up to eight hours apart, approve a shared instructions (5–1000 characters) and provide a authority reason (10–500).');}}
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!review)return;active.current=true;setBusy(true);try{const input=frozen.current??managerEntryCommand({work,offer_id:offer,action:'authorize',visit_id:visit,permit_id:null,version:0,visit_version:version,request_id:randomUUID(),valid_from:jamaicaTimestamp(starts),valid_until:jamaicaTimestamp(ends),shared_instructions:note,approved:approved as true,reason});frozen.current=input;const r=await submitManagerEntry(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Entry permit recorded as authorized (version ${r.version}). Current permit: ${r.currentState} (version ${r.currentVersion}). Permit reference: ${r.id}. Arrival eligibility is checked again at entry.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending){frozen.current=null;}setUncertain(pending);setMessage(pending?'Submission could not be confirmed. Keep these details and retry the same authorization, or refresh the permit register before preparing another.':'Submission was not confirmed. Check the details and refresh work details before changing the authorization.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Authorize appointment entry</Text><Text style={styles.body}>Confirmed appointment: {new Date(appointmentStarts).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} to {new Date(appointmentEnds).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time). Keep the access window within these bounds.</Text>{!done&&<>{!review?<>{([{label:'Start in Jamaica (YYYY-MM-DDTHH:mm)',value:starts,set:setStarts,max:16},{label:'End in Jamaica (YYYY-MM-DDTHH:mm)',value:ends,set:setEnds,max:16},{label:'Approved shared entry instructions',value:note,set:setNote,max:1000},{label:'Entry authority reason',value:reason,set:setReason,max:500}]).map(field=><View key={field.label}><Text style={styles.body}>{field.label}</Text><TextInput accessibilityLabel={field.label} multiline maxLength={field.max} value={field.value} editable={!busy&&!uncertain} onChangeText={value=>{if(editable())field.set(value);}} style={styles.input}/></View>)}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this access window and instructions for sharing with {company}.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review authorization</Text></Pressable></>:<><Text style={styles.heading}>{company}</Text><Text style={styles.heading}>{starts} to {ends} (Jamaica time)</Text><Text style={styles.body}>{note}</Text><Text style={styles.heading}>Entry authority reason</Text><Text style={styles.body}>{reason}</Text><Text style={styles.body}>Record your authority to grant access. The window must fall within the confirmed appointment. The server checks current scheduling and existing authorization; arrival is recorded separately.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Authorizing entry…':uncertain?'Retry same authorization':'Confirm authorization'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setReview(false);}}><Text style={styles.link}>Edit authorization</Text></Pressable>}</>}</>}{!!message&&<Text selectable accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh work details</Text></Pressable>}</View>;
}
