import {useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {managerUnits,managerLocation} from '../lib/manager-locations';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function ManagerUnitPicker({owner,property,onSelect}:{owner:string;property:string;onSelect:(location:Awaited<ReturnType<typeof managerLocation>>)=>void}){
 const [page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),active=useRef(false),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const loader=useCallback(()=>{if(!supabase)throw Error();return managerUnits(supabase,owner,property,page);},[owner,property,page]),result=useLoad(owner+property+page,loader);
 async function select(id:string|null){if(active.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);setMessage('');try{const location=await managerLocation(supabase,owner,property,id);if(mounted.current)onSelect(location);}catch{if(mounted.current)setMessage('Location selection could not be confirmed. Refresh current management access and try again.');}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(result.loading)return <ActivityIndicator accessibilityLabel="Loading property units"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert">Property units unavailable.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh units</Text></Pressable></View>;const r=result.data;
 return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<View><Text style={styles.heading}>{r.property.name}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void select(null)} style={styles.card}><Text style={styles.link}>Property-wide / common area →</Text></Pressable><Text style={styles.heading}>Choose a unit or property-wide scope</Text><Text style={styles.body}>Select the approved location for this plan.</Text>{!r.total&&<Text style={styles.body}>No units are recorded. Property-wide scope remains available.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Units changed while loading. Refresh to check.</Text>}</View>} renderItem={({item})=><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void select(item.id)} style={styles.card}><Text style={styles.heading}>{item.label} →</Text><Text selectable style={styles.body}>Unit reference: {item.id}</Text></Pressable>} ListFooterComponent={<View style={styles.card}><Text style={styles.body}>{r.total} units · Page {r.page} of {r.pages}</Text>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}{busy&&<ActivityIndicator accessibilityLabel="Checking selected location"/>}<Pressable accessibilityRole="button" disabled={busy||r.page===1} onPress={()=>{if(!active.current)setPage(r.page-1);}}><Text style={styles.link}>← Previous units</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||r.page===r.pages} onPress={()=>{if(!active.current)setPage(r.page+1);}}><Text style={styles.link}>More units →</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={()=>{if(!active.current)result.retry();}}><Text style={styles.link}>Refresh units</Text></Pressable></View>}/>;
}
