import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {returnVisit,requestManagerReturnVisit,type ReturnVisit} from '../lib/manager-return-visit';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerReturnVisit({owner,work,offer,id,version,offerVersion,workVersion,state,offerState,workState,onRefresh}:{owner:string;work:string;offer:string;id:string;version:number;offerVersion:number;workVersion:number;state:string;offerState:string;workState:string;onRefresh:()=>void}){
 const action='request return visit';const [approved,setApproved]=useState(false),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<ReturnVisit|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 const available=state==='changes_requested'&&offerState==='accepted'&&workState==='in_progress';
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||!approved||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??returnVisit({work,offer,report_id:id,request_id:randomUUID(),report_version:version,offer_version:offerVersion,work_version:workVersion,approved:approved as true,reason});frozen.current=input;const result=await requestManagerReturnVisit(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current work: ${result.currentState} (version ${result.currentVersion}). Refresh the work order before scheduling a replacement appointment.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh correction details.':'Response was not confirmed. Check the reason and refresh correction details before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Request a correction return visit</Text>{!done&&<>{!confirm&&<><TextInput accessibilityLabel="Return visit decision reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. This returns eligible correction work to assigned. A new appointment and entry permit must be arranged separately. The server checks departure, active visits and pending reports.</Text><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve a return visit for the recorded corrections.</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{if(editable()&&approved&&reason.trim().length>=5)setConfirm(true);}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same return request':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh correction details</Text></Pressable>}</View>;
}
