import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {workTransition,transitionManagerWork,type WorkTransition} from '../lib/manager-work-transition';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerWorkTransition({owner,id,version,state,initialPriority,onRefresh}:{owner:string;id:string;version:number;state:string;initialPriority:string;onRefresh:()=>void}){
 const [action,setAction]=useState<WorkTransition['action']>('triage'),[priority,setPriority]=useState(initialPriority),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<WorkTransition|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 const available=version>0&&(state==='reported'||state==='triaged');
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??workTransition({work_order_id:id,request_id:randomUUID(),version,action,priority:action==='triage'?priority:null,reason});frozen.current=input;const result=await transitionManagerWork(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current work: ${result.currentState} (version ${result.currentVersion}). Priority does not establish a contractual response deadline.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the work order.':'Response was not confirmed. Check the reason and refresh the work order before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Triage or cancel this work</Text>{!done&&<>{!confirm&&<>{(['triage','cancel']).map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:action===value}} onPress={()=>{if(editable())setAction(value as WorkTransition['action']);}}><Text style={styles.body}>{action===value?'●':'○'} {value}</Text></Pressable>)}{action==='triage'&&['low','standard','high','urgent'].map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:priority===value}} onPress={()=>{if(editable())setPriority(value);}}><Text style={styles.body}>{priority===value?'●':'○'} {value} priority</Text></Pressable>)}<TextInput accessibilityLabel="Work decision reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. Triage records priority; cancellation closes this issue. The server checks management access and the current work revision.</Text><Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(true);}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action}{action==='triage'?` (${priority} priority)`:''}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same work order response':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh work order</Text></Pressable>}</View>;
}
