import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {managerVisitCommand,submitManagerVisit,type ManagerVisitCommand} from '../lib/manager-visit-command';
import {jamaicaTimestamp} from '../../../lib/staff/jamaica-time';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerVisitPropose({owner,work,offer,version,company,onRefresh}:{owner:string;work:string;version:number;offer:string;company:string;onRefresh:()=>void}){
 const [starts,setStarts]=useState(''),[ends,setEnds]=useState(''),[note,setNote]=useState(''),[approved,setApproved]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<ManagerVisitCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable())return;try{managerVisitCommand({work,offer_id:offer,action:'propose',visit_id:null,version:0,offer_version:version,request_id:randomUUID(),starts_at:jamaicaTimestamp(starts),ends_at:jamaicaTimestamp(ends),shared_note:note,approved:approved as true,reason});setMessage('');setReview(true);}catch{setMessage('Enter Jamaica start/end as YYYY-MM-DDTHH:mm, up to eight hours apart, approve a shared note (5–1000 characters) and provide a reason (5–500).');}}
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!review)return;active.current=true;setBusy(true);try{const input=frozen.current??managerVisitCommand({work,offer_id:offer,action:'propose',visit_id:null,version:0,offer_version:version,request_id:randomUUID(),starts_at:jamaicaTimestamp(starts),ends_at:jamaicaTimestamp(ends),shared_note:note,approved:approved as true,reason});frozen.current=input;const r=await submitManagerVisit(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Appointment recorded as proposed (version ${r.version}). Current appointment: ${r.currentState} (version ${r.currentVersion}). Appointment reference: ${r.id}. Contractor confirmation and entry authorization remain separate.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending){frozen.current=null;}setUncertain(pending);setMessage(pending?'Submission could not be confirmed. Keep these details and retry the same appointment, or refresh the appointment register before preparing another.':'Submission was not confirmed. Check the details and refresh work details before changing the appointment.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Propose a contractor appointment</Text>{!done&&<>{!review?<>{([{label:'Start in Jamaica (YYYY-MM-DDTHH:mm)',value:starts,set:setStarts,max:16},{label:'End in Jamaica (YYYY-MM-DDTHH:mm)',value:ends,set:setEnds,max:16},{label:'Approved shared appointment note',value:note,set:setNote,max:1000},{label:'Appointment reason',value:reason,set:setReason,max:500}]).map(field=><View key={field.label}><Text style={styles.body}>{field.label}</Text><TextInput accessibilityLabel={field.label} multiline maxLength={field.max} value={field.value} editable={!busy&&!uncertain} onChangeText={value=>{if(editable())field.set(value);}} style={styles.input}/></View>)}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this appointment window and note for sharing with {company}.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review appointment</Text></Pressable></>:<><Text style={styles.heading}>{company}</Text><Text style={styles.heading}>{starts} to {ends} (Jamaica time)</Text><Text style={styles.body}>{note}</Text><Text style={styles.heading}>Appointment reason</Text><Text style={styles.body}>{reason}</Text><Text style={styles.body}>The contractor must confirm this proposed window. Entry authorization is separate. The server checks the assignment, future window and calendar conflicts.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Submitting appointment…':uncertain?'Retry same appointment':'Confirm appointment'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setReview(false);}}><Text style={styles.link}>Edit appointment</Text></Pressable>}</>}</>}{!!message&&<Text selectable accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh work details</Text></Pressable>}</View>;
}
