import {useCallback,useState} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {managerOfferHistory} from '../lib/manager-offer-history';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {ManagerCompletionReports} from './manager-completion-reports';
import {ManagerVisitHistory} from './manager-visit-history';
import {ManagerOfferAudit} from './manager-offer-audit';
import {styles} from './styles';
export function ManagerOfferHistory({owner,id}:{owner:string;id:string}){const [selected,setSelected]=useState(''),[page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return managerOfferHistory(supabase,owner,id,page);},[owner,id,page]);const result=useLoad(owner+id+page,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading retained work offers"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Offer history could not be loaded. Confirm your current management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh history</Text></Pressable></View>;const r=result.data,time=(v:string)=>new Date(v).toLocaleString('en-JM',{timeZone:'America/Jamaica'});return <View style={styles.card}><Text style={styles.heading}>Work offer history</Text>{!!selected&&<><ManagerCompletionReports key={owner+id+selected+':reports'} owner={owner} id={id} offer={selected}/><ManagerVisitHistory key={owner+id+selected+':visits'} owner={owner} id={id} offer={selected}/><ManagerOfferAudit key={owner+id+selected} owner={owner} id={id} offer={selected}/><Pressable accessibilityRole="button" onPress={()=>setSelected('')}><Text style={styles.link}>Close decision history</Text></Pressable></>}<Text style={styles.body}>{r.total} offers · Page {r.page} of {r.pages}</Text>{!r.total&&<Text style={styles.body}>No work audit offers are recorded.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Events changed while loading. Refresh to check.</Text>}{r.rows.map(row=><View key={row.id} style={styles.card}><Text style={styles.heading}>{row.title}</Text><Text style={styles.body}>{row.company} · {row.trade} · {row.expired?'Expired, awaiting recorded transition':row.state} · Revision {row.version}</Text><Text style={styles.body}>{row.scope}</Text><Text style={styles.body}>Created {time(row.created)} · Expiry {time(row.expires)} (Jamaica time)</Text><Text selectable style={styles.body}>Offer reference: {row.id}</Text><Pressable accessibilityRole="button" onPress={()=>setSelected(row.id)}><Text style={styles.link}>Review offer decisions</Text></Pressable></View>)}<Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Newer offers</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Older offers →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh history</Text></Pressable></View>;}
