import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {completionReview,reviewManagerCompletion,type CompletionReview} from '../lib/manager-completion-review';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerCompletionReview({owner,work,offer,id,version,state,onRefresh}:{owner:string;work:string;offer:string;id:string;version:number;state:string;onRefresh:()=>void}){
 const [action,setAction]=useState<CompletionReview['action']>('request_changes'),[review,setReview]=useState(''),[approved,setApproved]=useState(false),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<CompletionReview|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 const available=version>0&&state==='submitted';
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??completionReview({work,offer,report_id:id,request_id:randomUUID(),version,action,review_message:review,evidence_reviewed:action==='approve'?approved as true:null,reason});frozen.current=input;const result=await reviewManagerCompletion(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current report: ${result.currentState} (version ${result.currentVersion}). Refresh the work details to check the resulting work state.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the completion report.':'Response was not confirmed. Check the reason and refresh the completion report before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Review this completion report</Text>{!done&&<>{!confirm&&<>{(['request_changes','approve']).map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:action===value}} onPress={()=>{if(editable())setAction(value as CompletionReview['action']);}}><Text style={styles.body}>{action===value?'●':'○'} {value}</Text></Pressable>)}<TextInput accessibilityLabel="Review shared with contractor" multiline maxLength={2000} value={review} onChangeText={value=>{if(editable())setReview(value);}} style={styles.input}/>{action==='approve'&&<Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I reviewed the report and supporting evidence and approve this work.</Text></Pressable>}<TextInput accessibilityLabel="Completion decision reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. Provide a shared review of 10–2000 characters. Approval records completion; requests for changes keep the issue open. The server checks independent management authority and current revisions.</Text><Pressable accessibilityRole="button" onPress={()=>{if(!editable())return;try{completionReview({work,offer,report_id:id,request_id:randomUUID(),version,action,review_message:review,evidence_reviewed:action==='approve'?approved as true:null,reason});setConfirm(true);setMessage('');}catch{setMessage('Provide a shared review (10–2000 characters), reason (5–500), and evidence confirmation for approval.');}}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action}: {reason}</Text><Text style={styles.body}>{review}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same completion report response':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh completion report</Text></Pressable>}</View>;
}
