import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {preventiveCommand,sendPreventiveCommand,type PreventiveCommand} from '../lib/manager-preventive-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerPreventiveDecision({owner,id,version,state,interval,due,onRefresh}:{owner:string;id:string;version:number;state:string;interval:number;due:string;onRefresh:()=>void}){
 const [action,setAction]=useState<PreventiveCommand['action']>('issue'),[approved,setApproved]=useState(false),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<PreventiveCommand|null>(null),unknown=useRef(false),reviewing=useRef(false);const [today]=useState(()=>new Date(Date.now()-5*60*60*1000).toISOString().slice(0,10));
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!reviewing.current&&!active.current&&!complete.current&&!frozen.current;
 const available=version>0&&state==='active'&&due<=today;const next=new Date(due+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+interval);const nextDue=next.toISOString().slice(0,10);
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||!approved||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??preventiveCommand({plan_id:id,request_id:randomUUID(),version,action,approved:true,reason});frozen.current=input;const result=await sendPreventiveCommand(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded ${result.action} for ${result.due} (revision ${result.version}). Next scheduled date: ${result.nextDue}. Current plan revision: ${result.currentVersion}.${result.work?` Generated work reference: ${result.work}.`:' No work order was created; maintenance was not recorded as completed.'}`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the plan.':'Response was not confirmed. Check the reason and refresh the plan before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Issue or skip the next scheduled date</Text>{!done&&<>{!confirm&&<>{(['issue','skip']).map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:action===value}} onPress={()=>{if(editable())setAction(value as PreventiveCommand['action']);}}><Text style={styles.body}>{action===value?'●':'○'} {value}</Text></Pressable>)}<TextInput accessibilityLabel="Preventive decision reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. Issue creates one work order. Skip records an approved exception without completed maintenance. Each advances the schedule by one fixed interval. Appointments, contractor assignment and entry remain separate decisions.</Text><Text style={styles.body}>Scheduled date: {due} → {nextDue}{nextDue<=today?' · Further dates remain due.':''}</Text><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this scheduled decision.</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{if(!editable()||!approved)return;try{preventiveCommand({plan_id:id,version,request_id:randomUUID(),action,reason,approved:true});reviewing.current=true;setConfirm(true);setMessage('');}catch{setMessage('Provide an approved decision and a reason of 5–500 characters.');}}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action} for {due}, advancing to {nextDue}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same preventive decision':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){reviewing.current=false;setConfirm(false);}}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh plan</Text></Pressable>}</View>;
}
