import {useCallback,useRef,useState} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {managerContractors,managerContractor} from '../lib/manager-contractors';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {ManagerOfferCreate} from './manager-offer-create';
import {styles} from './styles';
export function ManagerContractors({owner,work,version,onRefresh}:{owner:string;work:string;version:number;onRefresh:()=>void}){const lockedRef=useRef(false);const [locked,setLocked]=useState(false),[selected,setSelected]=useState(''),[page,setPage]=useState(1),loader=useCallback(()=>{if(!supabase)throw Error();return managerContractors(supabase,owner,page);},[owner,page]);const result=useLoad(owner+page,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Loading approved contractors"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Contractor register could not be loaded. Confirm your current management membership or try again.</Text><Pressable accessibilityRole="button" disabled={locked} onPress={()=>{if(!lockedRef.current)result.retry();}}><Text style={styles.link}>Refresh contractors</Text></Pressable></View>;const r=result.data;return <View style={styles.card}><Text style={styles.heading}>Approved contractors</Text>{!!selected&&<Selected key={owner+selected} owner={owner} id={selected} work={work} version={version} locked={locked} isLocked={()=>lockedRef.current} onRefresh={onRefresh} onLocked={value=>{lockedRef.current=value;setLocked(value);}} onClear={()=>{if(!lockedRef.current)setSelected('');}}/>}<Text style={styles.body}>{r.total} contractors · Page {r.page} of {r.pages}</Text>{!r.total&&<Text style={styles.body}>No active approved contractors are recorded.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Contractors changed while loading. Refresh to check.</Text>}{r.rows.map(row=><View key={row.id} style={styles.card}><Text style={styles.heading}>{row.company}</Text><Text style={styles.body}>{row.trades.join(' · ')}</Text><Text selectable style={styles.body}>Contractor reference: {row.id}</Text><Pressable accessibilityRole="button" disabled={locked} onPress={()=>{if(!lockedRef.current)setSelected(row.id);}}><Text style={styles.link}>Review contractor selection</Text></Pressable></View>)}<Pressable accessibilityRole="button" disabled={locked||r.page===1} onPress={()=>{if(!lockedRef.current)setPage(r.page-1);}}><Text style={styles.link}>← Previous contractors</Text></Pressable><Pressable accessibilityRole="button" disabled={locked||r.page===r.pages} onPress={()=>{if(!lockedRef.current)setPage(r.page+1);}}><Text style={styles.link}>Next contractors →</Text></Pressable><Pressable accessibilityRole="button" disabled={locked} onPress={()=>{if(!lockedRef.current)result.retry();}}><Text style={styles.link}>Refresh contractors</Text></Pressable></View>;}

function Selected({owner,id,work,version,locked,isLocked,onRefresh,onLocked,onClear}:{owner:string;id:string;work:string;version:number;locked:boolean;isLocked:()=>boolean;onRefresh:()=>void;onLocked:(value:boolean)=>void;onClear:()=>void}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerContractor(supabase,owner,id);},[owner,id]);const result=useLoad(owner+id,loader);return <View style={styles.card}><Text style={styles.heading}>Selected contractor</Text>{result.loading?<ActivityIndicator accessibilityLabel="Checking selected contractor"/>:result.error||!result.data?<Text accessibilityRole="alert" style={styles.body}>Selection could not be verified. Check current approval before sharing scope.</Text>:<><Text style={styles.heading}>{result.data.company}</Text><Text style={styles.body}>{result.data.trades.join(' · ')} · Registration revision {result.data.version}</Text><ManagerOfferCreate key={work+id+version+result.data.version} owner={owner} work={work} version={version} contractor={id} company={result.data.company} trades={result.data.trades} onRefresh={onRefresh} onLocked={onLocked}/></>}<Pressable accessibilityRole="button" disabled={locked} onPress={()=>{if(!isLocked())result.retry();}}><Text style={styles.link}>Recheck selection</Text></Pressable><Pressable accessibilityRole="button" disabled={locked} onPress={onClear}><Text style={styles.link}>Clear selection</Text></Pressable></View>;}
