import {useCallback,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {Link} from 'expo-router';
import {managerSecurityAssignments} from '../lib/manager-security-assignments';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
import {ManagerSecurityCreate} from './manager-security-create';
import {useLoad} from './use-load';
export function ManagerSecurityRegister({owner,property}:{owner:string;property:string}){const [page,setPage]=useState(1),[creating,setCreating]=useState(false),loader=useCallback(()=>{if(!supabase)throw Error();return managerSecurityAssignments(supabase,owner,property,page);},[owner,property,page]);const result=useLoad(owner+property+page,loader);const heading=<View><Text style={styles.title}>Property security assignments</Text><Text style={styles.body}>Assignments authorize eligible property security workflows; they do not grant resident or internal work-record access.</Text></View>;if(result.loading)return <View style={styles.page}>{heading}<ActivityIndicator accessibilityLabel="Loading security assignments"/></View>;if(result.error||!result.data)return <View style={styles.page}>{heading}<Text accessibilityRole="alert" style={styles.body}>Security register unavailable. Check approved management membership or try again.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignments</Text></Pressable></View>;const r=result.data;return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<>{heading}<Text style={styles.heading}>{r.property.name}</Text><Pressable accessibilityRole="button" onPress={()=>setCreating(true)}><Text style={styles.link}>Assign security account →</Text></Pressable>{creating&&<ManagerSecurityCreate key={owner+property} owner={owner} property={property} name={r.property.name}/>}{!r.total&&<Text style={styles.body}>No security assignments are recorded.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Records changed while loading. Refresh to check.</Text>}</>} renderItem={({item})=><View style={styles.card}><Link href={{pathname:'/manage-security-assignment',params:{id:item.id}}} style={styles.heading}>Security account {item.user} →</Link><Text style={styles.body}>{item.active?'Active':'Inactive'} · Revision {item.version}</Text><Text selectable style={styles.body}>Assignment reference: {item.id}</Text></View>} ListFooterComponent={<View style={{gap:12}}><Text style={styles.body}>{r.total} assignments · Page {r.page} of {r.pages}</Text><Pressable accessibilityRole="button" disabled={r.page===1} onPress={()=>setPage(r.page-1)}><Text style={styles.link}>← Newer assignments</Text></Pressable><Pressable accessibilityRole="button" disabled={r.page===r.pages} onPress={()=>setPage(r.page+1)}><Text style={styles.link}>Older assignments →</Text></Pressable><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh assignments</Text></Pressable><Link href="/manage-work" style={styles.link}>Open management work queue →</Link></View>}/>;}
