import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {securityCommand,sendSecurityCommand,type SecurityCommand} from '../lib/manager-security-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerSecurityDecision({owner,id,version,initialActive,onRefresh}:{owner:string;id:string;version:number;initialActive:boolean;onRefresh:()=>void}){
 const [isActive,setIsActive]=useState(!initialActive),[approved,setApproved]=useState(false),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<SecurityCommand|null>(null),unknown=useRef(false),reviewing=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!reviewing.current&&!active.current&&!complete.current&&!frozen.current;
 const available=version>0;
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||!approved||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??securityCommand({assignment_id:id,request_id:randomUUID(),version,is_active:isActive,approved:true,reason});frozen.current=input;const result=await sendSecurityCommand(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded ${result.active?'active':'inactive'} (revision ${result.version}). Current assignment: ${result.currentActive?'active':'inactive'} (revision ${result.currentVersion}).`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the assignment.':'Response was not confirmed. Check the reason and refresh the assignment before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Approve activation or revoke this assignment</Text>{!done&&<>{!confirm&&<>{[true,false].map(value=><Pressable key={String(value)} accessibilityRole="radio" accessibilityState={{selected:isActive===value}} onPress={()=>{if(editable())setIsActive(value);}}><Text style={styles.body}>{isActive===value?'●':'○'} {value?'Activate':'Revoke'}</Text></Pressable>)}<TextInput accessibilityLabel="Security decision reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. Activation requires a verified security account. Revocation removes this property assignment; it does not record departure, cancel an appointment or complete work. Property and account bindings cannot change.</Text><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this property security access decision.</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>{if(!editable()||!approved)return;try{securityCommand({assignment_id:id,version,request_id:randomUUID(),is_active:isActive,reason,approved:true});reviewing.current=true;setConfirm(true);setMessage('');}catch{setMessage('Provide an approved decision and a reason of 5–500 characters.');}}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {isActive?'activation':'revocation'}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same security decision':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){reviewing.current=false;setConfirm(false);}}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh assignment</Text></Pressable>}</View>;
}
