import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {offerCreation,createManagerOffer,type OfferCreation} from '../lib/manager-offer-create';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerOfferCreate({owner,work,version,contractor,company,trades,onRefresh,onLocked}:{owner:string;work:string;version:number;contractor:string;company:string;trades:string[];onRefresh:()=>void;onLocked?:(value:boolean)=>void}){
 const [title,setTitle]=useState(''),[scope,setScope]=useState(''),[trade,setTrade]=useState(trades[0]||''),[approved,setApproved]=useState(false),[reason,setReason]=useState(''),[review,setReview]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<OfferCreation|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable())return;try{offerCreation({action:'offer',offer_id:null,work_order_id:work,work_version:version,contractor_id:contractor,version:0,request_id:randomUUID(),job_title:title,scope_summary:scope,trade,approved:approved as true,reason});setMessage('');setReview(true);}catch{setMessage('Approve the scope and provide a title (3–160 characters), scope (20–3000), approved trade and reason (5–500).');}}
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!review)return;active.current=true;setBusy(true);try{const input=frozen.current??offerCreation({action:'offer',offer_id:null,work_order_id:work,work_version:version,contractor_id:contractor,version:0,request_id:randomUUID(),job_title:title,scope_summary:scope,trade,approved:approved as true,reason});frozen.current=input;onLocked?.(true);const r=await createManagerOffer(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Offer recorded as offered (version ${r.version}). Current offer: ${r.currentState} (version ${r.currentVersion}). Offer reference: ${r.id}. Acceptance, scheduling and entry authorization remain separate.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending){frozen.current=null;onLocked?.(false);}setUncertain(pending);setMessage(pending?'Submission could not be confirmed. Keep these details and retry the same offer, or refresh the offer register before preparing another.':'Submission was not confirmed. Check the details and refresh work details before changing the offer.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>Prepare an approved work offer</Text>{!done&&<>{!review?<>{([{label:'Shared job title',value:title,set:setTitle,max:160},{label:'Scope shared with contractor',value:scope,set:setScope,max:3000},{label:'Offer reason',value:reason,set:setReason,max:500}]).map(field=><View key={field.label}><Text style={styles.body}>{field.label}</Text><TextInput accessibilityLabel={field.label} multiline maxLength={field.max} value={field.value} editable={!busy&&!uncertain} onChangeText={value=>{if(editable())field.set(value);}} style={styles.input}/></View>)}{trades.map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:trade===value}} onPress={()=>{if(editable())setTrade(value);}}><Text style={styles.body}>{trade===value?'●':'○'} {value}</Text></Pressable>)}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve this title, scope and trade for sharing with {company}.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review offer</Text></Pressable></>:<><Text style={styles.heading}>{company} · {trade}</Text><Text style={styles.heading}>{title}</Text><Text style={styles.body}>{scope}</Text><Text style={styles.heading}>Offer reason</Text><Text style={styles.body}>{reason}</Text><Text style={styles.body}>The contractor receives this approved scope. Acceptance assigns work; scheduling and entry authorization remain separate. The server checks current work and contractor approval again.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Submitting offer…':uncertain?'Retry same offer':'Confirm offer'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setReview(false);}}><Text style={styles.link}>Edit offer</Text></Pressable>}</>}</>}{!!message&&<Text selectable accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh work details</Text></Pressable>}</View>;
}
