import {ManagerEntryAuthorize} from './manager-entry-authorize';
import {ManagerVisitPropose} from './manager-visit-propose';
import {ManagerVisitCancel} from './manager-visit-cancel';
import {useCallback} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {managerCurrentVisit} from '../lib/manager-current-visit';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function ManagerCurrentVisit({owner,work}:{owner:string;work:string}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerCurrentVisit(supabase,owner,work);},[owner,work]);const result=useLoad(owner+work,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Checking current contractor appointment"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>Current appointment could not be checked.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Check again</Text></Pressable></View>;const r=result.data,v=r.visit,time=(value:string)=>new Date(value).toLocaleString('en-JM',{timeZone:'America/Jamaica'});return <View style={styles.card}><Text style={styles.heading}>Current appointment</Text>{r.parent.offer?.state!=='accepted'?<Text style={styles.body}>An accepted assignment is required before scheduling a visit.</Text>:v?<><Text style={styles.body}>{v.state} · Revision {v.version}</Text><Text style={styles.body}>{time(v.starts)} to {time(v.ends)} (Jamaica time)</Text><Text style={styles.body}>{v.note}</Text><Text selectable style={styles.body}>Appointment reference: {v.id}</Text><Text style={styles.body}>Appointment confirmation and entry authorization are separate.</Text>{v.state==='confirmed'&&r.parent.work.state==='scheduled'&&<ManagerEntryAuthorize key={v.id+':authorize'} owner={owner} work={work} offer={r.parent.offer!.id} visit={v.id} version={v.version} company={r.parent.offer!.company} appointmentStarts={v.starts} appointmentEnds={v.ends} onRefresh={result.retry}/>}<ManagerVisitCancel key={v.id} owner={owner} work={work} offer={r.parent.offer!.id} id={v.id} version={v.version} state={v.state} onRefresh={result.retry}/></>:<><Text style={styles.body}>No proposed or confirmed appointment is recorded for the accepted assignment.</Text>{r.parent.work.state==='assigned'&&<ManagerVisitPropose key={r.parent.offer.id} owner={owner} work={work} offer={r.parent.offer.id} version={r.parent.offer.version} company={r.parent.offer.company} onRefresh={result.retry}/>}</>}<Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh appointment</Text></Pressable></View>;}
