import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {inventoryCommand,sendInventoryCommand,type InventoryCommand} from '../lib/manager-inventory-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function ManagerInventoryEditor({owner,action,property,target,version,initial,onRefresh}:{owner:string;action:InventoryCommand['action'];property:string|null;target:string|null;version:number;initial:Record<string,unknown>;onRefresh:()=>void}){
 const unit=action.startsWith('unit_'),keys=unit?['unit_label','bedrooms','bathrooms','parking_spaces','floor','size_sq_ft']:['name','area','address_text'];
 const [values,setValues]=useState<Record<string,string>>(()=>Object.fromEntries(keys.map(k=>[k,initial[k]===null||initial[k]===undefined?'':String(initial[k])]))),[approved,setApproved]=useState(false),[review,setReview]=useState<InventoryCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');
 const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<InventoryCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved)return;try{const fields:Record<string,unknown>={};for(const k of keys){const v=values[k].trim();if(unit&&k!=='unit_label'){if(!v&&['floor','size_sq_ft'].includes(k))fields[k]=null;else{if(!/^-?\d+(?:\.\d+)?$/.test(v))throw Error();fields[k]=Number(v);}}else fields[k]=values[k];}const input=inventoryCommand({approved:true,request_id:randomUUID(),action,property,target_id:target,revision:version,fields});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Check all required fields and dimensional limits before reviewing.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendInventoryCommand(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded revision ${receipt.version}; current revision ${receipt.currentVersion}. Property reference: ${receipt.property}${receipt.unit?'; unit reference: '+receipt.unit:''}.`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry this exact reviewed change before starting another.':'Change was not confirmed. Refresh current revisions and tenancy protections before changing the request.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={styles.card}><Text style={styles.heading}>{action.replaceAll('_',' ')}</Text><Text style={styles.body}>Private management inventory. The server rechecks revisions and tenancy protections. Updating a reserved or occupied record requires its tenancy change workflow.</Text>{!done&&!review&&<>{keys.map(k=><View key={k}><Text style={styles.body}>{k.replaceAll('_',' ')}</Text><TextInput accessibilityLabel={'Inventory '+k} value={values[k]} multiline={k==='address_text'} maxLength={k==='address_text'?500:160} onChangeText={v=>{if(editable())setValues(old=>({...old,[k]:v}));}} style={styles.input}/></View>)}{unit&&<Text style={styles.body}>Bedrooms/bathrooms: 0–50 in half steps. Parking: 0–100 whole spaces. Optional floor: −10–200; optional size: 1–1,000,000 whole sq ft. Leave optional values blank when unrecorded.</Text>}<Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I approve these private inventory changes.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review inventory change</Text></Pressable></>}{!done&&review&&<><Text style={styles.body}>Review {review.action.replaceAll('_',' ')} · expected revision {review.revision}</Text>{Object.entries(review.fields).map(([k,v])=><Text key={k} style={styles.body}>{k.replaceAll('_',' ')}: {v===null?'Not recorded':String(v)}</Text>)}<Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording change…':uncertain?'Retry same inventory change':'Confirm inventory change'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit inventory change</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh inventory</Text></Pressable>}</View>;
}
