import {useCallback,useEffect,useRef,useState} from 'react';
import {ActivityIndicator,FlatList,Pressable,Text,View} from 'react-native';
import {managerProperties,managerLocation} from '../lib/manager-locations';
import {supabase} from '../lib/supabase';
import {useLoad} from './use-load';
import {styles} from './styles';
export function ManagerPropertyPicker({owner,onSelect}:{owner:string;onSelect:(location:Awaited<ReturnType<typeof managerLocation>>)=>void}){
 const [page,setPage]=useState(1),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),active=useRef(false),mounted=useRef(true);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const loader=useCallback(()=>{if(!supabase)throw Error();return managerProperties(supabase,owner,page);},[owner,page]),result=useLoad(owner+page,loader);
 async function select(id:string){if(active.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);setMessage('');try{const location=await managerLocation(supabase,owner,id,null);if(mounted.current)onSelect(location);}catch{if(mounted.current)setMessage('Property selection could not be confirmed. Refresh current management access and try again.');}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(result.loading)return <ActivityIndicator accessibilityLabel="Loading managed properties"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert">Managed properties unavailable.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Refresh properties</Text></Pressable></View>;const r=result.data;
 return <FlatList contentContainerStyle={styles.page} data={r.rows} keyExtractor={row=>row.id} ListHeaderComponent={<View><Text style={styles.heading}>Choose a managed property</Text><Text style={styles.body}>Select the property first, then a unit or property-wide scope.</Text>{!r.total&&<Text style={styles.body}>No managed properties are available.</Text>}{!!r.total&&!r.rows.length&&<Text style={styles.body}>Properties changed while loading. Refresh to check.</Text>}</View>} renderItem={({item})=><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void select(item.id)} style={styles.card}><Text style={styles.heading}>{item.name} →</Text><Text selectable style={styles.body}>Property reference: {item.id}</Text></Pressable>} ListFooterComponent={<View style={styles.card}><Text style={styles.body}>{r.total} properties · Page {r.page} of {r.pages}</Text>{!!message&&<Text accessibilityRole="alert" style={styles.body}>{message}</Text>}{busy&&<ActivityIndicator accessibilityLabel="Checking selected property"/>}<Pressable accessibilityRole="button" disabled={busy||r.page===1} onPress={()=>{if(!active.current)setPage(r.page-1);}}><Text style={styles.link}>← Previous properties</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||r.page===r.pages} onPress={()=>{if(!active.current)setPage(r.page+1);}}><Text style={styles.link}>More properties →</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={()=>{if(!active.current)result.retry();}}><Text style={styles.link}>Refresh properties</Text></Pressable></View>}/>;
}
