import {useCallback} from 'react';
import {ActivityIndicator,Pressable,Text,View} from 'react-native';
import {managerCurrentOffer} from '../lib/manager-current-offer';
import {supabase} from '../lib/supabase';
import {ManagerOfferWithdraw} from './manager-offer-withdraw';
import {ManagerContractors} from './manager-contractors';
import {useLoad} from './use-load';
import {styles} from './styles';
export function ManagerCurrentOffer({owner,work,onRefresh}:{owner:string;work:string;onRefresh:()=>void}){const loader=useCallback(()=>{if(!supabase)throw Error();return managerCurrentOffer(supabase,owner,work);},[owner,work]);const result=useLoad(owner+work,loader);if(result.loading)return <ActivityIndicator accessibilityLabel="Checking current contractor offer"/>;if(result.error||!result.data)return <View style={styles.card}><Text accessibilityRole="alert" style={styles.body}>The current offer could not be checked. Refresh before preparing another.</Text><Pressable accessibilityRole="button" onPress={result.retry}><Text style={styles.link}>Check current offer</Text></Pressable></View>;const r=result.data,o=r.offer;return <View style={styles.card}><Text style={styles.heading}>Current contractor offer</Text>{o?<><Text style={styles.heading}>{o.title}</Text><Text style={styles.body}>{o.company} · {o.trade} · {o.expired?'Expired pending offer':o.state} · Revision {o.version}</Text><Text style={styles.body}>{o.scope}</Text><Text style={styles.body}>Offer expiry {new Date(o.expires).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} (Jamaica time)</Text>{!o.expired&&<ManagerOfferWithdraw key={o.id+':'+o.version} owner={owner} work={work} id={o.id} version={o.version} state={o.state} onRefresh={onRefresh}/>}<Text selectable style={styles.body}>Offer reference: {o.id}</Text><Text style={styles.body}>Acceptance assigns work. Visit scheduling and entry authorization remain separate.</Text></>:<Text style={styles.body}>No pending or accepted offer is currently recorded.</Text>}{r.work.state==='triaged'&&(!o||o.expired)&&<ManagerContractors key={work+':'+r.work.version} owner={owner} work={work} version={r.work.version} onRefresh={onRefresh}/>}<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh work and current offer</Text></Pressable></View>;}
