import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import type {WorkingPreferences} from '../lib/realtors';
import {changePreferences,storedPreferences} from '../lib/matching-preferences';
import {supabase} from '../lib/supabase';
import {useIdentity} from './identity';
import {styles} from './styles';
export function PreferenceControls({answers,onLoad}:{answers:WorkingPreferences;onLoad:(p:WorkingPreferences)=>void}){
 const {user,loading}=useIdentity();if(loading)return <Text style={styles.body}>Checking your account…</Text>;if(!user)return <Text style={styles.body}>Sign in with a verified account to load or save preferences.</Text>;
 return <PreferenceActions key={user.id} owner={user.id} answers={answers} onLoad={onLoad}/>;
}
export function PreferenceActions({owner,answers,onLoad}:{owner:string;answers:WorkingPreferences;onLoad:(p:WorkingPreferences)=>void}){
 const [revision,setRevision]=useState<string|null>(null),[checked,setChecked]=useState(false),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[message,setMessage]=useState('');
 const active=useRef(false),mounted=useRef(true),generation=useRef(0);const renderedGeneration=generation.current;useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 async function check(load:boolean){if(active.current||!mounted.current||!supabase)return;active.current=true;setBusy(true);try{const stored=await storedPreferences(supabase,owner);if(!mounted.current)return;++generation.current;setRevision(stored?.revision??null);setChecked(true);setUncertain(false);setConsent(false);if(load&&stored)onLoad(stored.preferences);setMessage(stored?(load?'Stored preferences loaded.':'Stored preferences checked. Choose save or delete explicitly.'):'No preferences are stored for this account.');}catch{if(mounted.current){setChecked(false);setMessage('Unable to check stored preferences. Try again.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 async function change(action:'save'|'delete'){if(renderedGeneration!==generation.current||active.current||!mounted.current||!supabase||!checked||uncertain||(action==='save'&&!consent))return;active.current=true;setBusy(true);try{const stored=await changePreferences(supabase,owner,{action,revision,preferences:{...answers},consent});if(!mounted.current)return;++generation.current;setRevision(stored?.revision??null);setConsent(false);setMessage(action==='save'?'Preferences saved to your account.':'Stored preferences deleted. Current answers remain on this screen.');}catch{if(mounted.current){++generation.current;setUncertain(true);setConsent(false);setMessage('The update could not be confirmed. Check stored preferences before another update.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 return <View style={{gap:12}}><Text style={styles.heading}>Your preferences, your choice.</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void check(false)}><Text style={styles.link}>Check stored preferences</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||uncertain} onPress={()=>void check(true)}><Text style={styles.link}>Load saved answers</Text></Pressable><Pressable accessibilityRole="checkbox" disabled={busy||uncertain} accessibilityState={{checked:consent,disabled:busy||uncertain}} onPress={()=>setConsent(!consent)}><Text style={styles.body}>{consent?'☑':'☐'} Save these working preferences to my account for future visits.</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||uncertain||!checked||!consent} onPress={()=>void change('save')} style={styles.button}><Text style={styles.buttonText}>Save preferences</Text></Pressable><Pressable accessibilityRole="button" disabled={busy||uncertain||!checked||revision===null} onPress={()=>void change('delete')}><Text style={styles.link}>Delete stored preferences</Text></Pressable>{!!message&&<Text accessibilityRole={uncertain?'alert':'text'} style={styles.body}>{message}</Text>}</View>;
}
