import {useState} from 'react';
import {Pressable,Text,View} from 'react-native';
import {rankRealtors,type RealtorProfile,type WorkingPreferences} from '../lib/realtors';
import {EnquiryForm} from './enquiry-form';
import {PreferenceControls} from './preference-controls';
import {styles} from './styles';
const choices={intent:[['buy','Buy a home'],['rent','Rent a home'],['sell','Sell a property']],communication_style:[['thoughtful','Thoughtful and reassuring'],['direct','Direct and clear'],['collaborative','Collaborative and conversational']],guidance_style:[['step-by-step','Walk me through each step'],['data-led','Help me compare the evidence'],['independent','Give me room to explore']],decision_pace:[['considered','Time to reflect'],['decisive','A focused plan and prompt next steps'],['flexible','A flexible rhythm']]};
const labels={intent:'What brings you here?',communication_style:'How do you like to communicate?',guidance_style:'What guidance feels right?',decision_pace:'How do you like to make decisions?'};
export function RealtorMatch({roster}:{roster:RealtorProfile[]}){
 const [answers,setAnswers]=useState<WorkingPreferences>({intent:'',preferred_area:'',communication_style:'',guidance_style:'',decision_pace:''}),[submitted,setSubmitted]=useState(false);
 const areas=[...new Set(roster.flatMap(r=>r.service_areas))].sort();const complete=Object.values(answers).every(Boolean);const results=submitted?rankRealtors(roster,answers):null;
 function choose(key:keyof WorkingPreferences,value:string){setAnswers({...answers,[key]:value});setSubmitted(false);}
 return <View style={styles.card}><Text style={styles.heading}>A realtor who gets how you like to work.</Text><Text style={styles.body}>Service area and buying, renting or selling support determine eligibility. Communication, guidance and decision pace shape the suggestions. You can choose any realtor.</Text><Text style={styles.body}>This is a working-preference match, not a personality diagnosis. Answers stay on this screen unless you explicitly choose to save them.</Text>{(Object.keys(choices) as (keyof typeof choices)[]).map(key=><View key={key} style={{gap:8}}><Text style={styles.body}>{labels[key]}</Text>{choices[key].map(([value,label])=><Pressable key={value} accessibilityRole="radio" accessibilityLabel={label} accessibilityState={{checked:answers[key]===value}} onPress={()=>choose(key,value)}><Text style={styles.link}>{answers[key]===value?'◉':'○'} {label}</Text></Pressable>)}</View>)}<Text style={styles.body}>Where are you looking?</Text>{areas.map(area=><Pressable key={area} accessibilityRole="radio" accessibilityLabel={area} accessibilityState={{checked:answers.preferred_area===area}} onPress={()=>choose('preferred_area',area)}><Text style={styles.link}>{answers.preferred_area===area?'◉':'○'} {area}</Text></Pressable>)}<Pressable accessibilityRole="button" disabled={!complete} accessibilityState={{disabled:!complete}} onPress={()=>{if(complete)setSubmitted(true);}} style={styles.button}><Text style={styles.buttonText}>See my matches</Text></Pressable>{results&&<View style={{gap:16}}><Text style={styles.heading}>A starting point for a real connection.</Text>{results.length?results.map(({realtor,points,reasons})=><View key={realtor.id} style={{gap:8}}><Text style={styles.heading}>{realtor.display_name}</Text><Text style={styles.body}>{points}/8 preference points</Text>{reasons.map(reason=><Text key={reason} style={styles.body}>• {reason}</Text>)}<Text style={styles.body}>{realtor.bio}</Text><EnquiryForm realtorId={realtor.id}/></View>):<Text style={styles.body}>No published realtor currently covers this journey in your preferred area. Try another area or contact the team.</Text>}</View>}<PreferenceControls answers={answers} onLoad={p=>{setAnswers(p);setSubmitted(false);}}/></View>;
}
