import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {presenceAttempt,recordSecurityPresence,type PresenceAttempt} from '../lib/security-presence';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function SecurityPresence({owner,permit,presence,version,onRefresh}:{owner:string;permit:string;presence:string|null;version:number;onRefresh:()=>void}){

 const action=presence?'check_out':'check_in';const [identity,setIdentity]=useState(false),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<PresenceAttempt|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;

 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm)return;active.current=true;setBusy(true);try{const input=frozen.current??presenceAttempt({permit,permit_id:presence?null:permit,presence_id:presence,request_id:randomUUID(),version,action,identity_checked:presence?null:identity?true:null,reason});frozen.current=input;const result=await recordSecurityPresence(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current presence: ${result.currentState} (version ${result.currentVersion}). Recording presence does not approve completed work or payment.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the permit.':'Response was not confirmed. Check identity confirmation and the reason, then refresh the permit.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}

 return <View style={styles.card}><Text style={styles.heading}>{presence?'Record departure':'Record arrival'}</Text>{!done&&<>{!confirm&&<>{!presence&&<Pressable accessibilityRole="checkbox" accessibilityState={{checked:identity}} onPress={()=>{if(editable())setIdentity(!identity);}}><Text style={styles.body}>{identity?'☑':'☐'} I checked the visitor’s identity against the approved contractor and permit.</Text></Pressable>}<TextInput accessibilityLabel="Presence recording reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. The server checks current security authority and work state before recording presence.</Text><Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(true);}}><Text style={styles.link}>Review presence</Text></Pressable></>}{confirm&&<><Text style={styles.body}>{presence?'Departure':'Arrival'}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording presence…':uncertain?'Retry same presence action':'Confirm presence'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit presence</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh permit</Text></Pressable>}</View>;
}
