import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {teamInvitationCommand,sendTeamInvitationCommand,type TeamInvitationCommand} from '../lib/team-invitation-command';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function TeamInvitationDecision({owner,invitation,onRefresh}:{owner:string;invitation:{id:string;version:number;organization:string;role:string;email:string;canAccept:boolean;canDecline:boolean};onRefresh:()=>void}){
 const [action,setAction]=useState<'accept'|'decline'>(invitation.canAccept?'accept':'decline'),[reason,setReason]=useState(''),[approved,setApproved]=useState(false),[review,setReview]=useState<TeamInvitationCommand|null>(null),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const mounted=useRef(true),active=useRef(false),locked=useRef(false),complete=useRef(false),frozen=useRef<TeamInvitationCommand|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);const editable=()=>mounted.current&&!locked.current&&!active.current&&!complete.current&&!frozen.current;
 function prepare(){if(!editable()||!approved||!(action==='accept'?invitation.canAccept:invitation.canDecline))return;try{const input=teamInvitationCommand({action,invitation_id:invitation.id,version:invitation.version,organization:invitation.organization,invitedRole:invitation.role,invitedEmail:invitation.email,request_id:randomUUID(),reason,approved:true});locked.current=true;setReview(input);setMessage('');}catch{setMessage('Provide a reason of 5–500 characters and explicit consent to the organization and role shown.');}}
 async function submit(){if(!mounted.current||active.current||complete.current||!review||!supabase)return;active.current=true;setBusy(true);try{const input=frozen.current??review;frozen.current=input;const receipt=await sendTeamInvitationCommand(supabase,owner,input);if(mounted.current){complete.current=true;setDone(true);setUncertain(false);setMessage(`Invitation ${receipt.state} · revision ${receipt.version}. Refresh to review your account and current invitation.`);}}catch(error){if(mounted.current){const pending=unknown.current||!(error instanceof EnquiryFailure)||error.uncertain;unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry this same consent request before making another decision.':'Response was not confirmed. Check your verified account and current invitation before changing the request.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!invitation.canAccept&&!invitation.canDecline&&!review&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Your invitation decision</Text><Text style={styles.body}>{invitation.organization} · {invitation.role} · {invitation.email}</Text><Text style={styles.body}>Your decision reason is visible to the organization administrator. Accepting grants the approved staff role to this verified account.</Text>{!done&&!review&&<>{(['accept','decline'] as const).filter(v=>v==='accept'?invitation.canAccept:invitation.canDecline).map(v=><Pressable key={v} accessibilityRole="radio" accessibilityState={{selected:action===v}} onPress={()=>{if(editable())setAction(v);}}><Text style={styles.body}>{action===v?'●':'○'} {v==='accept'?'Accept staff access':'Decline invitation'}</Text></Pressable>)}<TextInput accessibilityLabel="Invitation decision reason" multiline maxLength={500} value={reason} onChangeText={v=>{if(editable())setReason(v);}} style={styles.input}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:approved}} onPress={()=>{if(editable())setApproved(!approved);}}><Text style={styles.body}>{approved?'☑':'☐'} I consent to this decision for the organization and role shown above.</Text></Pressable><Pressable accessibilityRole="button" onPress={prepare}><Text style={styles.link}>Review consent decision</Text></Pressable></>}{!done&&review&&<><Text style={styles.body}>Confirm {review.action} · {review.organization} · {review.invitedRole} · {review.invitedEmail}. Reason: {review.reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same consent decision':'Confirm consent decision'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(mounted.current&&!active.current&&!complete.current&&!frozen.current){locked.current=false;setReview(null);}}}><Text style={styles.link}>Edit consent decision</Text></Pressable>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{done&&<Pressable accessibilityRole="button" onPress={onRefresh}><Text style={styles.link}>Refresh invitation and account</Text></Pressable>}</View>;
}
