import {useEffect,useRef,useState} from 'react';
import {Pressable,Text,TextInput,View} from 'react-native';
import {randomUUID} from 'expo-crypto';
import {workOfferAttempt,respondToWorkOffer,type WorkOfferAttempt} from '../lib/work-offer-response';
import {EnquiryFailure} from '../lib/enquiries';
import {supabase} from '../lib/supabase';
import {styles} from './styles';
export function WorkOfferResponse({owner,id,version,state,expired,onRefresh}:{owner:string;id:string;version:number;state:string;expired:boolean;onRefresh:()=>void}){
 const [action,setAction]=useState<WorkOfferAttempt['action']>(state==='accepted'?'release':'accept'),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[uncertain,setUncertain]=useState(false),[done,setDone]=useState(false),[message,setMessage]=useState('');const active=useRef(false),mounted=useRef(true),complete=useRef(false),frozen=useRef<WorkOfferAttempt|null>(null),unknown=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const editable=()=>mounted.current&&!active.current&&!complete.current&&!frozen.current;
 const available=state==='accepted'||state==='offered'&&!expired;
 async function submit(){if(active.current||complete.current||!mounted.current||!supabase||!confirm||(!frozen.current&&!available))return;active.current=true;setBusy(true);try{const input=frozen.current??workOfferAttempt({offer_id:id,request_id:randomUUID(),version,action,reason});frozen.current=input;const result=await respondToWorkOffer(supabase,owner,input);if(!mounted.current)return;complete.current=true;setDone(true);setUncertain(false);setMessage(`Recorded outcome: ${result.state} (version ${result.version}). Current offer: ${result.currentState} (version ${result.currentVersion}). This does not authorize a visit or entry.`);}catch(error){if(mounted.current){const pending=!!frozen.current&&(unknown.current||!(error instanceof EnquiryFailure)||error.uncertain);unknown.current=pending;if(!pending)frozen.current=null;setUncertain(pending);setMessage(pending?'Response could not be confirmed. Retry the same action and reason or refresh the offer.':'Response was not confirmed. Check the reason and refresh the offer before changing it.');}}finally{active.current=false;if(mounted.current)setBusy(false);}}
 if(!available&&!uncertain&&!done)return null;
 return <View style={styles.card}><Text style={styles.heading}>Respond to the work offer</Text>{!done&&<>{!confirm&&<>{(state==='accepted'?['release']:['accept','decline']).map(value=><Pressable key={value} accessibilityRole="radio" accessibilityState={{selected:action===value}} onPress={()=>{if(editable())setAction(value as WorkOfferAttempt['action']);}}><Text style={styles.body}>{action===value?'●':'○'} {value}</Text></Pressable>)}<TextInput accessibilityLabel="Work offer response reason" multiline maxLength={500} value={reason} onChangeText={value=>{if(editable())setReason(value);}} style={styles.input}/><Text style={styles.body}>Provide a reason of 5–500 characters. Acceptance records your assignment. Release may require the team to resolve scheduled work first.</Text><Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(true);}}><Text style={styles.link}>Review response</Text></Pressable></>}{confirm&&<><Text style={styles.body}>Confirm {action}: {reason}</Text><Pressable accessibilityRole="button" disabled={busy} onPress={()=>void submit()}><Text style={styles.link}>{busy?'Recording response…':uncertain?'Retry same offer response':'Confirm response'}</Text></Pressable>{!busy&&!uncertain&&<Pressable accessibilityRole="button" onPress={()=>{if(editable())setConfirm(false);}}><Text style={styles.link}>Edit response</Text></Pressable>}</>}</>}{!!message&&<Text accessibilityLiveRegion="polite" style={styles.body}>{message}</Text>}{(done||uncertain)&&<Pressable accessibilityRole="button" disabled={busy} onPress={onRefresh}><Text style={styles.link}>Refresh offer</Text></Pressable>}</View>;
}
