'use client';
import {useRef,useState,type FormEvent} from 'react';
export type ContractorAccount={id:string;user_id:string;company_name:string;trade_coverage:string[];is_active:boolean;version:number};
export function ContractorEditor({account}:{account?:ContractorAccount}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const retry=useRef<{payload:string;id:string}|null>(null);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget),input={account_id:account?.id||null,version:account?.version||0,email:account?null:String(form.get('email')||''),company_name:String(form.get('company_name')||''),trade_coverage:String(form.get('trade_coverage')||'').split(',').map(item=>item.trim()).filter(Boolean),is_active:account?form.get('is_active')==='on':true,reason:String(form.get('reason')||''),approved:form.get('approved')==='on'};
 const payload=JSON.stringify(input);if(retry.current?.payload!==payload)retry.current={payload,id:crypto.randomUUID()};
 try{const response=await fetch('/api/staff/contractors',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,request_id:retry.current.id})});const result=await response.json();if(!response.ok){if(response.status<500)retry.current=null;throw new Error(result.error||'Unable to save contractor.');}window.location.assign(`/staff/contractors/${result.id}`);}catch(error){setMessage(error instanceof Error?error.message:'Unable to save contractor. Please retry.');}finally{setBusy(false);}}
 return <form className="staff-editor" onSubmit={submit}><h2>{account?'Review contractor registration':'Register an approved contractor'}</h2>{account?<p>Identity reference: {account.user_id}<br/>Revision {account.version}. This identity cannot be reassigned.</p>:<label>Approved verified account email<input type="email" name="email" required maxLength={254}/></label>}<label>Contractor / company name<input name="company_name" required minLength={2} maxLength={160} defaultValue={account?.company_name}/></label><label>Approved trade coverage<input name="trade_coverage" required maxLength={1620} defaultValue={account?.trade_coverage.join(', ')}/><small>Separate trades with commas. Up to 20 trades.</small></label>{account&&<label><input type="checkbox" name="is_active" defaultChecked={account.is_active}/> Active registration</label>}<label>Approval / change reason<textarea name="reason" required minLength={5} maxLength={500}/></label><label><input type="checkbox" name="approved" required/> Open House approved this registration or change.</label><button className="primary" disabled={busy}>{busy?'Saving…':'Save registration'}</button><p role="status">{message}</p></form>;
}
