'use client';
import {useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
export function InvitationForm({invitation,recipient=false}:{invitation?:{id:string;version:number;can_accept?:boolean;can_decline?:boolean};recipient?:boolean}){
 const router=useRouter(),lock=useRef(false),retry=useRef<{payload:string;id:string}|null>(null);
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setMessage('');
 const form=new FormData(event.currentTarget),input={action:invitation?(recipient?String(form.get('action')):'revoke'):'create',invitation_id:invitation?.id||null,version:invitation?.version||0,email:invitation?null:String(form.get('email')||''),role:invitation?null:String(form.get('role')||''),reason:String(form.get('reason')||''),approved:form.get('approved')==='on'};
 const payload=JSON.stringify(input);if(retry.current?.payload!==payload)retry.current={payload,id:crypto.randomUUID()};
 try{const response=await fetch('/api/staff/invitations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,request_id:retry.current.id})});const result=await response.json();if(!response.ok){if(response.status<500)retry.current=null;throw new Error(result.error||'Unable to update the invitation.');}setMessage(input.action==='accept'?'Invitation accepted. Your team tools are available from your account.':'Invitation updated.');retry.current=null;router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Unable to confirm the result. Retry unchanged details.');}finally{lock.current=false;setBusy(false);}}
 return <form className="staff-editor" onSubmit={submit}><h2>{invitation?(recipient?'Your decision':'Revoke this invitation'):'Invite a team member'}</h2>{!invitation&&<><label>Approved email<input name="email" type="email" required maxLength={254}/></label><label>Approved role<select name="role" defaultValue="realtor"><option value="realtor">Realtor</option><option value="manager">Manager</option><option value="finance">Finance</option><option value="admin">Administrator</option></select></label><p>The recipient must sign up, verify this exact email and accept before receiving access. Invitations expire after seven days.</p></>}{recipient&&<label>Decision<select name="action" defaultValue={invitation?.can_accept?'accept':'decline'}>{invitation?.can_accept&&<option value="accept">Accept staff access</option>}{invitation?.can_decline&&<option value="decline">Decline invitation</option>}</select></label>}<label>{recipient?'Decision reason (visible to the organization administrator)':'Private approval reason'}<textarea name="reason" required minLength={5} maxLength={500}/></label><label><input name="approved" type="checkbox" required/>{recipient?' I consent to this decision for the organization and role shown above.':' Open House has approved this invitation change.'}</label><button className="primary" disabled={busy}>{busy?'Saving…':invitation?(recipient?'Confirm decision':'Revoke invitation'):'Create invitation'}</button><p role="status">{message}</p></form>;
}
