'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export type ManagedProperty={id:string;name:string;area:string|null;address_text:string|null;management_revision:number};
export type ManagedUnit={id:string;unit_label:string;bedrooms:number;bathrooms:number;parking_spaces:number;floor:number|null;size_sq_ft:number|null;management_revision:number};
export function ManagedInventoryEditor({action,targetId,revision,property,unit,listingId,currentUnitId,units=[]}:{action:string;targetId?:string;revision:number;property?:ManagedProperty;unit?:ManagedUnit;listingId?:string;currentUnitId?:string;units?:ManagedUnit[]}){
 const router=useRouter();const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');const isProperty=action.startsWith('property_'),isLink=action==='listing_link';
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form),retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setNotice('');const body:Record<string,unknown>={action,target_id:targetId??null,revision,request_id:retry};if(isProperty){for(const key of ['name','area','address_text'])body[key]=data.get(key);}else if(isLink)body.unit_id=data.get('unit_id')==='__remove__'?null:data.get('unit_id');else{body.unit_label=data.get('unit_label');for(const key of ['bedrooms','bathrooms','parking_spaces','floor','size_sq_ft']){const value=data.get(key);body[key]=value===''?null:Number(value);}}
 try{const response=await fetch('/api/staff/managed-inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error);}setNotice('Private inventory saved.');setRequestId('');if(action==='property_create')form.reset();if(result.property_id&&action==='property_create')router.push(`/staff/properties?property=${result.property_id}${listingId?`&listing=${listingId}`:''}`);else router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to save. Retry unchanged.');}finally{setBusy(false);}}
 return <form onSubmit={submit} onChange={()=>setRequestId('')}><fieldset disabled={busy}><legend>{isProperty?(property?'Edit private property':'Create private property'):isLink?'Link this listing to a managed unit':unit?'Edit managed unit':'Add managed unit'}</legend>{isProperty?<><label>Property name<input name="name" defaultValue={property?.name||''} required minLength={2} maxLength={160}/></label><label>Area<input name="area" defaultValue={property?.area||''} required minLength={2} maxLength={120}/></label><label>Exact private address<textarea name="address_text" defaultValue={property?.address_text||''} required minLength={5} maxLength={500}/></label><p>Exact addresses remain private. Public map locations are configured separately in the catalog.</p></>:isLink?<><label>Managed unit<select name="unit_id" required defaultValue={currentUnitId||""}><option value="" disabled>Choose a unit or remove its link</option><option value="__remove__">Remove unit link</option>{units.map(row=><option key={row.id} value={row.id}>{row.unit_label}</option>)}</select></label><p>Linking does not copy the private address or overwrite approved public listing facts. Reserved units and seller-handoff property bindings remain protected.</p></>:<><label>Unit label<input name="unit_label" required maxLength={80} defaultValue={unit?.unit_label||''}/></label>{(['bedrooms','bathrooms','parking_spaces','floor','size_sq_ft'] as const).map(key=><label key={key}>{key.replaceAll('_',' ')}<input name={key} type="number" step={['bedrooms','bathrooms'].includes(key)?0.5:1} min={key==='floor'?-10:key==='size_sq_ft'?1:0} max={key==='floor'?200:key==='size_sq_ft'?1000000:key==='parking_spaces'?100:50} required={!['floor','size_sq_ft'].includes(key)} defaultValue={unit?.[key]??(['floor','size_sq_ft'].includes(key)?'':0)}/></label>)}</>}<button>{busy?'Saving…':'Save private inventory'}</button></fieldset><p role="status">{notice}</p></form>;
}
