'use client';
import {useRef,useState,type FormEvent} from 'react';
export type StaffMember={user_id:string;email:string;verified:boolean;role:string;membership_revision:string};
export function MembershipEditor({member}:{member?:StaffMember}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const retry=useRef<{payload:string;id:string}|null>(null);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const form=new FormData(event.currentTarget),role=String(form.get('role'));
 const input={email:member?.email||String(form.get('email')||''),role:role==='revoke'?null:role,revision:member?.membership_revision||null,reason:String(form.get('reason')||''),approved:form.get('approved')==='on'};
 const payload=JSON.stringify(input);if(retry.current?.payload!==payload)retry.current={payload,id:crypto.randomUUID()};
 try{const response=await fetch('/api/staff/memberships',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,request_id:retry.current.id})});const result=await response.json();if(!response.ok){if(response.status<500)retry.current=null;throw new Error(result.error||'Unable to change access.');}window.location.assign('/staff/memberships?saved=1');}catch(error){setMessage(error instanceof Error?error.message:'Unable to change access. Retry unchanged details if the outcome is uncertain.');}finally{setBusy(false);}}
 return <form onSubmit={submit} className="staff-editor"><h2>{member?member.email:'Assign an approved verified account'}</h2>{member?<p>{member.verified?'Verified email':'Email currently unverified'} · Current role: {member.role}<br/><small>Account reference: {member.user_id}</small></p>:<label>Approved account email<input name="email" type="email" required maxLength={254}/></label>}<label>Access<select name="role" defaultValue={member?.role||'realtor'}><option value="realtor">Realtor</option><option value="manager">Manager</option><option value="finance">Finance</option><option value="admin">Administrator</option>{member&&<option value="revoke">Revoke staff access</option>}</select></label><label>Change reason<textarea name="reason" required minLength={5} maxLength={500}/></label><label><input name="approved" type="checkbox" required/> This access change is approved by Open House.</label><button className="primary" disabled={busy}>{busy?'Updating…':'Update access'}</button><p role="status">{message}</p></form>;
}
