'use client';
import {useRef,useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {preventivePlanInput} from '@/lib/staff/preventive-plan-validation';
export type PreventivePlan={id:string;version:number;title:string;description:string;priority:string;interval_days:number;next_due_on:string;state:string};
export function PreventivePlanEditor({action,propertyId,units=[],plan}:{action:'create'|'revise'|'issue'|'skip';propertyId?:string;units?:{id:string;unit_label:string}[];plan?:PreventivePlan}){
 const router=useRouter(),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),working=useRef(false),retry=useRef<{payload:string;id:string}|null>(null);
 async function submit(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(working.current)return;working.current=true;setBusy(true);setMessage('');
  try{const values=new FormData(event.currentTarget),input={action,plan_id:plan?.id||null,version:plan?.version||0,property_id:propertyId||null,unit_id:String(values.get('unit_id')||'')||null,title:String(values.get('title')||''),description:String(values.get('description')||''),priority:String(values.get('priority')||''),interval_days:Number(values.get('interval_days')),next_due_on:String(values.get('next_due_on')||''),state:String(values.get('state')||''),reason:String(values.get('reason')||''),approved:values.get('approved')==='on'};
   const payload=JSON.stringify(input);if(retry.current?.payload!==payload)retry.current={payload,id:crypto.randomUUID()};const body={...input,request_id:retry.current.id};preventivePlanInput(body);
   const response=await fetch('/api/staff/preventive-plans',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),result=await response.json();if(!response.ok){if(response.status<500)retry.current=null;throw new Error(result.error||'Unable to confirm preventive plan.');}
   const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;if((action==='skip'&&result?.work_order_id!=null)||!result||typeof result.id!=='string'||!uuid.test(result.id)||(result.work_order_id!=null&&(typeof result.work_order_id!=='string'||!uuid.test(result.work_order_id)))||(action==='issue'&&(typeof result.work_order_id!=='string'||!uuid.test(result.work_order_id))))throw new Error('Result uncertain. Retry unchanged details.');
   retry.current=null;router.push(result.work_order_id?`/staff/work-orders/${result.work_order_id}`:`/staff/preventive-plans/${result.id}`);router.refresh();
  }catch(error){setMessage(error instanceof Error?error.message:'Result uncertain. Retry unchanged details.');}finally{working.current=false;setBusy(false);}
 }
 return <form className="staff-editor" onSubmit={submit}><h2>{action==='create'?'Create preventive plan':action==='revise'?'Revise approved plan':action==='skip'?'Record skipped due date':'Issue due work order'}</h2><fieldset disabled={busy}>{action!=='issue'&&action!=='skip'&&<>{action==='create'&&<label>Location<select name="unit_id"><option value="">Whole property / common area</option>{units.map(unit=><option key={unit.id} value={unit.id}>{unit.unit_label}</option>)}</select></label>}<label>Title<input name="title" required minLength={3} maxLength={160} defaultValue={plan?.title}/></label><label>Approved inspection / work scope<textarea name="description" required minLength={20} maxLength={5000} defaultValue={plan?.description}/></label><label>Priority<select name="priority" defaultValue={plan?.priority||'standard'}>{['low','standard','high','urgent'].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label>Fixed interval in days<input name="interval_days" type="number" required min={1} max={366} step={1} defaultValue={plan?.interval_days}/></label><label>Next unissued due date · Jamaica calendar<input name="next_due_on" type="date" required min="2000-01-01" max="2200-01-01" defaultValue={plan?.next_due_on}/></label><label>Plan state<select name="state" defaultValue={plan?.state||'active'}><option value="active">Active</option><option value="paused">Paused</option>{action==='revise'&&<option value="retired">Retired · Permanent</option>}</select></label><p>The next due date must follow the latest issued or skipped occurrence. Review the plan history before changing an overdue schedule. Choose the approved fixed-day cadence. Calendar-month schedules are not represented by a fixed number of days.</p></>}{action==='issue'&&<p>Create one work order for {plan?.next_due_on}. This advances the due date by {plan?.interval_days} days. It does not assign a contractor or authorize entry.</p>}{action==='skip'&&<p>Record {plan?.next_due_on} as skipped with an approved exception reason. Advance the next due date by {plan?.interval_days} days. This creates no work order and does not record maintenance as completed.</p>}<label>Management decision reason<textarea name="reason" required minLength={5} maxLength={500}/></label><label><input name="approved" type="checkbox" required/> {action==='skip'?'I approve skipping this scheduled date and understand the work is not recorded as completed.':'I approve this scope, cadence and management action.'}</label><button className="primary">{busy?'Saving…':action==='issue'?'Approve and issue work':action==='skip'?'Approve skipped date':'Approve and save plan'}</button></fieldset><p role="status" aria-live="polite">{message}</p></form>;
}
