import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {formatJmdMinor} from '@/lib/finance/money';
import {InvoiceReview} from '@/components/finance/invoice-review';
import {InvoiceEvidenceFiles} from '@/components/finance/invoice-evidence-files';
import {invoiceActions} from '@/lib/finance/invoice-actions';
import {InvoicePostingForm} from '@/components/finance/invoice-posting-form';
export const dynamic='force-dynamic';
export default async function Invoice({params,searchParams}:{params:Promise<{invoiceId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}) {
 const {client,user,membership}=await catalogAccess(['admin','manager','finance']);if(!user)redirect('/sign-in');if(!membership)notFound();const {invoiceId}=await params;
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(invoiceId))notFound();
 const invoice=await client.from('reviewed_vendor_invoices').select('id,property_id,work_order_id,vendor_name,invoice_number,amount_minor,state,version,submitted_by,reviewed_by,approved_by,submitted_at,reviewed_at,approved_at').eq('id',invoiceId).eq('organization_id',membership.organization_id).maybeSingle();if(invoice.error)throw new Error('Unable to load invoice.');if(!invoice.data)notFound();const row=invoice.data;
 const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1,href=(next:number)=>`/staff/finance/invoices/${invoiceId}?page=${next}`;
 const query=(head=false)=>client.from('vendor_invoice_reviews').select('id,actor_user_id,action,previous_state,new_state,version,reason,created_at',{head,count:'exact'}).eq('organization_id',membership.organization_id).eq('invoice_id',invoiceId);
 const count=await query(true);if(count.error)throw new Error('Unable to count invoice history.');const pages=Math.max(1,Math.ceil((count.count||0)/25));if(page>pages)redirect(href(pages));const historyQuery=query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 const evidenceQuery=()=>client.from('vendor_invoice_evidence').select('id,kind,file_name,state,expires_at').eq('organization_id',membership.organization_id).eq('invoice_id',invoiceId);
 const [history,uploaded,reserved,snapshot]=await Promise.all([historyQuery,evidenceQuery().eq('state','uploaded').order('created_at',{ascending:false}).order('id').limit(10),evidenceQuery().eq('state','reserved').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).order('id').limit(10),row.state==='submitted'?Promise.resolve({data:[],error:null}):client.from('vendor_invoice_review_evidence').select('evidence_id,kind,file_name,reviewed_version').eq('organization_id',membership.organization_id).eq('invoice_id',invoiceId).order('evidence_id').limit(11)]);
 const sealed=snapshot.data||[],snapshotRequired=['under_review','approved'].includes(row.state),evidenceFailed=uploaded.error||reserved.error||snapshot.error||sealed.length>10||(snapshotRequired&&(!sealed.some(file=>file.kind==='invoice')||sealed.some(file=>file.reviewed_version!==(row.state==='approved'?row.version-1:row.version))));
 const files=sealed.length?sealed.map(file=>({id:file.evidence_id,kind:file.kind,file_name:file.file_name,state:'uploaded',expires_at:''})):[...(uploaded.data||[]),...(reserved.data||[])];
 const key=process.env.SUPABASE_SECRET_KEY,uploadsEnabled=!!key&&key.length>=30&&!key.includes('YOUR-');
 const sourceReady=(uploaded.data||[]).some(file=>file.kind==='invoice'),actions=invoiceActions(row,user.id,membership.role).filter(action=>action!=='review'||sourceReady);
 const finance=['admin','finance'].includes(membership.role),posting=finance?await client.from('vendor_invoice_ledger_postings').select('journal_id').eq('invoice_id',row.id).eq('organization_id',membership.organization_id).maybeSingle():{data:null,error:null};
 const reversal=finance&&!posting.error&&posting.data?await client.from('finance_journal_reversals').select('reversal_journal_id,reason').eq('original_journal_id',posting.data.journal_id).eq('organization_id',membership.organization_id).maybeSingle():{data:null,error:null};
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Vendor invoice · Revision {row.version}</p><h1>{row.vendor_name} · {row.invoice_number}</h1><p>{formatJmdMinor(String(row.amount_minor))} · {row.state.replaceAll('_',' ')}</p><p>Submitted by {row.submitted_by}{row.reviewed_by&&` · Reviewed by ${row.reviewed_by}`}{row.approved_by&&` · Approved by ${row.approved_by}`}</p><p>Property allocation: {row.property_id||'Organization invoice'}{row.work_order_id&&` · Work order: ${row.work_order_id}`}</p><p>Approval does not create a payment or ledger posting. Submitted invoice details are fixed.</p>{evidenceFailed?<p role="alert">Unable to load invoice documents. Refresh before reviewing.</p>:<InvoiceEvidenceFiles key={`${row.id}-${row.version}`} files={files} invoiceId={row.id} editable={row.state==='submitted'&&row.submitted_by===user.id} enabled={uploadsEnabled} reviewedVersion={sealed[0]?.reviewed_version}/>}{!evidenceFailed&&<>{row.state==='submitted'&&!sourceReady&&<p>A format-checked vendor invoice document is required before finance can begin review.</p>}<InvoiceReview key={`${row.id}-${row.version}`} invoiceId={row.id} version={row.version} actions={actions}/></>}{finance&&(posting.error?<p role="alert">Unable to load invoice posting. Refresh before posting.</p>:posting.data?<section><p><a href={`/staff/finance/journals/${posting.data.journal_id}`}>View posted journal →</a></p>{reversal.error?<p role="alert">Unable to load reversal status. Refresh before interpreting this posting.</p>:reversal.data?<><p>Posting reversed · {reversal.data.reason}</p><a href={`/staff/finance/journals/${reversal.data.reversal_journal_id}`}>View invoice reversal →</a><p>This invoice retains its original posting history. A reversal does not permit another posting.</p></>:<p>Invoice posted to the ledger. Vendor payment is a separate workflow.</p>}</section>:row.state==='approved'&&!evidenceFailed?<InvoicePostingForm key={`${row.id}-${row.version}`} invoiceId={row.id} version={row.version} amount={formatJmdMinor(String(row.amount_minor))}/>:<p>Ledger posting requires an approved invoice and its reviewed source.</p>)}<h2>Review history</h2>{history.error?<p role="alert">Unable to load invoice history.</p>:history.data?.map(event=><article className="staff-editor" key={event.id}><h3>{event.action} · Revision {event.version}</h3><p>{event.previous_state||'New invoice'} → {event.new_state}</p><p className="enquiry-message">{event.reason}</p><small>Actor: {event.actor_user_id} · {new Date(event.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</small></article>)}<nav className="results-toolbar" aria-label="Invoice history pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{count.count||0} changes · Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><a href="/staff/finance/invoices">Invoice queue →</a></section></main></>;
}
