export type Home = { id: string; title: string; area: string; intent: 'rent' | 'sale'; price: number; beds: number; baths: number; parking: number; size: number; lat: number; lng: number; photo: string; description: string };
export const homes: Home[] = [
  {id:'residence-8c',title:'Residence 8C',area:'Kingston 6',intent:'rent',price:295000,beds:2,baths:2,parking:1,size:1310,lat:18.026,lng:-76.775,photo:'photo-1600596542815-ffad4c1539a9',description:'An airy apartment concept with a balcony, modern interiors, and space to make your own. Explore the neighborhood and discuss your priorities with the Open House team.'},
  {id:'residence-6a',title:'Residence 6A',area:'Kingston 6',intent:'rent',price:285000,beds:2,baths:2.5,parking:2,size:1420,lat:18.019,lng:-76.784,photo:'photo-1600607687920-4e2a09cf159d',description:'A spacious apartment concept for a connected city lifestyle. Two parking spaces and a flexible layout make this a useful starting point for your property search.'},
  {id:'norbrook-12',title:'Norbrook Residence',area:'Norbrook',intent:'rent',price:315000,beds:2,baths:2,parking:2,size:1480,lat:18.066,lng:-76.786,photo:'photo-1600047509807-ba8f99d2cdde',description:'A furnished residence concept with a balcony and generous living spaces. Start with the area, then let your realtor help you explore the details that matter.'},
  {id:'kingston-family',title:'Garden House',area:'Kingston 6',intent:'sale',price:48500000,beds:4,baths:4,parking:2,size:3200,lat:18.032,lng:-76.766,photo:'photo-1613977257363-707ba9348227',description:'A family home concept with indoor-outdoor living and room for a new chapter. This sample illustrates the buying journey; pricing and imagery are demonstration content.'},
  {id:'hope-gardens',title:'Hope Gardens Apartment',area:'Kingston 6',intent:'rent',price:180000,beds:1,baths:1,parking:1,size:780,lat:18.019,lng:-76.749,photo:'photo-1600596542815-ffad4c1539a9',description:'A fictional 1-bedroom property in the Kingston 6 area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'cherry-gardens',title:'Cherry Gardens Family Home',area:'Cherry Gardens',intent:'sale',price:72000000,beds:4,baths:3.5,parking:3,size:3600,lat:18.055,lng:-76.781,photo:'photo-1600607687920-4e2a09cf159d',description:'A fictional 4-bedroom property in the Cherry Gardens area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'constant-spring',title:'Constant Spring Townhouse',area:'Constant Spring',intent:'sale',price:36500000,beds:3,baths:2.5,parking:2,size:1850,lat:18.049,lng:-76.796,photo:'photo-1600047509807-ba8f99d2cdde',description:'A fictional 3-bedroom property in the Constant Spring area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'portmore-townhouse',title:'Portmore Starter Home',area:'Portmore',intent:'sale',price:24500000,beds:3,baths:2,parking:2,size:1500,lat:17.963,lng:-76.879,photo:'photo-1613977257363-707ba9348227',description:'A fictional 3-bedroom property in the Portmore area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'montego-bay-villa',title:'Montego Bay Coastal Villa',area:'Montego Bay',intent:'sale',price:95000000,beds:5,baths:5,parking:3,size:4400,lat:18.478,lng:-77.911,photo:'photo-1600596542815-ffad4c1539a9',description:'A fictional 5-bedroom property in the Montego Bay area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'ironshore-apartment',title:'Ironshore Apartment',area:'Montego Bay',intent:'rent',price:225000,beds:2,baths:2,parking:1,size:1150,lat:18.509,lng:-77.883,photo:'photo-1600607687920-4e2a09cf159d',description:'A fictional 2-bedroom property in the Montego Bay area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'ocho-rios-retreat',title:'Ocho Rios Garden Retreat',area:'Ocho Rios',intent:'rent',price:195000,beds:2,baths:2,parking:1,size:1250,lat:18.4,lng:-77.101,photo:'photo-1600047509807-ba8f99d2cdde',description:'A fictional 2-bedroom property in the Ocho Rios area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'},
  {id:'mandeville-family',title:'Mandeville Family Residence',area:'Mandeville',intent:'sale',price:42000000,beds:4,baths:3,parking:2,size:2700,lat:18.039,lng:-77.504,photo:'photo-1613977257363-707ba9348227',description:'A fictional 4-bedroom property in the Mandeville area, created to demonstrate property discovery, approximate maps and the client journey. Photos, prices and amenities are illustrative; this home is not available for purchase, rental or viewing.'}
];
export const photoUrl=(home:Home)=>`https://images.unsplash.com/${home.photo}?auto=format&fit=crop&w=1200&q=85`;
export const priceLabel=(home:Home)=>`JMD ${home.price.toLocaleString('en-JM')}${home.intent==='rent'?' / month':''}`;
export type MatchPreferences = { communication: string; guidance: string; pace: string; area: string; intent: string };
export type Realtor = {id:string;name:string;initials:string;tagline:string;bio:string;areas:string[];intents:string[];communication:string;guidance:string;pace:string};
export const realtors:Realtor[]=[
 {id:'sample-avery',name:'Avery · sample profile',initials:'A',tagline:'A calm guide for your next chapter',bio:'A sample of a realtor who explains each step, listens closely, and gives you space to weigh your options.',areas:['Kingston 6','Norbrook'],intents:['buy','rent'],communication:'thoughtful',guidance:'step-by-step',pace:'considered'},
 {id:'sample-jordan',name:'Jordan · sample profile',initials:'J',tagline:'Clear answers. Confident decisions.',bio:'A sample of a realtor who leads with comparisons, direct answers, and a focused plan for your property search.',areas:['Kingston 6'],intents:['buy','sell'],communication:'direct',guidance:'data-led',pace:'decisive'},
 {id:'sample-morgan',name:'Morgan · sample profile',initials:'M',tagline:'A collaborative partner in your search',bio:'A sample of a realtor who explores possibilities with you, offers a flexible shortlist, and adapts to your schedule.',areas:['Norbrook','Kingston 6','Cherry Gardens','Constant Spring'],intents:['rent','buy','sell'],communication:'collaborative',guidance:'independent',pace:'flexible'},
 {id:'sample-riley',name:'Riley · demo realtor',initials:'R',tagline:'A thoughtful guide to coastal living',bio:'Fictional coastal realtor profile for trying a reassuring, step-by-step property search.',areas:['Montego Bay','Ocho Rios'],intents:['rent','buy','sell'],communication:'thoughtful',guidance:'step-by-step',pace:'considered'},
 {id:'sample-quinn',name:'Quinn · demo realtor',initials:'Q',tagline:'Practical comparisons for your next move',bio:'Fictional Portmore realtor profile for exploring direct advice and clear property comparisons.',areas:['Portmore'],intents:['rent','buy','sell'],communication:'direct',guidance:'data-led',pace:'decisive'},
 {id:'sample-sage',name:'Sage · demo realtor',initials:'S',tagline:'Room to explore your possibilities',bio:'Fictional Mandeville realtor profile for exploring an independent search with a flexible working rhythm.',areas:['Mandeville'],intents:['rent','buy','sell'],communication:'collaborative',guidance:'independent',pace:'flexible'}
];
export function matchRealtors(preferences:MatchPreferences){
 const labels:Record<string,string>={communication:'communication style',guidance:'guidance preference',pace:'decision pace'};
 return realtors.filter(realtor=>realtor.areas.includes(preferences.area) && realtor.intents.includes(preferences.intent)).map(realtor=>{
  const reasons:string[]=[];let points=0;
  for(const key of ['communication','guidance','pace'] as const)if(realtor[key]===preferences[key]){points+=2;reasons.push(`Matches your ${labels[key]}`);}
  if(realtor.areas.includes(preferences.area)){points+=1;reasons.push(`Serves ${preferences.area}`);}
  if(realtor.intents.includes(preferences.intent)){points+=1;reasons.push(`Supports your ${preferences.intent} journey`);}
  return {realtor,points,reasons};
 }).sort((a,b)=>b.points-a.points||a.realtor.name.localeCompare(b.realtor.name));
}
