import {redirect} from 'next/navigation';
import {SiteHeader} from '@/components/discovery/site-header';
import {catalogAccess} from '@/lib/staff/access';
export const dynamic='force-dynamic';
export const metadata={title:'Lease questions | Open House Realty'};
export default async function LeaseQuestions({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','realtor','manager']);if(!user)redirect('/sign-in');if(!membership)redirect('/account');
 const raw=(await searchParams).page;const page=typeof raw==='string'&&/^\d{1,6}$/.test(raw)?Math.max(1,Math.min(100000,Number(raw))):1;
 const query=(head=false)=>client.from('pending_lease_review_questions').select('release_id,application_id,draft_id,draft_version,title_snapshot,review_version,message,asked_at',{head,count:'exact'}).eq('organization_id',membership.organization_id);
 let count:number|null=null,error=false;try{const result=await query(true);if(!result.error&&typeof result.count==='number'&&Number.isSafeInteger(result.count)&&result.count>=0)count=result.count;else error=true;}catch{error=true;}
 const pages=Math.max(1,Math.ceil((count||0)/25));if(!error&&page>pages)redirect(`/staff/lease-reviews?page=${pages}`);
 let rows:{release_id:string;application_id:string;draft_id:string;draft_version:number;title_snapshot:string;review_version:number;message:string;asked_at:string}[]=[];
 if(!error&&count){try{const result=await query().order('asked_at',{ascending:true}).order('release_id').range((page-1)*25,page*25-1);if(result.error||!Array.isArray(result.data))error=true;else rows=result.data;}catch{error=true;}}
 return <><SiteHeader/><main className="listing-workspace"><section className="page-intro"><p className="eyebrow">Team follow-up</p><h1>Lease questions awaiting a reply.</h1><p>Latest unanswered applicant questions on current released summaries for your organization, oldest first. Replaced or withdrawn versions are excluded. Counts and records are read independently.</p><p><a href="/staff/applications">Rental application inbox →</a></p></section>{error?<p role="alert">Unable to load pending questions. Refresh before treating this queue as clear.</p>:<><p>{count?.toLocaleString('en-JM')} unanswered questions</p><div className="enquiry-grid">{rows.map(row=><article key={row.release_id} className="staff-editor"><h2>{row.title_snapshot}</h2><p>Draft version {row.draft_version} · Response {row.review_version}</p><p className="enquiry-message">{row.message}</p><p>Asked {new Date(row.asked_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</p><a href={`/applications/${row.application_id}/lease/${row.draft_id}`}>Read discussion and reply →</a></article>)}</div>{count===0&&<section className="empty-state"><h2>No questions in this view.</h2><p>The queue may change as applicants respond or staff reply. Reviewing a summary does not sign or accept a lease.</p></section>}{count!==0&&!rows.length&&<p role="status">The queue changed while loading. Refresh to see its latest questions.</p>}{pages>1&&<nav aria-label="Pending lease question pages">{page>1&&<a href={`/staff/lease-reviews?page=${page-1}`}>← Previous questions</a>}<span>Page {page} of {pages}</span>{page<pages&&<a href={`/staff/lease-reviews?page=${page+1}`}>More questions →</a>}</nav>}</>}</main></>;
}
