import {redirect,notFound} from 'next/navigation';
import {SiteHeader} from '@/components/discovery/site-header';
import {createClient} from '@/lib/supabase/server';
import {uuidPattern} from '@/lib/enquiries/validation';
import {applicantLeaseSummaryResult,leaseSummaryMoney} from '@/lib/leases/summary';
export const dynamic='force-dynamic';
export const metadata={title:'Your lease summary | Open House Realty'};
export default async function ApplicantLease({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {id}=await params;if(!uuidPattern.test(id))notFound();
 const client=await createClient();const {data:{user},error:authError}=await client.auth.getUser();if(authError||!user?.email_confirmed_at)redirect('/sign-in');
 const {data:application,error}=await client.from('rental_applications').select('id,title_snapshot').eq('id',id).eq('user_id',user.id).maybeSingle();if(error)throw new Error('Unable to check your application.');if(!application)notFound();
 const input=await searchParams,raw=input.page;const page=typeof raw==='string'&&/^\d{1,6}$/.test(raw)&&Number(raw)>=1&&Number(raw)<=100000?Number(raw):1;
 let summaries:ReturnType<typeof applicantLeaseSummaryResult>|null=null;try{const result=await client.rpc('applicant_lease_summaries',{p_application_id:id,p_page:page});if(!result.error)summaries=applicantLeaseSummaryResult(result.data);}catch{/* A failed read is not an empty history. */}
 const pages=summaries?Math.max(1,Math.ceil(summaries.total/25)):1;
 if(summaries&&page>pages)redirect(`/applications/${id}/lease?page=${pages}`);
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Your rental application</p><h1>Your lease summary.</h1><p>{application.title_snapshot}</p><p><a href={`/applications/${id}`}>← Application and next steps</a></p><p>These summaries were explicitly shared by the team. They do not replace the full legal lease or establish a signature, payment receipt or permission to move in. Ask the team to resolve any questions before signing.</p>{!summaries?<p role="alert">Unable to load your shared summaries. Refresh before making a decision.</p>:summaries.items.length?summaries.items.map(item=><article key={item.id}><h2>Version {item.version} · {item.state==='prepared'?'Prepared summary':item.state==='superseded'?'Replaced summary':'Withdrawn summary'}</h2>{item.state!=='prepared'&&<p>This historical summary is no longer current. Check with the team before relying on its terms.</p>}<dl><dt>Home</dt><dd>{item.property_name} · {item.unit_label}</dd><dt>Proposed lease dates</dt><dd>{item.starts_on} through {item.ends_on}</dd><dt>Monthly rent</dt><dd>{leaseSummaryMoney(item.rent_minor)}</dd><dt>Proposed deposit</dt><dd>{leaseSummaryMoney(item.deposit_minor)} · receipt not established</dd><dt>Proposed billing day</dt><dd>{item.billing_day} · the approved schedule must account for shorter months</dd><dt>Template</dt><dd>{item.template_title}</dd></dl><p>Shared {new Date(item.released_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</p><p><a href={`/applications/${id}/lease/${item.id}`}>Review and shared questions →</a></p><small>Draft reference: {item.id}</small></article>):<p>The team has not shared a lease summary yet. An approved application alone does not mean the lease is ready to sign.</p>}{summaries&&pages>1&&<nav aria-label="Shared lease history pages">{page>1&&<a href={`/applications/${id}/lease?page=${page-1}`}>← Newer summaries</a>}<span>Page {page} of {pages}</span>{page<pages&&<a href={`/applications/${id}/lease?page=${page+1}`}>Older summaries →</a>}</nav>}</section></main></>;
}
