'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
import {jamaicaToday} from '@/lib/applications/validation';
export type LeaseTemplateOption={id:string;title:string;template_key:string;version:number};
export function LeaseDraftEditor({applicationId,applicationVersion,draftVersion,templates,desiredMoveIn}:{applicationId:string;applicationVersion:number;draftVersion:number;templates:LeaseTemplateOption[];desiredMoveIn:string}){
 const router=useRouter();const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),template=templates.find(item=>item.id===data.get('template'));if(!template)return;const retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setNotice('');try{const response=await fetch('/api/staff/lease-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({application_id:applicationId,application_version:applicationVersion,draft_version:draftVersion,template_id:template.id,template_version:template.version,request_id:retry,starts_on:data.get('start'),ends_on:data.get('end'),billing_day:Number(data.get('billing')),deposit_jmd:data.get('deposit'),approval_reference:data.get('reference'),terms_approved:data.get('approved')==='on'})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error||'Unable to save draft.');}setNotice(`Draft version ${result.version} prepared. Signing has not started.`);router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to save. Retry unchanged.');}finally{setBusy(false);}}
 if(!templates.length)return <p>An administrator must register an approved lease template before a draft can be prepared. <a href="/staff/lease-templates">Open template registry ↗</a></p>;
 const today=jamaicaToday(new Date());return <section><h2>{draftVersion?'Prepare a revised draft':'Prepare the first draft'}</h2><p>Applicant, rental amount, reserved unit and participating co-signers come from the approved records. Each revision preserves the previous draft. Template references record business approval; the actual legal document still needs to be supplied and checked before signing.</p><form onSubmit={submit} onChange={()=>setRequestId('')}><fieldset disabled={busy}><label>Approved lease template<select name="template" required defaultValue=""><option value="" disabled>Choose an approved template</option>{templates.map(template=><option key={template.id} value={template.id}>{template.title} · v{template.version}</option>)}</select></label><label>Lease start<input name="start" type="date" required min={today} defaultValue={desiredMoveIn<today?today:desiredMoveIn}/></label><label>Lease end<input name="end" type="date" required min={today}/></label><label>Monthly billing day<input name="billing" type="number" required min={1} max={31} step={1}/></label><p>For days 29–31, the payment schedule must apply the approved month-end rule before charges can be generated.</p><label>Approved deposit (JMD)<input name="deposit" type="text" inputMode="decimal" required pattern="[0-9]{1,12}(\.[0-9]{1,2})?" placeholder="Enter the approved amount"/></label><label>Internal approved terms reference<textarea name="reference" required minLength={5} maxLength={500}/></label><label><input name="approved" type="checkbox" required/>The selected template, lease dates, billing day and deposit were approved through the business process.</label><p>Preparing this record does not send a signature request, certify the legal document or activate a tenancy.</p><button>{busy?'Saving…':draftVersion?'Save revised draft':'Save lease draft'}</button></fieldset></form><p role="status">{notice}</p></section>;
}
