'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
type Template={template_key:string;version:number;title:string;source_reference:string;content_sha256:string};
export function LeaseTemplateEditor({template}:{template:Template|null}){
 const router=useRouter();const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setNotice('');const key=String(data.get('key'));try{const response=await fetch('/api/staff/lease-templates',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:retry,template_key:key,version:template?.version||0,title:data.get('title'),source_reference:data.get('reference'),sha256:data.get('sha256'),business_approved:data.get('approved')==='on'})});const result=await response.json();if(!response.ok){if(response.status===409)router.push(`/staff/lease-templates?key=${encodeURIComponent(key)}`);throw new Error(result.error);}setNotice('Approved template reference registered.');setRequestId('');router.push(`/staff/lease-templates?key=${encodeURIComponent(key)}`);router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to register. Retry unchanged.');}finally{setBusy(false);}}
 return <form onSubmit={submit} onChange={()=>setRequestId('')}><fieldset disabled={busy}><legend>{template?`Register next version after ${template.version}`:'Register an approved template reference'}</legend><label>Template key<input name="key" pattern="[a-z][a-z0-9_-]{2,63}" required maxLength={64} defaultValue={template?.template_key||''} readOnly={!!template}/></label><label>Title<input name="title" required minLength={3} maxLength={160} defaultValue={template?.title||''}/></label><label>Approved document source reference<textarea name="reference" required minLength={5} maxLength={500} defaultValue={template?.source_reference||''}/></label><label>Business-supplied SHA-256 fingerprint<input name="sha256" required pattern="[a-fA-F0-9]{64}" minLength={64} maxLength={64} defaultValue={template?.content_sha256||''}/></label><p>This records a reference and approval attestation. It does not upload, verify or sign a document.</p><label><input type="checkbox" name="approved" required/>Open House has approved this exact template version for its lease process.</label><button>{busy?'Recording…':'Register approved version'}</button></fieldset><p role="status">{notice}</p></form>;
}
