import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {OpenHouseCreate,OpenHouseResolve} from '@/components/open-houses/staff-editor';
export const dynamic='force-dynamic';
export default async function OpenHouses({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','realtor','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const input=await searchParams,parse=(value:unknown)=>typeof value==='string'&&/^\d{1,5}$/.test(value)?Math.max(1,Number(value)):1,page=parse(input.page),listingPage=parse(input.listings),state=typeof input.state==='string'&&['scheduled','cancelled','completed','all'].includes(input.state)?input.state:'scheduled';
 const events=(head=false)=>{let query=client.from('open_house_events').select('id,title,starts_at,ends_at,capacity,status,open_house_management!inner(organization_id,version,host_user_id)',{head,count:'exact'}).eq('open_house_management.organization_id',membership.organization_id);if(state!=='all')query=query.eq('status',state);return query;};
 const [eventCount,listingCount]=await Promise.all([events(true),client.from('listings').select('id',{head:true,count:'exact'}).eq('organization_id',membership.organization_id).eq('status','published')]);if(eventCount.error||listingCount.error)throw new Error('Unable to load event or property counts.');const pages=Math.max(1,Math.ceil((eventCount.count||0)/25)),listingPages=Math.max(1,Math.ceil((listingCount.count||0)/25)),href=(eventPage:number,propertyPage:number)=>`/staff/open-houses?${new URLSearchParams({state,page:String(eventPage),listings:String(propertyPage)})}`;if(page>pages||listingPage>listingPages)redirect(href(Math.min(page,pages),Math.min(listingPage,listingPages)));
 const [eventRows,listingRows]=await Promise.all([events().order('starts_at').order('id').range((page-1)*25,page*25-1),client.from('listings').select('id,title').eq('organization_id',membership.organization_id).eq('status','published').order('title').order('id').range((listingPage-1)*25,listingPage*25-1)]);
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Organization open houses</p><h1>Open the door to a new chapter.</h1><p>Staff scheduling and public map discovery with verified-account RSVPs are available. Staff check-in and attendance corrections are available from each private roster. Approved private arrival instructions and queued event email notices are available. Check the notification monitor for delivery setup and outcomes. Cancel and create a new event to change a scheduled time; the authoring audit is preserved.</p>{listingRows.error?<p role="alert">Unable to load published property choices.</p>:<OpenHouseCreate key={`${listingPage}-${listingRows.data?.map(row=>row.id).join('|')}`} listings={listingRows.data||[]}/>}<nav className="results-toolbar" aria-label="Published property choices">{listingPage>1?<a href={href(page,listingPage-1)}>← Previous properties</a>:<span/>}<span>Properties {listingPage} of {listingPages}</span>{listingPage<listingPages?<a href={href(page,listingPage+1)}>More properties →</a>:<span/>}</nav><form method="get"><label>Event state<select name="state" defaultValue={state}>{['scheduled','cancelled','completed','all'].map(status=><option key={status}>{status}</option>)}</select></label><button>Filter events</button></form><h2>Event schedule</h2>{eventRows.error?<p role="alert">Unable to load event schedule.</p>:eventRows.data?.length?eventRows.data.map(event=>{const management=Array.isArray(event.open_house_management)?event.open_house_management[0]:event.open_house_management;return <article key={event.id}><h3>{event.title}</h3><p>{new Date(event.starts_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} – {new Date(event.ends_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</p><p>{event.status} · Capacity {event.capacity??'not set'} · {management.host_user_id===user.id?'You are the host':management.host_user_id?'Organization host assigned':'Legacy event needs host review'}</p>{event.status==='scheduled'&&<OpenHouseResolve key={`${event.id}-${management.version}`} id={event.id} version={management.version} ended={new Date(event.ends_at)<=new Date()}/>}<p><a href={`/staff/open-houses/${event.id}`}>View private attendee roster ↗</a></p><small>Event reference: {event.id} · Revision {management.version}</small></article>}):<p>No events match this state.</p>}{pages>1&&<nav className="results-toolbar" aria-label="Event schedule pages">{page>1?<a href={href(page-1,listingPage)}>← Previous</a>:<span/>}<span>Page {page} of {pages}</span>{page<pages?<a href={href(page+1,listingPage)}>Next →</a>:<span/>}</nav>}<p><a href="/account">My account ↗</a></p></section></main></>;
}
