'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
import {DocumentReview,type DocumentReviewRecord} from '@/components/applications/document-review';
import {DOCUMENT_BUCKET,documentFile,documentKinds} from '@/lib/documents/files';
type Document={id:string;file_name:string;kind:string;state:string;created_at:string};
export function ApplicationDocuments({applicationId,documents,isOwner,active,enabled,isReviewer,underReview,reviews}:{applicationId:string;documents:Document[];isOwner:boolean;active:boolean;enabled:boolean;isReviewer:boolean;underReview:boolean;reviews:DocumentReviewRecord[]}){
 const router=useRouter();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const request=useRef<{file:File;id:string;documentId?:string}|null>(null);
 async function call(body:unknown){const response=await fetch('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Document action failed.');return result;}
 async function upload(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const input=form.elements.namedItem('file') as HTMLInputElement;const file=input.files?.[0];if(!file)return;setBusy(true);setMessage('');try{documentFile(file.name,file.type,file.size);if(request.current?.file!==file)request.current={file,id:crypto.randomUUID()};const attempt=request.current;
 if(!attempt.documentId){const result=await call({action:'reserve',application_id:applicationId,request_id:attempt.id,kind:new FormData(form).get('kind'),file_name:file.name,mime_type:file.type,size:file.size});attempt.documentId=result.id;if(result.state!=='uploaded'){const {error}=await createClient().storage.from(DOCUMENT_BUCKET).uploadToSignedUrl(result.path,result.token,file,{contentType:file.type});if(error){attempt.documentId=undefined;throw new Error('Upload interrupted. Retry with the same file.');}}}
 await call({action:'finish',id:attempt.documentId});request.current=null;form.reset();setMessage('Document uploaded for staff review.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Unable to upload document.');}finally{setBusy(false);}}
 async function action(id:string,operation:'download'|'withdraw'|'finish'){setBusy(true);setMessage('');try{if(operation!=='download'){await call({action:operation,id});router.refresh();setMessage(operation==='withdraw'?'Document withdrawn from application access.':'Document uploaded for staff review.');}else{const response=await fetch(`/api/documents?id=${encodeURIComponent(id)}`);const result=await response.json();if(!response.ok)throw new Error(result.error);window.location.assign(result.url);}}catch(error){setMessage(error instanceof Error?error.message:'Document action failed.');}finally{setBusy(false);}}
 return <section><h2>Private supporting documents</h2>{isReviewer&&<><h3>Document verification checklist</h3><ul>{documentKinds.map(kind=><li key={kind}>{kind.charAt(0).toUpperCase()+kind.slice(1)}: {documents.some(doc=>doc.kind===kind&&doc.state==='uploaded'&&reviews.some(review=>review.document_id===doc.id&&review.status==='verified'))?'Verified document on file':'No currently verified document'}</li>)}</ul><p>These checks record document evidence. Application approval also requires the remaining eligibility, co-signer and property checks.</p></>}<p>Only you and authorized application staff can access these files. Uploads receive basic format checks; staff still need to verify their contents.</p>{documents.length?documents.map(doc=><article key={doc.id}><strong>{doc.file_name}</strong><p>{doc.kind} · {doc.state==='uploaded'?'Ready for review':'Upload not finalized'}</p>{doc.state==='uploaded'&&<button disabled={busy} onClick={()=>action(doc.id,'download')}>Download</button>}{isOwner&&active&&doc.state==='reserved'&&<button disabled={busy||!enabled} onClick={()=>action(doc.id,'finish')}>Finish uploaded file</button>}{isOwner&&active&&<button disabled={busy||!enabled} onClick={()=>action(doc.id,'withdraw')}>Withdraw document</button>}{isReviewer&&doc.state==='uploaded'&&<DocumentReview key={`${doc.id}-${reviews.find(review=>review.document_id===doc.id)?.version||0}`} documentId={doc.id} review={reviews.find(review=>review.document_id===doc.id)} editable={underReview}/>}</article>):<p>No supporting documents uploaded.</p>}{isOwner&&active&&(enabled?<form onSubmit={upload}><label>Document category<select name="kind">{documentKinds.map(kind=><option key={kind} value={kind}>{kind}</option>)}</select></label><label>PDF, JPEG or PNG, up to 8 MB<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required disabled={busy}/></label><p>Upload only documents requested by Open House. Up to ten active documents per application.</p><button disabled={busy}>{busy?'Working…':'Upload private document'}</button></form>:<p>Private uploads are being configured. Open House will let you know when documents are required.</p>)}<p role="status" aria-live="polite">{message}</p></section>;
}
