'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {documentKinds} from '@/lib/documents/files';
import type {ApprovalPolicy} from '@/lib/applications/approval';
async function post(body:unknown){const response=await fetch('/api/staff/application-approval',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw {status:response.status,message:data.error||'Unable to record approval.'};return data;}
export function PolicyEditor({policy}:{policy:ApprovalPolicy|null}){
 const router=useRouter();const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,data=new FormData(form);const retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setNotice('');try{await post({action:'policy',request_id:retry,version:policy?.version||0,document_kinds:data.getAll('kinds'),cosigners:Number(data.get('cosigners')),approver_roles:data.getAll('roles'),reference:data.get('reference'),approved:data.get('approved')==='on'});setNotice('Approved business policy recorded.');router.refresh();}catch(error){const result=error as {message?:string;status?:number};if(result.status===409)router.refresh();setNotice(result.message||'Unable to store policy. Retry unchanged.');}finally{setBusy(false);}}
 return <form onSubmit={submit} onChange={()=>setRequestId('')}><fieldset disabled={busy}><legend>Required document categories</legend>{documentKinds.map(kind=><label key={kind}><input type="checkbox" name="kinds" value={kind} defaultChecked={policy?.required_document_kinds.includes(kind)}/>{kind}</label>)}<label>Required consenting co-signers<select name="cosigners" defaultValue={policy?.required_cosigners||0}>{[0,1,2].map(n=><option key={n} value={n}>{n}</option>)}</select></label><fieldset><legend>Roles permitted to approve</legend>{['admin','realtor','manager'].map(role=><label key={role}><input type="checkbox" name="roles" value={role} defaultChecked={policy?policy.approver_roles.includes(role):role==='admin'}/>{role}</label>)}</fieldset><label>Approved business policy reference<textarea name="reference" required minLength={5} maxLength={500} defaultValue={policy?.policy_reference||''}/></label><label><input type="checkbox" name="approved" required/>I confirm these requirements and approver roles are approved by Open House.</label><button>{busy?'Recording…':'Record approved policy version'}</button></fieldset><p role="status">{notice}</p></form>;
}
export function ApplicationApproval({id,version,policy}:{id:string;version:number;policy:ApprovalPolicy|null}){
 const router=useRouter();const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!policy)return;const form=event.currentTarget,data=new FormData(form);const retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setNotice('');try{await post({action:'approve',application_id:id,version,policy_version:policy.version,request_id:retry,reason:data.get('reason'),evidence_reference:data.get('evidence'),eligibility_checked:data.get('eligibility')==='on',availability_checked:data.get('availability')==='on'});setNotice('Application approved and unit reserved for lease preparation.');router.refresh();}catch(error){const result=error as {message?:string;status?:number};if(result.status===409)router.refresh();setNotice(result.message||'Unable to approve. Retry unchanged.');}finally{setBusy(false);}}
 return <section><h2>Approval checks</h2>{!policy?<p>An administrator must record an approved business policy before applications can be approved.</p>:<><p>Policy version {policy.version}: {policy.required_document_kinds.join(', ')||'No uploaded document categories required'} · {policy.required_cosigners} consenting co-signers · Approvers: {policy.approver_roles.join(', ')}</p><p className="enquiry-message">Business process: {policy.policy_reference}</p><p>Required documents must be verified, clarification issues resolved and invitations answered. The advertised rent must match the application, and the published listing must be linked to an available managed unit.</p><form onSubmit={submit} onChange={()=>setRequestId('')}><fieldset disabled={busy}><label>Internal eligibility evidence reference<textarea name="evidence" required minLength={5} maxLength={500}/></label><label><input name="eligibility" type="checkbox" required/>I completed the approved eligibility process for the applicant and any participating co-signers.</label><label><input name="availability" type="checkbox" required/>I confirmed the managed unit, availability, advertised rental terms and intended move-in.</label><label>Shared approval reason<textarea name="reason" required minLength={5} maxLength={2000}/></label><p>Approval reserves the unit for lease preparation. It does not sign a lease or activate resident access.</p><button>{busy?'Checking…':'Approve and reserve unit'}</button></fieldset></form></>}<p role="status">{notice}</p></section>;
}
