'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
export type CosignerRecord={id:string;invite_email:string;state:string;version:number;expires_at:string;recipient_user_id:string|null};
export function CosignerInvites({applicationId,invitations,isOwner,active}:{applicationId:string;invitations:CosignerRecord[];isOwner:boolean;active:boolean}){
 const router=useRouter();const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState(''),[email,setEmail]=useState(''),[permission,setPermission]=useState(false);
 async function send(body:unknown){const response=await fetch('/api/cosigners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error);}return result;}
 async function invite(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice('');const retry=requestId||crypto.randomUUID();setRequestId(retry);try{await send({action:'invite',application_id:applicationId,request_id:retry,email,permission});setEmail('');setPermission(false);setRequestId('');setNotice('Invitation saved for email delivery. Delivery awaits the configured email worker; you can also share its private link with the intended recipient.');router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to invite.');}finally{setBusy(false);}}
 async function revoke(invitation:CosignerRecord){setBusy(true);setNotice('');try{await send({action:'revoke',id:invitation.id,version:invitation.version,request_id:crypto.randomUUID()});setNotice('Invitation revoked.');router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to revoke.');}finally{setBusy(false);}}
 return <section><h2>Co-signer invitations</h2><small>Active invitations plus the latest 25 records. Each invitation includes its full decision history.</small><p>Review consent does not sign a lease or create a guarantee. Co-signers have a separate, limited account experience.</p>{invitations.length?invitations.map(invitation=><article key={invitation.id}><strong>{invitation.invite_email}</strong><p>{invitation.state==='pending'&&new Date(invitation.expires_at)<new Date()?'Expired':invitation.state}</p><a href={`/cosigners/${invitation.id}`}>Private invitation link ↗</a>{isOwner&&active&&['pending','accepted'].includes(invitation.state)&&<button disabled={busy} onClick={()=>revoke(invitation)}>Revoke invitation</button>}</article>):<p>No co-signer invitations.</p>}{isOwner&&active&&<form onSubmit={invite}><label>Co-signer email<input type="email" required maxLength={254} value={email} disabled={busy} onChange={event=>{setEmail(event.target.value);setRequestId('');}}/></label><label><input type="checkbox" required checked={permission} disabled={busy} onChange={event=>{setPermission(event.target.checked);setRequestId('');}}/>I have permission to share my name and these property details with this person for co-signer review.</label><button disabled={busy||!permission}>{busy?'Creating…':'Create private invitation'}</button></form>}<p role="status">{notice}</p></section>;
}
export function CosignerResponse({id,state,version,active}:{id:string;state:string;version:number;active:boolean}){
 const router=useRouter();const [consent,setConsent]=useState(false),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const [retry,setRetry]=useState<{action:string;id:string}|null>(null);
 async function respond(action:string){const attempt=retry?.action===action?retry:{action,id:crypto.randomUUID()};setRetry(attempt);setBusy(true);setNotice('');try{const response=await fetch('/api/cosigners',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,version,action,request_id:attempt.id,consent})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error);}setNotice('Your response is recorded.');router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to record response.');}finally{setBusy(false);}}
 return <section><h2>Your review consent</h2><p>I agree to participate in Open House’s co-signer review for this application and permit the team to record my response. This does not sign a lease or guarantee; any legal commitment requires a separate agreement.</p>{active&&state==='pending'&&<><label><input type="checkbox" checked={consent} disabled={busy} onChange={event=>setConsent(event.target.checked)}/>I consent to participate in this review.</label><button disabled={busy||!consent} onClick={()=>respond('accept')}>Accept review invitation</button><button disabled={busy} onClick={()=>respond('decline')}>Decline invitation</button></>}{active&&state==='accepted'&&<button disabled={busy} onClick={()=>respond('withdraw')}>Withdraw review consent</button>}{!active&&<p>This invitation is expired or its application is closed.</p>}<p role="status">{notice}</p></section>;
}
