'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {documentReviewStatuses,documentReviewLabel} from '@/lib/applications/document-review';
export type DocumentReviewRecord={document_id:string;status:string;reason:string;version:number;updated_at:string};
export function DocumentReview({documentId,review,editable}:{documentId:string;review?:DocumentReviewRecord;editable:boolean}){
 type Event={id:string;old_status:string|null;new_status:string;reason:string;version:number;created_at:string};
 const [events,setEvents]=useState<Event[]>([]),[historyPage,setHistoryPage]=useState(0),[hasMore,setHasMore]=useState(false),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState('');
 async function history(){setHistoryBusy(true);setHistoryError('');try{const response=await fetch(`/api/staff/application-documents?id=${encodeURIComponent(documentId)}&page=${historyPage+1}`);const result=await response.json();if(!response.ok)throw new Error(result.error);setEvents(current=>[...current,...result.events]);setHistoryPage(current=>current+1);setHasMore(result.hasMore);}catch(error){setHistoryError(error instanceof Error?error.message:'Unable to load history.');}finally{setHistoryBusy(false);}}
 const router=useRouter();const [status,setStatus]=useState(''),[reason,setReason]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[requestId,setRequestId]=useState('');
 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setNotice('');const retry=requestId||crypto.randomUUID();setRequestId(retry);try{const response=await fetch('/api/staff/application-documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({document_id:documentId,request_id:retry,version:review?.version||0,status,reason})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error||'Unable to record review.');}setNotice('Document decision recorded.');router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to record review. Retry without changing your decision.');}finally{setBusy(false);}}
 return <section aria-label="Internal document review"><h4>{documentReviewLabel(review?.status||'')}</h4>{review&&<><p className="enquiry-message">{review.reason}</p><small>Recorded {new Date(review.updated_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</small></>}{editable&&<form onSubmit={submit}><label>Staff decision<select required value={status} disabled={busy} onChange={event=>{setStatus(event.target.value);setRequestId('');}}><option value="" disabled>Choose a decision</option>{documentReviewStatuses.map(value=><option key={value} value={value}>{documentReviewLabel(value)}</option>)}</select></label><label>Internal verification reason<textarea required minLength={5} maxLength={2000} value={reason} disabled={busy} onChange={event=>{setReason(event.target.value);setRequestId('');}}/></label><p>Confirm you have checked the document and its source. Keep unnecessary sensitive details out of these notes. Use the application’s shared information request to contact the applicant.</p><button disabled={busy||!status}>{busy?'Recording…':'Record document decision'}</button></form>}<p role="status">{notice}</p>{review&&<><h4>Internal decision history</h4>{events.map(event=><article key={event.id}><strong>{documentReviewLabel(event.new_status)}</strong><p className="enquiry-message">{event.reason}</p><small>Revision {event.version} · {new Date(event.created_at).toLocaleString("en-JM",{timeZone:"America/Jamaica"})}</small></article>)}{(!historyPage||hasMore||historyError)&&<button type="button" disabled={historyBusy} onClick={history}>{historyBusy?"Loading…":historyPage?"Load older decisions":"View decision history"}</button>}<p role="status">{historyError}</p></>}</section>;
}
