'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
export type StaffMember = {user_id:string;display_name:string|null;role:string};
export type Assignment = {enquiry_id:string;assignee_user_id:string|null;version:number};
type Note = {id:string;author_user_id:string;body:string;created_at:string};
type Event = {id:string;actor_user_id:string;previous_assignee_user_id:string|null;assignee_user_id:string|null;version:number;created_at:string};
export function StaffCollaboration({id,staff,assignment}:{id:string;staff:StaffMember[];assignment?:Assignment}){
 const router=useRouter();const [assignee,setAssignee]=useState(assignment?.assignee_user_id||'');const [version,setVersion]=useState(assignment?.version||0);const [body,setBody]=useState('');const [requestId,setRequestId]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [opened,setOpened]=useState(false);const [notes,setNotes]=useState<Note[]>([]);const [events,setEvents]=useState<Event[]>([]);const [page,setPage]=useState(0);const [more,setMore]=useState(false);
 const label=(userId:string|null)=>!userId?'Unassigned':staff.find(row=>row.user_id===userId)?.display_name||`${staff.find(row=>row.user_id===userId)?.role||'Former staff'} · ${userId.slice(0,8)}`;
 async function history(next=1){setBusy(true);setMessage('');try{const response=await fetch(`/api/staff/enquiries?id=${id}&page=${next}`,{cache:'no-store'});const result=await response.json();if(!response.ok)throw new Error(result.error);setNotes(current=>next===1?result.notes:[...current,...result.notes.filter((note:Note)=>!current.some(row=>row.id===note.id))]);setEvents(current=>next===1?result.events:[...current,...result.events.filter((event:Event)=>!current.some(row=>row.id===event.id))]);setPage(next);setMore(result.hasMore);setOpened(true);}catch(error){setMessage(error instanceof Error?error.message:'Unable to load history.');}finally{setBusy(false);}}
 async function save(action:'assign'|'note'){setBusy(true);setMessage('');const retryId=action==='note'?(requestId||crypto.randomUUID()):'';if(retryId)setRequestId(retryId);try{const response=await fetch('/api/staff/enquiries',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='assign'?{id,action,assignee:assignee||null,version}:{id,action,body,requestId:retryId})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error||'Unable to save.');}if(action==='assign')setVersion(result.version);else{setBody('');setRequestId('');}setMessage(action==='assign'?'Assignment saved.':'Private note saved.');router.refresh();if(opened)await history();}catch(error){setMessage(error instanceof Error?error.message:'Unable to save. Retry with the same content.');}finally{setBusy(false);}}
 return <section aria-label="Internal enquiry collaboration"><h3>Staff follow-up</h3><p>Internal to your organization. These notes are not sent to the prospect.</p><label>Assigned colleague<select value={assignee} disabled={busy} onChange={event=>setAssignee(event.target.value)}><option value="">Unassigned</option>{assignment?.assignee_user_id&&!staff.some(row=>row.user_id===assignment.assignee_user_id)&&<option value={assignment.assignee_user_id}>{label(assignment.assignee_user_id)}</option>}{staff.map(row=><option key={row.user_id} value={row.user_id}>{label(row.user_id)}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>save('assign')}>Save assignment</button><form onSubmit={event=>{event.preventDefault();void save('note');}}><label>Private follow-up note<textarea required minLength={2} maxLength={2000} value={body} disabled={busy} onChange={event=>{setBody(event.target.value);setRequestId('');}} placeholder="Record contact attempts and agreed next steps."/></label><button disabled={busy||body.trim().length<2}>Add private note</button></form><p role="status">{message}</p><button className="secondary" disabled={busy} onClick={()=>history()}> {opened?'Refresh staff history':'View staff history'}</button>{opened&&<><h4>Private notes</h4>{notes.map(note=><div key={note.id}><small>{label(note.author_user_id)} · {new Date(note.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})}</small><p className="enquiry-message">{note.body}</p></div>)}{!notes.length&&<p>No private notes yet.</p>}<h4>Assignment history</h4>{events.map(event=><p key={event.id}><small>{new Date(event.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · {label(event.actor_user_id)} assigned {label(event.assignee_user_id)} (previously {label(event.previous_assignee_user_id)}).</small></p>)}{!events.length&&<p>No assignment changes yet.</p>}{more&&<button disabled={busy} className="secondary" onClick={()=>history(page+1)}>Load older history</button>}</>}</section>;
}
