import {notFound,redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {SiteHeader} from '@/components/discovery/site-header';
import {CosignerResponse} from '@/components/applications/cosigners';
import {uuidPattern} from '@/lib/enquiries/validation';
export const dynamic='force-dynamic';
export default async function Cosigner({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const input=await searchParams;const raw=typeof input.page==='string'?input.page:'1';const page=/^\d{1,5}$/.test(raw)?Math.max(1,Number(raw)):1;
 const {id}=await params;if(!uuidPattern.test(id))notFound();const client=await createClient();const {data:{user},error:authError}=await client.auth.getUser();if(authError||!user?.email_confirmed_at)redirect('/sign-in');
 const {data:invitation,error}=await client.from('application_cosigners').select('id,application_id,applicant_user_id,recipient_user_id,invite_email,applicant_name_snapshot,title_snapshot,area_snapshot,rent_jmd_snapshot,state,version,expires_at').eq('id',id).maybeSingle();if(error)throw new Error('Unable to load invitation.');if(!invitation)notFound();
 const {data:active,error:activeError}=await client.rpc('cosigner_invitation_active',{p_id:id});if(activeError)throw new Error('Unable to load invitation availability.');
 const {count,error:countError}=await client.from('application_cosigner_events').select('id',{head:true,count:'exact'}).eq('cosigner_id',id);const pages=Math.max(1,Math.ceil((count||0)/25));if(!countError&&page>pages)redirect(`/cosigners/${id}${pages>1?`?page=${pages}`:''}`);
 const {data:events,error:historyError}=countError?{data:null,error:countError}:await client.from('application_cosigner_events').select('id,event_name,new_state,created_at').eq('cosigner_id',id).order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 const recipient=invitation.recipient_user_id===user.id||(!invitation.recipient_user_id&&invitation.invite_email===user.email?.toLowerCase());
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Private co-signer invitation</p><h1>{invitation.title_snapshot}</h1><p>{invitation.area_snapshot} · Advertised monthly rent at application: JMD {Number(invitation.rent_jmd_snapshot).toLocaleString('en-JM')}</p><p>Applicant: {invitation.applicant_name_snapshot}</p><p>Invitation: {invitation.state}</p>{recipient?<CosignerResponse key={`${id}-${invitation.version}`} id={id} state={invitation.state} version={invitation.version} active={active===true}/>:<p>This is the limited invitation preview. Only the invited verified recipient can consent.</p>}<h2>Invitation history</h2>{historyError?<p role="alert">Unable to load invitation history.</p>:events?.map(event=><article key={event.id}><strong>{event.event_name} · {event.new_state}</strong><p>{new Date(event.created_at).toLocaleString("en-JM",{timeZone:"America/Jamaica"})}</p></article>)}{!historyError&&pages>1&&<nav aria-label="Invitation history pages">{page>1&&<a href={`/cosigners/${id}?page=${page-1}`}>Newer decisions ←</a>}<span> Page {page} of {pages} </span>{page<pages&&<a href={`/cosigners/${id}?page=${page+1}`}>Older decisions →</a>}</nav>}<p><a href="/account">My account ↗</a>{invitation.applicant_user_id===user.id&&<> · <a href={`/applications/${invitation.application_id}`}>My application ↗</a></>}</p></section></main></>;
}
