import {redirect} from 'next/navigation';
import {createClient} from '@/lib/supabase/server';
import {SiteHeader} from '@/components/discovery/site-header';
import {OpenHouseRsvp} from '@/components/open-houses/rsvp-form';
export const dynamic='force-dynamic';
export default async function MyOpenHouses({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const client=await createClient(),{data:{user},error}=await client.auth.getUser();if(error||!user?.email_confirmed_at)redirect('/sign-in');const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const query=(head=false)=>client.from('open_house_rsvps').select('id,event_id,party_size,status,version,attendance_state,attended_count,title_snapshot,area_snapshot,starts_at_snapshot,ends_at_snapshot,open_house_events(title,starts_at,ends_at,status)',{head,count:'exact'}).eq('user_id',user.id);
 const counts=await query(true);if(counts.error)throw new Error('Unable to load your open house reservations.');const pages=Math.max(1,Math.ceil((counts.count||0)/25)),href=(next:number)=>`/account/open-houses?page=${next}`;if(page>pages)redirect(href(pages));const rows=await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 const arrival=rows.data?.length?await client.from('open_house_arrival').select('event_id,meeting_point,details,latitude,longitude').eq('is_active',true).in('event_id',rows.data.map(row=>row.event_id)):{data:[],error:null};
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Your open houses</p><h1>A place on your calendar.</h1><p>Confirm arrival details with the team before travelling. Approved meeting details appear for active RSVPs from 24 hours before the event until it ends.</p><a href="/open-houses">Explore upcoming open houses ↗</a>{rows.error?<p role="alert">Unable to load your reservations. Please refresh.</p>:rows.data?.length?rows.data.map(row=>{const event=Array.isArray(row.open_house_events)?row.open_house_events[0]:row.open_house_events,available=!!event&&event.status==='scheduled'&&new Date(event.starts_at).getTime()>Date.now()+15*60000;return <article key={row.id}><h2>{row.title_snapshot}</h2><p>{row.area_snapshot} · {new Date(row.starts_at_snapshot).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} – {new Date(row.ends_at_snapshot).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</p><small>Event details recorded when you first reserved.</small><p>{row.status==='cancelled'?'Your RSVP is cancelled.':available?'Your RSVP is active.':'This event is past, cancelled or unavailable. Contact the team before attending.'}</p>{row.status==='going'||available?<OpenHouseRsvp key={`${row.id}-${row.version}`} eventId={row.event_id} verified reservation={row} available={available}/>:null}{(()=>{const details=arrival.data?.find(item=>item.event_id===row.event_id);return details?<section><h3>Approved arrival instructions</h3><strong>{details.meeting_point}</strong><p className="enquiry-message">{details.details}</p>{details.latitude!==null&&details.longitude!==null&&<a href={`https://www.google.com/maps/dir/?api=1&destination=${details.latitude},${details.longitude}`} target="_blank" rel="noreferrer">Directions to the approved meeting point ↗</a>}</section>:row.status==='going'?<p>{arrival.error?'Arrival details are temporarily unavailable. Contact the team before travelling.':'Meeting details are not currently available. Check closer to the event or contact the team.'}</p>:null})()}<small>Reservation reference: {row.id}</small></article>}):<p>No open house reservations yet.</p>}<nav className="results-toolbar" aria-label="Reservation pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><a href="/account">Back to my account ↗</a></section></main></>;
}
