import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {notificationOrigin} from '@/lib/notifications/origin';
import {InvitationForm} from '@/components/staff/invitation-form';
export const dynamic='force-dynamic';
export default async function Invitations({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin']);if(!user)redirect('/sign-in');if(!membership)notFound();
 const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const count=await client.from('staff_invitations').select('id',{head:true,count:'exact'}).eq('organization_id',membership.organization_id);if(count.error)throw new Error('Unable to count staff invitations.');
 const pages=Math.max(1,Math.ceil((count.count||0)/25));if(page>pages)redirect(`/staff/invitations?page=${pages}`);
 const emailReady=!!process.env.SUPABASE_SECRET_KEY&&!!process.env.RESEND_API_KEY&&!!process.env.RESEND_FROM_EMAIL&&!!process.env.ENQUIRY_TO_EMAIL&&!!notificationOrigin(process.env.NEXT_PUBLIC_APP_URL)&&(process.env.CRON_SECRET?.length||0)>=32;
 const rows=await client.from('staff_invitations').select('id,invite_email,role,state,version,expires_at,created_at').eq('organization_id',membership.organization_id).order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Organization administration</p><h1>Invite your team.</h1><p>Invitations reserve an approved role for one verified email. Existing staff access is managed in the membership register.</p><p><a href="/staff/memberships">Team access →</a> · <a href="/staff/invitations/history">Private invitation history →</a></p><p><a href="/staff/notifications?family=staff_invitation">Invitation delivery monitor →</a></p><InvitationForm/>{rows.error?<p role="alert">Unable to load invitations. Please refresh.</p>:rows.data?.length?rows.data.map(row=><article className="staff-editor" key={`${row.id}-${row.version}`}><h2>{row.invite_email}</h2><p>{row.role} · {row.state}{row.state==='pending'&&new Date(row.expires_at).getTime()<=Date.now()?' (expired)':''}</p><p>Expires {new Date(row.expires_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</p><p>Recipient link: <a href={`/account/invitations/${row.id}`}>Review invitation →</a></p><p>The recipient can also find this invitation in their verified account. {emailReady?'The invitation email is queued; check the delivery monitor for worker and provider outcomes.':'The invitation email is queued. Worker configuration is incomplete, so use the recipient link until sending is configured.'}</p>{row.state==='pending'&&<InvitationForm invitation={row}/>}</article>):<p>No staff invitations yet.</p>}<nav className="results-toolbar" aria-label="Staff invitation pages">{page>1?<a href={`/staff/invitations?page=${page-1}`}>← Previous</a>:<span/>}<span>{count.count||0} invitations · Page {page} of {pages}</span>{page<pages?<a href={`/staff/invitations?page=${page+1}`}>Next →</a>:<span/>}</nav></section></main></>;
}
