import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
export const dynamic='force-dynamic';
export default async function WorkOrders({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const input=await searchParams;
 const states=['reported','triaged','assigned','scheduled','on_site','in_progress','completed','closed','cancelled'],state=typeof input.state==='string'&&states.includes(input.state)?input.state:'',page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const href=(next:number)=>`/staff/work-orders?page=${next}${state?`&state=${state}`:''}`;
 const query=(head=false)=>{let q=client.from('work_orders').select('id,title,priority,status,created_at',{head,count:'exact'}).eq('organization_id',membership.organization_id);if(state)q=q.eq('status',state);return q;};
 const count=await query(true);if(count.error)throw new Error('Unable to count work orders.');const pages=Math.max(1,Math.ceil((count.count||0)/25));if(page>pages)redirect(href(pages));
 const rows=await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Property maintenance</p><h1>Your work orders.</h1><p>Report issues against a managed property, then record triage and priority decisions.</p><p><a href="/workspace">Team workspace ↗</a> · <a href="/staff/properties">Choose a property to report an issue ↗</a> · <a href="/staff/contractors">Approved contractor register ↗</a></p><form className="filter-bar" action="/staff/work-orders"><label>State<select name="state" defaultValue={state}><option value="">All states</option>{states.map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><button className="secondary">Apply filter</button></form>{rows.error?<p role="alert">Unable to load work orders. Please refresh.</p>:rows.data?.length?rows.data.map(row=><article className="staff-editor" key={row.id}><h2><a href={`/staff/work-orders/${row.id}`}>{row.title}</a></h2><p>{row.status.replaceAll('_',' ')} · {row.priority} priority</p><small>{new Date(row.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</small></article>):<p>No work orders in this view.</p>}<nav className="results-toolbar" aria-label="Work order pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{count.count||0} work orders · Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav></section></main></>;
}
