import {redirect} from 'next/navigation';
import {SiteHeader} from '@/components/discovery/site-header';
import {catalogAccess} from '@/lib/staff/access';
import {applicationStatuses,applicationLabel} from '@/lib/applications/validation';
export const dynamic='force-dynamic';
export default async function Applications({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const input=await searchParams;const status=typeof input.status==='string'&&applicationStatuses.includes(input.status as typeof applicationStatuses[number])?input.status:'all';const raw=typeof input.page==='string'?input.page:'';const page=/^\d{1,6}$/.test(raw)?Math.max(1,Math.min(100000,Number(raw))):1;
 const href=(value:number)=>`/staff/applications?${new URLSearchParams({...status!=='all'?{status}:{},...value>1?{page:String(value)}:{}})}`;
 const {client,user,membership}=await catalogAccess(['admin','realtor','manager']);if(!user)redirect('/sign-in');if(!membership)return <><SiteHeader/><main className="account-layout"><h1>Staff access required.</h1><a href="/account">Return to your account</a></main></>;
 const query=(head=false)=>{let request=client.from('rental_applications').select('id,contact_name,title_snapshot,area_snapshot,status,created_at',{head,count:'exact'}).eq('organization_id',membership.organization_id);if(status!=='all')request=request.eq('status',status);return request;};
 const {count,error:countError}=await query(true);const totalPages=Math.max(1,Math.ceil((count||0)/25));if(!countError&&page>totalPages)redirect(href(totalPages));const {data,error}=countError?{data:null,error:countError}:await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1);
 return <><SiteHeader/><main className="listing-workspace"><section className="page-intro"><p className="eyebrow">STAFF RENTAL APPLICATIONS</p><h1>Help the next chapter begin.</h1><p>Review your organization’s applicants and record clear shared next steps.</p><a href="/staff/lease-reviews">Unanswered lease questions ↗</a> · <a href="/staff/enquiries">Enquiries ↗</a> · <a href="/staff/viewings">Viewings ↗</a></section><form className="filter-bar" action="/staff/applications"><label>Review stage<select name="status" defaultValue={status}><option value="all">All stages</option>{applicationStatuses.map(stage=><option key={stage} value={stage}>{applicationLabel(stage)}</option>)}</select></label><button>Filter applications</button><p>{count||0} matching applications</p></form>{error?<p role="alert">Unable to load applications. Please refresh.</p>:<div className="enquiry-grid">{data?.map(row=><article className="staff-editor" key={row.id}><p className="eyebrow">{applicationLabel(row.status)} · {row.area_snapshot}</p><h2>{row.contact_name}</h2><p>{row.title_snapshot}</p><a href={`/applications/${row.id}`}>Open private review ↗</a></article>)}{!data?.length&&<section className="empty-state"><h2>No applications in this view.</h2><p>Verified rental applications appear here for team review.</p></section>}</div>}{!error&&totalPages>1&&<nav className="results-toolbar" aria-label="Application result pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>Page {page} of {totalPages}</span>{page<totalPages?<a href={href(page+1)}>Next →</a>:<span/>}</nav>}</main></>;
}
