const fs = require('fs');
const ts = require('typescript');
const assert = require('node:assert/strict');
const moduleObject = { exports: {} };
new Function('exports','module', ts.transpileModule(fs.readFileSync('lib/staff/catalog-validation.ts','utf8'), { compilerOptions:{ module:ts.ModuleKind.CommonJS, target:ts.ScriptTarget.ES2022 } }).outputText)(moduleObject.exports,moduleObject);
const { catalogInput } = moduleObject.exports;
const draft = { kind:'listing',title:'Approved property',area:'Kingston',intent:'rent',property_type:'house',status:'draft',price_jmd:100,bedrooms:2,bathrooms:2,parking_spaces:1,description:'',photo_url:'',approximate_latitude:null,approximate_longitude:null,location_label:'' };
assert.equal(catalogInput(draft).record.photo_url,null);
for (const invalid of [ {status:'published'}, {price_jmd:NaN}, {price_jmd:-1}, {approximate_latitude:18}, {photo_url:'javascript:alert(1)'}, {photo_url:'https://user:password@example.com/photo'}, {parking_spaces:1.5}, {organization_id:'spoof',status:'confirmed'} ]) assert.throws(() => catalogInput({...draft,...invalid}));
const published = catalogInput({...draft,status:'published',description:'A complete approved property description.',photo_url:'https://example.com/approved.jpg',organization_id:'spoof'});
assert.equal(published.record.organization_id,undefined);
assert.equal(published.record.status,'published');
assert.throws(()=>catalogInput({...draft,status:'published',description:'Approved property description.',photo_url:'https://example.com/approved.jpg',price_jmd:0}));
const realtor = {kind:'realtor',request_id:'22334455-0000-4000-8000-000000000006',expected_revision:0,reason:'Approved profile release',approved:true,display_name:'Verified realtor',bio:'Approved professional biography.',photo_url:'',service_areas:['Kingston'],supported_intents:['rent'],communication_style:'thoughtful',guidance_style:'step-by-step',decision_pace:'considered',is_published:true};
assert.equal(catalogInput(realtor).record.is_published,true);
assert.throws(() => catalogInput({...realtor,supported_intents:['invented']}));
assert.throws(() => catalogInput({...realtor,service_areas:[]}));
for(const invalid of [{request_id:'bad'},{expected_revision:-1},{expected_revision:1.5},{reason:'tiny'},{approved:false}])assert.throws(()=>catalogInput({...realtor,...invalid}));
console.log('PASS: catalog publication requirements, numeric/coordinate bounds, URL safety, service eligibility and ignored ownership spoofing');
