'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export type Arrival={event_id:string;meeting_point:string;details:string;latitude:number|null;longitude:number|null;is_active:boolean;version:number};
export function ArrivalEditor({eventId,arrival,canSave}:{eventId:string;arrival:Arrival|null;canSave:boolean}){
 const router=useRouter(),request=useRef(''),actionRef=useRef(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reason,setReason]=useState(''),[approved,setApproved]=useState(false);const changed=()=>{request.current=''};
 async function submit(action:'save'|'withdraw',form?:HTMLFormElement){setBusy(true);setMessage('');if(!request.current||actionRef.current!==action){request.current=crypto.randomUUID();actionRef.current=action}const fields=form?new FormData(form):null,latitude=String(fields?.get('latitude')||''),longitude=String(fields?.get('longitude')||'');try{const response=await fetch('/api/staff/open-house-arrival',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_id:eventId,request_id:request.current,version:arrival?.version||0,action,meeting_point:fields?.get('meeting_point'),details:fields?.get('details'),latitude:latitude?Number(latitude):null,longitude:longitude?Number(longitude):null,reason,approved})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save instructions.');request.current='';setMessage(action==='withdraw'?'Arrival instructions withdrawn.':'Approved arrival instructions saved.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Connection interrupted. Retry with the same details.');}finally{setBusy(false)}}
 return <section><p>{arrival?`Revision ${arrival.version} · ${arrival.is_active?'Active':'Withdrawn'}`:'No arrival instructions approved yet.'}</p><p>Verified attendees with an active RSVP can read active instructions from 24 hours before the event until it ends. Public map pins remain approximate.</p>{canSave&&<form onSubmit={e=>{e.preventDefault();void submit('save',e.currentTarget)}} onChange={changed}><fieldset disabled={busy}><label>Approved meeting point<input name="meeting_point" required minLength={3} maxLength={250} defaultValue={arrival?.meeting_point||''}/></label><label>Arrival and access instructions<textarea name="details" required minLength={10} maxLength={2000} defaultValue={arrival?.details||''}/></label><label>Exact latitude (optional)<input name="latitude" type="number" step="any" min="-90" max="90" defaultValue={arrival?.latitude??''}/></label><label>Exact longitude (optional)<input name="longitude" type="number" step="any" min="-180" max="180" defaultValue={arrival?.longitude??''}/></label><label><input type="checkbox" checked={approved} required onChange={e=>setApproved(e.target.checked)}/> I confirm these directions and location are approved for reserved attendees.</label><button disabled={!approved||reason.trim().length<5}>{busy?'Saving…':'Save approved instructions'}</button></fieldset></form>}<label>Change / withdrawal reason<textarea required minLength={5} maxLength={500} value={reason} disabled={busy} onChange={e=>{setReason(e.target.value);changed()}}/></label>{arrival?.is_active&&<button className="secondary" disabled={busy||reason.trim().length<5} onClick={()=>void submit('withdraw')}>Withdraw instructions</button>}<p role="status">{message}</p></section>;
}
