'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export function AttendanceEditor({id,rsvpVersion,attendanceVersion,partySize,currentState,attendedCount,startsAt,endsAt,eventStatus}:{id:string;rsvpVersion:number;attendanceVersion:number;partySize:number;currentState:string;attendedCount:number;startsAt:string;endsAt:string;eventStatus:string}){
 const router=useRouter(),request=useRef(''),[state,setState]=useState(eventStatus==='cancelled'?'unrecorded':currentState==='unrecorded'?'attended':currentState),[count,setCount]=useState(attendedCount||partySize),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');const now=Date.now(),withinWindow=now>=Date.parse(startsAt)-30*60000&&now<=Date.parse(endsAt)+7*86400000;
 if(!withinWindow)return <p>Attendance can be recorded from 30 minutes before the event until seven days after it ends.</p>;
 if(eventStatus==='cancelled'&&currentState==='unrecorded')return <p>Attendance cannot be recorded for a cancelled event.</p>;
 async function save(){setBusy(true);setMessage('');if(!request.current)request.current=crypto.randomUUID();try{const response=await fetch('/api/staff/open-house-attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({rsvp_id:id,request_id:request.current,rsvp_version:rsvpVersion,attendance_version:attendanceVersion,state,attended_count:state==='attended'?count:0,reason})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to record attendance.');request.current='';setMessage('Attendance recorded with a staff audit.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Connection interrupted. Retry with the same details.');}finally{setBusy(false);}}
 return <form onSubmit={e=>{e.preventDefault();void save()}}><label>Attendance<select value={state} disabled={busy} onChange={e=>{setState(e.target.value);request.current=''}}>{eventStatus!=='cancelled'&&<option value="attended">Attended</option>}{eventStatus!=='cancelled'&&now>=Date.parse(endsAt)&&<option value="no_show">Did not attend</option>}{currentState!=='unrecorded'&&<option value="unrecorded">Clear incorrect attendance</option>}</select></label>{state==='attended'&&<label>Attendees present<select value={count} disabled={busy} onChange={e=>{setCount(Number(e.target.value));request.current=''}}>{Array.from({length:partySize},(_,i)=>i+1).map(n=><option key={n} value={n}>{n}</option>)}</select></label>}<label>Staff record / correction reason<textarea required minLength={5} maxLength={500} disabled={busy} value={reason} onChange={e=>{setReason(e.target.value);request.current=''}} placeholder="Record what was confirmed at the event."/></label><button disabled={busy||reason.trim().length<5}>{busy?'Recording…':'Save attendance'}</button><p role="status">{message}</p></form>;
}
