'use client';
import {useMemo,useState} from 'react';
import {PropertyMap} from '@/components/discovery/property-map';
import type {PublishedListing} from '@/components/discovery/live-catalog';
import {OpenHouseRsvp,type OwnRsvp} from './rsvp-form';
import type {Home} from '@/lib/discovery/data';
export type PublicOpenHouse={id:string;title:string;starts_at:string;ends_at:string;capacity:number|null;listing:PublishedListing};
export function OpenHouseBrowser({events,verified,reservations}:{events:PublicOpenHouse[];verified:boolean;reservations:OwnRsvp[]}){
 const [selected,setSelected]=useState(''),[view,setView]=useState<'split'|'list'|'map'>('split');
 const mapped=useMemo(()=>events.filter(e=>e.listing.approximate_latitude!==null&&e.listing.approximate_longitude!==null).map(e=>({id:e.id,title:e.title,area:e.listing.area,intent:e.listing.intent as 'rent'|'sale',price:Number(e.listing.price_jmd),beds:Number(e.listing.bedrooms),baths:Number(e.listing.bathrooms),parking:e.listing.parking_spaces,size:e.listing.size_sq_ft||0,lat:e.listing.approximate_latitude!,lng:e.listing.approximate_longitude!,photo:'',description:''} satisfies Home)),[events]);
 const current=events.find(e=>e.id===selected),time=(value:string)=>new Date(value).toLocaleString('en-JM',{timeZone:'America/Jamaica',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
 return <><div className="results-toolbar"><span>{events.length} events on this page · {mapped.length} approximate map locations</span><div className="segmented">{(['split','list','map'] as const).map(mode=><button key={mode} aria-pressed={view===mode} onClick={()=>setView(mode)}>{mode==='split'?'List + map':mode==='list'?'List':'Map'}</button>)}</div></div><div className={`results-layout view-${view}`}>
 {view!=='map'&&<div className="results-cards">{events.map(event=><article key={event.id} className={`listing-card ${selected===event.id?'is-selected':''}`}>{event.listing.photo_url&&<img className="live-property-photo" src={event.listing.photo_url} alt={event.listing.title} loading="lazy" referrerPolicy="no-referrer"/>}<div className="listing-content"><p className="eyebrow">{event.listing.area} · Open house</p><h2>{event.title}</h2><p><time dateTime={event.starts_at}>{time(event.starts_at)}</time> – <time dateTime={event.ends_at}>{time(event.ends_at)}</time><br/>Jamaica time</p><h3><a href={`/listings/${event.listing.id}`}>{event.listing.title}</a></h3><p>JMD {Number(event.listing.price_jmd).toLocaleString('en-JM')}{event.listing.intent==='rent'?' / month':''}</p><OpenHouseRsvp key={`${event.id}-${reservations.find(r=>r.event_id===event.id)?.version||0}`} eventId={event.id} verified={verified} reservation={reservations.find(r=>r.event_id===event.id)}/><a href={`/listings/${event.listing.id}#enquiry`}>Ask about attending ↗</a>{mapped.some(home=>home.id===event.id)&&<button className="secondary" onClick={()=>{setSelected(event.id);setView('split')}}>Show on map</button>}</div></article>)}{!events.length&&<div className="empty-state"><h2>No upcoming open houses match.</h2><p>Explore available homes or ask a realtor about a private viewing.</p><a href="/listings">Browse properties ↗</a></div>}</div>}
 {view!=='list'&&<aside className="results-map"><PropertyMap homes={mapped} selected={selected} onSelect={setSelected} demo={false}/>{current&&<div className="map-selection" role="status"><strong>{current.title}</strong><p>{current.listing.location_label||current.listing.area} · {time(current.starts_at)}</p><a href={`/listings/${current.listing.id}`}>View property ↗</a></div>}{events.length>mapped.length&&<p>{events.length-mapped.length} events have no public map location. They remain available in the list.</p>}</aside>}
 </div></>;
}
