'use client';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
export type OwnRsvp={event_id:string;party_size:number;status:string;version:number;attendance_state?:string;attended_count?:number};
export function OpenHouseRsvp({eventId,verified,reservation,available=true}:{eventId:string;verified:boolean;reservation?:OwnRsvp;available?:boolean}){
 const router=useRouter(),request=useRef(''),requestAction=useRef(''),[party,setParty]=useState(reservation?.party_size||1),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function submit(action:'reserve'|'cancel'){
  setBusy(true);setMessage('');if(!request.current||requestAction.current!==action){request.current=crypto.randomUUID();requestAction.current=action;}
  try{const response=await fetch('/api/open-house-rsvps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event_id:eventId,request_id:request.current,version:reservation?.version||0,action,party_size:action==='reserve'?party:null,consent:action==='reserve'?consent:null})});const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save reservation.');request.current='';setMessage(action==='cancel'?'Your reservation is cancelled.':'Your place is reserved. Ask the team to confirm arrival details.');router.refresh();}catch(error){setMessage(error instanceof Error?error.message:'Connection interrupted. Retry with the same details.');}finally{setBusy(false);}
 }
 if(!verified)return <p><a href="/sign-in">Sign in with a verified email to RSVP ↗</a></p>;
 if(reservation?.attendance_state&&reservation.attendance_state!=='unrecorded')return <p>Attendance recorded: {reservation.attendance_state==='attended'?`${reservation.attended_count} attended`:'did not attend'}. Contact the team to correct this record before changing your RSVP.</p>;
 return <section aria-label="Open house reservation"><p>{reservation?.status==='going'?`Your reservation: ${reservation.party_size} attendee${reservation.party_size===1?'':'s'}.`:'Reserve a place for yourself and your guests.'}</p>{available&&<form onSubmit={e=>{e.preventDefault();void submit('reserve')}}><label>Attendees, including you<select value={party} disabled={busy} onChange={e=>{setParty(Number(e.target.value));request.current=''}}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n}</option>)}</select></label><label><input type="checkbox" checked={consent} required disabled={busy} onChange={e=>{setConsent(e.target.checked);request.current=''}}/> I agree that Open House may contact me about attending this event.</label><button disabled={busy||!consent}>{busy?'Saving…':reservation?.status==='going'?'Update my RSVP':'Reserve my place'}</button></form>}{reservation?.status==='going'&&<button className="secondary" disabled={busy} onClick={()=>void submit('cancel')}>Cancel my RSVP</button>}<p role="status">{message}</p><a href="/account">My account ↗</a></section>;
}
