'use client';
import {useState,type FormEvent} from 'react';
import {useRouter} from 'next/navigation';
export function OpenHouseCreate({listings}:{listings:{id:string;title:string}[]}){
 const router=useRouter(),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[requestId,setRequestId]=useState('');
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),retry=requestId||crypto.randomUUID();setRequestId(retry);setBusy(true);setNotice('');try{const response=await fetch('/api/staff/open-houses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',request_id:retry,version:0,listing_id:form.get('listing'),title:form.get('title'),starts_at:new Date(`${form.get('start')}-05:00`).toISOString(),ends_at:new Date(`${form.get('end')}-05:00`).toISOString(),capacity:Number(form.get('capacity')),approved:form.get('approved')==='on'})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error);}setNotice('Open house scheduled. Public discovery and RSVP handling are being completed.');router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to schedule. Retry unchanged.');}finally{setBusy(false);}}
 return <section><h2>Schedule an open house</h2><p>You are recorded as the host. Choose a published listing; the property and host must have no overlapping open house or viewing slot. All entered times are Jamaica time.</p>{!listings.length?<p>No published listings on this page. Publish approved property content first.</p>:<form onSubmit={submit} onChange={()=>setRequestId('')}><fieldset disabled={busy}><label>Published property<select name="listing" required>{listings.map(listing=><option key={listing.id} value={listing.id}>{listing.title}</option>)}</select></label><label>Approved public event title<input name="title" required minLength={3} maxLength={160}/></label><label>Start (Jamaica)<input name="start" type="datetime-local" required/></label><label>End (Jamaica)<input name="end" type="datetime-local" required/></label><label>Maximum visitors<input name="capacity" type="number" required min={1} max={250} step={1}/></label><label><input name="approved" type="checkbox" required/>The event title, time, capacity and property access have been approved.</label><button>{busy?'Scheduling…':'Schedule open house'}</button></fieldset></form>}<p role="status">{notice}</p></section>;
}
export function OpenHouseResolve({id,version,ended}:{id:string;version:number;ended:boolean}){
 const router=useRouter(),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[retry,setRetry]=useState<{action:string;id:string}|null>(null);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),action=(event.nativeEvent as SubmitEvent).submitter?.getAttribute('value');if(!action)return;const attempt=retry?.action===action?retry:{action,id:crypto.randomUUID()};setRetry(attempt);setBusy(true);setNotice('');try{const response=await fetch('/api/staff/open-houses',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,event_id:id,version,request_id:attempt.id,reason:form.get('reason')})});const result=await response.json();if(!response.ok){if(response.status===409)router.refresh();throw new Error(result.error);}setNotice(`Event ${result.status}.`);router.refresh();}catch(error){setNotice(error instanceof Error?error.message:'Unable to resolve.');}finally{setBusy(false);}}
 return <form onSubmit={submit} onChange={()=>setRetry(null)}><fieldset disabled={busy}><label>Resolution reason<textarea name="reason" required minLength={5} maxLength={500}/></label><button type="submit" value="cancel">Cancel event</button>{ended&&<button type="submit" value="complete">Mark event complete</button>}</fieldset><p role="status">{notice}</p></form>;
}
