import {InvoiceIntake} from '@/components/finance/invoice-intake';
import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {WorkOrderEditor} from '@/components/staff/work-order-editor';
export const dynamic='force-dynamic';
export default async function WorkOrder({params,searchParams}:{params:Promise<{workOrderId:string}>;searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const {workOrderId}=await params;
 if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(workOrderId))notFound();
 const order=await client.from('work_orders').select('id,title,description,priority,status,revision,property_id,unit_id,reported_by,created_at').eq('id',workOrderId).eq('organization_id',membership.organization_id).maybeSingle();if(order.error)throw new Error('Unable to load work order.');if(!order.data)notFound();
 const property=await client.from('properties').select('id,name').eq('id',order.data.property_id).eq('organization_id',membership.organization_id).maybeSingle();if(property.error||!property.data)throw new Error('Unable to verify work order property.');
 const input=await searchParams,page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1,href=(next:number)=>`/staff/work-orders/${workOrderId}?page=${next}`;
 const query=(head=false)=>client.from('work_order_changes').select('id,actor_user_id,action,previous_status,new_status,previous_priority,new_priority,version,reason,created_at',{head,count:'exact'}).eq('organization_id',membership.organization_id).eq('work_order_id',workOrderId);
 const count=await query(true);if(count.error)throw new Error('Unable to count work order history.');const pages=Math.max(1,Math.ceil((count.count||0)/25));if(page>pages)redirect(href(pages));
 const history=await query().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1),record=order.data;
 const preventive=await client.from('preventive_maintenance_occurrences').select('plan_id,due_on').eq('work_order_id',record.id).eq('organization_id',membership.organization_id).maybeSingle();
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Private maintenance record</p><h1>{record.title}</h1><p>{record.status.replaceAll('_',' ')} · {record.priority} priority · Revision {record.revision}</p><p className="enquiry-message">{record.description}</p><p><a href={`/staff/properties?property=${record.property_id}`}>Managed property ↗</a>{record.unit_id&&<small> · Unit reference: {record.unit_id}</small>}</p>{preventive.error?<p role="alert">Unable to load preventive source.</p>:preventive.data&&<p>Preventive occurrence · Due {preventive.data.due_on} · <a href={`/staff/preventive-plans/${preventive.data.plan_id}`}>Source plan →</a> · <a href={`/staff/preventive-plans/${preventive.data.plan_id}/history`}>Approved occurrence history →</a></p>}<small>Reported by: {record.reported_by||'Baseline record'}</small>{['reported','triaged'].includes(record.status)&&record.revision>0&&<><WorkOrderEditor key={`${record.id}-triage-${record.revision}`} action="triage" workOrderId={record.id} version={record.revision} priority={record.priority}/><WorkOrderEditor key={`${record.id}-cancel-${record.revision}`} action="cancel" workOrderId={record.id} version={record.revision}/></>}<p><a href={`/staff/work-orders/${record.id}/offers`}>Contractor work offer ↗</a> · <a href={`/staff/work-orders/${record.id}/offers/history`}>Offer history ↗</a> · <a href={`/staff/work-orders/${record.id}/visits`}>Visit scheduling ↗</a> · <a href={`/staff/work-orders/${record.id}/presence`}>Arrival and departure history ↗</a> · <a href={`/staff/work-orders/${record.id}/completion`}>Completion review ↗</a></p><InvoiceIntake property={property.data} workOrder={{id:order.data.id,title:order.data.title}}/><h2>Work order history</h2>{history.error?<p role="alert">Unable to load history. Please refresh.</p>:history.data?.length?history.data.map(event=><article className="staff-editor" key={event.id}><h3>{event.action} · Revision {event.version}</h3><p>{event.previous_status||'New issue'} → {event.new_status} · {event.previous_priority||'No priority'} → {event.new_priority}</p><p className="enquiry-message">{event.reason}</p><small>Actor: {event.actor_user_id}<br/>{new Date(event.created_at).toLocaleString('en-JM',{timeZone:'America/Jamaica'})} · Jamaica time</small></article>):<p>No audited changes yet.</p>}<nav className="results-toolbar" aria-label="Work order history pages">{page>1?<a href={href(page-1)}>← Previous</a>:<span/>}<span>{count.count||0} changes · Page {page} of {pages}</span>{page<pages?<a href={href(page+1)}>Next →</a>:<span/>}</nav><a href="/staff/work-orders">Back to work orders ↗</a></section></main></>;
}
