import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
export const dynamic='force-dynamic';
export default async function Plans({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const {client,user,membership}=await catalogAccess(['admin','manager']);if(!user)redirect('/sign-in');if(!membership)notFound();const input=await searchParams,state=typeof input.state==='string'?input.state:'active';if(!['active','paused','retired'].includes(state))notFound();const page=typeof input.page==='string'&&/^\d{1,5}$/.test(input.page)?Math.max(1,Number(input.page)):1;
 const query=(head=false)=>client.from('preventive_maintenance_plans').select('id,title,next_due_on,interval_days,state,version',{head,count:'exact'}).eq('organization_id',membership.organization_id).eq('state',state),href=(next:number)=>`/staff/preventive-plans?${new URLSearchParams({state,page:String(next)})}`;
 const {count,error:countError}=await query(true);if(countError)throw new Error('Unable to count preventive plans.');const pages=Math.max(1,Math.ceil((count||0)/25));if(page>pages)redirect(href(pages));const {data:plans,error}=await query().order('next_due_on').order('id').range((page-1)*25,page*25-1);if(error)throw new Error('Unable to load preventive plans.');
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Management</p><h1>Preventive maintenance</h1><p>Review due plans and issue one work order per scheduled occurrence.</p><a href="/staff/properties">Choose a managed property to create a plan →</a><nav aria-label="Plan states">{['active','paused','retired'].map(value=><a key={value} href={`/staff/preventive-plans?state=${value}`} aria-current={state===value?'page':undefined}>{value} </a>)}</nav>{plans?.length?plans.map(plan=><article key={plan.id}><h2><a href={`/staff/preventive-plans/${plan.id}`}>{plan.title}</a></h2><p>Due {plan.next_due_on} · Every {plan.interval_days} days · Revision {plan.version}</p></article>):<p>No {state} plans.</p>}<nav aria-label="Preventive plan pages">{page>1&&<a href={href(page-1)}>← Previous</a>}<span> Page {page} of {pages} </span>{page<pages&&<a href={href(page+1)}>Next →</a>}</nav></section></main></>;
}
