import {SiteHeader} from '@/components/discovery/site-header';
import {homes,realtors} from '@/lib/discovery/data';
import {roles} from '@/lib/demo/model';
export const metadata={title:'Demo people & workflows | Open House Realty',robots:{index:false,follow:false}};
const records=[
 {title:'Prospects & applications',name:'Daniel Brooks · demo prospect',detail:'Try a viewing request, application, approval and move-in journey.',href:'/demo?role=prospect'},
 {title:'Residents & tenancy',name:'Leslie Morgan · demo resident',detail:'Explore a sample tenancy, maintenance request, rent balance and documents.',href:'/demo?role=resident'},
 {title:'Sellers & landlords',name:'Olivia Grant · demo seller',detail:'Follow listing preparation, a marketing proposal and simulated publishing.',href:'/demo?role=seller'},
 {title:'Contractors & work orders',name:'Taylor James · demo contractor',detail:'Follow an assigned maintenance job, access and completion steps.',href:'/demo?role=contractor'},
 {title:'Security & visitor access',name:'Sam Clarke · demo security staff',detail:'Review an expected contractor and simulate arrival and departure.',href:'/demo?role=security'},
 {title:'Finance & documents',name:'Casey Lewis · demo finance staff',detail:'Explore sample rent, invoices, cheque custody and tax tracking. No funds move.',href:'/demo?role=finance'},
 {title:'Owners & portfolios',name:'Robin Bennett · demo owner',detail:'Explore illustrative occupancy, collections and operating activity.',href:'/demo?role=owner'},
 {title:'Property management',name:'Chris Reid · demo manager',detail:'Connect leasing, maintenance, assignments and portfolio activity.',href:'/demo?role=manager'}
];
export default function DemoExplore(){return <><SiteHeader/><main><section className="page-intro"><p className="eyebrow">OPEN HOUSE · DEMO EXPERIENCE</p><h1>Meet the people.<br/>Explore the possibilities.</h1><p>A connected demonstration with fictional people, properties and operational records. Every item on this page is demo content.</p><p className="inventory-note">Actions run in a local simulation. No real application, booking, payment, legal signing or staff assignment is made.</p></section><section className="marketplace"><div className="section-heading"><div><p className="eyebrow">START YOUR SEARCH</p><h2>Properties and people.</h2></div></div><div className="listing-grid"><article className="listing-card"><div className="listing-content"><p className="eyebrow">DEMO INVENTORY</p><h3>{homes.length} fictional properties</h3><p>Sales and rentals across Jamaica, with illustrative photography and approximate map pins.</p><a className="button-link" href="/demo/listings">Explore properties &amp; maps ↗</a></div></article><article className="listing-card"><div className="listing-content"><p className="eyebrow">DEMO REALTORS</p><h3>{realtors.length} working styles</h3><p>Meet fictional realtors and try matching by area, communication, guidance and decision pace.</p><a className="button-link" href="/demo/realtors">Meet your demo match ↗</a></div></article><article className="listing-card"><div className="listing-content"><p className="eyebrow">DEMO ROLE SWITCHER</p><h3>{roles.length} connected perspectives</h3><p>Switch roles to follow how a prospect journey and a maintenance request move through the team.</p><a className="button-link" href="/demo">Choose a demo profile ↗</a></div></article></div></section><section className="marketplace"><div className="section-heading"><div><p className="eyebrow">FICTIONAL PEOPLE · SAMPLE RECORDS</p><h2>Life around the property.</h2></div></div><div className="listing-grid">{records.map(record=><article className="listing-card" key={record.href}><div className="listing-content"><p className="eyebrow">DEMO EXPERIENCE</p><h3>{record.title}</h3><strong>{record.name}</strong><p>{record.detail}</p><a className="button-link" href={record.href}>Explore this perspective ↗</a></div></article>)}</div></section></main></>}
