create or replace function private.approve_rental_application(p_application_id uuid,p_request_id uuid,p_expected_version integer,p_policy_version integer,p_reason text,p_evidence_reference text,p_eligibility_checked boolean,p_availability_checked boolean) returns jsonb language plpgsql security definer set search_path='' as $$
declare caller uuid:=auth.uid();org uuid:=private.verified_enquiry_staff_organization();application public.rental_applications;policy public.rental_approval_policies;listing public.listings;existing public.rental_approval_decisions;decision uuid;role_name text;documents jsonb;cosigners jsonb;
begin
 if org is null then raise exception 'Verified organization reviewer required' using errcode='42501';end if;
 if p_request_id is null or p_expected_version is null or p_expected_version<1 or p_expected_version>=2147483647 or p_policy_version is null or p_policy_version<1 or p_reason is null or length(trim(p_reason)) not between 5 and 2000 or p_evidence_reference is null or length(trim(p_evidence_reference)) not between 5 and 500 or p_eligibility_checked is distinct from true or p_availability_checked is distinct from true then raise exception 'Completed business checks and shared decision reason required' using errcode='22023';end if;
 perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended(org::text,115));
 select * into application from public.rental_applications where id=p_application_id for update;
 if application.id is null or application.organization_id<>org or application.user_id=caller or exists(select 1 from public.application_cosigners where application_id=application.id and recipient_user_id=caller and state='accepted') then raise exception 'Independent organization approver required' using errcode='42501';end if;
 select * into existing from public.rental_approval_decisions where application_id=application.id and approved_by=caller and request_id=p_request_id;
 if existing.id is not null then if existing.application_version<>p_expected_version+1 or existing.reason<>trim(p_reason) or existing.evidence_reference<>trim(p_evidence_reference) or not exists(select 1 from public.rental_approval_policies where id=existing.policy_id and version=p_policy_version) then raise exception 'Request ID already used' using errcode='22023';end if;return jsonb_build_object('status',application.status,'version',application.version);end if;
 select * into policy from public.rental_approval_policies where organization_id=org order by version desc limit 1;
 if policy.id is null then raise exception 'Approved business policy not configured' using errcode='22023';end if;
 if policy.version<>p_policy_version or application.version<>p_expected_version then raise exception 'Application or policy changed; refresh' using errcode='40001';end if;
 select role into role_name from public.staff_accounts where user_id=caller;
 if not role_name=any(policy.approver_roles) then raise exception 'Role not authorized by business approval policy' using errcode='42501';end if;
 if application.status<>'under_review' or application.desired_move_in<(now() at time zone 'America/Jamaica')::date then raise exception 'Application review or move-in date incomplete' using errcode='22023';end if;
 if exists(select 1 from unnest(policy.required_document_kinds) kind where not exists(select 1 from public.application_documents d join public.application_document_reviews r on r.document_id=d.id where d.application_id=application.id and d.organization_id=org and d.kind=kind and d.state='uploaded' and r.status='verified' and r.file_sha256=d.sha256 and r.reviewer_user_id<>application.user_id and not exists(select 1 from public.application_cosigners c where c.application_id=application.id and c.recipient_user_id=r.reviewer_user_id and c.state='accepted'))) or exists(select 1 from public.application_documents d join public.application_document_reviews r on r.document_id=d.id where d.application_id=application.id and d.state='uploaded' and r.status in('needs_info','not_accepted')) then raise exception 'Required document evidence not verified or issues remain open' using errcode='22023';end if;
 if exists(select 1 from public.application_cosigners where application_id=application.id and state='pending' and expires_at>now()) or (select count(*) from public.application_cosigners c join auth.users u on u.id=c.recipient_user_id where c.application_id=application.id and c.state='accepted' and c.consent_version=1 and u.email_confirmed_at is not null)<policy.required_cosigners then raise exception 'Required co-signer review consent incomplete' using errcode='22023';end if;
 select * into listing from public.listings where id=application.listing_id for update;
 if listing.organization_id is distinct from org or listing.intent<>'rent' or listing.status<>'published' or listing.price_jmd<>application.rent_jmd_snapshot or listing.unit_id is null then raise exception 'Published rental terms and managed unit required' using errcode='22023';end if;
 perform 1 from public.units u join public.properties p on p.id=u.property_id where u.id=listing.unit_id and p.id=listing.property_id and p.organization_id=org for update of u;
 if not found then raise exception 'Managed unit unavailable' using errcode='22023';end if;
 if exists(select 1 from public.rental_unit_reservations where unit_id=listing.unit_id and state in('held','converted')) then raise exception 'Unit already reserved or occupied' using errcode='23505';end if;
 select coalesce(jsonb_agg(jsonb_build_object('document_id',d.id,'sha256',d.sha256,'review_version',r.version,'reviewer',r.reviewer_user_id)), '[]'::jsonb) into documents from public.application_documents d join public.application_document_reviews r on r.document_id=d.id where d.application_id=application.id and d.state='uploaded' and r.status='verified' and r.file_sha256=d.sha256;
 select coalesce(jsonb_agg(jsonb_build_object('cosigner_id',id,'recipient_user_id',recipient_user_id,'version',version,'consented_at',consented_at,'consent_version',consent_version)), '[]'::jsonb) into cosigners from public.application_cosigners where application_id=application.id and state='accepted';
 insert into public.rental_approval_decisions(application_id,organization_id,policy_id,listing_id,unit_id,approved_by,request_id,application_version,reason,evidence_reference,document_snapshot,cosigner_snapshot) values(application.id,org,policy.id,listing.id,listing.unit_id,caller,p_request_id,application.version+1,trim(p_reason),trim(p_evidence_reference),documents,cosigners) returning id into decision;
 insert into public.rental_unit_reservations(decision_id,application_id,organization_id,listing_id,unit_id) values(decision,application.id,org,listing.id,listing.unit_id);
 update public.listings set status=case when id=listing.id then 'under_offer' else 'paused' end,updated_at=now() where unit_id=listing.unit_id and organization_id=org and status='published';
 update public.rental_applications set status='approved',version=version+1,updated_at=now() where id=application.id;
 perform private.record_application_event(application.id,p_request_id,'approved',application.status,trim(p_reason));
 return jsonb_build_object('status','approved','version',application.version+1);
end $$;

create function private.guard_reserved_listing() returns trigger language plpgsql security invoker set search_path='' as $$
begin
 if tg_op='UPDATE' and exists(select 1 from public.rental_unit_reservations where listing_id=old.id and state in('held','converted')) and (new.unit_id is distinct from old.unit_id or new.property_id is distinct from old.property_id or new.organization_id is distinct from old.organization_id) then raise exception 'Reserved listing property/unit linkage is immutable' using errcode='22023';end if;
 if new.status='published' and new.unit_id is not null and exists(select 1 from public.rental_unit_reservations where unit_id=new.unit_id and state in('held','converted')) then raise exception 'Reserved or occupied unit cannot be advertised as available' using errcode='23505';end if;
 return new;
end $$;
revoke all on function private.guard_reserved_listing() from public,anon,authenticated;
create trigger guard_reserved_listing before insert or update of property_id,unit_id,organization_id,status on public.listings for each row execute function private.guard_reserved_listing();
