import {notFound,redirect} from 'next/navigation';
import {catalogAccess} from '@/lib/staff/access';
import {SiteHeader} from '@/components/discovery/site-header';
import {LeaseTemplateEditor} from '@/components/leases/template-editor';
import {TemplateDocumentFiles} from '@/components/leases/template-document-files';
export const dynamic='force-dynamic';
export default async function Templates({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const params=await searchParams,key=typeof params.key==='string'?params.key:'';if(params.key!==undefined&&!/^[a-z][a-z0-9_-]{2,63}$/.test(key))notFound();const raw=typeof params.page==='string'?params.page:'1',page=/^\d{1,5}$/.test(raw)?Math.max(1,Number(raw)):1;
 const {client,user,membership}=await catalogAccess(['admin']);if(!user)redirect('/sign-in');if(!membership)notFound();
 const base=()=>{let query=client.from('approved_lease_templates').select('id,template_key,version,title,source_reference,content_sha256,created_at').eq('organization_id',membership.organization_id);if(key)query=query.eq('template_key',key);return query;};
 let countQuery=client.from('approved_lease_templates').select('id',{head:true,count:'exact'}).eq('organization_id',membership.organization_id);if(key)countQuery=countQuery.eq('template_key',key);const {count,error:countError}=await countQuery;if(countError)throw new Error('Unable to load template count.');const pages=Math.max(1,Math.ceil((count||0)/25)),href=(n:number)=>`/staff/lease-templates?${new URLSearchParams({...key?{key}:{},page:String(n)})}`;if(page>pages)redirect(href(pages));
 const [{data:templates,error},{data:current,error:currentError}]=await Promise.all([base().order('created_at',{ascending:false}).order('id').range((page-1)*25,page*25-1),key?base().order('version',{ascending:false}).limit(1).maybeSingle():Promise.resolve({data:null,error:null})]);if(error||currentError)throw new Error('Unable to load approved template references.');
 const {data:documents,error:documentError}=templates?.length?await client.from('lease_template_documents').select('id,template_id,user_id,file_name,state,expires_at').eq('organization_id',membership.organization_id).in('template_id',templates.map(template=>template.id)).or(`state.eq.certified,and(state.eq.reserved,expires_at.gt.${new Date().toISOString()})`).order('created_at',{ascending:false}).limit(100):{data:[],error:null};if(documentError)throw new Error('Unable to load legal document status.');
 const secret=process.env.SUPABASE_SECRET_KEY,enabled=!!secret&&secret.length>=30&&!secret.includes('YOUR-');
 return <><SiteHeader/><main className="account-layout"><section className="account-card"><p className="eyebrow">Organization administrator</p><h1>Approved lease template references</h1><p>Register only business-approved source documents. Each version is immutable. Signing-provider setup and document verification are separate steps.</p><LeaseTemplateEditor key={`${key}-${current?.version||0}`} template={current}/><h2>Registered versions</h2>{templates?.length?templates.map(template=><article key={template.id}><a href={`/staff/lease-templates?key=${encodeURIComponent(template.template_key)}`}>{template.title} · {template.template_key} · Version {template.version}</a><p className="enquiry-message">{template.source_reference}</p><small>Reference ID: {template.id}</small><TemplateDocumentFiles templateId={template.id} files={documents?.filter(document=>document.template_id===template.id)||[]} currentUserId={user.id} enabled={enabled}/></article>):<p>No approved template references registered.</p>}{pages>1&&<nav aria-label="Template version pages">{page>1&&<a href={href(page-1)}>← Newer</a>}<span> Page {page} of {pages} </span>{page<pages&&<a href={href(page+1)}>Older →</a>}</nav>}<p><a href="/staff/lease-templates">All templates / new key ↗</a> · <a href="/account">My account ↗</a></p></section></main></>;
}
