import type {SupabaseClient} from '@supabase/supabase-js';
import {adminInvitationDetail} from './admin-invitation-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function adminInvitationHistory(client:SupabaseClient,owner:string,id:string,pageInput:number){
 const work=await adminInvitationDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access||access.role!=='admin')throw new Error('Approved work access required.');
 const query=(head=false)=>client.from('staff_invitation_events').select('id,organization_id,invitation_id,actor_user_id,action,previous_state,new_state,version,reason,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('invitation_id',id);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Work audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Work audit unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.invitation_id!==id||!validId(r.actor_user_id)||!['create','accept','decline','revoke','expire'].includes(r.action)||r.previous_state!==null&&r.previous_state!=='pending'||!['pending','accepted','declined','revoked','expired'].includes(r.new_state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid invitation decision.');const expected={create:'pending',accept:'accepted',decline:'declined',revoke:'revoked',expire:'expired'}[r.action as 'create'|'accept'|'decline'|'revoke'|'expire'];if(r.new_state!==expected||(r.action==='create'?(r.previous_state!==null||r.version!==1):(r.previous_state!=='pending'||r.version<2)))throw new Error('Invalid invitation transition.');return {id:r.id as string,actor:r.actor_user_id as string,action:r.action as string,before:r.previous_state as string|null,state:r.new_state as string,version:r.version as number,reason:r.reason as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Duplicate security decisions.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw new Error('Security access changed.');const latest=await adminInvitationDetail(client,owner,id);if(!latest||latest.email!==work.email||latest.role!==work.role)throw new Error('Assignment changed.');return {total,pages,page,rows};
}
