import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function adminInvitations(client:SupabaseClient,owner:string,pageInput:number){
 const access=await managerAccess(client,owner);if(!access||access.role!=='admin')throw Error('Administrator membership required.');const query=(head=false)=>client.from('staff_invitations').select('id,organization_id,invite_email,role,state,version,expires_at,created_at',{head,count:'exact'}).eq('organization_id',access.organization);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Invitation count unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw Error('Invitations unavailable.');
 const rows=response.data.map(r=>invitationRecord(r,access.organization));if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate invitations.');const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw Error('Administrator membership changed.');return {total,pages,page,rows};
}

export function invitationRecord(r:Record<string,unknown>,organization:string){if(!validId(r.id)||r.organization_id!==organization||typeof r.invite_email!=='string'||r.invite_email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(r.invite_email)||typeof r.role!=='string'||!['admin','manager','realtor','finance'].includes(r.role)||typeof r.state!=='string'||!['pending','accepted','declined','revoked','expired'].includes(r.state)||typeof r.version!=='number'||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at))||typeof r.expires_at!=='string'||!Number.isFinite(Date.parse(r.expires_at)))throw Error('Invalid invitation record.');return {id:r.id as string,email:r.invite_email as string,role:r.role as string,state:r.state as string,version:r.version as number,created:r.created_at as string,expires:r.expires_at as string};}
