import type {SupabaseClient} from '@supabase/supabase-js';
import {invitationInput} from '../../../lib/staff/invitation-validation';
import {managerAccess} from './manager-access';
import {adminInvitationDetail} from './admin-invitation-detail';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type InvitationCommand=Readonly<{action:'create'|'revoke';invitation_id:string|null;version:number;email:string|null;role:string|null;request_id:string;reason:string;approved:true}>;
export function adminInvitationCommand(value:InvitationCommand):InvitationCommand{const r=invitationInput(value);if(!['create','revoke'].includes(r.p_action))throw new EnquiryFailure('Administrator invitation action required.',false);return Object.freeze({action:r.p_action as 'create'|'revoke',invitation_id:r.p_invitation_id,version:r.p_expected_version,email:r.p_email,role:r.p_role,request_id:r.p_request_id,reason:r.p_reason,approved:true});}
export async function sendAdminInvitationCommand(client:SupabaseClient,owner:string,value:InvitationCommand){
 let input:InvitationCommand,access:NonNullable<Awaited<ReturnType<typeof managerAccess>>>,parent:Awaited<ReturnType<typeof adminInvitationDetail>>=null;
 try{input=adminInvitationCommand(value);const current=await managerAccess(client,owner);if(!current||current.role!=='admin')throw Error();access=current;if(input.invitation_id){parent=await adminInvitationDetail(client,owner,input.invitation_id);if(!parent)throw Error();}const latest=await managerAccess(client,owner);if(!latest||latest.organization!==access.organization||latest.role!==access.role||latest.revision!==access.revision)throw Error();}catch{throw new EnquiryFailure('Check administrator membership and approved invitation fields.',false);}
 let response;try{response=await client.rpc('manage_staff_invitation',invitationInput(input));}catch{throw new EnquiryFailure('Invitation decision could not be confirmed. Retry the same request.',true);}
 if(response.error)throw new EnquiryFailure('Invitation decision could not be confirmed. Refresh or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));
 try{const ack=response.data,state=input.action==='create'?'pending':'revoked';if(!ack||!validId(ack.id)||input.invitation_id&&ack.id!==input.invitation_id||ack.version!==input.version+1||ack.state!==state)throw Error();const event=await client.from('staff_invitation_events').select('organization_id,invitation_id,actor_user_id,request_id,action,previous_state,new_state,version,reason,payload').eq('organization_id',access.organization).eq('invitation_id',ack.id).eq('actor_user_id',owner).eq('request_id',input.request_id).maybeSingle(),r=event.data;
 if(event.error||!r||r.organization_id!==access.organization||r.invitation_id!==ack.id||r.actor_user_id!==owner||r.request_id!==input.request_id||r.action!==input.action||r.previous_state!==(input.action==='create'?null:'pending')||r.new_state!==state||r.version!==ack.version||r.reason!==input.reason||!r.payload||Object.entries({action:input.action,invitation_id:input.invitation_id,version:input.version,email:input.email,role:input.role,reason:input.reason}).some(([k,v])=>r.payload[k]!==v))throw Error();
 const current=await adminInvitationDetail(client,owner,ack.id),latest=await managerAccess(client,owner);if(!current||current.version<ack.version||current.version===ack.version&&current.state!==state||current.email!==(parent?.email??input.email)||current.role!==(parent?.role??input.role)||!latest||latest.organization!==access.organization||latest.role!==access.role||latest.revision!==access.revision)throw Error();return {id:ack.id as string,state,version:ack.version as number,currentState:current.state,currentVersion:current.version};
 }catch{throw new EnquiryFailure('Recorded invitation decision could not be confirmed. Retry the same request.',true);}
}
