import type {SupabaseClient} from '@supabase/supabase-js';
import {adminOwnerAccessDetail} from './admin-owner-access-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function adminOwnerAccessHistory(client:SupabaseClient,owner:string,id:string,pageInput:number){
 const work=await adminOwnerAccessDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access||access.role!=='admin')throw new Error('Approved work access required.');
 const query=(head=false)=>client.from('owner_property_access_changes').select('id,organization_id,access_id,actor_user_id,before_record,after_record,version,reason,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('access_id',id);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Work audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Work audit unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.access_id!==id||!validId(r.actor_user_id)||r.before_record!==null&&typeof r.before_record?.is_active!=='boolean'||typeof r.after_record?.is_active!=='boolean'||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid owner access decision.');if(r.before_record===null?(r.version!==1||r.after_record.is_active!==true):r.version<2)throw new Error('Invalid owner access creation/revision.');return {id:r.id as string,actor:r.actor_user_id as string,before:r.before_record===null?null:r.before_record.is_active as boolean,active:r.after_record.is_active as boolean,version:r.version as number,reason:r.reason as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Duplicate security decisions.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw new Error('Security access changed.');const latest=await adminOwnerAccessDetail(client,owner,id);if(!latest||latest.user!==work.user||latest.property.property!==work.property.property)throw new Error('Assignment changed.');return {total,pages,page,rows};
}
