import type {SupabaseClient} from '@supabase/supabase-js';
import {completionInput} from '../../../lib/staff/completion-validation';
import {contractorWorkOffer} from './work-offers';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type CompletionAttempt=Readonly<{action:'submit';offer_id:string;offer_version:number;version:0;request_id:string;summary:string;tests_performed:string;outstanding_items:string;reason:string}>;
export function completionAttempt(value:CompletionAttempt):CompletionAttempt{const r=completionInput(value);if(r.p_action!=='submit')throw new EnquiryFailure('Contractor submission required.',false);return Object.freeze({action:'submit',offer_id:r.p_offer_id!,offer_version:r.p_expected_offer_version!,version:0,request_id:r.p_request_id,summary:r.p_summary!,tests_performed:r.p_tests_performed!,outstanding_items:r.p_outstanding_items!,reason:r.p_reason});}
export async function submitContractorCompletion(client:SupabaseClient,owner:string,attempt:CompletionAttempt){
 let input:CompletionAttempt;try{input=completionAttempt(attempt);if(!await contractorWorkOffer(client,owner,input.offer_id))throw Error();}catch{throw new EnquiryFailure('Verify your assignment and report details before submitting.',false);}
 let response;try{response=await client.rpc('manage_completion_report',completionInput(input));}catch{throw new EnquiryFailure('Report could not be confirmed. Retry the same request.',true);}
 if(response.error)throw new EnquiryFailure('Report could not be confirmed. Check the assignment, departure and pending review or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));
 const r=response.data;try{if(!r||!validId(r.id)||r.version!==1||r.state!=='submitted')throw Error();const stored=await client.from('contractor_completion_reports').select('id,offer_id,contractor_user_id,state,version,summary,tests_performed,outstanding_items').eq('id',r.id).eq('offer_id',input.offer_id).eq('contractor_user_id',owner).maybeSingle();const s=stored.data;if(stored.error||!s||s.id!==r.id||s.offer_id!==input.offer_id||s.contractor_user_id!==owner||!['submitted','changes_requested','approved'].includes(s.state)||!Number.isInteger(s.version)||s.version<1||s.version>=2147483647||s.version===1&&s.state!=='submitted'||s.summary!==input.summary||s.tests_performed!==input.tests_performed||s.outstanding_items!==input.outstanding_items)throw Error();if(!await contractorWorkOffer(client,owner,input.offer_id))throw Error();return {id:r.id as string,state:'submitted' as const,version:1,currentState:s.state as string,currentVersion:s.version as number};}catch{throw new EnquiryFailure('Recorded report could not be confirmed. Retry the same request.',true);}
}
