import type {SupabaseClient} from '@supabase/supabase-js';
import {contractorWorkOffer} from './work-offers';
import {validId} from './catalog';
export async function contractorEvidence(client:SupabaseClient,owner:string,offer:string,pageInput:number){
 if(!await contractorWorkOffer(client,owner,offer))throw new Error('Assigned work offer required.');
 const query=(head=false)=>client.from('contractor_evidence').select('id,offer_id,user_id,file_name,mime_type,declared_size,state,expires_at,contractor_report_evidence(report_id)',{head,count:'exact'}).eq('offer_id',offer).eq('user_id',owner).in('state',['reserved','uploaded']);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Private evidence unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1).limit(1,{referencedTable:'contractor_report_evidence'}):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Private evidence unavailable.');
 const rows=response.data.map(r=>{const size=Number(r.declared_size);if(!validId(r.id)||r.offer_id!==offer||r.user_id!==owner||typeof r.file_name!=='string'||!r.file_name.trim()||r.file_name.length>255||/[\x00-\x1f\x7f/\\]/.test(r.file_name)||!['application/pdf','image/jpeg','image/png'].includes(r.mime_type)||!Number.isSafeInteger(size)||size<1||size>8388608||!['reserved','uploaded'].includes(r.state)||typeof r.expires_at!=='string'||!Number.isFinite(Date.parse(r.expires_at))||!Array.isArray(r.contractor_report_evidence)||r.contractor_report_evidence.length>1||r.contractor_report_evidence.some(e=>!validId(e.report_id)))throw new Error('Invalid private evidence.');return {id:r.id as string,name:r.file_name as string,mime:r.mime_type as string,size,state:r.state as 'reserved'|'uploaded',expires:r.expires_at as string,frozen:r.contractor_report_evidence.length>0};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid private evidence.');
 const current=await contractorWorkOffer(client,owner,offer);if(!current)throw new Error('Contractor access changed.');return {offerState:current.state,total,pages,page,rows};
}
