import type {SupabaseClient} from '@supabase/supabase-js';
import {contractorWorkOffer} from './work-offers';
import {validId} from './catalog';
export async function contractorCurrentVisit(client:SupabaseClient,owner:string,offerId:string){
 const offer=await contractorWorkOffer(client,owner,offerId);if(!offer)throw new Error('Work offer unavailable.');if(offer.state!=='accepted')return {offer,visit:null,permit:null};
 const result=await client.from('contractor_visits').select('id,offer_id,contractor_user_id,state,version,starts_at,ends_at,shared_note').eq('offer_id',offerId).eq('contractor_user_id',owner).in('state',['proposed','confirmed']).maybeSingle();if(result.error)throw new Error('Appointment unavailable.');const r=result.data;
 let visit:{id:string;state:'proposed'|'confirmed';version:number;starts:string;ends:string;note:string;started:boolean}|null=null;
 if(r){const start=Date.parse(r.starts_at),end=Date.parse(r.ends_at);if(!validId(r.id)||r.offer_id!==offerId||r.contractor_user_id!==owner||!['proposed','confirmed'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.starts_at!=='string'||typeof r.ends_at!=='string'||!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>8*60*60*1000||typeof r.shared_note!=='string'||r.shared_note.length>2000)throw new Error('Invalid appointment.');visit={id:r.id,state:r.state,version:r.version,starts:r.starts_at,ends:r.ends_at,note:r.shared_note,started:start<=Date.now()};}
 let permit:{id:string;from:string;until:string;instructions:string;window:'upcoming'|'within'|'expired'}|null=null;
 if(visit?.state==='confirmed'){const response=await client.from('contractor_entry_permits').select('id,visit_id,contractor_user_id,state,valid_from,valid_until,shared_instructions').eq('visit_id',visit.id).eq('contractor_user_id',owner).eq('state','authorized').maybeSingle();if(response.error)throw new Error('Entry authorization unavailable.');const p=response.data;if(p){const from=Date.parse(p.valid_from),until=Date.parse(p.valid_until),now=Date.now();if(!validId(p.id)||p.visit_id!==visit.id||p.contractor_user_id!==owner||p.state!=='authorized'||typeof p.valid_from!=='string'||typeof p.valid_until!=='string'||!Number.isFinite(from)||!Number.isFinite(until)||until<=from||from<Date.parse(visit.starts)||until>Date.parse(visit.ends)||typeof p.shared_instructions!=='string'||p.shared_instructions.length>2000)throw new Error('Invalid entry authorization.');permit={id:p.id,from:p.valid_from,until:p.valid_until,instructions:p.shared_instructions,window:now<from?'upcoming':now>=until?'expired':'within'};}}
 const current=await contractorWorkOffer(client,owner,offerId);if(!current||current.state!=='accepted'||current.version!==offer.version)throw new Error('Assignment changed. Refresh to check.');
 return {offer:current,visit,permit};
}
