import type {SupabaseClient} from '@supabase/supabase-js';
import {contractorWorkOffer} from './work-offers';
import {validId} from './catalog';
export async function contractorCompletionReports(client:SupabaseClient,owner:string,offerId:string,pageInput:number){
 const offer=await contractorWorkOffer(client,owner,offerId);if(!offer)throw new Error('Assigned work offer required.');
 const query=(head=false)=>client.from('contractor_completion_reports').select('id,offer_id,contractor_user_id,state,version,summary,tests_performed,outstanding_items,review_message,created_at',{head,count:'exact'}).eq('offer_id',offerId).eq('contractor_user_id',owner);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Completion reports unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Completion reports unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.offer_id!==offerId||r.contractor_user_id!==owner||!['submitted','changes_requested','approved'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||([['summary',20,4000],['tests_performed',10,2000],['outstanding_items',5,2000]] as const).some(([k,min,max])=>typeof r[k]!=='string'||r[k].trim().length<min||r[k].length>max)||(r.state==='submitted'?r.review_message!==null:typeof r.review_message!=='string'||r.review_message.trim().length<10||r.review_message.length>2000)||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid completion report.');return {id:r.id as string,state:r.state as string,version:r.version as number,summary:r.summary as string,tests:r.tests_performed as string,outstanding:r.outstanding_items as string,review:r.review_message as string|null,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid completion reports.');
 const current=await contractorWorkOffer(client,owner,offerId);if(!current)throw new Error('Contractor access changed.');return {offer:current,total,pages,page,rows};
}
