import type {SupabaseClient} from '@supabase/supabase-js';
import {financeAccess} from './finance-access';
import {financeChequeBankHistory} from './finance-cheque-bank-history';
import {validId} from './catalog';
export async function withdrawChequeUpload(client:SupabaseClient,owner:string,cheque:string,id:string){
 if(!validId(cheque)||!validId(id))throw Error('Valid cheque document required.');const access=await financeAccess(client,owner),history=await financeChequeBankHistory(client,owner,cheque),parent=history.cheque;if(!access||!['received','deposited','cleared'].includes(parent.state)||history.rows.some(r=>r.evidence===id))throw Error('Own unused document on an editable cheque required.');
 const read=async()=>{const result=await client.from('cheque_bank_evidence').select('id,cheque_id,organization_id,user_id,state').eq('id',id).eq('cheque_id',cheque).eq('organization_id',access.organization).eq('user_id',owner).maybeSingle(),r=result.data;if(result.error||!r||r.id!==id||r.cheque_id!==cheque||r.organization_id!==access.organization||r.user_id!==owner||!['reserved','uploaded','withdrawn','expired'].includes(r.state))throw Error('Cheque document unavailable.');return r.state as string;};
 const before=await read();if(before!=='withdrawn'){const result=await client.rpc('withdraw_cheque_evidence',{p_evidence_id:id});if(result.error||result.data!==true)throw Error('Withdrawal could not be confirmed. Check the same document.');}
 if(await read()!=='withdrawn')throw Error('Retained withdrawal could not be verified.');const event=await client.from('cheque_bank_evidence_events').select('evidence_id,actor_user_id,event_name').eq('evidence_id',id).eq('actor_user_id',owner).eq('event_name','withdrawn').maybeSingle();if(event.error||event.data?.evidence_id!==id||event.data.actor_user_id!==owner||event.data.event_name!=='withdrawn')throw Error('Withdrawal audit unavailable.');const current=await financeAccess(client,owner),fresh=(await financeChequeBankHistory(client,owner,cheque)).cheque;if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||fresh.version!==parent.version||fresh.state!==parent.state)throw Error('Cheque access changed.');return 'withdrawn' as const;
}
