import type {SupabaseClient} from '@supabase/supabase-js';
import {invoiceAccess} from './invoice-access';
import {financeInvoiceDetail} from './finance-invoice-detail';
import {validId} from './catalog';
export async function withdrawInvoiceUpload(client:SupabaseClient,owner:string,invoice:string,id:string){
 if(!validId(invoice)||!validId(id))throw Error('Valid invoice document required.');const access=await invoiceAccess(client,owner),parent=await financeInvoiceDetail(client,owner,invoice);if(!access||!parent||parent.submitter!==owner||parent.state!=='submitted')throw Error('Own submitted invoice required.');
 const read=async()=>{const result=await client.from('vendor_invoice_evidence').select('id,invoice_id,organization_id,user_id,state').eq('id',id).eq('invoice_id',invoice).eq('organization_id',access.organization).eq('user_id',owner).maybeSingle(),r=result.data;if(result.error||!r||r.id!==id||r.invoice_id!==invoice||r.organization_id!==access.organization||r.user_id!==owner||!['reserved','uploaded','withdrawn','expired'].includes(r.state))throw Error('Invoice document unavailable.');return r.state as string;};
 const before=await read();if(before!=='withdrawn'){const result=await client.rpc('withdraw_invoice_evidence',{p_evidence_id:id});if(result.error||result.data!==true)throw Error('Withdrawal could not be confirmed. Check the same document.');}
 if(await read()!=='withdrawn')throw Error('Retained withdrawal could not be verified.');const event=await client.from('vendor_invoice_evidence_events').select('evidence_id,actor_user_id,event_name').eq('evidence_id',id).eq('actor_user_id',owner).eq('event_name','withdrawn').maybeSingle();if(event.error||event.data?.evidence_id!==id||event.data.actor_user_id!==owner||event.data.event_name!=='withdrawn')throw Error('Withdrawal audit unavailable.');const current=await invoiceAccess(client,owner),fresh=await financeInvoiceDetail(client,owner,invoice);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!fresh||fresh.submitter!==owner||fresh.version!==parent.version||fresh.state!==parent.state)throw Error('Invoice access changed.');return 'withdrawn' as const;
}
