import type {SupabaseClient} from '@supabase/supabase-js';
import {invoiceAccess} from './invoice-access';
import {financeInvoiceEvidence} from './finance-invoice-evidence';
import {validId} from './catalog';
export async function financeInvoiceDownload(client:SupabaseClient,owner:string,invoice:string,id:string){
 if(!validId(invoice)||!validId(id))throw Error('Invoice document reference required.');const access=await invoiceAccess(client,owner);if(!access)throw Error('Verified invoice membership required.');
 const evidence=await financeInvoiceEvidence(client,owner,invoice),file=evidence.rows.find(f=>f.id===id);if(!file)throw Error('Certified invoice document unavailable.');
 async function read(){const response=await client.from('vendor_invoice_evidence').select('id,invoice_id,organization_id,user_id,state,object_path,file_name').eq('id',id).eq('invoice_id',invoice).eq('organization_id',access!.organization).eq('state','uploaded').maybeSingle();const r=response.data;if(response.error||!r||r.id!==id||r.invoice_id!==invoice||r.organization_id!==access!.organization||r.user_id!==evidence.invoice.submitter||r.state!=='uploaded'||typeof r.object_path!=='string'||!r.object_path||r.object_path.length>1024||r.file_name!==file!.name)throw Error('Document unavailable.');return r.object_path as string;}
 const path=await read(),signed=await client.storage.from('vendor-invoice-evidence').createSignedUrl(path,120,{download:file.name});if(signed.error||typeof signed.data?.signedUrl!=='string')throw Error('Private document link unavailable.');const url=new URL(signed.data.signedUrl);if(url.protocol!=='https:'||url.hostname!=='zikxzkbfxgdilykyyswt.supabase.co'||url.port||url.username||url.password||url.hash||decodeURIComponent(url.pathname)!=='/storage/v1/object/sign/vendor-invoice-evidence/'+path||!url.searchParams.get('token'))throw Error('Invalid private document link.');
 const fresh=await financeInvoiceEvidence(client,owner,invoice),current=await invoiceAccess(client,owner);if(await read()!==path||!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||fresh.invoice.version!==evidence.invoice.version||fresh.invoice.state!==evidence.invoice.state||JSON.stringify(fresh.rows.find(f=>f.id===id))!==JSON.stringify(file))throw Error('Document access changed.');return url.toString();
}
