import type {SupabaseClient} from '@supabase/supabase-js';
import {financeAccess} from './finance-access';
import {financeChequeEvidence} from './finance-cheque-evidence';
import {validId} from './catalog';
export async function financeChequeDownload(client:SupabaseClient,owner:string,cheque:string,id:string){
 if(!validId(cheque)||!validId(id))throw Error('Cheque document reference required.');const access=await financeAccess(client,owner);if(!access)throw Error('Verified cheque membership required.');
 const evidence=await financeChequeEvidence(client,owner,cheque),file=evidence.rows.find(f=>f.id===id);if(!file)throw Error('Certified cheque document unavailable.');
 async function read(){const response=await client.from('cheque_bank_evidence').select('id,cheque_id,organization_id,user_id,state,object_path,file_name').eq('id',id).eq('cheque_id',cheque).eq('organization_id',access!.organization).eq('state','uploaded').maybeSingle();const r=response.data;if(response.error||!r||r.id!==id||r.cheque_id!==cheque||r.organization_id!==access!.organization||!validId(r.user_id)||r.state!=='uploaded'||typeof r.object_path!=='string'||!r.object_path||r.object_path!==cheque+'/'+id+(file!.mime==='application/pdf'?'.pdf':file!.mime==='image/jpeg'?'.jpg':'.png')||r.file_name!==file!.name)throw Error('Document unavailable.');return r.object_path as string;}
 const path=await read(),signed=await client.storage.from('cheque-bank-evidence').createSignedUrl(path,120,{download:file.name});if(signed.error||typeof signed.data?.signedUrl!=='string')throw Error('Private document link unavailable.');const url=new URL(signed.data.signedUrl);if(url.protocol!=='https:'||url.hostname!=='zikxzkbfxgdilykyyswt.supabase.co'||url.port||url.username||url.password||url.hash||decodeURIComponent(url.pathname)!=='/storage/v1/object/sign/cheque-bank-evidence/'+path||!url.searchParams.get('token'))throw Error('Invalid private document link.');
 const fresh=await financeChequeEvidence(client,owner,cheque),current=await financeAccess(client,owner);if(await read()!==path||!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||fresh.cheque.version!==evidence.cheque.version||fresh.cheque.state!==evidence.cheque.state||JSON.stringify(fresh.rows.find(f=>f.id===id))!==JSON.stringify(file))throw Error('Document access changed.');return url.toString();
}
