import type {SupabaseClient} from '@supabase/supabase-js';
import {financeAccess} from './finance-access';
import {validId} from './catalog';
const amount=(v:unknown):string=>{if(typeof v==='number'&&Number.isSafeInteger(v)&&v>=0)v=String(v);if(typeof v!=='string'||!/^(0|[1-9]\d{0,13})$/.test(v)||BigInt(v)>99999999999999n)throw Error('Invalid journal amount.');return v;};
export async function financeJournalDetail(client:SupabaseClient,owner:string,id:string){
 if(!validId(id))throw Error('Valid journal reference required.');const access=await financeAccess(client,owner);if(!access)throw Error('Approved finance membership required.');
 const response=await client.from('finance_journals').select('id,organization_id,memo,reason,currency,posted_by,posted_at,request_id').eq('id',id).eq('organization_id',access.organization).maybeSingle();if(response.error)throw Error('Posted journal unavailable.');const r=response.data;
 if(r&&(r.id!==id||r.organization_id!==access.organization||r.currency!=='JMD'||typeof r.memo!=='string'||r.memo.trim().length<5||r.memo.length>1000||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||!validId(r.posted_by)||!validId(r.request_id)||typeof r.posted_at!=='string'||!Number.isFinite(Date.parse(r.posted_at))))throw Error('Invalid posted journal.');
 if(!r){const current=await financeAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw Error('Finance membership changed.');return null;}
 const result=await client.from('finance_journal_lines').select('id,journal_id,organization_id,line_number,account_id,property_id,unit_id,debit_minor,credit_minor').eq('journal_id',id).eq('organization_id',access.organization).order('line_number',{ascending:true}).limit(201);
 if(result.error||!Array.isArray(result.data)||result.data.length<2||result.data.length>200)throw Error('Complete journal lines unavailable.');
 const lines=result.data.map((l,i)=>{if(!validId(l.id)||l.journal_id!==id||l.organization_id!==access.organization||l.line_number!==i+1||!validId(l.account_id)||l.property_id!==null&&!validId(l.property_id)||l.unit_id!==null&&(!validId(l.unit_id)||l.property_id===null))throw Error('Invalid journal line.');const debit=amount(l.debit_minor),credit=amount(l.credit_minor);if((BigInt(debit)>0n)===(BigInt(credit)>0n))throw Error('Invalid journal line amounts.');return {id:l.id as string,number:l.line_number as number,account:l.account_id as string,property:l.property_id as string|null,unit:l.unit_id as string|null,debit,credit};});
 if(new Set(lines.map(l=>l.id)).size!==lines.length)throw Error('Duplicate journal lines.');const debit=lines.reduce((sum,l)=>sum+BigInt(l.debit),0n),credit=lines.reduce((sum,l)=>sum+BigInt(l.credit),0n);if(debit!==credit)throw Error('Posted journal totals differ.');
 const reversal=async(column:'original_journal_id'|'reversal_journal_id')=>{const result=await client.from('finance_journal_reversals').select('organization_id,original_journal_id,reversal_journal_id,reason,actor_user_id,created_at').eq(column,id).eq('organization_id',access.organization).maybeSingle();if(result.error)throw Error('Reversal history unavailable.');const x=result.data;if(!x)return null;if(x.organization_id!==access.organization||x[column]!==id||!validId(x.original_journal_id)||!validId(x.reversal_journal_id)||x.original_journal_id===x.reversal_journal_id||!validId(x.actor_user_id)||typeof x.reason!=='string'||x.reason.trim().length<5||x.reason.length>500||typeof x.created_at!=='string'||!Number.isFinite(Date.parse(x.created_at)))throw Error('Invalid journal reversal.');return {original:x.original_journal_id as string,reversal:x.reversal_journal_id as string,reason:x.reason as string,actor:x.actor_user_id as string,created:x.created_at as string};};
 const [outgoing,incoming]=await Promise.all([reversal('original_journal_id'),reversal('reversal_journal_id')]);if(outgoing&&incoming)throw Error('Invalid reversal chain.');const current=await financeAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw Error('Finance membership changed.');
 return {id,memo:r.memo as string,reason:r.reason as string,actor:r.posted_by as string,posted:r.posted_at as string,request:r.request_id as string,debit:debit.toString(),credit:credit.toString(),lines,outgoing,incoming};
}
