import type {SupabaseClient} from '@supabase/supabase-js';
import {financeAccess} from './finance-access';
import {financeChequeBankHistory} from './finance-cheque-bank-history';
import {validId} from './catalog';
export async function financeChequeReservations(client:SupabaseClient,owner:string,id:string,pageInput:number){
 if(!validId(id))throw Error('Valid cheque reference required.');const access=await financeAccess(client,owner),history=await financeChequeBankHistory(client,owner,id),cheque=history.cheque;if(!access)throw Error('Verified finance upload records required.');
 const query=(head=false)=>client.from('cheque_bank_evidence').select('id,cheque_id,organization_id,user_id,kind,file_name,mime_type,declared_size,state,expires_at,created_at',{head,count:'exact'}).eq('cheque_id',id).eq('organization_id',access.organization).eq('user_id',owner);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Upload records unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const result=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(result.error||!Array.isArray(result.data)||result.data.length!==Math.min(25,Math.max(0,total-(page-1)*25)))throw Error('Complete upload records unavailable.');
 const rows=result.data.map(r=>{const size=typeof r.declared_size==='string'&&/^[1-9]\d*$/.test(r.declared_size)?Number(r.declared_size):r.declared_size;if(!validId(r.id)||r.cheque_id!==id||r.organization_id!==access.organization||r.user_id!==owner||!['deposit','clearance','return'].includes(r.kind)||typeof r.file_name!=='string'||!r.file_name.trim()||r.file_name.length>160||/[\x00-\x1f\x7f/\\]/.test(r.file_name)||!['application/pdf','image/jpeg','image/png'].includes(r.mime_type)||!Number.isSafeInteger(size)||size<1||size>8388608||!['reserved','uploaded','withdrawn','expired'].includes(r.state)||typeof r.expires_at!=='string'||!Number.isFinite(Date.parse(r.expires_at))||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw Error('Invalid upload record.');return {used:history.rows.some(event=>event.evidence===r.id),id:r.id as string,kind:r.kind as 'deposit'|'clearance'|'return',name:r.file_name as string,mime:r.mime_type as string,size:size as number,state:r.state as 'reserved'|'uploaded'|'withdrawn'|'expired',expires:r.expires_at as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate upload records.');
 const current=await financeAccess(client,owner),fresh=(await financeChequeBankHistory(client,owner,id)).cheque;if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||fresh.version!==cheque.version||fresh.state!==cheque.state)throw Error('Cheque upload access changed.');return {cheque,total,pages,page,rows};
}
