import type {SupabaseClient} from '@supabase/supabase-js';
import {invoiceAccess} from './invoice-access';
import {financeInvoiceDetail} from './finance-invoice-detail';
import {validId} from './catalog';
export async function financeInvoiceReservations(client:SupabaseClient,owner:string,id:string,pageInput:number){
 if(!validId(id))throw Error('Valid invoice reference required.');const access=await invoiceAccess(client,owner),invoice=await financeInvoiceDetail(client,owner,id);if(!access||!invoice||invoice.submitter!==owner)throw Error('Own invoice upload records required.');
 const query=(head=false)=>client.from('vendor_invoice_evidence').select('id,invoice_id,organization_id,user_id,kind,file_name,mime_type,declared_size,state,expires_at,created_at',{head,count:'exact'}).eq('invoice_id',id).eq('organization_id',access.organization).eq('user_id',owner);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Upload records unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const result=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(result.error||!Array.isArray(result.data)||result.data.length!==Math.min(25,Math.max(0,total-(page-1)*25)))throw Error('Complete upload records unavailable.');
 const rows=result.data.map(r=>{const size=typeof r.declared_size==='string'&&/^[1-9]\d*$/.test(r.declared_size)?Number(r.declared_size):r.declared_size;if(!validId(r.id)||r.invoice_id!==id||r.organization_id!==access.organization||r.user_id!==owner||!['invoice','supporting'].includes(r.kind)||typeof r.file_name!=='string'||!r.file_name.trim()||r.file_name.length>160||/[\x00-\x1f\x7f/\\]/.test(r.file_name)||!['application/pdf','image/jpeg','image/png'].includes(r.mime_type)||!Number.isSafeInteger(size)||size<1||size>8388608||!['reserved','uploaded','withdrawn','expired'].includes(r.state)||typeof r.expires_at!=='string'||!Number.isFinite(Date.parse(r.expires_at))||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw Error('Invalid upload record.');return {id:r.id as string,kind:r.kind as 'invoice'|'supporting',name:r.file_name as string,mime:r.mime_type as string,size:size as number,state:r.state as 'reserved'|'uploaded'|'withdrawn'|'expired',expires:r.expires_at as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate upload records.');
 const current=await invoiceAccess(client,owner),fresh=await financeInvoiceDetail(client,owner,id);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!fresh||fresh.submitter!==owner||fresh.version!==invoice.version||fresh.state!==invoice.state)throw Error('Invoice upload access changed.');return {invoice,total,pages,page,rows};
}
