import type {SupabaseClient} from '@supabase/supabase-js';
import {completionInput} from '../../../lib/staff/completion-validation';
import {managerAccess} from './manager-access';
import {managerWorkDetail} from './manager-work-detail';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type CompletionReview=Readonly<{work:string;offer:string;report_id:string;version:number;request_id:string;action:'approve'|'request_changes';review_message:string;reason:string;evidence_reviewed:true|null}>;
export function completionReview(value:CompletionReview):CompletionReview{if(!validId(value.work)||!validId(value.offer))throw Error('Work and assignment required.');const r=completionInput(value);if(!['approve','request_changes'].includes(r.p_action))throw Error('Management review required.');return Object.freeze({work:value.work,offer:value.offer,report_id:r.p_report_id!,version:r.p_expected_report_version,request_id:r.p_request_id,action:r.p_action as CompletionReview['action'],review_message:r.p_review_message!,reason:r.p_reason,evidence_reviewed:r.p_evidence_reviewed as true|null});}
async function scoped(client:SupabaseClient,owner:string,input:CompletionReview){const access=await managerAccess(client,owner);if(!access||!await managerWorkDetail(client,owner,input.work))throw Error();const response=await client.from('contractor_completion_reports').select('id,organization_id,work_order_id,offer_id,state,version,review_message').eq('id',input.report_id).eq('organization_id',access.organization).eq('work_order_id',input.work).eq('offer_id',input.offer).maybeSingle();const r=response.data;if(response.error||!r||r.id!==input.report_id||r.organization_id!==access.organization||r.work_order_id!==input.work||r.offer_id!==input.offer||!['submitted','changes_requested','approved'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647)throw Error();const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw Error();return {state:r.state as string,version:r.version as number,review:r.review_message as string|null};}
export async function reviewManagerCompletion(client:SupabaseClient,owner:string,value:CompletionReview){let input:CompletionReview;try{input=completionReview(value);await scoped(client,owner,input);}catch{throw new EnquiryFailure('Refresh approved work and completion report access.',false);}let response;try{response=await client.rpc('manage_completion_report',completionInput(input));}catch{throw new EnquiryFailure('Completion decision could not be confirmed. Retry the same request.',true);}if(response.error)throw new EnquiryFailure('Completion decision could not be confirmed. Refresh or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));try{const r=response.data,expected=input.action==='approve'?'approved':'changes_requested';if(!r||r.id!==input.report_id||r.version!==input.version+1||r.state!==expected)throw Error();const current=await scoped(client,owner,input);if(current.version<r.version||current.version===r.version&&(current.state!==r.state||current.review!==input.review_message))throw Error();return{id:r.id as string,state:expected,version:r.version as number,currentState:current.state,currentVersion:current.version};}catch{throw new EnquiryFailure('Recorded completion decision could not be confirmed. Retry the same request.',true);}}
