import type {SupabaseClient} from '@supabase/supabase-js';
import {managerInventoryProperty} from './manager-inventory-property';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerInventoryHistory(client:SupabaseClient,owner:string,property:string,pageInput:number){
 const parent=await managerInventoryProperty(client,owner,property),access=await managerAccess(client,owner);if(!parent||!access)throw Error('Private property access required.');
 const query=(head=false)=>client.from('managed_inventory_events').select('id,organization_id,actor_user_id,action,target_id,expected_revision,payload,result,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('result->>property_id',property);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Inventory history unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw Error('Inventory history unavailable.');
 const rows=response.data.map(r=>{
  if(!validId(r.id)||r.organization_id!==access.organization||!validId(r.actor_user_id)||!['property_create','property_update','unit_create','unit_update','listing_link'].includes(r.action)||!Number.isInteger(r.expected_revision)||r.expected_revision<0||r.expected_revision>=2147483647||!r.result||r.result.property_id!==property||!Number.isInteger(r.result.revision)||r.result.revision<1||r.result.revision>=2147483647||!r.payload||typeof r.payload!=='object'||Array.isArray(r.payload)||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw Error('Invalid inventory history.');
  const p=r.payload;let fields:Record<string,string|number|null>;const text=(v:unknown,min:number,max:number)=>typeof v==='string'&&v.trim().length>=min&&v.length<=max;const number=(v:unknown,min:number,max:number,step=1)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max&&v/step===Math.round(v/step);
  if(r.action.startsWith('property_')){if(!text(p.name,2,160)||!text(p.area,2,120)||!text(p.address_text,5,500))throw Error('Invalid property fields.');if(r.action==='property_create'?(r.target_id!==null||r.expected_revision!==0||r.result.revision!==1):(r.target_id!==property||r.expected_revision<1||r.result.revision!==r.expected_revision+1))throw Error('Invalid property change.');fields={name:p.name,area:p.area,address:p.address_text};}
  else if(r.action.startsWith('unit_')){if(!validId(r.result.unit_id)||!text(p.unit_label,1,80)||!number(p.bedrooms,0,50,0.5)||!number(p.bathrooms,0,50,0.5)||!number(p.parking_spaces,0,100)||p.floor!==null&&!number(p.floor,-10,200)||p.size_sq_ft!==null&&!number(p.size_sq_ft,1,1000000)||r.expected_revision<1||r.action==='unit_create'&&(r.target_id!==property||r.result.revision!==1)||r.action==='unit_update'&&(r.target_id!==r.result.unit_id||r.result.revision!==r.expected_revision+1))throw Error('Invalid unit change.');fields={label:p.unit_label,bedrooms:p.bedrooms,bathrooms:p.bathrooms,parking:p.parking_spaces,floor:p.floor,size:p.size_sq_ft};}
  else{if(!validId(r.target_id)||r.target_id!==r.result.listing_id||r.expected_revision<1||r.result.revision!==r.expected_revision+1||p.unit_id!==null&&!validId(p.unit_id)||p.unit_id!==r.result.unit_id)throw Error('Invalid listing linkage.');fields={unit:p.unit_id};}
  return {id:r.id as string,actor:r.actor_user_id as string,action:r.action as string,version:r.result.revision as number,created:r.created_at as string,fields};
 });if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate inventory events.');const current=await managerAccess(client,owner),latest=await managerInventoryProperty(client,owner,property);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!latest)throw Error('Inventory access changed.');return {total,pages,page,rows};
}
