import type {SupabaseClient} from '@supabase/supabase-js';
import {managerWorkDetail} from './manager-work-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerOfferAudit(client:SupabaseClient,owner:string,id:string,offer:string,pageInput:number){
 const work=await managerWorkDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access)throw new Error('Approved work access required.');
 if(!validId(offer))throw new Error('Offer reference required.');const parent=await client.from('contractor_work_offers').select('id,organization_id,work_order_id').eq('id',offer).eq('organization_id',access.organization).eq('work_order_id',id).maybeSingle();if(parent.error||parent.data?.id!==offer||parent.data?.organization_id!==access.organization||parent.data?.work_order_id!==id)throw new Error('Retained offer required.');
 const query=(head=false)=>client.from('contractor_work_offer_changes').select('id,organization_id,offer_id,actor_user_id,action,previous_state,new_state,version,reason,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('offer_id',offer);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Work audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Work audit unavailable.');
 const state=(v:unknown)=>typeof v==='string'&&['offered','accepted','declined','withdrawn','expired','completed'].includes(v);const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.offer_id!==offer||r.actor_user_id!==null&&!validId(r.actor_user_id)||typeof r.action!=='string'||!r.action.trim()||r.action.length>80||!state(r.new_state)||r.previous_state!==null&&!state(r.previous_state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid offer audit.');return {id:r.id as string,actor:r.actor_user_id as string|null,action:r.action as string,before:r.previous_state as string|null,state:r.new_state as string,version:r.version as number,reason:r.reason as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid offer events.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerWorkDetail(client,owner,id))throw new Error('Work access changed.');return {total,pages,page,rows};
}
