import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerPreventiveDetail(client:SupabaseClient,owner:string,id:string){
 if(!validId(id))throw new Error('Plan reference required.');const access=await managerAccess(client,owner);if(!access)throw new Error('Approved management membership required.');
 const response=await client.from('preventive_maintenance_plans').select('id,organization_id,title,description,priority,state,version,property_id,unit_id,next_due_on,interval_days,created_at').eq('id',id).eq('organization_id',access.organization).maybeSingle();const r=response.data;if(response.error)throw new Error('Preventive plan unavailable.');
 async function recheck(){const current=await managerAccess(client,owner);if(!current||current.organization!==access!.organization||current.role!==access!.role||current.revision!==access!.revision)throw new Error('Management access changed.');}
 if(!r){await recheck();return null;}
 if(typeof r.next_due_on!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(r.next_due_on)||!Number.isFinite(Date.parse(r.next_due_on+'T00:00:00Z'))||new Date(r.next_due_on+'T00:00:00Z').toISOString().slice(0,10)!==r.next_due_on||!Number.isInteger(r.interval_days)||r.interval_days<1||r.interval_days>366||r.id!==id||r.organization_id!==access.organization||!validId(r.property_id)||r.unit_id!==null&&!validId(r.unit_id)||typeof r.title!=='string'||r.title.trim().length<3||r.title.length>160||typeof r.description!=='string'||r.description.trim().length<20||r.description.length>5000||!['active','paused','retired'].includes(r.state)||!['low','standard','high','urgent'].includes(r.priority)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid preventive plan.');
 const property=await client.from('properties').select('id,organization_id,name').eq('id',r.property_id).eq('organization_id',access.organization).maybeSingle();const p=property.data;if(property.error||!p||p.id!==r.property_id||p.organization_id!==access.organization||typeof p.name!=='string'||!p.name.trim()||p.name.length>500)throw new Error('Plan property unavailable.');
 if(r.unit_id){const unit=await client.from('units').select('id,property_id').eq('id',r.unit_id).eq('property_id',r.property_id).maybeSingle();if(unit.error||!unit.data||unit.data.id!==r.unit_id||unit.data.property_id!==r.property_id)throw new Error('Plan unit unavailable.');}
 await recheck();return {id:r.id as string,title:r.title as string,description:r.description as string,state:r.state as string,priority:r.priority as string,version:r.version as number,property:p.name as string,propertyId:r.property_id as string,unit:r.unit_id as string|null,due:r.next_due_on as string,interval:r.interval_days as number,created:r.created_at as string};
}
