import type {SupabaseClient} from '@supabase/supabase-js';
import {managerWorkDetail} from './manager-work-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerOfferHistory(client:SupabaseClient,owner:string,id:string,pageInput:number){
 const work=await managerWorkDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access)throw new Error('Approved work access required.');
 const query=(head=false)=>client.from('contractor_work_offers').select('id,organization_id,work_order_id,job_title,scope_summary,company_name_snapshot,trade,state,version,expires_at,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('work_order_id',id);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Work audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Work audit unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.work_order_id!==id||!['offered','accepted','declined','withdrawn','expired','completed'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||(['expires_at','created_at'] as const).some(k=>typeof r[k]!=='string'||!Number.isFinite(Date.parse(r[k])))||([['job_title',3,160],['scope_summary',20,3000],['company_name_snapshot',2,160],['trade',1,80]] as const).some(([k,min,max])=>typeof r[k]!=='string'||r[k].trim().length<min||r[k].length>max))throw new Error('Invalid retained offer.');return {id:r.id as string,title:r.job_title as string,scope:r.scope_summary as string,company:r.company_name_snapshot as string,trade:r.trade as string,state:r.state as string,version:r.version as number,expires:r.expires_at as string,created:r.created_at as string,expired:r.state==='offered'&&Date.parse(r.expires_at)<=Date.now()};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid retained offers.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerWorkDetail(client,owner,id))throw new Error('Work access changed.');return {total,pages,page,rows};
}
