import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {managerWorkDetail} from './manager-work-detail';
import {validId} from './catalog';
export async function managerEntryPermits(client:SupabaseClient,owner:string,workId:string,offerId:string,visitId:string,pageInput:number){
 if(!validId(offerId)||!validId(visitId))throw Error('Appointment reference required.');const access=await managerAccess(client,owner),work=await managerWorkDetail(client,owner,workId);if(!access||!work)throw Error('Management work access required.');
 async function parent(){const offer=await client.from('contractor_work_offers').select('id,organization_id,work_order_id').eq('id',offerId).eq('organization_id',access!.organization).eq('work_order_id',workId).maybeSingle();if(offer.error||!offer.data||offer.data.id!==offerId||offer.data.organization_id!==access!.organization||offer.data.work_order_id!==workId)throw Error('Assignment unavailable.');const visit=await client.from('contractor_visits').select('id,organization_id,offer_id,property_id,unit_id,contractor_user_id,starts_at,ends_at').eq('id',visitId).eq('organization_id',access!.organization).eq('offer_id',offerId).eq('property_id',work!.propertyId).maybeSingle();const r=visit.data;if(visit.error||!r||r.id!==visitId||r.organization_id!==access!.organization||r.offer_id!==offerId||r.property_id!==work!.propertyId||r.unit_id!==work!.unit||!validId(r.contractor_user_id)||typeof r.starts_at!=='string'||typeof r.ends_at!=='string'||!Number.isFinite(Date.parse(r.starts_at))||!Number.isFinite(Date.parse(r.ends_at))||Date.parse(r.ends_at)<=Date.parse(r.starts_at))throw Error('Appointment unavailable.');return r;}
 const visit=await parent();const query=(head=false)=>client.from('contractor_entry_permits').select('id,organization_id,visit_id,contractor_user_id,valid_from,valid_until,shared_instructions,state,version',{head,count:'exact'}).eq('organization_id',access.organization).eq('visit_id',visitId);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Entry history unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw Error('Entry history unavailable.');
 const rows=response.data.map(r=>{const from=Date.parse(r.valid_from),until=Date.parse(r.valid_until);if(!validId(r.id)||r.organization_id!==access.organization||r.visit_id!==visitId||r.contractor_user_id!==visit.contractor_user_id||!['authorized','revoked'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.valid_from!=='string'||typeof r.valid_until!=='string'||!Number.isFinite(from)||!Number.isFinite(until)||until<=from||from<Date.parse(visit.starts_at)||until>Date.parse(visit.ends_at)||typeof r.shared_instructions!=='string'||r.shared_instructions.trim().length<5||r.shared_instructions.length>1000)throw Error('Invalid entry permit.');return {id:r.id as string,state:r.state as string,version:r.version as number,from:r.valid_from as string,until:r.valid_until as string,instructions:r.shared_instructions as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate entry permits.');
 const fresh=await parent(),current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||fresh.contractor_user_id!==visit.contractor_user_id||fresh.starts_at!==visit.starts_at||fresh.ends_at!==visit.ends_at||!await managerWorkDetail(client,owner,workId))throw Error('Management access changed.');return {total,pages,page,rows};
}
