import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {managerWorkDetail} from './manager-work-detail';
import {validId} from './catalog';
export async function managerReportEvidence(client:SupabaseClient,owner:string,work:string,offer:string,report:string,pageInput:number){
 if(!validId(offer)||!validId(report))throw Error('Report reference required.');const access=await managerAccess(client,owner);if(!access||!await managerWorkDetail(client,owner,work))throw Error('Management access required.');
 async function parent(){const r=await client.from('contractor_completion_reports').select('id,organization_id,work_order_id,offer_id,contractor_user_id').eq('id',report).eq('organization_id',access!.organization).eq('work_order_id',work).eq('offer_id',offer).maybeSingle();const d=r.data;if(r.error||!d||d.id!==report||d.organization_id!==access!.organization||d.work_order_id!==work||d.offer_id!==offer||!validId(d.contractor_user_id))throw Error('Report unavailable.');return d.contractor_user_id as string;}
 const contractor=await parent(),query=(head=false)=>client.from('contractor_report_evidence').select('report_id,evidence_id,contractor_evidence(id,organization_id,offer_id,user_id,file_name,mime_type,declared_size,state)',{head,count:'exact'}).eq('report_id',report);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Report evidence unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('evidence_id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw Error('Report evidence unavailable.');
 const rows=response.data.map(r=>{const d=r.contractor_evidence as unknown as Record<string,unknown>|null,size=Number(d?.declared_size);if(r.report_id!==report||!validId(r.evidence_id)||!d||Array.isArray(d)||d.id!==r.evidence_id||d.organization_id!==access.organization||d.offer_id!==offer||d.user_id!==contractor||d.state!=='uploaded'||typeof d.file_name!=='string'||!d.file_name.trim()||d.file_name.length>255||/[\x00-\x1f\x7f/\\]/.test(d.file_name)||!['application/pdf','image/jpeg','image/png'].includes(String(d.mime_type))||!Number.isSafeInteger(size)||size<1||size>8388608)throw Error('Invalid report evidence.');return{id:r.evidence_id as string,name:d.file_name,mime:d.mime_type as string,size};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate report evidence.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||await parent()!==contractor||!await managerWorkDetail(client,owner,work))throw Error('Report access changed.');return{total,pages,page,rows};
}
