import type {SupabaseClient} from '@supabase/supabase-js';
import {managerPreventiveDetail} from './manager-preventive-detail';
import {managerAccess} from './manager-access';
import {preventiveSnapshot} from './preventive-snapshot';
import {validId} from './catalog';
export async function managerPreventiveHistory(client:SupabaseClient,owner:string,id:string,pageInput:number){
 const work=await managerPreventiveDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access)throw new Error('Approved plan access required.');
 const query=(head=false)=>client.from('preventive_maintenance_events').select('id,organization_id,plan_id,actor_user_id,action,version,reason,work_order_id,created_at,snapshot',{head,count:'exact'}).eq('organization_id',access.organization).eq('plan_id',id);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Preventive audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Preventive audit unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.plan_id!==id||!validId(r.actor_user_id)||!['create','revise','issue','skip'].includes(r.action)||(r.action==='issue'?!validId(r.work_order_id):r.work_order_id!==null)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid preventive audit event.');const after=preventiveSnapshot(r.snapshot?.after,id,access.organization),before=r.action==='create'&&r.snapshot?.before===null?null:preventiveSnapshot(r.snapshot?.before,id,access.organization);if(after.version!==r.version||(before?before.version+1!==after.version:after.version!==1))throw new Error('Invalid decision revisions.');if(before&&(before.property!==after.property||before.unit!==after.unit))throw new Error('Decision property changed.');if(before&&['issue','skip'].includes(r.action)){const next=new Date(before.due+'T00:00:00Z');next.setUTCDate(next.getUTCDate()+before.interval);if(after.due!==next.toISOString().slice(0,10)||before.title!==after.title||before.description!==after.description||before.priority!==after.priority||before.state!==after.state||before.interval!==after.interval)throw new Error('Invalid scheduled decision scope.');}return {before,after,id:r.id as string,actor:r.actor_user_id as string,action:r.action as string,work:r.work_order_id as string|null,version:r.version as number,reason:r.reason as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid plan events.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerPreventiveDetail(client,owner,id))throw new Error('Plan access changed.');return {total,pages,page,rows};
}
