import type {SupabaseClient} from '@supabase/supabase-js';
import {workOfferInput} from '../../../lib/staff/work-offer-validation';
import {managerWorkDetail} from './manager-work-detail';
import {managerContractor} from './manager-contractors';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type OfferCreation=Readonly<{action:'offer';offer_id:null;version:0;work_order_id:string;work_version:number;contractor_id:string;job_title:string;scope_summary:string;trade:string;reason:string;approved:true;request_id:string}>;
export function offerCreation(value:OfferCreation):OfferCreation{const r=workOfferInput(value);if(r.p_action!=='offer')throw new EnquiryFailure('Approved scope required.',false);return Object.freeze({action:'offer',offer_id:null,version:0,work_order_id:r.p_work_order_id!,work_version:r.p_expected_work_version!,contractor_id:r.p_contractor_id!,job_title:r.p_job_title!,scope_summary:r.p_scope_summary!,trade:r.p_trade!,reason:r.p_reason,approved:true,request_id:r.p_request_id});}
export async function createManagerOffer(client:SupabaseClient,owner:string,value:OfferCreation){
 let input:OfferCreation,access:NonNullable<Awaited<ReturnType<typeof managerAccess>>>;try{input=offerCreation(value);const membership=await managerAccess(client,owner);if(!membership||!await managerWorkDetail(client,owner,input.work_order_id))throw Error();access=membership;const contractor=await managerContractor(client,owner,input.contractor_id);if(!contractor.trades.includes(input.trade))throw Error();}catch{throw new EnquiryFailure('Check approved work access, contractor trade and scope.',false);}
 let response;try{response=await client.rpc('manage_contractor_work_offer',workOfferInput(input));}catch{throw new EnquiryFailure('Offer could not be confirmed. Retry the same request.',true);}
 if(response.error)throw new EnquiryFailure('Offer could not be confirmed. Refresh work access or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));
 const r=response.data;try{if(!r||!validId(r.id)||r.version!==1||r.state!=='offered')throw Error();const stored=await client.from('contractor_work_offers').select('id,organization_id,work_order_id,contractor_id,job_title,scope_summary,trade,state,version').eq('id',r.id).eq('organization_id',access.organization).eq('work_order_id',input.work_order_id).maybeSingle();const s=stored.data;if(stored.error||!s||s.id!==r.id||s.organization_id!==access.organization||s.work_order_id!==input.work_order_id||s.contractor_id!==input.contractor_id||s.job_title!==input.job_title||s.scope_summary!==input.scope_summary||s.trade!==input.trade||!['offered','accepted','declined','withdrawn','expired','completed'].includes(s.state)||!Number.isInteger(s.version)||s.version<1||s.version>=2147483647||s.version===1&&s.state!=='offered')throw Error();const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerWorkDetail(client,owner,input.work_order_id))throw Error();return {id:r.id as string,state:'offered' as const,version:1,currentState:s.state as string,currentVersion:s.version as number};}catch{throw new EnquiryFailure('Recorded offer could not be confirmed. Retry the same request.',true);}
}
