import type {SupabaseClient} from '@supabase/supabase-js';
import {managerWorkDetail} from './manager-work-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerCompletionAudit(client:SupabaseClient,owner:string,id:string,offer:string,report:string,pageInput:number){
 const work=await managerWorkDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access)throw new Error('Approved work access required.');
 if(!validId(offer)||!validId(report))throw Error('Report reference required.');async function parent(){const r=await client.from('contractor_completion_reports').select('id,organization_id,work_order_id,offer_id').eq('id',report).eq('organization_id',access!.organization).eq('work_order_id',id).eq('offer_id',offer).maybeSingle();if(r.error||r.data?.id!==report||r.data?.organization_id!==access!.organization||r.data?.work_order_id!==id||r.data?.offer_id!==offer)throw Error('Retained report required.');}await parent();
 const query=(head=false)=>client.from('contractor_completion_changes').select('id,organization_id,report_id,actor_user_id,action,previous_state,new_state,version,reason,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('report_id',report);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Work audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Work audit unavailable.');
 const state=(v:unknown)=>typeof v==='string'&&['submitted','changes_requested','approved'].includes(v);const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.report_id!==report||!validId(r.actor_user_id)||!['submit','request_changes','approve'].includes(r.action)||!state(r.new_state)||r.previous_state!==null&&!state(r.previous_state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid completion audit.');return {id:r.id as string,actor:r.actor_user_id as string|null,action:r.action as string,before:r.previous_state as string|null,state:r.new_state as string,version:r.version as number,reason:r.reason as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid completion events.');
 await parent();const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerWorkDetail(client,owner,id))throw new Error('Work access changed.');return {total,pages,page,rows};
}
