import type {SupabaseClient} from '@supabase/supabase-js';
import {returnVisitInput} from '../../../lib/staff/return-visit-validation';
import {managerAccess} from './manager-access';
import {managerWorkDetail} from './manager-work-detail';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type ReturnVisit=Readonly<{work:string;offer:string;report_id:string;request_id:string;report_version:number;offer_version:number;work_version:number;reason:string;approved:true}>;
export function returnVisit(value:ReturnVisit):ReturnVisit{if(!validId(value.work)||!validId(value.offer))throw Error('Work and assignment required.');const r=returnVisitInput(value);return Object.freeze({work:value.work,offer:value.offer,report_id:r.p_report_id,request_id:r.p_request_id,report_version:r.p_expected_report_version,offer_version:r.p_expected_offer_version,work_version:r.p_expected_work_version,reason:r.p_reason,approved:true});}
export async function managerReturnVisitContext(client:SupabaseClient,owner:string,workId:string,offerId:string,reportId:string){if(!validId(offerId)||!validId(reportId))throw Error('Report reference required.');const access=await managerAccess(client,owner),work=await managerWorkDetail(client,owner,workId);if(!access||!work)throw Error('Work unavailable.');const offer=await client.from('contractor_work_offers').select('id,organization_id,work_order_id,state,version').eq('id',offerId).eq('organization_id',access.organization).eq('work_order_id',workId).maybeSingle(),report=await client.from('contractor_completion_reports').select('id,organization_id,work_order_id,offer_id,state,version').eq('id',reportId).eq('organization_id',access.organization).eq('work_order_id',workId).eq('offer_id',offerId).maybeSingle();const o=offer.data,r=report.data;if(offer.error||report.error||!o||!r||o.id!==offerId||o.organization_id!==access.organization||o.work_order_id!==workId||r.id!==reportId||r.organization_id!==access.organization||r.work_order_id!==workId||r.offer_id!==offerId||!['offered','accepted','declined','withdrawn','expired','completed'].includes(o.state)||!['submitted','changes_requested','approved'].includes(r.state)||![o.version,r.version].every(v=>Number.isInteger(v)&&v>=1&&v<2147483647))throw Error('Correction context unavailable.');const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw Error('Management access changed.');return{work,offer:{state:o.state as string,version:o.version as number},report:{state:r.state as string,version:r.version as number}};}
export async function requestManagerReturnVisit(client:SupabaseClient,owner:string,value:ReturnVisit){let input:ReturnVisit;try{input=returnVisit(value);await managerReturnVisitContext(client,owner,input.work,input.offer,input.report_id);}catch{throw new EnquiryFailure('Refresh work and correction report access.',false);}let response;try{response=await client.rpc('request_contractor_return_visit',returnVisitInput(input));}catch{throw new EnquiryFailure('Return decision could not be confirmed. Retry the same request.',true);}if(response.error)throw new EnquiryFailure('Return decision could not be confirmed. Refresh or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));try{const r=response.data;if(!r||r.id!==input.work||r.state!=='assigned'||r.version!==input.work_version+1)throw Error();const current=await managerReturnVisitContext(client,owner,input.work,input.offer,input.report_id);if(current.work.version<r.version||current.work.version===r.version&&current.work.state!==r.state)throw Error();return{id:r.id as string,state:'assigned',version:r.version as number,currentState:current.work.state,currentVersion:current.work.version};}catch{throw new EnquiryFailure('Recorded return decision could not be confirmed. Retry the same request.',true);}}
