import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {managerWorkDetail} from './manager-work-detail';
import {validId} from './catalog';
export async function managerEvidenceDownload(client:SupabaseClient,owner:string,work:string,offer:string,report:string,id:string){
 if(!validId(offer)||!validId(report)||!validId(id))throw Error('Report evidence required.');const access=await managerAccess(client,owner);if(!access||!await managerWorkDetail(client,owner,work))throw Error('Management access required.');
 async function read(){const parent=await client.from('contractor_completion_reports').select('id,organization_id,work_order_id,offer_id,contractor_user_id').eq('id',report).eq('organization_id',access!.organization).eq('work_order_id',work).eq('offer_id',offer).maybeSingle();const p=parent.data;if(parent.error||!p||p.id!==report||p.organization_id!==access!.organization||p.work_order_id!==work||p.offer_id!==offer||!validId(p.contractor_user_id))throw Error('Report unavailable.');const link=await client.from('contractor_report_evidence').select('report_id,evidence_id').eq('report_id',report).eq('evidence_id',id).maybeSingle();if(link.error||link.data?.report_id!==report||link.data?.evidence_id!==id)throw Error('Report file unavailable.');const response=await client.from('contractor_evidence').select('id,organization_id,offer_id,user_id,state,object_path,file_name').eq('id',id).eq('organization_id',access!.organization).eq('offer_id',offer).eq('user_id',p.contractor_user_id).eq('state','uploaded').maybeSingle();const d=response.data;if(response.error||!d||d.id!==id||d.organization_id!==access!.organization||d.offer_id!==offer||d.user_id!==p.contractor_user_id||d.state!=='uploaded'||typeof d.object_path!=='string'||!d.object_path||d.object_path.length>1024||typeof d.file_name!=='string'||!d.file_name.trim()||d.file_name.length>255||/[\x00-\x1f\x7f/\\]/.test(d.file_name))throw Error('Evidence unavailable.');return {path:d.object_path,name:d.file_name,contractor:p.contractor_user_id};}
 const doc=await read();const signed=await client.storage.from('contractor-evidence').createSignedUrl(doc.path,120,{download:doc.name});if(signed.error||typeof signed.data?.signedUrl!=='string')throw Error('Private link unavailable.');const url=new URL(signed.data.signedUrl);if(url.protocol!=='https:'||url.hostname!=='zikxzkbfxgdilykyyswt.supabase.co'||url.port||url.username||url.password||url.hash||decodeURIComponent(url.pathname)!=='/storage/v1/object/sign/contractor-evidence/'+doc.path||!url.searchParams.get('token'))throw Error('Invalid private link.');
 const fresh=await read(),current=await managerAccess(client,owner);if(fresh.path!==doc.path||fresh.name!==doc.name||fresh.contractor!==doc.contractor||!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerWorkDetail(client,owner,work))throw Error('Evidence access changed.');return url.toString();
}
