import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerContractors(client:SupabaseClient,owner:string,pageInput:number){
 const access=await managerAccess(client,owner);if(!access)throw new Error('Approved manager membership required.');
 const query=(head=false)=>{return client.from('contractor_accounts').select('id,organization_id,company_name,trade_coverage,is_active',{head,count:'exact'}).eq('organization_id',access.organization).eq('is_active',true);};
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Contractor register unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('company_name',{ascending:true}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Contractor register unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.is_active!==true||typeof r.company_name!=='string'||r.company_name.trim().length<2||r.company_name.length>160||!Array.isArray(r.trade_coverage)||r.trade_coverage.length<1||r.trade_coverage.length>20||r.trade_coverage.some((t:unknown)=>typeof t!=='string'||!t.trim()||t.length>80)||new Set(r.trade_coverage).size!==r.trade_coverage.length)throw new Error('Invalid approved contractor.');return {id:r.id as string,company:r.company_name as string,trades:[...r.trade_coverage] as string[]};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid contractors.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw new Error('Management access changed.');return {total,pages,page,rows};
}
export async function managerContractor(client:SupabaseClient,owner:string,id:string){
 if(!validId(id))throw new Error('Contractor reference required.');const access=await managerAccess(client,owner);if(!access)throw new Error('Approved manager membership required.');
 const response=await client.from('contractor_accounts').select('id,organization_id,company_name,trade_coverage,is_active,version').eq('id',id).eq('organization_id',access.organization).eq('is_active',true).maybeSingle();const r=response.data;if(response.error||!r||r.id!==id||r.organization_id!==access.organization||r.is_active!==true||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.company_name!=='string'||r.company_name.trim().length<2||r.company_name.length>160||!Array.isArray(r.trade_coverage)||r.trade_coverage.length<1||r.trade_coverage.length>20||r.trade_coverage.some((t:unknown)=>typeof t!=='string'||!t.trim()||t.length>80)||new Set(r.trade_coverage).size!==r.trade_coverage.length)throw new Error('Active approved contractor unavailable.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw new Error('Management access changed.');return {id:r.id as string,company:r.company_name as string,trades:[...r.trade_coverage] as string[],version:r.version as number};
}
