import type {SupabaseClient} from '@supabase/supabase-js';
import {managerPresence} from './manager-presence';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerPresenceAudit(client:SupabaseClient,owner:string,work:string,presence:string,pageInput:number){
 const parent=await managerPresence(client,owner,work,presence),access=await managerAccess(client,owner);if(!access)throw new Error('Approved management membership required.');
 const query=(head=false)=>client.from('contractor_presence_changes').select('id,organization_id,presence_id,property_id,actor_user_id,action,previous_state,new_state,version,reason,created_at',{head,count:'exact'}).eq('organization_id',access.organization).eq('presence_id',presence).eq('property_id',parent.property);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Presence events unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Presence events unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||r.presence_id!==presence||r.property_id!==parent.property||!validId(r.actor_user_id)||!['check_in','check_out'].includes(r.action)||r.new_state!==(r.action==='check_in'?'on_site':'exited')||r.previous_state!==(r.action==='check_in'?null:'on_site')||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.reason!=='string'||r.reason.trim().length<5||r.reason.length>500||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid presence event.');return {id:r.id as string,actor:r.actor_user_id as string,action:r.action as string,before:r.previous_state as string|null,state:r.new_state as string,version:r.version as number,reason:r.reason as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid presence events.');
 const current=await managerPresence(client,owner,work,presence),membership=await managerAccess(client,owner);if(current.visit!==parent.visit||current.permit!==parent.permit||current.property!==parent.property||!membership||membership.organization!==access.organization||membership.role!==access.role||membership.revision!==access.revision)throw new Error('Presence access changed.');return {total,pages,page,rows};
}
