import type {SupabaseClient} from '@supabase/supabase-js';
import {managerWorkDetail} from './manager-work-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerVisitHistory(client:SupabaseClient,owner:string,workId:string,offer:string,pageInput:number){
 if(!validId(offer))throw Error('Offer reference required.');const work=await managerWorkDetail(client,owner,workId),access=await managerAccess(client,owner);if(!work||!access)throw Error('Approved work required.');
 async function parent(){const r=await client.from('contractor_work_offers').select('id,organization_id,work_order_id').eq('id',offer).eq('organization_id',access!.organization).eq('work_order_id',workId).maybeSingle();if(r.error||!r.data||r.data.id!==offer||r.data.organization_id!==access!.organization||r.data.work_order_id!==workId)throw Error('Assignment access required.');}await parent();
 const query=(head=false)=>client.from('contractor_visits').select('id,offer_id,organization_id,property_id,unit_id,state,version,starts_at,ends_at,shared_note',{head,count:'exact'}).eq('offer_id',offer).eq('organization_id',access.organization).eq('property_id',work.propertyId);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Appointment history unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Appointment history unavailable.');
 const rows=response.data.map(r=>{const start=Date.parse(r.starts_at),end=Date.parse(r.ends_at);if(!validId(r.id)||r.offer_id!==offer||r.organization_id!==access.organization||r.property_id!==work.propertyId||r.unit_id!==work.unit||!['proposed','confirmed','declined','cancelled','completed'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.starts_at!=='string'||typeof r.ends_at!=='string'||!Number.isFinite(start)||!Number.isFinite(end)||end<=start||end-start>8*60*60*1000||typeof r.shared_note!=='string'||r.shared_note.trim().length<5||r.shared_note.length>1000)throw new Error('Invalid appointment history.');return {id:r.id as string,state:r.state as string,version:r.version as number,starts:r.starts_at as string,ends:r.ends_at as string,note:r.shared_note as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Invalid appointment history.');
 await parent();const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerWorkDetail(client,owner,workId))throw Error('Management access changed.');return {total,pages,page,rows};
}
