import type {SupabaseClient} from '@supabase/supabase-js';
import {managerPreventiveDetail} from './manager-preventive-detail';
import {managerAccess} from './manager-access';
import {preventiveSnapshot} from './preventive-snapshot';
import {validId} from './catalog';
export async function managerPreventiveSkips(client:SupabaseClient,owner:string,id:string,pageInput:number){
 const work=await managerPreventiveDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access)throw new Error('Approved plan access required.');
 const query=(head=false)=>client.from('preventive_maintenance_skips').select('organization_id,plan_id,due_on,event_id,created_at,snapshot,decision:preventive_maintenance_events(id,organization_id,plan_id,action,actor_user_id,reason,version,work_order_id)',{head,count:'exact'}).eq('organization_id',access.organization).eq('plan_id',id);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Preventive audit unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('due_on',{ascending:false}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Preventive audit unavailable.');
 const rows=response.data.map(r=>{if(r.organization_id!==access.organization||r.plan_id!==id||!validId(r.event_id)||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at)))throw new Error('Invalid preventive occurrence.');const scope=preventiveSnapshot(r.snapshot,id,access.organization);if(scope.due!==r.due_on||scope.state!=='active')throw new Error('Invalid occurrence scope.');const candidate:unknown=r.decision;const d=candidate&&typeof candidate==='object'&&!Array.isArray(candidate)?candidate as Record<string,unknown>:null;if(!d||Array.isArray(d)||d.id!==r.event_id||d.organization_id!==access.organization||d.plan_id!==id||d.action!=='skip'||!validId(d.actor_user_id)||d.work_order_id!==null||d.version!==scope.version+1||typeof d.reason!=='string'||d.reason.trim().length<5||d.reason.length>500)throw new Error('Invalid skip decision.');return {actor:d.actor_user_id as string,reason:d.reason as string,due:scope.due,event:r.event_id as string,scope,created:r.created_at as string};});for(const key of ['due','event'] as const)if(new Set(rows.map(r=>r[key])).size!==rows.length)throw new Error('Duplicate occurrences.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision||!await managerPreventiveDetail(client,owner,id))throw new Error('Plan access changed.');return {total,pages,page,rows};
}
