import type {SupabaseClient} from '@supabase/supabase-js';
import {managedInventoryInput} from '../../../lib/staff/managed-inventory';
import {managerInventoryProperty} from './manager-inventory-property';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type InventoryCommand=Readonly<{approved:true;request_id:string;action:'property_create'|'property_update'|'unit_create'|'unit_update';target_id:string|null;revision:number;property:string|null;fields:Readonly<Record<string,unknown>>}>;
export function inventoryCommand(value:InventoryCommand):InventoryCommand{
 if(value.approved!==true||!['property_create','property_update','unit_create','unit_update'].includes(value.action))throw new EnquiryFailure('Approved inventory action required.',false);
 const r=managedInventoryInput({...value.fields,action:value.action,target_id:value.target_id,revision:value.revision,request_id:value.request_id});
 if(value.action==='property_create'?value.property!==null:!validId(value.property))throw new EnquiryFailure('Exact property binding required.',false);
 if(['property_update','unit_create'].includes(value.action)&&value.target_id!==value.property)throw new EnquiryFailure('Property target changed.',false);
 return Object.freeze({approved:true,request_id:r.p_request_id,action:value.action,target_id:r.p_target_id,revision:r.p_expected_revision,property:value.property,fields:Object.freeze({...r.p_payload})});
}
async function unitRecord(client:SupabaseClient,property:string,id:string){const response=await client.from('units').select('id,property_id,unit_label,bedrooms,bathrooms,parking_spaces,floor,size_sq_ft,management_revision').eq('id',id).eq('property_id',property).maybeSingle(),u=response.data;if(response.error||!u||u.id!==id||u.property_id!==property||!Number.isInteger(u.management_revision)||u.management_revision<1||u.management_revision>=2147483647)throw Error('Unit unavailable.');const fields=managedInventoryInput({action:'unit_update',target_id:id,revision:u.management_revision,request_id:id,unit_label:u.unit_label,bedrooms:u.bedrooms,bathrooms:u.bathrooms,parking_spaces:u.parking_spaces,floor:u.floor,size_sq_ft:u.size_sq_ft}).p_payload;return {version:u.management_revision as number,fields};}
export async function sendInventoryCommand(client:SupabaseClient,owner:string,value:InventoryCommand){
 let input:InventoryCommand,access:NonNullable<Awaited<ReturnType<typeof managerAccess>>>;
 try{input=inventoryCommand(value);const membership=await managerAccess(client,owner);if(!membership)throw Error();if(input.property){if(!await managerInventoryProperty(client,owner,input.property))throw Error();if(input.action==='unit_update')await unitRecord(client,input.property,input.target_id!);}const latest=await managerAccess(client,owner);if(!latest||latest.organization!==membership.organization||latest.role!==membership.role||latest.revision!==membership.revision)throw Error();access=membership;}catch{throw new EnquiryFailure('Check management access and reviewed inventory fields.',false);}
 const args=managedInventoryInput({...input.fields,action:input.action,target_id:input.target_id,revision:input.revision,request_id:input.request_id});let response;try{response=await client.rpc('author_managed_inventory',args);}catch{throw new EnquiryFailure('Inventory change could not be confirmed. Retry the same request.',true);}
 if(response.error)throw new EnquiryFailure('Inventory change could not be confirmed. Refresh or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));
 try{const ack=response.data,unitAction=input.action.startsWith('unit_'),expected=input.action.endsWith('create')?1:input.revision+1;if(!ack||!validId(ack.property_id)||ack.revision!==expected||input.property&&ack.property_id!==input.property||unitAction&&(!validId(ack.unit_id)||input.action==='unit_update'&&ack.unit_id!==input.target_id))throw Error();
 const event=await client.from('managed_inventory_events').select('organization_id,actor_user_id,request_id,action,target_id,expected_revision,payload,result').eq('organization_id',access.organization).eq('actor_user_id',owner).eq('request_id',input.request_id).maybeSingle(),r=event.data;
 if(event.error||!r||r.organization_id!==access.organization||r.actor_user_id!==owner||r.request_id!==input.request_id||r.action!==input.action||r.target_id!==input.target_id||r.expected_revision!==input.revision||!r.payload||!r.result||r.result.property_id!==ack.property_id||r.result.revision!==ack.revision||unitAction&&r.result.unit_id!==ack.unit_id||Object.keys(r.payload).length!==Object.keys(input.fields).length||Object.entries(input.fields).some(([k,v])=>r.payload[k]!==v))throw Error();
 const property=await managerInventoryProperty(client,owner,ack.property_id);if(!property)throw Error();let currentVersion:number;if(unitAction){const unit=await unitRecord(client,ack.property_id,ack.unit_id);currentVersion=unit.version;if(currentVersion<ack.revision||currentVersion===ack.revision&&Object.entries(input.fields).some(([k,v])=>unit.fields[k]!==v))throw Error();}else{currentVersion=property.version;if(currentVersion<ack.revision||currentVersion===ack.revision&&(property.name!==input.fields.name||property.area!==input.fields.area||property.address!==input.fields.address_text))throw Error();}
 const latest=await managerAccess(client,owner);if(!latest||latest.organization!==access.organization||latest.role!==access.role||latest.revision!==access.revision)throw Error();return {property:ack.property_id as string,unit:unitAction?ack.unit_id as string:null,version:ack.revision as number,currentVersion};
 }catch{throw new EnquiryFailure('Recorded inventory change could not be confirmed. Retry the same request.',true);}
}
