import type {SupabaseClient} from '@supabase/supabase-js';
import {workOfferInput} from '../../../lib/staff/work-offer-validation';
import {managerAccess} from './manager-access';
import {managerWorkDetail} from './manager-work-detail';
import {validId} from './catalog';
import {EnquiryFailure} from './enquiries';
export type OfferWithdrawal=Readonly<{work:string;action:'withdraw';offer_id:string;request_id:string;version:number;reason:string}>;
export function offerWithdrawal(value:OfferWithdrawal):OfferWithdrawal{if(!validId(value.work))throw new EnquiryFailure('Work reference required.',false);const r=workOfferInput(value);if(r.p_action!=='withdraw')throw new EnquiryFailure('Manager withdrawal required.',false);return Object.freeze({work:value.work,action:'withdraw',offer_id:r.p_offer_id!,request_id:r.p_request_id,version:r.p_expected_offer_version,reason:r.p_reason});}
async function scoped(client:SupabaseClient,owner:string,work:string,offer:string){const access=await managerAccess(client,owner);if(!access||!await managerWorkDetail(client,owner,work))throw Error();const response=await client.from('contractor_work_offers').select('id,organization_id,work_order_id,state,version').eq('id',offer).eq('organization_id',access.organization).eq('work_order_id',work).maybeSingle();const r=response.data;if(response.error||!r||r.id!==offer||r.organization_id!==access.organization||r.work_order_id!==work||!['offered','accepted','declined','withdrawn','expired','completed'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647)throw Error();const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw Error();return {state:r.state as string,version:r.version as number};}
export async function withdrawManagerOffer(client:SupabaseClient,owner:string,value:OfferWithdrawal){let input:OfferWithdrawal;try{input=offerWithdrawal(value);await scoped(client,owner,input.work,input.offer_id);}catch{throw new EnquiryFailure('Check approved work and offer access before withdrawal.',false);}
 let response;try{response=await client.rpc('manage_contractor_work_offer',workOfferInput(input));}catch{throw new EnquiryFailure('Withdrawal could not be confirmed. Retry the same request.',true);}
 if(response.error)throw new EnquiryFailure('Withdrawal could not be confirmed. Resolve scheduled or progressed work, refresh, or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));
 const r=response.data;try{if(!r||r.id!==input.offer_id||r.version!==input.version+1||!['withdrawn','expired'].includes(r.state))throw Error();const current=await scoped(client,owner,input.work,input.offer_id);if(current.version<r.version||current.version===r.version&&current.state!==r.state)throw Error();return {id:r.id as string,state:r.state as string,version:r.version as number,currentState:current.state,currentVersion:current.version};}catch{throw new EnquiryFailure('Recorded withdrawal could not be confirmed. Retry the same request.',true);}
}
