import type {SupabaseClient} from '@supabase/supabase-js';
import {managerWorkDetail} from './manager-work-detail';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
export async function managerPresence(client:SupabaseClient,owner:string,id:string,presence:string){
 if(!validId(presence))throw new Error('Presence reference required.');const work=await managerWorkDetail(client,owner,id),access=await managerAccess(client,owner);if(!work||!access)throw new Error('Approved work access required.');
 const query=(head=false)=>client.from('contractor_presence').select('id,organization_id,property_id,visit_id,permit_id,state,version,checked_in_at,checked_out_at,contractor_visits!inner(id,organization_id,property_id,unit_id,offer_id,contractor_work_offers!inner(id,organization_id,work_order_id))',{head,count:'exact'}).eq('id',presence).eq('organization_id',access.organization).eq('property_id',work.propertyId).eq('contractor_visits.contractor_work_offers.work_order_id',id);
 const record=await query().maybeSingle();if(record.error||!record.data||record.data.id!==presence)throw new Error('Presence unavailable.');const response={data:[record.data]};
 function relation(value:unknown){const v=Array.isArray(value)&&value.length===1?value[0]:value;if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('Presence parent unavailable.');return v as Record<string,unknown>;}
 const rows=response.data.map(r=>{const visit=relation(r.contractor_visits),offer=relation(visit.contractor_work_offers);if(!validId(r.id)||r.organization_id!==access.organization||r.property_id!==work.propertyId||!validId(r.visit_id)||!validId(r.permit_id)||!['on_site','exited'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.checked_in_at!=='string'||!Number.isFinite(Date.parse(r.checked_in_at))||(r.state==='on_site'?r.checked_out_at!==null:typeof r.checked_out_at!=='string'||!Number.isFinite(Date.parse(r.checked_out_at))||Date.parse(r.checked_out_at)<Date.parse(r.checked_in_at))||visit.id!==r.visit_id||visit.organization_id!==access.organization||visit.property_id!==work.propertyId||visit.unit_id!==work.unit||!validId(visit.offer_id)||offer.id!==visit.offer_id||offer.organization_id!==access.organization||offer.work_order_id!==id)throw new Error('Invalid presence record.');return {id:r.id as string,visit:r.visit_id as string,permit:r.permit_id as string,state:r.state as string,version:r.version as number,arrived:r.checked_in_at as string,departed:r.checked_out_at as string|null};});if(new Set(rows.map(r=>r.id)).size!==rows.length||new Set(rows.map(r=>r.visit)).size!==rows.length)throw new Error('Duplicate presence.');
 const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw new Error('Work access changed.');const latest=await managerWorkDetail(client,owner,id);if(!latest||latest.propertyId!==work.propertyId||latest.unit!==work.unit)throw new Error('Work location changed.');return {...rows[0],property:work.propertyId};
}
