import type {SupabaseClient} from '@supabase/supabase-js';
import {managerAccess} from './manager-access';
import {validId} from './catalog';
type Access=NonNullable<Awaited<ReturnType<typeof managerAccess>>>;
async function recheck(client:SupabaseClient,owner:string,access:Access){const current=await managerAccess(client,owner);if(!current||current.organization!==access.organization||current.role!==access.role||current.revision!==access.revision)throw new Error('Management access changed.');}
function name(value:unknown){return typeof value==='string'&&!!value.trim()&&value.length<=500;}
export async function managerProperties(client:SupabaseClient,owner:string,pageInput:number){
 const access=await managerAccess(client,owner);if(!access)throw new Error('Approved management membership required.');const query=(head=false)=>client.from('properties').select('id,organization_id,name',{head,count:'exact'}).eq('organization_id',access.organization);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Managed properties unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('name',{ascending:true}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Managed properties unavailable.');const rows=response.data.map(r=>{if(!validId(r.id)||r.organization_id!==access.organization||!name(r.name))throw new Error('Invalid managed property.');return {id:r.id as string,name:r.name as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Duplicate properties.');await recheck(client,owner,access);return {total,pages,page,rows};
}
export async function managerLocation(client:SupabaseClient,owner:string,property:string,unit:string|null){
 if(!validId(property)||unit!==null&&!validId(unit))throw new Error('Managed location reference required.');const access=await managerAccess(client,owner);if(!access)throw new Error('Approved management membership required.');const response=await client.from('properties').select('id,organization_id,name').eq('id',property).eq('organization_id',access.organization).maybeSingle(),r=response.data;if(response.error||!r||r.id!==property||r.organization_id!==access.organization||!name(r.name))throw new Error('Managed property unavailable.');let label:string|null=null;
 if(unit){const response=await client.from('units').select('id,property_id,unit_label').eq('id',unit).eq('property_id',property).maybeSingle(),u=response.data;if(response.error||!u||u.id!==unit||u.property_id!==property||!name(u.unit_label))throw new Error('Property unit unavailable.');label=u.unit_label;}await recheck(client,owner,access);return {property,unit,name:r.name as string,label};
}
export async function managerUnits(client:SupabaseClient,owner:string,property:string,pageInput:number){
 const access=await managerAccess(client,owner);if(!access)throw new Error('Approved management membership required.');const location=await managerLocation(client,owner,property,null);await recheck(client,owner,access);const query=(head=false)=>client.from('units').select('id,property_id,unit_label',{head,count:'exact'}).eq('property_id',property);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw new Error('Property units unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);
 const response=total?await query().order('unit_label',{ascending:true}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw new Error('Property units unavailable.');const rows=response.data.map(r=>{if(!validId(r.id)||r.property_id!==property||!name(r.unit_label))throw new Error('Invalid property unit.');return {id:r.id as string,label:r.unit_label as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw new Error('Duplicate units.');await recheck(client,owner,access);const current=await managerLocation(client,owner,property,null);if(current.name!==location.name)throw new Error('Property changed.');return {total,pages,page,rows,property:location};
}
