import type {SupabaseClient} from '@supabase/supabase-js';
import {invitationInput} from '../../../lib/staff/invitation-validation';
import {invitationIdentity,teamInvitation} from './team-invitations';
import {EnquiryFailure} from './enquiries';
export type TeamInvitationCommand=Readonly<{action:'accept'|'decline';invitation_id:string;version:number;request_id:string;reason:string;approved:true;organization:string;invitedRole:string;invitedEmail:string}>;
export function teamInvitationCommand(value:TeamInvitationCommand):TeamInvitationCommand{const r=invitationInput(value);if(!['accept','decline'].includes(r.p_action)||!r.p_invitation_id||typeof value.organization!=='string'||!value.organization.trim()||value.organization.length>500||!['admin','manager','finance','realtor'].includes(value.invitedRole)||typeof value.invitedEmail!=='string'||value.invitedEmail.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.invitedEmail))throw new EnquiryFailure('Reviewed invitation and explicit consent required.',false);return Object.freeze({action:value.action,invitation_id:r.p_invitation_id,version:r.p_expected_version,request_id:r.p_request_id,reason:r.p_reason,approved:true,organization:value.organization,invitedRole:value.invitedRole,invitedEmail:value.invitedEmail.toLowerCase()});}
export async function sendTeamInvitationCommand(client:SupabaseClient,owner:string,value:TeamInvitationCommand){
 let input:TeamInvitationCommand,email:string;try{input=teamInvitationCommand(value);email=await invitationIdentity(client,owner);const summary=await teamInvitation(client,owner,input.invitation_id);if(!summary||email!==input.invitedEmail||summary.organization!==input.organization||summary.role!==input.invitedRole||await invitationIdentity(client,owner)!==email)throw Error();}catch{throw new EnquiryFailure('Check the current verified invited account and reviewed invitation.',false);}
 let response;try{response=await client.rpc('manage_staff_invitation',invitationInput(input));}catch{throw new EnquiryFailure('Invitation response could not be confirmed. Retry the same consent request.',true);}
 if(response.error)throw new EnquiryFailure('Invitation response could not be confirmed. Refresh or retry the same request.',!['42501','22023','22P02','40001','23505'].includes(response.error.code));
 try{const state=input.action==='accept'?'accepted':'declined',ack=response.data;if(!ack||ack.id!==input.invitation_id||ack.version!==input.version+1||ack.state!==state)throw Error();const record=await client.from('staff_invitations').select('id,invite_email,role,state,version,accepted_by,responded_at').eq('id',input.invitation_id).eq('invite_email',email).maybeSingle(),r=record.data;if(record.error||!r||r.id!==input.invitation_id||r.invite_email!==email||r.role!==input.invitedRole||r.state!==state||r.version!==ack.version||(state==='accepted'?r.accepted_by!==owner:r.accepted_by!==null)||typeof r.responded_at!=='string'||!Number.isFinite(Date.parse(r.responded_at)))throw Error();const summary=await teamInvitation(client,owner,input.invitation_id);if(!summary||summary.organization!==input.organization||summary.role!==input.invitedRole||summary.version!==ack.version||summary.state!==state||await invitationIdentity(client,owner)!==email)throw Error();return {id:input.invitation_id,state,version:ack.version as number};}catch{throw new EnquiryFailure('Recorded consent response could not be confirmed. Retry the same request.',true);}
}
