import type {SupabaseClient} from '@supabase/supabase-js';
import {validId} from './catalog';
export async function invitationIdentity(client:SupabaseClient,owner:string){const response=await client.auth.getUser(),u=response.data.user;if(response.error||!u||u.id!==owner||u.is_anonymous||!u.email_confirmed_at||typeof u.email!=='string'||u.email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(u.email))throw Error('Current verified invited account required.');return u.email.toLowerCase();}
export async function teamInvitations(client:SupabaseClient,owner:string,pageInput:number){
 const email=await invitationIdentity(client,owner),query=(head=false)=>client.from('staff_invitations').select('id,invite_email,role,state,expires_at,created_at',{head,count:'exact'}).eq('invite_email',email);
 const count=await query(true);if(count.error||!Number.isSafeInteger(count.count)||count.count!<0)throw Error('Your invitation count unavailable.');const total=count.count!,pages=Math.max(1,Math.ceil(total/25)),page=Math.min(Math.max(1,Number.isSafeInteger(pageInput)?pageInput:1),pages);const response=total?await query().order('created_at',{ascending:false}).order('id',{ascending:true}).range((page-1)*25,page*25-1):{data:[],error:null};if(response.error||!Array.isArray(response.data)||response.data.length>25)throw Error('Your invitations unavailable.');
 const rows=response.data.map(r=>{if(!validId(r.id)||r.invite_email!==email||!['admin','manager','realtor','finance'].includes(r.role)||!['pending','accepted','declined','revoked','expired'].includes(r.state)||typeof r.created_at!=='string'||!Number.isFinite(Date.parse(r.created_at))||typeof r.expires_at!=='string'||!Number.isFinite(Date.parse(r.expires_at)))throw Error('Invalid account invitation.');return {id:r.id as string,role:r.role as string,state:r.state as string,expires:r.expires_at as string,created:r.created_at as string};});if(new Set(rows.map(r=>r.id)).size!==rows.length)throw Error('Duplicate invitations.');if(await invitationIdentity(client,owner)!==email)throw Error('Invited identity changed.');return {total,pages,page,rows,email};
}
export async function teamInvitation(client:SupabaseClient,owner:string,id:string){
 if(!validId(id))throw Error('Invitation reference required.');const email=await invitationIdentity(client,owner),response=await client.rpc('staff_invitation_summary',{p_invitation_id:id}),r=response.data;if(response.error)throw Error('Invitation unavailable.');if(r&&(r.id!==id||r.invite_email!==email||typeof r.organization_name!=='string'||!r.organization_name.trim()||r.organization_name.length>500||!['admin','manager','realtor','finance'].includes(r.role)||!['pending','accepted','declined','revoked','expired'].includes(r.state)||!Number.isInteger(r.version)||r.version<1||r.version>=2147483647||typeof r.expires_at!=='string'||!Number.isFinite(Date.parse(r.expires_at))||typeof r.can_accept!=='boolean'||typeof r.can_decline!=='boolean'||r.state!=='pending'&&(r.can_accept||r.can_decline)||r.blocked_reason!==null&&(typeof r.blocked_reason!=='string'||r.blocked_reason.length>500)))throw Error('Invalid invitation summary.');if(await invitationIdentity(client,owner)!==email)throw Error('Invited identity changed.');return r?{id,email,organization:r.organization_name as string,role:r.role as string,state:r.state as string,version:r.version as number,expires:r.expires_at as string,canAccept:r.can_accept as boolean,canDecline:r.can_decline as boolean,blocked:r.blocked_reason as string|null}:null;
}
